Repository great-expectations/great_expectations, pull requests merged in 2020-09, with the labels that each got.

#1798 [DOCS] how_to_instantiate_a_data_context_on_an_databricks_spark_cluster
  docs/guides/how_to_guides.rst
  docs/guides/how_to_guides/configuring_data_contexts.rst
  docs/guides/how_to_guides/configuring_data_contexts/how_to_instantiate_a_data_context_on_a_databricks_spark_cluster.rst
  docs/guides/how_to_guides/configuring_data_contexts/how_to_instantiate_a_data_context_on_an_emr_spark_cluster.rst
  docs/guides/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_on_a_filesystem.rst
  docs/guides/how_to_guides/creating_and_editing_expectations/how_to_create_custom_expectations_for_pandas.rst
Labels: documentation

#1914 [BUGFIX] Building data docs no longer crashes when a data asset name is an integer
  docs/changelog.rst
  great_expectations/render/renderer/page_renderer.py
  great_expectations/render/renderer/site_builder.py
Labels: bug

#1922 [ENHANCEMENT] Checkpoint run command now prints out details on each validation #1437
  docs/changelog.rst
  docs/guides/how_to_guides/miscellaneous/command_line.rst
  docs/guides/how_to_guides/validation/how_to_run_a_checkpoint_in_python.rst
  docs/guides/how_to_guides/validation/how_to_run_a_checkpoint_in_terminal.rst
  docs/guides/tutorials/getting_started/validate_your_data.rst
  great_expectations/cli/checkpoint.py
  great_expectations/cli/checkpoint_script_template.py
  great_expectations/cli/validation_operator.py
  tests/cli/test_checkpoint.py
  tests/cli/test_validation_operator.py
Labels: enhancement, feature:cli

#1916 [ENHANCEMENT] expect_table_columns_to_match_set
  docs/changelog.rst
  docs/reference/core_concepts/expectations/implemented_expectations.rst
  docs/reference/glossary_of_expectations.rst
  great_expectations/core/__init__.py
  great_expectations/dataset/dataset.py
  great_expectations/jupyter_ux/expectation_explorer.py
  great_expectations/render/renderer/content_block/expectation_string.py
  tests/data_asset/test_data_asset.py
  tests/render/test_render.py
  tests/test_definitions/other_expectations/expect_table_columns_to_match_set_test_set.json
  tests/test_utils.py
Labels: enhancement
