Repository great-expectations/great_expectations, pull requests merged in 2020-10, with the labels that each got.

#1968 [Draft - Enhancement] - enable using Minio for S3 backend
  great_expectations/data_context/store/tuple_store_backend.py
Labels: triage

#1983 [ENHANCEMENT] - Fix boto3 options passing into datasource correctly
  great_expectations/data_context/types/base.py
  great_expectations/datasource/pandas_datasource.py
Labels: #hacktoberfest-accepted

#1796 [DOCS] update docker release instructions
  docs/releasing/docker_release_process.rst
Labels: documentation

#1797 [DOCS] how to use docker images
  docs/guides/how_to_guides/miscellaneous/how_to_use_official_docker_images.rst
Labels: documentation

#2013 [BUGFIX] Fixed bug where slack messages cause stacktrace
  docs/changelog.rst
  great_expectations/render/renderer/slack_renderer.py
Labels: bug
