Repository great-expectations/great_expectations, pull requests merged in 2020-07, with the labels that each got.

#1580 [ENHANCEMENT] Will/patch for store_backend (S3 and GCS) to throw InvalidKeyError if file does not exist at expected location
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/exceptions.py
  great_expectations/render/renderer/site_builder.py
  tests/data_context/store/test_store_backends.py
Labels: enhancement

#1650 [DOCS] Will/docs/metadata store/formatting
  docs/how_to_guides/configuring_data_docs/how_to_host_and_share_data_docs_on_azure_blob_storage.rst
  docs/how_to_guides/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_azure_blob_storage.rst
  docs/how_to_guides/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_gcs.rst
  docs/how_to_guides/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_s3.rst
  docs/how_to_guides/configuring_metadata_stores/how_to_configure_a_validation_result_store_on_a_filesystem.rst
  docs/how_to_guides/configuring_metadata_stores/how_to_configure_a_validation_result_store_to_postgresql.rst
  docs/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_in_amazon_s3.rst
  docs/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_in_azure_blob_storage.rst
  docs/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_in_gcs.rst
  docs/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_on_a_filesystem.rst
  docs/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_to_postgresql.rst
  docs/how_to_guides/validation.rst
Labels: docs

#1701 [BUGFIX] Fix missing importlib for python 3.8 #1651
  docs/reference/changelog.rst
  great_expectations/util.py
Labels: bug

#1732 [MAINTENANCE] dependabot ignore isort
  .github/dependabot.yml
Labels: dependencies

#1735 [ENHANCEMENT] log class instantiation errors for better debugging
  docs/reference/changelog.rst
  great_expectations/data_context/data_context.py
Labels: enhancement
