Repository great-expectations/great_expectations, pull requests merged in 2021-02, with the labels that each got.

#2354 [WIP][CONTRIB] Hackathon: expect column values to be normally distributed
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_normally_distributed.py
Labels: automerge, hackathon-20210123

#2348 [DOCS] Fill in missing docs links in Expectation Template
  examples/expectations/column_map_expectation_template.py
Labels: automerge, hackathon-20210128

#2319 Great Expectations Hackathon Valid Email Expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_contain_valid_email.py
Labels: hackathon-20210123

#2168 [ENHANCEMENT]A notebook that demonstrates how to create an Expectation Suite without sample data
  examples/notebooks/create_expectation_suite_without_sample_data.ipynb
Labels: in-review

#1975 [FEATURE] Add TupleAzureBlobStoreBackend: Support Azure Blob Storage as a backend store
  docs/changelog.rst
  docs/guides/how_to_guides/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_azure_blob_storage.rst
  docs/guides/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_in_azure_blob_storage.rst
  great_expectations/data_context/store/__init__.py
  great_expectations/data_context/store/tuple_store_backend.py
  requirements-dev-util.txt
  tests/data_context/store/test_store_backends.py
Labels: in-review

#2345 Adding expect_column_values_to_be_valid_urls expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_urls.py
Labels: hackathon-20210128, in-review

#1875 [BUGFIX] Display correct unexpected_percent in DataDocs
  docs/changelog.rst
  great_expectations/data_asset/data_asset.py
  great_expectations/expectations/expectation.py
  tests/data_asset/test_data_asset_internals.py
  tests/data_asset/test_filedata_asset_expectations.py
  tests/expectations/test_run_diagnostics.py
  tests/test_great_expectations.py
  tests/test_sets/titanic_expected_data_asset_validate_results.json
  tests/test_sets/titanic_expected_data_asset_validate_results_with_exceptions.json
Labels: in-review

#2203 [ENHANCEMENT] Added call to map function in _get_evaluation_dependencies
  great_expectations/expectations/metrics/map_metric.py
Labels: in-review

#2377 [DOCS] Fix broken documentation link, add utm params
  great_expectations/render/renderer/suite_scaffold_notebook_renderer.py
  tests/render/renderer/test_suite_scaffold_notebook_renderer.py
  tests/render/renderer/test_suite_scaffold_notebook_renderer_pre_v013.py
Labels: in-review

#2349 Hackathon/foreign key expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_pair_values_foreign_keys_in_column_A_to_exist_in_column_B.py
Labels: hackathon-20210128, in-review

#2393 [DOCS] How to validate data without a Checkpoint (update with 0.13.8)
  docs/guides/how_to_guides/validation/how_to_validate_data_without_a_checkpoint.rst
Labels: asana

#2422 [BUGFIX] Missing `markown_text.j2` jinja template
  great_expectations/render/view/templates/markdown_collapse.j2
  great_expectations/render/view/templates/markdown_graph.j2
  great_expectations/render/view/templates/markdown_markdown.j2
  great_expectations/render/view/templates/markdown_text.j2
  great_expectations/render/view/view.py
  tests/render/test_default_markdown_view.py
Labels: automerge

#2407 [ENHANCEMENT] Added expectation to check if data is in alphabetical ordering
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_alphabetical.py
Labels: hackathon-20210206

#2406 [CONTRIB] Expectation: Matches benfords law with 80 percent confidence interval test
  contrib/experimental/great_expectations_experimental/expectations/expect_column_match_benfords_law.py
Labels: hackathon-20210206

#2402 [MAINTENANCE] Allowing the tests to run with Docker-in-Windows
  great_expectations/cli/datasource.py
  great_expectations/expectations/self_check_util.py
  great_expectations/marshmallow__shade/validate.py
  tests/conftest.py
  tests/data_asset/test_filedata_asset_expectations.py
  tests/data_context/store/test_database_store_backend.py
  tests/data_context/store/test_evaluation_parameter_store.py
  tests/data_context/store/test_evaluation_parameter_store_pre_v013.py
  tests/data_context/store/test_metric_store.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_config_ui.py
  tests/data_context/test_data_context_config_variables.py
  tests/data_context/test_data_context_test_yaml_config.py
  tests/data_context/test_data_context_utils.py
  tests/datasource/batch_kwarg_generator/test_s3_subdir_reader_generator.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/test_utils.py
Labels: in-review

#2408 [FEATURE] Add Expectation "expect_column_to_follow_rule"
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_follow_rule.py
Labels: hackathon-20210206

#2403 Hackathon expectation: check for valid Wikipedia articles
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_wikipedia_articles.py
Labels: cla-not-signed, hackathon-20210206

#2409 [FEATURE] Add experimental expectations/metrics for XML, EDTF, and language
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_edtf_parseable.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_xml_parseable.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_language.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_xml_schema.py
Labels: in-review

#2440 [BUGFIX] [ENHANCEMENT] Allows gzipped files and other encodings to be read from S3
  great_expectations/core/util.py
  great_expectations/execution_engine/pandas_execution_engine.py
  tests/core/test_util.py
  tests/datasource/test_util.py
  tests/execution_engine/test_pandas_execution_engine.py
Labels: in-review
