Repository great-expectations/great_expectations, pull requests merged in 2021-11, with the labels that each got.

#3533 [DOCS] Choosing and configuring DataConnectors
  docs/changelog.md
  docs/guides/connecting_to_your_data/how_to_choose_which_dataconnector_to_use.md
  docs/guides/connecting_to_your_data/how_to_configure_a_configuredassetdataconnector.md
  docs/guides/connecting_to_your_data/how_to_configure_a_runtimedataconnector.md
  docs/guides/connecting_to_your_data/how_to_configure_an_inferredassetdataconnector.md
  great_expectations/datasource/data_connector/configured_asset_filesystem_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_filesystem_data_connector.py
  sidebars.js
  tests/integration/docusaurus/connecting_to_your_data/how_to_choose_which_dataconnector_to_use.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_configure_a_configuredassetdataconnector.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_configure_a_runtimedataconnector.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_configure_an_inferredassetdataconnector.py
  tests/integration/test_script_runner.py
  tests/test_sets/dataconnector_docs/nested_directories_complex/green_tripdata/green_tripdata_2019-01.csv
  tests/test_sets/dataconnector_docs/nested_directories_complex/green_tripdata/green_tripdata_2019-02.csv
  tests/test_sets/dataconnector_docs/nested_directories_complex/green_tripdata/green_tripdata_2019-03.csv
  tests/test_sets/dataconnector_docs/nested_directories_complex/yellow/tripdata/yellow_tripdata_2019-01.txt
  tests/test_sets/dataconnector_docs/nested_directories_complex/yellow/tripdata/yellow_tripdata_2019-02.txt
  tests/test_sets/dataconnector_docs/nested_directories_complex/yellow/tripdata/yellow_tripdata_2019-03.txt
  tests/test_sets/dataconnector_docs/nested_directories_data_asset/green_tripdata/2019-01.csv
  tests/test_sets/dataconnector_docs/nested_directories_data_asset/green_tripdata/2019-02.csv
  tests/test_sets/dataconnector_docs/nested_directories_data_asset/green_tripdata/2019-03.csv
  tests/test_sets/dataconnector_docs/nested_directories_data_asset/yellow_tripdata/yellow_tripdata_2019-01.csv
  tests/test_sets/dataconnector_docs/nested_directories_data_asset/yellow_tripdata/yellow_tripdata_2019-02.csv
  tests/test_sets/dataconnector_docs/nested_directories_data_asset/yellow_tripdata/yellow_tripdata_2019-03.csv
  tests/test_sets/dataconnector_docs/nested_directories_time/2018/10/green_tripdata.csv
  tests/test_sets/dataconnector_docs/nested_directories_time/2018/10/yellow_tripdata.csv
  tests/test_sets/dataconnector_docs/nested_directories_time/2018/11/green_tripdata.csv
  tests/test_sets/dataconnector_docs/nested_directories_time/2018/11/yellow_tripdata.csv
  tests/test_sets/dataconnector_docs/nested_directories_time/2018/12/green_tripdata.csv
  tests/test_sets/dataconnector_docs/nested_directories_time/2018/12/yellow_tripdata.csv
  tests/test_sets/dataconnector_docs/nested_directories_time/2019/01/green_tripdata.csv
  tests/test_sets/dataconnector_docs/nested_directories_time/2019/01/yellow_tripdata.csv
  tests/test_sets/dataconnector_docs/nested_directories_time/2019/02/green_tripdata.csv
  tests/test_sets/dataconnector_docs/nested_directories_time/2019/02/yellow_tripdata.csv
  tests/test_sets/dataconnector_docs/nested_directories_time/2019/03/green_tripdata.csv
  tests/test_sets/dataconnector_docs/nested_directories_time/2019/03/yellow_tripdata.csv
  tests/test_sets/dataconnector_docs/single_directory_one_data_asset/yellow_tripdata_2019-01.csv
  tests/test_sets/dataconnector_docs/single_directory_one_data_asset/yellow_tripdata_2019-02.csv
  tests/test_sets/dataconnector_docs/single_directory_one_data_asset/yellow_tripdata_2019-03.csv
  tests/test_sets/dataconnector_docs/single_directory_two_data_assets/green_tripdata_2019-01.csv
  tests/test_sets/dataconnector_docs/single_directory_two_data_assets/green_tripdata_2019-02.csv
  tests/test_sets/dataconnector_docs/single_directory_two_data_assets/green_tripdata_2019-03.csv
  tests/test_sets/dataconnector_docs/single_directory_two_data_assets/yellow_tripdata_2019-01.csv
  tests/test_sets/dataconnector_docs/single_directory_two_data_assets/yellow_tripdata_2019-02.csv
  tests/test_sets/dataconnector_docs/single_directory_two_data_assets/yellow_tripdata_2019-03.csv
Labels: core-team

#3498 DevRel - docs fixes
  docs/guides/validation/checkpoints/how_to_create_a_new_checkpoint.md
  great_expectations/render/renderer/checkpoint_new_notebook_renderer.py
  tests/render/renderer/test_checkpoint_new_notebook_renderer.py
Labels: core-team

#3386 [BUGFIX] Allowing user specified run_id to appear in WarningAndFailureExpectationSuitesValidationOperator validation result
  great_expectations/validation_operators/validation_operators.py
  tests/actions/test_validation_operators.py
Labels: community, devrel

#3408 [BUGFIX] fix Issue #3405 - gcs client init in pandas engine
  great_expectations/execution_engine/pandas_execution_engine.py
  tests/execution_engine/test_pandas_execution_engine.py
Labels: community, devrel

#3496 [FEATURE] Enable support for Teradata SQLAlchemy dialect
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/metrics/util.py
  requirements-dev-sqlalchemy.txt
Labels: triage, community

#3624 [FEATURE] Dremio connector added (SQLalchemy)
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/util.py
  requirements-dev-sqlalchemy.txt
Labels: community, devrel

#3642 [FEATURE] Adds expect_column_values_to_be_string_integers_increasing
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_string_integers_increasing.py
Labels: feature:custom expectations

#3684 [BUGFIX] evaluation parameters from different expectation suites dependencies
  great_expectations/data_context/data_context.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context.py
Labels: community, devrel

#3346 [FEATURE] Add new result_format to include unexpected_row_list
  docs/reference/expectations/result_format.md
  great_expectations/core/expectation_configuration.py
  great_expectations/expectations/expectation.py
  tests/expectations/metrics/test_map_metric.py
  tests/expectations/test_expectation_arguments.py
Labels: triage, core-team

#3711 [DOCS] Update the link to configure a MetricStore
  docs/reference/metrics.md
Labels: community, devrel

#3632 [DOCS]: Updated code example to remove deprecated "File"function
  docs/reference/validation.md
Labels: community, devrel

#3129 [BUGFIX] fixed a bug where expectation metadata doesn't appear in edit template for table-level expectations
  great_expectations/render/notebook_assets/suite_edit/table_expectation.py.j2
Labels: community, devrel

#3397 [FEATURE] Feature/render validation metadata
  great_expectations/expectations/expectation.py
  great_expectations/render/notebook_assets/suite_edit/header.py.j2
  great_expectations/render/renderer/content_block/content_block.py
  great_expectations/render/renderer/content_block/validation_results_table_content_block.py
  great_expectations/render/renderer/page_renderer.py
  great_expectations/render/renderer/suite_edit_notebook_renderer.py
  tests/cli/v012/test_init.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/render/test_render_ValidationResultsTableContentBlockRenderer.py
Labels: community, devrel

#2849 FEATURE: Added expectation expect_column_values_to_not_contain_special_characters()
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_not_contain_special_characters.py
Labels: community
