Repository great-expectations/great_expectations, pull requests merged in 2021-01, with the labels that each got.

#2224 [ENHANCEMENT] Data docs can now be built skipping the index page using the python API
  docs/changelog.rst
  great_expectations/cli/docs.py
  great_expectations/data_context/data_context.py
  great_expectations/render/renderer/site_builder.py
  great_expectations/validation_operators/actions.py
  tests/data_context/test_data_context.py
Labels: enhancement

#2315 [CONTRIB] Adding Expectation for Number of Decimal Points
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_number_of_decimal_places_to_equal.py
Labels: hackathon-01232021

#2318 [FEATURE] expect_column_values_to_be_ascii & expect_column_values_to_not_contain_character
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_ascii.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_not_contain_character.py
Labels: hackathon-20210123

#2346 [FEATURE] Add expectation for text in a column to be in a given language.
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_are_in_language.py
Labels: hackathon-20210128

#2347 [FEATURE] Expect record point to be within geo region (identified by iso a3 country code)
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_point_within_geo_region.py
Labels: hackathon-20210128

#2344 FEATURE: Add expectation to check for mostly non bot useragents in column
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_a_non_bot_user_agent.py
Labels: hackathon-20210128

#2314 [CONTRIB] Added Expectation expect_column_values_to_be_us_zipcode_within_radius
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_us_zipcode_within_radius_of_given_zipcode.py
Labels: hackathon-20210123

#2356 Typo
  docs/guides/how_to_guides/creating_and_editing_expectations/how_to_contribute_a_new_expectation_to_great_expectations.rst
Labels: automerge
