Repository great-expectations/great_expectations, pull requests merged in 2021-08, with the labels that each got.

#3160 improve doc
  docs_rtd/contributing/testing.rst
Labels: community

#2695 [BUGFIX] allow reader_options in the CLI so can read `.csv.gz` files
  docs_rtd/changelog.rst
  great_expectations/cli/v012/datasource.py
  tests/cli/v012/test_suite.py
  tests/conftest.py
Labels: community, devrel

#3143 [FEATURE] add python3.9 to python versions
  azure-pipelines.yml
  setup.py
  tests/render/test_render.py
Labels: community, triage

#3188 [FEATURE] Set foundation for Azure-related DataConnectors
  great_expectations/core/batch_spec.py
  great_expectations/core/usage_statistics/anonymizers/data_connector_anonymizer.py
  great_expectations/data_context/data_context.py
  great_expectations/data_context/types/base.py
  great_expectations/datasource/data_connector/__init__.py
  great_expectations/datasource/data_connector/asset/asset.py
  great_expectations/datasource/data_connector/configured_asset_azure_data_connector.py
Labels: core-team

#3190 [BUGFIX] Fixes an error with expect_column_values_to_be_dateutil_parseable
  great_expectations/expectations/core/expect_column_values_to_be_dateutil_parseable.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_dateutil_parseable.json
Labels: core-team

#3179 [BUGFIX] Restore support for V2 API style custom expectation rendering
  docs_rtd/changelog.rst
  great_expectations/render/renderer/content_block/validation_results_table_content_block.py
  tests/render/test_render_ValidationResultsTableContentBlockRenderer.py
Labels: community, devrel

#3196 Add conda as installing method
  README.md
Labels: community, devrel

#3161 [FEATURE] Update ExpectCompoundColumnsToBeUnique for V3 API
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/expectations/core/expect_compound_columns_to_be_unique.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/profile/user_configurable_profiler.py
  great_expectations/self_check/util.py
  tests/execution_engine/test_pandas_execution_engine.py
  tests/profile/test_user_configurable_profiler_v3_batch_request.py
  tests/test_definitions/multicolumn_map_expectations/expect_compound_columns_to_be_unique.json
Labels: core-team

#3198 [DOCS] Standardize capitalization of Spark in docs
  docs/contributing/contributing_setup.md
  docs/guides/connecting_to_your_data/cloud/s3/spark.md
  docs/guides/connecting_to_your_data/components/spark_additional_notes.md
  docs/guides/connecting_to_your_data/filesystem/spark.md
  docs/guides/connecting_to_your_data/in_memory/spark.md
  docs/guides/expectations/contributing/how_to_contribute_a_new_expectation_to_great_expectations.md
  docs/reference/core_concepts.md
Labels: core-team

#3200 [BUGFIX] Fix incorrect schema validation for Azure data connectors
  great_expectations/data_context/types/base.py
Labels: core-team

#3194 [MAINTENANCE] Fix minor typo in S3 DataConnectors
  great_expectations/datasource/data_connector/configured_asset_s3_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_s3_data_connector.py
Labels: core-team

#3141 [FEATURE] ConfiguredAssetDataConnector for Azure Blob Storage
  great_expectations/datasource/data_connector/configured_asset_azure_data_connector.py
  great_expectations/datasource/data_connector/util.py
  tests/datasource/data_connector/test_configured_asset_azure_data_connector.py
Labels: core-team

#2952 [BUGFIX] Improve parsing of .ge_store_backend_id
  docs_rtd/changelog.rst
  great_expectations/data_context/store/store_backend.py
  tests/data_context/store/test_database_store_backend.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context_in_code_config.py
Labels: core-team

#3192 [DOCS}/GDOC-205/Create _redirects
  docs_rtd/_static/style.css
  docs_rtd/_templates/layout.html
  docusaurus.config.js
  static/_redirects
Labels: core-team

#3215 [FEATURE] Replace MetricFunctionTypes.IDENTITY domain type with convenience method get_domain_records() for SqlAlchemyExecutionEngine
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/map_metric_provider.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
Labels: core-team

#3226 [FEATURE] Replace MetricFunctionTypes.IDENTITY domain type with convenience method get_domain_records() for SparkDFExecutionEngine
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/map_metric_provider.py
  tests/execution_engine/test_sparkdf_execution_engine.py
Labels: core-team

#3227 [FEATURE] Implementation of ColumnPairValuesAGreaterThanB metric for PandasExecutionEngine
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_greater.py
  great_expectations/expectations/metrics/map_metric_provider.py
  tests/expectations/metrics/test_core.py
Labels: core-team

#3240 [FEATURE] Implement ColumnPairValuesInSet metric for PandasExecutionEngine
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_in_set.py
  tests/expectations/metrics/test_core.py
Labels: core-team

#3242 [FEATURE] Implement "expect_column_pair_values_to_be_in_set" expectation (support for PandasExecutionEngine)
  great_expectations/core/expectation_configuration.py
  great_expectations/expectations/core/expect_column_pair_values_a_to_be_greater_than_b.py
  great_expectations/expectations/core/expect_column_pair_values_to_be_in_set.py
  great_expectations/expectations/util.py
  great_expectations/jupyter_ux/expectation_explorer.py
  tests/test_definitions/multicolumn_map_expectations/expect_multicolumn_sum_to_equal.json
Labels: core-team

#3214 [MAINTENANCE] Allow `PandasExecutionEngine` to accept `Azure DataConnectors`
  great_expectations/core/util.py
  great_expectations/datasource/data_connector/runtime_data_connector.py
  great_expectations/execution_engine/pandas_execution_engine.py
  tests/core/test_util.py
  tests/data_context/test_data_context_test_yaml_config.py
  tests/datasource/test_new_datasource.py
  tests/datasource/test_new_datasource_with_runtime_data_connector.py
  tests/execution_engine/test_pandas_execution_engine.py
Labels: core-team

#3220 [FEATURE] Set foundation for GCS DataConnectors
  great_expectations/core/batch_spec.py
  great_expectations/core/usage_statistics/anonymizers/data_connector_anonymizer.py
  great_expectations/data_context/data_context.py
  great_expectations/datasource/data_connector/__init__.py
  great_expectations/datasource/data_connector/configured_asset_gcs_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_gcs_data_connector.py
Labels: core-team

#3243 V3 - Implement ColumnPairValuesEqual for PandasExecutionEngine
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_equal.py
  tests/expectations/metrics/test_core.py
Labels: core-team

#3250 [FEATURE] Implement the SelectColumnValuesUniqueWithinRecord metric (for PandasExecutionEngine)
  great_expectations/expectations/metrics/multicolumn_map_metrics/__init__.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/select_column_values_unique_within_record.py
  tests/expectations/metrics/test_core.py
Labels: core-team

#3251 [FEATURE] Implementation of the "expect_select_column_values_to_be_unique_within_record" Expectation
  great_expectations/expectations/core/expect_select_column_values_to_be_unique_within_record.py
  great_expectations/self_check/util.py
  tests/expectations/metrics/test_core.py
  tests/test_definitions/multicolumn_map_expectations/expect_select_column_values_to_be_unique_within_record.json
Labels: core-team

#3253 [FEATURE] GCS `DataConnector` schema validation
  great_expectations/data_context/types/base.py
  great_expectations/datasource/data_connector/asset/asset.py
Labels: core-team

#3252 [FEATURE] V3 implement expect_column_pair_values_to_be_equal expectation for PandasExecutionEngine
  docs_rtd/changelog.rst
  great_expectations/expectations/core/expect_column_pair_values_to_be_equal.py
  great_expectations/self_check/util.py
Labels: core-team

#3256 [FEATURE] V3 - Implement column_pair helpers/providers for SqlAlchemyExecutionEngine
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_equal.py
  great_expectations/expectations/metrics/map_metric_provider.py
  tests/expectations/metrics/test_core.py
Labels: core-team

#3259 Make BigQuery SqlAlchemy dialect conform to "dialect" attribute convention and dataset cleanup
  docs/contributing/contributing_test.md
  docs_rtd/contributing/testing.rst
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py
  great_expectations/expectations/metrics/util.py
  great_expectations/self_check/util.py
Labels: community

#3258 [FEATURE] Add schema validation for different GCS auth methods
  great_expectations/data_context/types/base.py
Labels: core-team

#3228 [BUGFIX] Fix deprecation warning for importing from collections
  docs/changelog.md
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
Labels: community, devrel

#3219 [FEATURE] Enable Expectations tests for BigQuery
  azure-pipelines-cloud-db-integration.yml
  docs/contributing/contributing_test.md
  docs/guides/validation/advanced/how_to_implement_a_custom_validation_action.md
  docs_rtd/contributing/testing.rst
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/metrics/util.py
  great_expectations/self_check/util.py
  tests/conftest.py
  tests/expectations/test_util.py
  tests/test_definitions/column_aggregate_expectations/expect_column_mean_to_be_between.json
  tests/test_definitions/column_aggregate_expectations/expect_column_sum_to_be_between.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_regex.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_regex_list.json
  tests/test_definitions/test_expectations.py
  tests/test_definitions/test_expectations_cfe.py
Labels: core-team

#3049 [FEATURE] add expectation for discrete column entropy
  contrib/experimental/great_expectations_experimental/expectations/expect_column_discrete_entropy_to_be_between.py
Labels: community, devrel

#3267 [FEATURE] V3 implement expect_column_pair_values_to_be_equal for SqlAlchemyExecutionEngine
  docs_rtd/changelog.rst
  great_expectations/expectations/core/expect_column_pair_values_to_be_equal.py
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_equal.py
  great_expectations/self_check/util.py
Labels: core-team

#2594 [ENHANCEMENT] Edtf with support levels
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_edtf_parseable.py
Labels: triage, community

#3278 [FEATURE] V3 implement ColumnPairValuesInSet for SQL Alchemy execution engine
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_in_set.py
  tests/expectations/metrics/test_core.py
Labels: core-team

#3279 [FEATURE] Implementation of the Metric "select_column_values.unique.within_record" for SQLAlchemyExecutionEngine
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_equal.py
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_greater.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/select_column_values_unique_within_record.py
  tests/expectations/metrics/test_core.py
Labels: core-team

#3247 [FEATURE] Implement `ConfiguredAssetGCSDataConnector`
  great_expectations/datasource/data_connector/configured_asset_gcs_data_connector.py
  great_expectations/datasource/data_connector/util.py
  tests/datasource/data_connector/test_configured_asset_gcs_data_connector.py
  tests/datasource/data_connector/test_data_connector_util.py
Labels: core-team

#3281 [FEATURE] V3 implement expect_column_pair_values_to_be_in_set for SQL Alchemy execution engine
  docs_rtd/changelog.rst
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_in_set.py
  great_expectations/self_check/util.py
  tests/expectations/metrics/test_core.py
Labels: core-team

#3126 [MAINTENANCE] [MAINTENANCE] Add force_reuse_spark_context to DatasourceConfigSchema
  docs_rtd/changelog.rst
  great_expectations/data_context/types/base.py
  tests/datasource/test_sparkdf_datasource.py
Labels: community, devrel

#3289 [FEATURE] Implement Spark Decorators and Helpers; Demonstrate on MulticolumnSumEqual Metric
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/multicolumn_sum_equal.py
  tests/expectations/metrics/test_core.py
Labels: core-team

#3292 [BUGFIX] Fix import issues around cloud providers (GCS/Azure/S3)
  constraints-dev.txt
  great_expectations/datasource/data_connector/configured_asset_azure_data_connector.py
  great_expectations/datasource/data_connector/util.py
  great_expectations/execution_engine/pandas_execution_engine.py
Labels: core-team

#3272 [FEATURE]/change run time format
  great_expectations/render/renderer/page_renderer.py
  tests/render/fixtures/ValidationResultsPageRenderer_render_with_run_info_at_end.json
  tests/render/fixtures/ValidationResultsPageRenderer_render_with_run_info_at_end_nc.json
  tests/render/fixtures/ValidationResultsPageRenderer_render_with_run_info_at_start.json
  tests/render/fixtures/ValidationResultsPageRenderer_render_with_run_info_at_start_nc.json
  tests/render/test_default_markdown_view.py
  tests/render/test_page_renderer.py
Labels: triage, community

#3295 DOCS Fix broken link to Contributor docs
  CONTRIBUTING.md
  docs/contributing/contributing_setup.md
Labels: community, devrel

#3288 [MAINTENANCE] Additional tests for RuntimeDataConnector at Datasource-level (query)
  tests/datasource/test_new_datasource_with_runtime_data_connector.py
Labels: core-team

#3294 [FEATURE] Enable column_pair expectations and tests for Spark
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_equal.py
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_greater.py
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_in_set.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/compound_columns_unique.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/multicolumn_sum_equal.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/select_column_values_unique_within_record.py
  great_expectations/self_check/util.py
  tests/expectations/metrics/test_core.py
  tests/test_definitions/multicolumn_map_expectations/expect_compound_columns_to_be_unique.json
  tests/test_definitions/multicolumn_map_expectations/expect_select_column_values_to_be_unique_within_record.json
Labels: core-team

#3284 [FEATURE] Implement `InferredAssetGCSDataConnector`
  great_expectations/data_context/types/base.py
  great_expectations/datasource/data_connector/configured_asset_gcs_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_gcs_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_gcs_data_connector.py
Labels: core-team

#3204 [MAINTENANCE] Write integration/E2E tests for `ConfiguredAssetAzureDataConnector`
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/pandas/configured_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/pandas/configured_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/pandas/python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/pandas/yaml_example.py
  tests/integration/test_script_runner.py
Labels: core-team

#2630 [ENHANCEMENT] - Update GCSStoreBackend to Limit IAM Permissions Required
  great_expectations/data_context/store/tuple_store_backend.py
  tests/data_context/store/test_store_backends.py
Labels: community, devrel

#3264 [FEATURE] Enable `GCS DataConnector` integration with `PandasExecutionEngine`
  great_expectations/core/util.py
  great_expectations/execution_engine/pandas_execution_engine.py
  requirements-dev-base.txt
  tests/core/test_util.py
  tests/data_context/test_data_context_test_yaml_config.py
  tests/datasource/test_new_datasource.py
  tests/datasource/test_new_datasource_with_runtime_data_connector.py
  tests/execution_engine/test_pandas_execution_engine.py
Labels: core-team

#3304 [MAINTENANCE] Tests for RuntimeDataConnector at DataContext-level
  great_expectations/core/batch.py
  great_expectations/data_context/data_context.py
  great_expectations/datasource/data_connector/inferred_asset_file_path_data_connector.py
  tests/checkpoint/test_simple_checkpoint.py
  tests/cli/test_suite.py
  tests/conftest.py
  tests/data_context/test_data_context_datasource_runtime_data_connector.py
  tests/datasource/data_connector/test_data_connector.py
  tests/datasource/data_connector/test_runtime_data_connector.py
  tests/datasource/test_new_datasource.py
  tests/datasource/test_new_datasource_with_runtime_data_connector.py
Labels: core-team

#3318 [MAINTENANCE] Tests for RuntimeDataConnector at Datasource-level (Spark and Pandas)
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  tests/conftest.py
  tests/data_context/test_data_context_v013.py
  tests/datasource/test_new_datasource_with_runtime_data_connector.py
  tests/test_sets/taxi_yellow_trip_data_samples/first_3_files/yellow_trip_data_sample_2019-01.csv
  tests/test_sets/taxi_yellow_trip_data_samples/first_3_files/yellow_trip_data_sample_2019-02.csv
  tests/test_sets/taxi_yellow_trip_data_samples/first_3_files/yellow_trip_data_sample_2019-03.csv
Labels: core-team

#3311 [DOCS] "How to connect to data on GCS using Pandas"
  docs/guides/connecting_to_your_data/cloud/gcs/pandas.md
Labels: core-team
