Repository great-expectations/great_expectations, pull requests merged in 2021-09, with the labels that each got.

#3325 [MAINTENANCE] Tests for RuntimeDataConnector at DataContext-level (Spark and Pandas)
  docs/guides/connecting_to_your_data/filesystem/spark.md
  great_expectations/execution_engine/sparkdf_execution_engine.py
  tests/conftest.py
  tests/data_context/test_data_context_datasource_runtime_data_connector.py
  tests/datasource/test_new_datasource.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/pandas_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/pandas_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/spark_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/spark_yaml_example.py
  tests/integration/test_script_runner.py
Labels: core-team

#3236 [BUGFIX] Addresses Issue 2937.
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  tests/dataset/test_sqlalchemydataset.py
  tests/expectations/core/test_expect_column_values_to_be_in_type_list.py
  tests/expectations/core/test_expect_column_values_to_be_of_type.py
Labels: community, devrel

#3334 [MAINTENANCE] Renaming `default_batch_identifier` in examples
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/pandas/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/pandas/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/pandas/python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/pandas/yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/bigquery_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/bigquery_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/mysql_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/mysql_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/postgres_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/postgres_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/redshift_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/redshift_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/snowflake_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/snowflake_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/sqlite_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/sqlite_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/pandas_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/pandas_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/spark_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/spark_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/in_memory/pandas_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/in_memory/pandas_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/in_memory/spark_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/in_memory/spark_yaml_example.py
Labels: core-team

#3280 [FEATURE] Add performance test
  azure-pipelines-cloud-db-integration.yml
  docs/contributing/contributing_test.md
  docs_rtd/changelog.rst
  requirements-dev-base.txt
  tests/conftest.py
  tests/performance/README.md
  tests/performance/bigquery_schema.json
  tests/performance/results/initial_baseline.json
  tests/performance/setup_bigquery_tables_for_performance_test.sh
  tests/performance/taxi_benchmark_util.py
  tests/performance/test_bigquery_benchmarks.py
Labels: community, devrel

#3340 Prepare AzureUrl to handle WASBS format (for Spark)
  great_expectations/core/util.py
  tests/core/test_util.py
Labels: core-team

#3222 [BUGFIX] Fix issue where multiple validators reused the same execution engine, causing a conflict in active batch (GE-3168)
  great_expectations/validator/validator.py
  tests/datasource/data_connector/test_sql_data_connector.py
  tests/expectations/core/test_expect_column_value_z_scores_to_be_less_than.py
  tests/expectations/core/test_expect_column_values_to_be_in_type_list.py
  tests/expectations/core/test_expect_column_values_to_be_of_type.py
  tests/integration/fixtures/yellow_trip_data_pandas_fixture/multiple_batch_requests_one_validator_multiple_steps.py
  tests/validator/test_validator.py
Labels: core-team

#3335 [BUGFIX] Allow for RuntimeDataConnector to accept custom query while suppressing temp table creation
  docs_rtd/changelog.rst
  great_expectations/datasource/data_connector/runtime_data_connector.py
  great_expectations/expectations/metrics/table_metrics/table_column_types.py
  great_expectations/expectations/metrics/table_metrics/table_head.py
  great_expectations/expectations/metrics/util.py
  tests/datasource/test_new_datasource_with_runtime_data_connector.py
Labels: core-team, devrel

#3348 [DOCS] Updating to reflect current Expectation dev state
  docs/reference/expectations/implemented_expectations.md
Labels: core-team

#3262 [FEATURE] [MER-293] GE Cloud Mode for DataContext
  docs/changelog.md
  great_expectations/core/expectation_suite.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/core/usage_statistics/usage_statistics.py
  great_expectations/data_context/data_context.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/store/validations_store.py
  great_expectations/data_context/templates.py
  great_expectations/data_context/types/base.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/util.py
  tests/data_context/conftest.py
  tests/data_context/fixtures/conf/great_expectations_cloud_config_complete_1.conf
  tests/data_context/fixtures/conf/great_expectations_cloud_config_complete_2.conf
  tests/data_context/fixtures/conf/great_expectations_cloud_config_complete_with_usage_stats_section.conf
  tests/data_context/fixtures/conf/great_expectations_cloud_config_minimal_1.conf
  tests/data_context/fixtures/conf/great_expectations_cloud_config_minimal_2.conf
  tests/data_context/fixtures/conf/great_expectations_cloud_config_minimal_missing_token_1.conf
  tests/data_context/fixtures/conf/great_expectations_cloud_config_minimal_missing_token_2.conf
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context_ge_cloud_mode.py
Labels: core-team

#3338 [BUGFIX] added casting of numeric value to fix redshift issue #3293
  docs_rtd/changelog.rst
  great_expectations/expectations/metrics/map_metric_provider.py
Labels: community, devrel

#3363 [DOCS] GREAT-195 Docs remove all stubs and links to them
  docs/deployment_patterns/contributing/how_to_add_a_new_deployment_pattern_document.md
  docs/deployment_patterns/contributing/how_to_contribute_to_an_existing_deployment_pattern_document.md
  docs/guides/connecting_to_your_data/advanced/how_to_create_a_batch_from_a_sql_query.md
  docs/guides/connecting_to_your_data/advanced/how_to_create_a_lightweight_data_catalog_by_applying_a_descriptive_profiler_to_a_configured_datasource.md
  docs/guides/connecting_to_your_data/advanced/how_to_explore_changes_in_data_over_time_using_a_configured_datasource.md
  docs/guides/connecting_to_your_data/cloud/azure/pandas.md
  docs/guides/connecting_to_your_data/cloud/azure/spark.md
  docs/guides/connecting_to_your_data/contributing/how_to_add_support_for_a_new_sqlalchemy_dialect.md
  docs/guides/connecting_to_your_data/how_to_configure_a_dataconnector_to_introspect_and_partition_a_file_system_or_blob_store.md
  docs/guides/connecting_to_your_data/how_to_configure_a_dataconnector_to_introspect_and_partition_tables_in_sql.md
  docs/guides/connecting_to_your_data/how_to_get_a_batch_of_data_from_a_configured_datasource.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_expectations_from_a_sql_query.md
  docs/guides/miscellaneous/how_to_template.md
  docs/guides/setup/how_to_instantiate_a_data_context.md
  docs/guides/setup/installation/databricks.md
  docs/guides/validation/advanced/how_to_implement_a_custom_validation_action.md
  docs/guides/validation/contributing/how_to_contribute_a_new_validation_action.md
  docs/guides/validation/how_to_validate_data_by_running_a_checkpoint.md
  docs/guides/validation/validation_actions/how_to_store_validation_results_as_a_validation_action.md
  docs/guides/validation/validation_actions/how_to_update_data_docs_as_a_validation_action.md
  docs/reference/core_concepts.md
  docs/reference/spare_parts.md
  docs/reference/stores.md
  docs/reference/stub.md
  docs/sitemap.xml
  docs/tutorials/getting_started/customize_your_deployment.md
  docs/tutorials/getting_started/initialize_a_data_context.md
  sidebars.js
Labels: core-team

#3365 [FEATURE] Spark connecting to Google Cloud Storage
  azure-pipelines-docs-integration.yml
  docs/guides/connecting_to_your_data/cloud/s3/pandas.md
  docs/guides/connecting_to_your_data/cloud/s3/spark.md
  great_expectations/datasource/data_connector/configured_asset_azure_data_connector.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  tests/execution_engine/test_sparkdf_execution_engine.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/pandas/configured_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/pandas/configured_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/spark/configured_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/spark/configured_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/spark/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/spark/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/spark/python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/spark/yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/pandas/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/pandas/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/inferred_and_runtime_yaml_example.py
  tests/integration/test_script_runner.py
Labels: core-team

#3353 [DOCS] Docusaurus - How to connect to an MSSQL database
  azure-pipelines-docs-integration.yml
  docs/guides/connecting_to_your_data/components/adding_database_credentials.md
  docs/guides/connecting_to_your_data/database/mssql.md
  docs_rtd/changelog.rst
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/expectations/metrics/table_metrics/table_head.py
  tests/integration/docusaurus/connecting_to_your_data/database/mssql_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/mssql_yaml_example.py
  tests/integration/test_script_runner.py
Labels: docs, core-team, devrel

#3371 [DOCS] Clean up Docusaurus refs after changes made to integration tests
  docs/guides/connecting_to_your_data/cloud/gcs/pandas.md
  docs/guides/connecting_to_your_data/cloud/s3/pandas.md
  docs/guides/connecting_to_your_data/cloud/s3/spark.md
Labels: core-team

#3352 [FEATURE]/CLOUD-165/CLOUD-171/add_rendered_data_doc_store
  docs/changelog.md
  great_expectations/checkpoint/actions.py
  great_expectations/data_context/data_context.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/html_site_store.py
  great_expectations/data_context/store/json_site_store.py
  great_expectations/data_context/store/validations_store.py
  great_expectations/data_context/templates.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/render/renderer/site_builder.py
  great_expectations/render/types/__init__.py
  great_expectations/util.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context_ge_cloud_mode.py
  tests/render/fixtures/ValidationResultsPageRenderer_render_with_run_info_at_end.json
  tests/render/fixtures/ValidationResultsPageRenderer_render_with_run_info_at_start.json
Labels: core-team

#3360 [MAINTENANCE] Insure Correct Processing of the catch_exception Flag in Metrics Resolution
  great_expectations/checkpoint/checkpoint.py
  great_expectations/data_context/data_context.py
  great_expectations/validation_operators/validation_operators.py
  great_expectations/validator/validator.py
  tests/cli/test_checkpoint.py
  tests/expectations/test_expectation_arguments.py
  tests/validator/test_validator.py
Labels: core-team

#3361 [DOCS] Docusaurus - Deploying Great Expectations in a hosted environment without file system or CLI
  docs/deployment_patterns/how_to_instantiate_a_data_context_hosted_environments.md
  docs_rtd/changelog.rst
Labels: core-team, devrel

#3364 [BUGFIX] Insure that the "result_format" Expectation Argument is Processed Properly
  great_expectations/validator/validator.py
  tests/expectations/test_expectation_arguments.py
Labels: core-team

#3329 [BUGFIX] Adds expect_table_columns_to_match_set to kwarg_lookup_dict
  great_expectations/core/expectation_configuration.py
Labels: community

#3381 [WIP] Enhancement/cloud 169/update checkpoint.run for ge cloud
  great_expectations/checkpoint/actions.py
  great_expectations/checkpoint/checkpoint.py
  great_expectations/checkpoint/util.py
  great_expectations/core/util.py
  great_expectations/data_context/data_context.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/validations_store.py
  great_expectations/data_context/templates.py
  great_expectations/data_context/types/base.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/datasource/data_connector/runtime_data_connector.py
  great_expectations/validation_operators/validation_operators.py
  tests/actions/test_core_actions.py
  tests/checkpoint/test_simple_checkpoint.py
  tests/cli/test_checkpoint.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_ge_cloud_mode.py
Labels: core-team

#3347 [BUGFIX] fixed typo and added CLA links
  docs/contributing/contributing.md
Labels: core-team

#3359 [BUGFIX] fix error getting validation result from DataContext
  great_expectations/core/data_context_key.py
  tests/data_context/test_data_context.py
Labels: community

#3362 [FEATURE] Configurable multi-threaded checkpoint speedup
  docs/contributing/contributing_test.md
  docs_rtd/changelog.rst
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/async_executor.py
  great_expectations/data_context/data_context.py
  great_expectations/data_context/types/base.py
  great_expectations/datasource/new_datasource.py
  great_expectations/datasource/sqlalchemy_datasource.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/validation_operators/validation_operators.py
  tests/core/test_async_executor.py
  tests/data_context/test_concurrency_config.py
  tests/data_context/test_data_context_config_ui.py
  tests/data_context/test_data_context_ge_cloud_mode.py
  tests/data_context/test_data_context_v013.py
  tests/performance/results/initial_baseline.json
  tests/performance/results/initial_baseline_run_1.json
  tests/performance/results/initial_baseline_run_2.json
  tests/performance/results/initial_baseline_run_3.json
  tests/performance/results/minimal_multithreading_run_1.json
  tests/performance/results/minimal_multithreading_run_2.json
  tests/performance/results/minimal_multithreading_run_3.json
  tests/performance/run_benchmark_multiple_times.sh
  tests/performance/taxi_benchmark_util.py
  tests/performance/test_bigquery_benchmarks.py
Labels: community, devrel

#3399 [MAINTENANCE] Clean Up ValidationGraph API Usage, Improve Exception Handling for Metrics, Clean Up Type Hints
  great_expectations/checkpoint/checkpoint.py
  great_expectations/exceptions/exceptions.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/expectations/metrics/column_aggregate_metric_provider.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/metric_provider.py
  great_expectations/validator/validation_graph.py
  great_expectations/validator/validator.py
  tests/cli/test_checkpoint.py
  tests/expectations/metrics/test_core.py
  tests/expectations/test_expectation_arguments.py
  tests/validator/test_validator.py
Labels: core-team

#3377 [BUGFIX] Addresses issue #2993 (#3054) by using configuration when it is available instead of discovering keys (listing keys) in existing sources.
  docs/changelog.md
  great_expectations/checkpoint/actions.py
  great_expectations/data_context/data_context.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/validation_operators/validation_operators.py
  tests/data_context/store/test_evaluation_parameter_store.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context.py
Labels: community, devrel

#3413 [DOCS] minor fix to syntax highlighting in how_to_contribute_a_new_expectation…
  docs/guides/expectations/contributing/how_to_contribute_a_new_expectation_to_great_expectations.md
Labels: community

#3368 [MAINTENANCE] Performance improvement refactor for Spark unexpected values
  docs_rtd/changelog.rst
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/self_check/util.py
Labels: core-team

#3410 [DOCS][BUGFIX] Fix broken links in how_to_create_a_new_expectation_suite_using_rule_based_profile…
  docs/guides/expectations/advanced/how_to_create_a_new_expectation_suite_using_rule_based_profilers.md
  docs_rtd/changelog.rst
Labels: bug, community, devrel

#3438 Fix issue where BatchRequest cause Checkpoint run to fail
  great_expectations/checkpoint/util.py
  tests/checkpoint/test_checkpoint.py
Labels: core-team

#3434 [DOCS] Fix typo in command to create new checkpoint
  docs/tutorials/getting_started/validate_your_data.md
  docs_rtd/changelog.rst
Labels: community

#3448 [BUGFIX] Handle RuntimeBatchRequest passed to Checkpoint programatically (without yml)
  docs/changelog.md
  great_expectations/checkpoint/checkpoint.py
  great_expectations/checkpoint/util.py
  tests/checkpoint/test_checkpoint.py
Labels: core-team, devrel

#3440 [FEATURE] GREAT-3439 extended SlackNotificationsAction for slack app tokens
  docs/changelog.md
  docs/guides/validation/validation_actions/how_to_trigger_slack_notifications_as_a_validation_action.md
  great_expectations/checkpoint/actions.py
  great_expectations/checkpoint/util.py
  tests/actions/test_core_actions.py
Labels: community, devrel

#3457 [MAINTENANCE] Add helpful comments to integration test for introspection using SimpleSqlalchemyDatasource
  tests/integration/docusaurus/connecting_to_your_data/how_to_introspect_and_partition_your_data/sql_database/yaml_example.py
Labels: core-team

#3453 [ENHANCEMENT] cloud-199 - Update Expectation and ExpectationSuite classes for GE Cloud
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_suite.py
  great_expectations/core/util.py
  tests/core/test_expectation_suite_crud_methods.py
  tests/profile/test_jsonschema_profiler.py
Labels: core-team

#3436 [DOCS] How to validate data by running a Checkpoint
  docs/guides/validation/checkpoints/how_to_run_a_checkpoint_in_python.md
  docs/guides/validation/checkpoints/how_to_run_a_checkpoint_in_terminal.md
  docs/guides/validation/how_to_add_a_validation_operator.md
  docs/guides/validation/how_to_validate_data_by_running_a_checkpoint.md
  docs/guides/validation/validation_actions/how_to_update_data_docs_as_a_validation_action.md
  docs/sitemap.xml
  great_expectations/execution_engine/pandas_execution_engine.py
  sidebars.js
Labels: core-team

#3460 Does not test using numpy.float128 when it doesn't exist
  tests/data_asset/test_data_asset_util.py
Labels: core-team

#3467 [MAINTENANCE] Remove validation playground notebooks
  docs/changelog.md
  docs/tutorials/getting_started/initialize_a_data_context.md
  great_expectations/cli/cli_messages.py
  great_expectations/cli/init.py
  great_expectations/cli/v012/cli_messages.py
  great_expectations/data_context/data_context.py
  great_expectations/data_context/types/base.py
  great_expectations/init_notebooks/pandas/validation_playground.ipynb
  great_expectations/init_notebooks/spark/validation_playground.ipynb
  great_expectations/init_notebooks/sql/validation_playground.ipynb
  tests/cli/test_init.py
  tests/cli/test_init_missing_libraries.py
  tests/cli/test_init_pandas.py
  tests/cli/test_init_sqlite.py
  tests/cli/v012/test_init.py
  tests/cli/v012/test_init_pandas.py
  tests/cli/v012/test_init_sqlite.py
  tests/data_context/test_data_context.py
Labels: core-team, devrel
