Repository great-expectations/great_expectations, pull requests merged in 2021-07, with the labels that each got.

#2506 [BUGFIX] Fix issue where compression key was added to reader_method for read_parquet
  docs_rtd/changelog.rst
  great_expectations/core/util.py
  great_expectations/execution_engine/pandas_execution_engine.py
  tests/core/test_util.py
  tests/execution_engine/test_pandas_execution_engine.py
Labels: stale

#3105 [BUGFIX] Populate (data) asset name in data docs for RuntimeDataConnector
  docs_rtd/changelog.rst
  great_expectations/datasource/data_connector/runtime_data_connector.py
  tests/datasource/data_connector/test_runtime_data_connector.py
Labels: community

#3119 [BUGFIX] fix pip install snowflake build error with python 3.9
  docs_rtd/changelog.rst
  requirements-dev-sqlalchemy.txt
Labels: community, devrel

#3120 [DOCS] Correct path to docs_rtd/changelog.rst
  .github/workflows/changelog-bot.yml
  docs_rtd/changelog.rst
  docs_rtd/contributing/contribution_checklist.rst
Labels: community, devrel

#3127 [BUGFIX] Added newline to CLI message for consistent formatting
  great_expectations/cli/batch_request.py
  great_expectations/cli/suite.py
  great_expectations/cli/toolkit.py
  scripts/trace_docs_deps.py
  tests/cli/test_suite.py
Labels: community, devrel
