Repository great-expectations/great_expectations, pull requests merged in 2022-06, with the labels that each got.

#5226 [MAINTENANCE] Improve NaN handling in numeric ParameterBuilder implementations
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/types/attributed_resolved_metrics.py
Labels: core-team

#5230 [BUGFIX] Repair "CLI Suite --Profile" Operation
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/validation_operators/validation_operators.py
  great_expectations/validator/validator.py
  tests/cli/test_suite.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/test_fixtures/great_expectations_v013_no_datasource_stats_enabled.yml
Labels: core-team

#4907 [BUGFIX] Minor updates & org changes to contributor docs
  docs/contributing/contributing_checklist.md
  docs/contributing/contributing_package.md
  docs/guides/expectations/features_custom_expectations/how_to_add_input_validation_for_an_expectation.md
  docs/guides/expectations/features_custom_expectations/how_to_add_spark_support_for_an_expectation.md
  docs/guides/expectations/features_custom_expectations/how_to_add_sqlalchemy_support_for_an_expectation.md
  docs/guides/expectations/index.md
  sidebars.js
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_be_in_solfege_scale_set.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_only_contain_vowels.py
  tests/integration/test_script_runner.py
Labels: devrel

#5050 [DOCS] How to compare two tables with the UserConfigurableProfiler
  docs/guides/expectations/advanced/how_to_compare_two_tables_with_the_user_configurable_profiler.md
  docs/guides/expectations/index.md
  sidebars.js
  tests/integration/docusaurus/expectations/advanced/user_configurable_profiler_cross_table_comparison.py
  tests/integration/docusaurus/expectations/advanced/user_configurable_profiler_cross_table_comparison_from_query.py
  tests/integration/test_script_runner.py
Labels: devrel

#5236 [FEATURE] Replace UserConfigurableProfiler with OnboardingDataAssistant in "CLI suite new --profile" Jupyter Notebooks
  great_expectations/checkpoint/actions.py
  great_expectations/cli/suite.py
  great_expectations/core/batch.py
  great_expectations/render/renderer/notebook_renderer.py
  great_expectations/render/renderer/renderer.py
  great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/parameter_builder/mean_table_columns_set_match_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/validator/validator.py
  tests/cli/test_suite.py
  tests/integration/docusaurus/tutorials/getting-started/getting_started.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/render/test_renderer.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5206 [FEATURE] `DatasourceStore`
  great_expectations/data_context/store/__init__.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/types/base.py
  great_expectations/util.py
  scripts/check_docstring_coverage.py
  scripts/check_type_hint_coverage.py
  tests/conftest.py
  tests/data_context/store/test_datasource_store.py
Labels: core-team

#4956 [BUGFIX] Hive temporary tables creation fix
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/execution_engine/sqlalchemy_dialect.py
  requirements-dev-hive.txt
  requirements-dev-sqlalchemy.txt
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
  tests/execution_engine/test_sqlalchemy_dialect.py
  tests/test_packaging.py
Labels: community, devrel

#4964 [DOCS] Auto API documentation script
  docs/api_docs/classes/great_expectations-data_context-data_context-data_context-DataContext.md
  docs/api_docs/methods/great_expectations-data_context-data_context-data_context-DataContext-create.md
  docs/api_docs/methods/great_expectations-data_context-data_context-data_context-DataContext-test_yaml_config.md
  docs/guides/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config.md
  docs/guides/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config__api_links.mdx
  docs/terms/data_context.md
  docs/terms/data_context__api_links.mdx
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/data_context.py
  scripts/build_api_docs.py
  sidebars.js
Labels: devrel

#5188 [FEATURE] add new expectation on validating hexadecimals
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_hexadecimal.py
Labels: community, devrel

#5252 [MAINTENANCE] Don't use jupyter-client 7.3.2
  constraints-dev.txt
Labels: core-team

#5253 MAINTENANCE] undo commit 2b0ca859ff7d56ee7cf9f4694e78ba4b71abd513
  constraints-dev.txt
Labels: core-team

#5251 [FEATURE] Usage Statistics Events for Profiler and DataAssistant "get_expectation_suite()" methods.
  great_expectations/core/usage_statistics/anonymizers/anonymizer.py
  great_expectations/core/usage_statistics/anonymizers/batch_request_anonymizer.py
  great_expectations/core/usage_statistics/anonymizers/checkpoint_anonymizer.py
  great_expectations/core/usage_statistics/anonymizers/profiler_anonymizer.py
  great_expectations/core/usage_statistics/events.py
  great_expectations/core/usage_statistics/schemas.py
  great_expectations/core/usage_statistics/usage_statistics.py
  great_expectations/core/usage_statistics/usage_statistics_record_schema.json
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/rule_based_profiler/rule_based_profiler_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  tests/cli/test_suite.py
  tests/core/usage_statistics/test_usage_stats_schema.py
  tests/integration/docusaurus/tutorials/getting-started/getting_started.py
  tests/integration/profiling/rule_based_profilers/test_rule_based_profiler.py
  tests/integration/usage_statistics/test_usage_statistics_messages.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5216 [FEATURE] `InlineStoreBackend`
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/store/__init__.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/data_context/types/base.py
  scripts/check_type_hint_coverage.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/store/test_store_dynamic_loading.py
Labels: core-team

#5254 [MAINTENANCE] Add `cloud` mark to `pytest.ini`
  pytest.ini
Labels: core-team

#5250 [DOCS] Update DataContext docstring
  docs/api_docs/classes/great_expectations-data_context-data_context-data_context-DataContext.md
  docs/api_docs/methods/great_expectations-data_context-data_context-data_context-DataContext-create.md
  docs/api_docs/methods/great_expectations-data_context-data_context-data_context-DataContext-test_yaml_config.md
  great_expectations/data_context/data_context/data_context.py
Labels: core-team

#5256 [BUGFIX] Provide error handling when metric fails for all Batch data samples
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/types/attributed_resolved_metrics.py
Labels: core-team

#5255 [MAINTENANCE] `DataContextVariableKey` for use in Stores
  great_expectations/core/data_context_key.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/data_context/types/data_context_variables.py
  scripts/check_docstring_coverage.py
  scripts/check_type_hint_coverage.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_store_backends.py
Labels: core-team

#5257 [MAINTENANCE] Clarification of events in test with multiple checkpoint validations
  tests/checkpoint/test_checkpoint.py
Labels: core-team

#5258 [FEATURE] The "column.histogram" metric must support integer values of the "bins" parameter for all execution engine options.
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
  tests/expectations/metrics/test_core.py
Labels: core-team

#5244 [MAINTENANCE] Misc updates to improve security and automation of the weekly release process
  .github/workflows/release-cut.yml
  azure-pipelines.yml
  tests/test_release.py
Labels: core-team

#5238 [FEATURE] Initial implementation of `DataContextVariables` accessors
  great_expectations/core/data_context_key.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/store/__init__.py
  great_expectations/data_context/store/data_context_variables_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/data_context/types/data_context_variables.py
  great_expectations/util.py
  scripts/check_type_hint_coverage.py
  tests/conftest.py
  tests/core/test_expectation_suite_crud_methods.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5208 [FEATURE] `OnboardingDataAssistant` plots for `expect_table_columns_to_match_set`
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/onboarding_data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/plot_components.py
  great_expectations/rule_based_profiler/types/data_assistant_result/volume_data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5267 [MAINTENANCE] Add proper unit tests for Column Histogram metric and use Column Value Partitioner in OnboardingDataAssistant
  great_expectations/execution_engine/util.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/parameter_builder/metric_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/partition_parameter_builder.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  tests/expectations/metrics/test_core.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/integration/profiling/rule_based_profilers/test_rule_based_profiler.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/parameter_builder/test_partition_parameter_builder.py
Labels: core-team

#4909 [MAINTENANCE] Updates contributor docs to reflect updated linting guidance
  docs/contributing/contributing_maturity.md
  docs/guides/expectations/contributing/how_to_contribute_a_custom_expectation_to_great_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_table_expectations.md
  docs/guides/expectations/creating_custom_expectations/overview.md
Labels: devrel

#5262 [FEATURE] `DataContextVariables` CRUD for `config_variables_file_path`
  great_expectations/data_context/types/data_context_variables.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5270 [MAINTENANCE] Remove condition from `autoupdate` GitHub action
  .github/workflows/autoupdate.yml
Labels: core-team

#5264 [FEATURE] `DataContextVariables` CRUD for store name accessors
  great_expectations/data_context/types/data_context_variables.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5278 [BUGFIX] Patch automated release test date comparisons
  tests/test_release.py
Labels: core-team

#5279 [MAINTENANCE] Improve code readability in the processing section of "MapMetricColumnDomainBuilder".
  great_expectations/rule_based_profiler/domain_builder/map_metric_column_domain_builder.py
Labels: core-team

#5282 [BUGFIX] Fix ColumnPartition metric handling of the number of bins (must always be integer).
  great_expectations/expectations/metrics/column_aggregate_metrics/column_partition.py
Labels: core-team

#5269 [FEATURE] `DataContextVariables` CRUD for `data_docs_sites`
  great_expectations/data_context/types/data_context_variables.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5272 [FEATURE] `DataContextVariables` CRUD for `notebooks`
  great_expectations/data_context/types/data_context_variables.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5273 [FEATURE] `DataContextVariables` CRUD for `concurrency`
  great_expectations/data_context/types/base.py
  great_expectations/data_context/types/data_context_variables.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5274 [FEATURE] `DataContextVariables` CRUD for `progress_bars`
  great_expectations/data_context/types/data_context_variables.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5266 [DOCS] how to create an expectation suite with the onboarding assistant
  docs/guides/connecting_to_your_data/components/prerequisites.jsx
  docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.md
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  sidebars.js
  tests/integration/docusaurus/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.py
  tests/integration/test_script_runner.py
Labels: devrel

#5276 [BUGFIX] Add new high precision rule for mean and stdev in `OnboardingDataAssistant`
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  tests/cli/test_suite.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
Labels: core-team

#5294 [DOCS] update getting started tutorial for onboarding assistant
  docs/images/getting_started_tutorial/tutorial_create_expectations_cell3_onboarding_assistant.png
  docs/tutorials/getting_started/tutorial_create_expectations.md
  tests/integration/docusaurus/tutorials/getting-started/getting_started.py
Labels: devrel

#5295 [DOCS] getting started tutorial doc standards updates
  docs/tutorials/getting_started/tutorial_connect_to_data.md
  docs/tutorials/getting_started/tutorial_create_expectations.md
  tests/integration/docusaurus/tutorials/getting-started/getting_started.py
Labels: devrel

#5259 [MAINTENANCE] `DataAssistantResult` cleanup and extensibility enhancements
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/onboarding_data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/volume_data_assistant_result.py
Labels: core-team

#5298 [MAINTENANCE] Handle compare Expectation in presence of high precision floating point numbers and NaN values
  great_expectations/datasource/data_connector/runtime_data_connector.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/expectation.py
  great_expectations/render/renderer/datasource_new_notebook_renderer.py
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  tests/cli/test_suite.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
Labels: core-team

#5052 [DOCS] Update standard arguments doc for Expectations to not reference datasets.
  docs/reference/expectations/standard_arguments.md
Labels: devrel

#5305 [MAINTENANCE] Suppress persisting of temporary ExpectationSuite configurations in Rule-Based Profiler computations
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/helpers/util.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/parameter_builder/test_regex_pattern_string_parameter_builder.py
Labels: core-team

#5292 [FEATURE] Integrate `DatasourceStore` with `DataContext`
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/util.py
  scripts/check_docstring_coverage.py
  scripts/check_type_hint_coverage.py
  tests/conftest.py
  tests/data_context/store/test_store_backends.py
Labels: core-team

#5302 Adds column values github user validation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_github_username.py
Labels: devrel

#5303 Adds column values IATA code validation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_iata_code.py
Labels: devrel

#5304 Adds column values ARN validation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_arn.py
Labels: devrel

#5306 [FEATURE] Support both UserConfigurableProfiler and OnboardingDataAssistant in "CLI SUITE NEW --PROFILE <name>" command
  great_expectations/cli/suite.py
  great_expectations/render/renderer/suite_scaffold_notebook_renderer.py
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  tests/cli/test_suite.py
  tests/integration/docusaurus/tutorials/getting-started/getting_started.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
Labels: core-team

#5310 [MAINTENANCE] Fixing a typo in a comment (in several files)
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  tests/cli/test_suite.py
  tests/integration/docusaurus/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
Labels: core-team

#5312 lint fixes
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_scientific_notation.py
Labels: devrel

#5297 [BUGFIX] Warning in Getting Started Guide notebook.
  docs/tutorials/getting_started/tutorial_connect_to_data.md
  great_expectations/cli/datasource.py
  tests/cli/test_datasource_new_helpers.py
  tests/cli/test_datasource_new_pandas_paths.py
  tests/cli/test_datasource_pandas.py
  tests/integration/docusaurus/tutorials/getting-started/getting_started.py
Labels: core-team

#5313 Adds column value JSON validation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_json.py
Labels: devrel

#5316 [RELEASE] 0.15.10
  .github/release_schedule.json
  docs/changelog.md
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team

#5318 [BUGFIX] Update `test_basic_spark_datasource_self_check` to work with all supported versions of PySpark
  tests/datasource/test_new_datasource.py
Labels: core-team

#5242 Fix link in suite profile renderer
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
Labels: community, devrel

#5308 [DOCS] mark onboarding assistant guide as experimental and update cli command
  docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.md
Labels: devrel

#5286 [MAINTENANCE] Refactor of `_apply_global_config_overrides()` method to return config
  great_expectations/data_context/data_context/base_data_context.py
  tests/cli/test_datasource_pandas.py
  tests/cli/test_datasource_sqlite.py
  tests/cli/test_project.py
  tests/conftest.py
  tests/integration/docusaurus/miscellaneous/migration_guide_postgresql_v3_api.py
Labels: core-team

#5320 [MAINTENANCE] Remove "json_serialize" directive from ParameterBuilder computations
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_match_regex.py
  great_expectations/expectations/core/expect_column_values_to_match_strftime_format.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex.py
  great_expectations/expectations/core/expect_table_columns_to_match_set.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/rule_based_profiler/config/base.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/expectation_configuration_builder/expectation_configuration_builder.py
  great_expectations/rule_based_profiler/parameter_builder/mean_table_columns_set_match_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/mean_unexpected_map_metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/partition_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/rule/rule.py
  great_expectations/rule_based_profiler/rule_based_profiler_result.py
  great_expectations/rule_based_profiler/types/__init__.py
  great_expectations/rule_based_profiler/types/parameter_container.py
  tests/conftest.py
  tests/datasource/test_new_datasource.py
  tests/integration/profiling/rule_based_profiler/__init__.py
  tests/integration/profiling/rule_based_profiler/test_profiler_basic_workflows.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/integration/profiling/rule_based_profiler/test_rule_based_profiler.py
  tests/integration/profiling/rule_based_profiler/test_run_profiler_notebook.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/parameter_builder/test_mean_table_columns_set_match_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_mean_unexpected_map_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_partition_parameter_builder.py
  tests/rule_based_profiler/test_rule_based_profiler.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/SelfInitializingExpectations.ipynb
Labels: core-team

#5323 [FEATURE] Enable NumericMetricRangeMultiBatchParameterBuilder to use evaluation dependencies
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
Labels: core-team

#5327 [MAINTENANCE] Standardize instantiation of NumericMetricRangeMultibatchParameterBuilder throughout the codebase.
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  tests/conftest.py
  tests/core/test_expectation_suite.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
Labels: core-team

#5329 [MAINTENANCE] Reuse MetricMultiBatchParameterBuilder computation results as evaluation dependencies for performance enhancement
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5331 [MAINTENANCE] clean up type declarations
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
Labels: core-team

#5114 [FEATURE] added support to Aws Athena quantiles
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  scripts/check_type_hint_coverage.py
Labels: community

#5336 [BUGFIX] Numpy dtype.float64 formatted floating point numbers must be converted to Python float for use in SQLAlchemy Boolean clauses
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
Labels: core-team

#5338 [FEATURE] Implement the "column.standard_deviation" metric for sqlite database
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_mean.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_standard_deviation.py
  great_expectations/self_check/util.py
  great_expectations/util.py
  tests/datasource/conftest.py
Labels: core-team

#5349 [MAINTENANCE] Update release schedule JSON
  .github/release_schedule.json
  .github/workflows/release-prep.yml
  tests/test_release.py
Labels: core-team

#5334 [FEATURE] Update `add_datasource` to leverage the `DatasourceStore`
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/data_context/types/base.py
  scripts/check_type_hint_coverage.py
Labels: core-team

#5360 [MAINTENANCE] Include only essential public methods in DataAssistantResult class (and its descendants)
  great_expectations/rule_based_profiler/data_assistant/data_assistant_dispatcher.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
Labels: core-team

#5363 [MAINTENANCE] Update `release-prep` GitHub action to ensure `ge_releaser` tool is not included in output PR
  .github/workflows/release-prep.yml
Labels: core-team

#5362 [MAINTENANCE] Reduce output amount in Jupyter notebooks when displaying DataAssistantResult
  great_expectations/core/expectation_validation_result.py
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  tests/integration/docusaurus/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
Labels: core-team

#5367 [MAINTENANCE] Update linter thresholds
  scripts/check_type_hint_coverage.py
Labels: core-team

#5285 [MAINTENANCE] Move `_apply_global_config_overrides()` to AbstractDataContext
  great_expectations/data_context/__init__.py
  great_expectations/data_context/data_context/__init__.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  pytest.ini
  tests/cli/test_datasource_sqlite.py
  tests/core/usage_statistics/test_usage_statistics.py
  tests/data_context/conftest.py
  tests/data_context/test_base_data_context.py
Labels: core-team

#5368 [FEATURE] Add Rule Statistics to DataAssistantResult for display in Jupyter notebook
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
Labels: core-team

#5375 [FEATURE] Include detailed Rule Execution statistics in jupyter notebook "repr" style output
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/rule/rule.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/rule_based_profiler/rule_based_profiler_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/rule_state.py
Labels: core-team

#5225 Replace string formatting with f-string
  great_expectations/core/usage_statistics/anonymizers/profiler_anonymizer.py
  great_expectations/core/util.py
  great_expectations/data_asset/data_asset.py
  great_expectations/data_asset/util.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/data_context/util.py
  great_expectations/dataset/pandas_dataset.py
  great_expectations/dataset/sparkdf_dataset.py
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/datasource/batch_kwargs_generator/batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/glob_reader_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/s3_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/s3_subdir_reader_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/subdir_reader_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/table_batch_kwargs_generator.py
  great_expectations/datasource/datasource.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_match_like_pattern_list.py
  great_expectations/expectations/regex_based_column_map_expectation.py
  great_expectations/render/renderer/page_renderer.py
  great_expectations/rule_based_profiler/config/base.py
  great_expectations/rule_based_profiler/expectation_configuration_builder/expectation_configuration_builder.py
  great_expectations/util.py
  great_expectations/validator/validator.py
  scripts/docs_link_checker.py
  scripts/validate_docs_snippet_line_numbers.py
  tests/datasource/batch_kwarg_generator/test_s3_subdir_reader_generator.py
  tests/integration/profiling/rule_based_profiler/test_run_profiler_notebook.py
Labels: community, devrel

#5340 Fix links in docs
  docs/api_docs/classes/great_expectations-data_context-data_context-data_context-DataContext.md
  docs/api_docs/methods/great_expectations-data_context-data_context-data_context-DataContext-create.md
  docs/api_docs/methods/great_expectations-data_context-data_context-data_context-DataContext-test_yaml_config.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
Labels: community, devrel

#5376 [MAINTENANCE] Caching of `config_variables` in `DataContext`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/util.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_config_variables.py
  tests/data_context/test_data_context_v013.py
  tests/integration/test_script_runner.py
Labels: core-team

#5390 [MAINTENANCE] StaleBot Half DryRun
  .github/workflows/stale.yml
Labels: devrel

#5391 [Maintenance] StaleBot DryRun 2
  .github/workflows/stale.yml
Labels: devrel

#5399 file extentions applied to rel links
  docs/api_docs/classes/great_expectations-data_context-data_context-data_context-DataContext.md
  docs/api_docs/methods/great_expectations-data_context-data_context-data_context-DataContext-create.md
  docs/api_docs/methods/great_expectations-data_context-data_context-data_context-DataContext-test_yaml_config.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
Labels: devrel

#5382 [MAINTENANCE] Allow installing jinja2 version 3.1.0 and higher
  great_expectations/render/view/view.py
  requirements.txt
Labels: devrel

#5410 [MAINTENANCE] Ensure that changes made to env vars / config vars are recognized within subsequent calls of the same process
  tests/data_context/test_data_context.py
Labels: core-team

#5386 [DOCS] Add sqlalchemy-redshfit to dependencies in redshift doc
  docs/guides/connecting_to_your_data/database/redshift.md
Labels: devrel

#5411 [MAINTENANCE] Keep all Pandas Splitter Tests in a Dedicated Module
  great_expectations/execution_engine/split_and_sample/data_splitter.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_splitter.py
  tests/conftest.py
  tests/execution_engine/conftest.py
  tests/execution_engine/split_and_sample/test_pandas_execution_engine_splitting.py
  tests/execution_engine/test_pandas_execution_engine.py
Labels: core-team

#5366 [MAINTENANCE] Refactor `DataContextVariables` to only persist state to Store using explicit save command
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/data_context/store/__init__.py
  great_expectations/data_context/store/data_context_store.py
  great_expectations/data_context/store/data_context_variables_store.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/util.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5412 [MAINTENANCE] Refactor to put tests for splitting and sampling into modules for respective ExecutionEngine implementation
  tests/execution_engine/conftest.py
  tests/execution_engine/split_and_sample/test_pandas_execution_engine_sampling.py
  tests/execution_engine/split_and_sample/test_sparkdf_execution_engine_sampling.py
  tests/execution_engine/split_and_sample/test_sparkdf_execution_engine_splitting.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
  tests/execution_engine/test_pandas_execution_engine.py
  tests/execution_engine/test_sparkdf_execution_engine.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
Labels: core-team

#5419 [MAINTENANCE] Change property name of TaxiSplittingTestCase to make it more general
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
  tests/integration/db/test_sql_data_splitting.py
  tests/integration/fixtures/split_and_sample_data/splitter_test_cases_and_fixtures.py
Labels: core-team
