Repository great-expectations/great_expectations, pull requests merged in 2022-08, with the labels that each got.

#5636 [BUGFIX] Remove datasource from config on delete
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/data_context/abstract_data_context/__init__.py
  tests/data_context/abstract_data_context/test_datasource_delete.py
Labels: core-team

#5576 [MAINTENANCE] type-checking round 2
  .gitignore
  docs/contributing/style_guides/code_style.md
  great_expectations/core/expectation_diagnostics/expectation_test_data_cases.py
  great_expectations/data_asset/data_asset.py
  great_expectations/exceptions/exceptions.py
  great_expectations/jupyter_ux/__init__.py
  great_expectations/jupyter_ux/expectation_explorer.py
  great_expectations/self_check/util.py
  great_expectations/types/base.py
  tasks.py
Labels: core-team

#5641 [MAINTENANCE] minor cleanup of old comments
  great_expectations/expectations/metrics/column_map_metrics/column_values_between.py
Labels: core-team

#5644 [BUGFIX] Patch issue with usage stats sync not respecting usage stats opt-out
  great_expectations/data_context/data_context/data_context.py
  tests/data_context/test_data_context.py
Labels: core-team

#5639 [MAINTENANCE] add `--clear-cache` flag for `invoke type-check`
  tasks.py
Labels: core-team

#5645 [MAINTENANCE] Install `dgtest` test runner utilizing Git URL in CI
  azure-pipelines-dependency-graph-testing.yml
Labels: core-team

#5630 [BUGFIX] Fix table.head metric issue when using BQ without temp tables
  great_expectations/expectations/metrics/table_metrics/table_head.py
  tests/integration/db/bigquery.py
Labels: devrel

#5640 [FEATURE] Enable retrieve by name for datasource with cloud store backend
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/data_context/store/store_backend.py
  great_expectations/data_context/types/resource_identifiers.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
  tests/data_context/store/test_store_backends.py
Labels: core-team

#5638 [FEATURE] Update `DataContext.add_checkpoint()` to ensure validations within `CheckpointConfig` contain ids
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/store/store_backend.py
  scripts/check_type_hint_coverage.py
  tests/data_context/cloud_data_context/conftest.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/conftest.py
Labels: core-team

#5642 Make comparisons of aggregate values date aware
  great_expectations/expectations/expectation.py
  tests/test_definitions/column_aggregate_expectations/expect_column_max_to_be_between.json
Labels: core-team

#5653 [MAINTENANCE] Add E2E Cloud test for `DataContext.add_checkpoint()`
  great_expectations/data_context/store/checkpoint_store.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
Labels: core-team

#5646 [MAINTENANCE] Use docker to run tests in the Azure CI pipeline.
  azure-pipelines.yml
  docker/Dockerfile.tests
  great_expectations/core/usage_statistics/package_dependencies.py
  requirements-dev-test-pipeline.txt
Labels: core-team

#5593 [ANALYTICS] add new invoke tasks to `tasks.py` and create new file `usage_stats_utils.py`
  tasks.py
  tests/integration/usage_statistics/usage_stats_utils.py
Labels: core-team, analytics

#5659 [MAINTENANCE] Don't include 'test-pipeline' in extras_require dict
  setup.py
Labels: devrel

#5580 [FEATURE] Add `expect_column_values_to_be_valid_crc32`
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_crc32.py
Labels: community, devrel

#5649 [MAINTENANCE] move tool config to pyproject.toml
  .isort.cfg
  .pre-commit-config.yaml
  azure-pipelines-contrib.yml
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
  contrib/cli/requirements.txt
  mypy.ini
  pyproject.toml
  pytest.ini
  requirements-dev-contrib.txt
  tasks.py
Labels: core-team

#5665 [MAINTENANCE] Refactor docker test CI steps into jobs.
  azure-pipelines.yml
Labels: core-team

#5670 [MAINTENANCE] Only run Cloud E2E tests in primary pipeline
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
Labels: core-team

#5656 [MAINTENANCE] Improve DateTime Conversion Candling in Comparison Metrics & Expectations and Provide a Clean Object Model for Metrics Computation Bundling
  great_expectations/core/util.py
  great_expectations/execution_engine/bundled_metric_configuration.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_between.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/util.py
  tests/cli/v012/test_datasource_sqlite.py
  tests/core/test_serialization.py
  tests/execution_engine/test_pandas_execution_engine.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/test_definitions/column_aggregate_expectations/expect_column_max_to_be_between.json
Labels: core-team

#5660 [MAINTENANCE] Ensure that `id_` fields in Marshmallow schema serialize as `id`
  great_expectations/data_context/types/base.py
  great_expectations/rule_based_profiler/config/base.py
  tests/core/test_serialization.py
  tests/datasource/test_datasource_serialization.py
  tests/rule_based_profiler/test_rule_based_profiler_serialization.py
Labels: core-team

#5673 [FEATURE]Enable showing expectation suite by domain and by expectation_type -- from DataAssistantResult
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
Labels: core-team

#5662 [MAINTENANCE] data_context initial type checking
  great_expectations/data_context/types/base.py
  great_expectations/data_context/types/resource_identifiers.py
  tasks.py
Labels: core-team

#5678 [MAINTENANCE]DEVREL-2289/StaleBot/Text_formatting-Tidy-MoreOp
  .github/workflows/stale.yml
Labels: core-team, devrel, maintenance

#5677 [BUGFIX] Patch bug with `id` vs `id_` in Cloud integration tests
  azure-pipelines.yml
  great_expectations/data_context/data_context/cloud_data_context.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
Labels: core-team

#5671 [MAINTENANCE] Assign `resource_type` in `InlineStoreBackend` constructor
  great_expectations/core/data_context_key.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/data_context/store/store_backend.py
  tests/cli/v012/test_suite.py
  tests/cli/v012/test_suite_pre_v013.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_store_backends.py
Labels: core-team

#5536 [DOCS]added guide how to use great expectations with aws glue
  docs/deployment_patterns/how_to_use_great_expectations_in_aws_glue.md
  docs/sitemap.xml
  sidebars.js
  tests/integration/docusaurus/deployment_patterns/aws_glue_deployment_patterns.py
  tests/integration/docusaurus/deployment_patterns/aws_glue_deployment_patterns_great_expectations.yaml
  tests/integration/test_script_runner.py
Labels: docs, community

#5681 [MAINTENANCE] Add mysql client to Dockerfile.tests
  docker/Dockerfile.tests
Labels: core-team

#5631 [MAINTENANCE] `RuleBasedProfiler` corner case configuration changes
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/rule/rule.py
  tests/cli/test_suite.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/parameter_builder/test_parameter_computations.py
  tests/rule_based_profiler/test_rule_based_profiler.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/SelfInitializingExpectations.ipynb
Labels: core-team

#5687 [BUGFIX] Fixing a typo in variable name for default profiler for auto-initializing expectation "expect_column_mean_to_be_between"
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
Labels: core-team

#5684 [MAINTENANCE] Update teams.yml
  .github/teams.yml
Labels: core-team

#5690 [BUGFIX] Remove `resource_type` from call to `StoreBackend.build_key`
  great_expectations/data_context/store/datasource_store.py
Labels: core-team

#5691 [MAINTENANCE] Utilize `e2e` mark on E2E Cloud tests
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/test_base_data_context.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5692 [MAINTENANCE] pyproject.tooml build-system typo
  pyproject.toml
Labels: core-team, maintenance

#5676 [MAINTENANCE] expand flake8 coverage
  .pre-commit-config.yaml
  azure-pipelines-contrib.yml
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
  docker/build.py
  docs_rtd/conf.py
  docs_rtd/feature_annotation_parser.py
  examples/expectations/query_expectation_template.py
  great_expectations/core/batch.py
  great_expectations/core/evaluation_parameters.py
  great_expectations/core/usage_statistics/anonymizers/checkpoint_anonymizer.py
  great_expectations/core/util.py
  great_expectations/data_asset/data_asset.py
  great_expectations/data_asset/file_data_asset.py
  great_expectations/data_asset/util.py
  great_expectations/exceptions/__init__.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/util.py
  great_expectations/validation_operators/validation_operators.py
  great_expectations/validator/validator.py
  requirements-dev-contrib.txt
  scripts/validate_docs_snippet_line_numbers.py
  setup.cfg
  tasks.py
Labels: core-team

#5695 [MAINTENANCE] Ensure Cloud E2E tests are isolated to `gx-cloud-e2e` stage of CI
  azure-pipelines.yml
Labels: core-team

#5682 [MAINTENANCE] Add usage stats and initial database docker tests to CI
  azure-pipelines.yml
Labels: core-team

#5699 [MAINTENANCE] Add `e2e` mark to `pyproject.toml`
  pyproject.toml
Labels: core-team

#5683 [FEATURE] Example notebooks for multi-batch Spark
  tests/integration/profiling/rule_based_profiler/test_run_profiler_notebook.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_ConfiguredAssetFileSystemExample_Pandas.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_ConfiguredAssetFileSystemExample_Spark.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_InferredAssetFileSystemExample_Pandas.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_InferredAssetFileSystemExample_Spark.ipynb
Labels: core-team

#5701 [MAINTENANCE] Update docker readme to mount your repo over the builtin one.
  docker/README.md
Labels: core-team

#5702 [CONTRIB] ExpectColumnValuesToBeInSetSparkOptimized
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_in_set_spark_optimized.py
Labels: devrel

#5661 [CONTRIB] expect_column_pair_values_to_have_difference_of_custom_perc…
  contrib/experimental/great_expectations_experimental/expectations/expect_column_pair_values_to_have_difference_of_custom_percentage.py
Labels: community, devrel

#5700 Remove non-docker version of CI tests that are now running in docker.
  azure-pipelines.yml
Labels: core-team

#5694 [MAINTENANCE]DEVREL-2289/Stale/Triage
  .github/workflows/stale.yml
Labels: core-team, devrel, maintenance

#5696 [BUGFIX]Updated how_to_use_great_expectations_in_aws_glue.md again
  docs/deployment_patterns/how_to_use_great_expectations_in_aws_glue.md
Labels: community, devrel

#5672 [DOCS] Document the ZenML integration for Great Expectations
  docs/deployment_patterns/index.md
  docs/integrations/index.md
  docs/integrations/integration_zenml.md
  sidebars.js
Labels: community, devrel

#5706 [MAINTENANCE] revert expansive flake8 pre-commit checking - flake8 5.0.4
  .pre-commit-config.yaml
  azure-pipelines-contrib.yml
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
  requirements-dev-contrib.txt
Labels: core-team

#5714 [DOCS] Converts broken ZenML md refs to Technical Tags
  docs/integrations/integration_zenml.md
Labels: devrel

#5460 [DOCS] How to create a Custom Query Expectation
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_query_expectations.md
  docs/guides/expectations/index.md
  great_expectations/expectations/metrics/query_metrics/query_table.py
  sidebars.js
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_queried_column_value_frequency_to_meet_threshold.py
  tests/integration/test_script_runner.py
Labels: devrel

#5704 [MAINTENANCE] Bugfix for `cloud-db-integration-pipeline`
  great_expectations/data_context/data_context/base_data_context.py
  tests/test_definitions/column_aggregate_expectations/expect_column_stdev_to_be_between.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_unique.json
  tests/test_definitions/test_expectations.py
  tests/test_definitions/test_expectations_cfe.py
Labels: core-team

#5716 [MAINTENANCE] Remove pytest-azurepipelines
  azure-pipelines.yml
  requirements-dev-test-pipeline.txt
Labels: core-team

#5693 [FEATURE] Introduce top-level `default_validation_id` in `CheckpointConfig`
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/types/base.py
  tests/checkpoint/test_checkpoint.py
  tests/checkpoint/test_simple_checkpoint.py
  tests/core/test_serialization.py
Labels: core-team

#5717 [MAINTENANCE] Remove deprecation warning from `DataConnector`-level `batch_identifiers` for `RuntimeDataConnector`
  great_expectations/datasource/data_connector/runtime_data_connector.py
Labels: core-team

#5698 [MAINTENANCE] Refactor `AbstractConfig` to make `name` and `id_` consistent attrs
  great_expectations/core/configuration.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/types/base.py
  great_expectations/datasource/data_connector/asset/asset.py
  great_expectations/rule_based_profiler/config/base.py
  great_expectations/types/__init__.py
  scripts/check_type_hint_coverage.py
  tests/core/test_serialization.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
  tests/data_context/test_data_context_profilers.py
  tests/integration/profiling/rule_based_profiler/test_profiler_basic_workflows.py
Labels: core-team

#5719 [MAINTENANCE] Move CLI tests to docker
  azure-pipelines.yml
Labels: core-team

#5715 [MAINTENANCE] Leverage `DataContextVariables` in `DataContext` hierarchy to automatically determine how to persist changes
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/store/inline_store_backend.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5679 [MAINTENANCE] Refactor `InMemoryStoreBackend` out of `store_backend.py`
  great_expectations/data_context/store/__init__.py
  great_expectations/data_context/store/_store_backend.py
  great_expectations/data_context/store/in_memory_store_backend.py
  great_expectations/data_context/store/store_backend.py
Labels: core-team

#5725 [FEATURE] Pass down validation ids to `ExpectationSuiteValidationResult.meta` within `Checkpoint.run()`
  great_expectations/checkpoint/checkpoint.py
  great_expectations/checkpoint/util.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/validation_operators/validation_operators.py
  tests/checkpoint/test_checkpoint.py
Labels: core-team

#5728 [MAINTENANCE] Move compatibility matrix tests to docker
  azure-pipelines.yml
  requirements.txt
  tests/test_great_expectations.py
Labels: core-team

#5727 [FEATURE] Refactor data assistant runner to compute formal parameters for data assistant run method signatures
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/helpers/runtime_environment.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  requirements.txt
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5729 Adds additional file extensions for Parquet assets
  great_expectations/datasource/batch_kwargs_generator/s3_subdir_reader_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/subdir_reader_batch_kwargs_generator.py
  great_expectations/datasource/pandas_datasource.py
  great_expectations/datasource/sparkdf_datasource.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
Labels: devrel

#5733 Linting profile
  great_expectations/profile/basic_dataset_profiler.py
  great_expectations/profile/basic_suite_builder_profiler.py
  great_expectations/profile/user_configurable_profiler.py
  setup.cfg
Labels: core-team

#5735 [MAINTENANCE] Introduce NumericRangeEstimator class hierarchy and encapsulate existing estimator implementations
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/estimators/__init__.py
  great_expectations/rule_based_profiler/estimators/bootstrap_numeric_range_estimator.py
  great_expectations/rule_based_profiler/estimators/exact_numeric_range_estimator.py
  great_expectations/rule_based_profiler/estimators/kde_numeric_range_estimator.py
  great_expectations/rule_based_profiler/estimators/numeric_range_estimation_result.py
  great_expectations/rule_based_profiler/estimators/numeric_range_estimator.py
  great_expectations/rule_based_profiler/estimators/oneshot_numeric_range_estimator.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_parameter_computations.py
  tests/test_fixtures/rule_based_profiler/bobby_user_workflow_verbose_profiler_config.yml
Labels: core-team

#5731 [DOCS] Fixing the logo on the RTD docs page with an s3 hosted logo image file
  docs_rtd/_templates/layout.html
Labels: devrel

#5746 [MAINTENANCE] Pin makefun package to version range for support assurance
  requirements.txt
Labels: core-team

#5556 [FEATURE] `DataAssistantResult` plot multiple metrics per expectation
  great_expectations/profile/basic_dataset_profiler.py
  great_expectations/profile/basic_suite_builder_profiler.py
  great_expectations/profile/user_configurable_profiler.py
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/data_assistant_result/onboarding_data_assistant_result.py
  great_expectations/rule_based_profiler/data_assistant_result/plot_components.py
  great_expectations/rule_based_profiler/data_assistant_result/plot_result.py
  great_expectations/rule_based_profiler/data_assistant_result/volume_data_assistant_result.py
  great_expectations/rule_based_profiler/helpers/util.py
  setup.cfg
  tests/rule_based_profiler/data_assistant/test_data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5740 [MAINTENANCE] Add ids to `DataConnectorConfig`
  great_expectations/data_context/types/base.py
  great_expectations/datasource/data_connector/configured_asset_azure_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_dbfs_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_filesystem_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_gcs_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_s3_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py
  great_expectations/datasource/data_connector/data_connector.py
  great_expectations/datasource/data_connector/file_path_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_azure_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_dbfs_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_file_path_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_filesystem_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_gcs_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_s3_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py
  great_expectations/datasource/data_connector/runtime_data_connector.py
  tests/datasource/data_connector/test_data_connector_serialization.py
  tests/datasource/test_datasource_serialization.py
Labels: core-team

#5751 [BUGFIX] dir update for data_assistant_result
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
Labels: core-team

#5748 [MAINTENANCE] Rename GX Cloud "contract" resource to "checkpoint"
  great_expectations/checkpoint/actions.py
  great_expectations/checkpoint/checkpoint.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/validations_store.py
  tests/actions/conftest.py
  tests/actions/test_core_actions.py
  tests/conftest.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/conftest.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context_ge_cloud_mode.py
Labels: core-team

#5734 [BUGFIX] Fix docs_integration pipeline
  azure-pipelines-docs-integration.yml
  great_expectations/data_context/util.py
  great_expectations/self_check/util.py
  great_expectations/types/__init__.py
  requirements-dev.txt
  tests/integration/db/bigquery.py
  tests/integration/docusaurus/deployment_patterns/aws_glue_deployment_patterns.py
  tests/integration/test_script_runner.py
  tests/test_packaging.py
Labels: devrel

#5749 [MAINTENANCE] Rename GX Cloud "suite_validation_result" resource to "validation_result"
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/validation_operators/validation_operators.py
  tests/conftest.py
  tests/data_context/conftest.py
  tests/data_context/test_data_context_ge_cloud_mode.py
  tests/test_ge_utils.py
Labels: core-team

#5730 [MAINTENANCE] Store Refactor - cloud store return types & http-errors
  .gitignore
  great_expectations/data_context/store/ge_cloud_store_backend.py
  tasks.py
  tests/data_context/cloud_data_context/conftest.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/conftest.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5741 [MAINTENANCE]profile_numeric_columns_diff_expectation
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/__init__.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/example_profiles/expect_profile_diff_less_than_threshold_profile.pkl
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_between_exclusive_threshold_range.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_between_inclusive_threshold_range.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_greater_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_greater_than_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_less_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_less_than_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_between_exclusive_threshold_range.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_between_inclusive_threshold_range.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_greater_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_greater_than_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_less_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_less_than_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/profile_numeric_columns_diff_expectation.py
Labels: community, devrel

#5703 [MAINTENANCE] invoke docker
  tasks.py
Labels: core-team

#5752 [BUGFIX] Patch flaky E2E Cloud test with randomized suite names
  tests/data_context/test_base_data_context.py
Labels: core-team

#5754 [MAINTENANCE] Add plist to build docker test image daily.
  docker/io.greatexpectations.build_docker_dev_image.plist
Labels: core-team

#5713 [MAINTENANCE] opt-out type-checking
  docs/contributing/style_guides/code_style.md
  pyproject.toml
  scripts/check_type_hint_coverage.py
  tasks.py
Labels: core-team

#5744 [FEATURE] Enable passing "exact_estimation" boolean at `DataAssistant.run()` level (default value is True)
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/helpers/runtime_environment.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/cli/test_suite.py
  tests/integration/docusaurus/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5756 [MAINTENANCE] Linting & initial typing for data context
  great_expectations/core/data_context_key.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/data_context/store/_store_backend.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  great_expectations/data_context/store/database_store_backend.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/html_site_store.py
  great_expectations/data_context/store/in_memory_store_backend.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/data_context/store/json_site_store.py
  great_expectations/data_context/store/metric_store.py
  great_expectations/data_context/store/profiler_store.py
  great_expectations/data_context/store/query_store.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/store/store_backend.py
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/data_context/store/util.py
  great_expectations/data_context/store/validations_store.py
  great_expectations/data_context/types/base.py
  great_expectations/data_context/util.py
  pyproject.toml
  scripts/check_type_hint_coverage.py
  setup.cfg
Labels: core-team

#5757 [BUGFIX] Fix RegexPatternStringParameterBuilder to use legal character repetition. Remove median, mean, and standard deviation features from OnboardingDataAssistant "datetime_columns_rule" definition.
  great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_container.py
  tests/rule_based_profiler/parameter_builder/test_regex_pattern_string_parameter_builder.py
Labels: core-team

#5737 [MAINTENANCE] Update `oneshot` estimator to `quantiles` estimator
  great_expectations/rule_based_profiler/estimators/bootstrap_numeric_range_estimator.py
  great_expectations/rule_based_profiler/estimators/kde_numeric_range_estimator.py
  great_expectations/rule_based_profiler/estimators/numeric_range_estimator.py
  great_expectations/rule_based_profiler/estimators/quantiles_numeric_range_estimator.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  tests/conftest.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/test_user_workflow_fixtures.py
  tests/test_fixtures/rule_based_profiler/bobby_user_workflow_verbose_profiler_config.yml
  tests/test_fixtures/rule_based_profiler/example_notebooks/BasicExample_RBP_Instantiation_and_running.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/SelfInitializingExpectations.ipynb
Labels: core-team

#5760 [BUGFIX] Move `SuiteValidationResult.meta` validation id propogation before `ValidationOperator._run_action`
  great_expectations/validation_operators/validation_operators.py
Labels: core-team

#5759 [MAINTENANCE] Update Auto-Initializing Expectations to use `exact` estimator by default
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
Labels: core-team

#5764 [BUGFIX] Update "column.partition" Metric to handle DateTime Arithmetic Properly
  great_expectations/core/util.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_partition.py
  great_expectations/self_check/util.py
  great_expectations/util.py
  tests/expectations/metrics/test_core.py
Labels: core-team

#5765 [BUGFIX] JSON-serialize RowCondition and enable IDDict to support comparison operations
  great_expectations/core/id_dict.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/row_conditions.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  tests/core/test_batch_related_objects.py
  tests/expectations/metrics/test_core.py
Labels: core-team

#5623 [DOCS] added guide how to use gx with emr serverless
  docs/deployment_patterns/how_to_use_great_expectations_in_emr_serverless.md
  docs/sitemap.xml
  sidebars.js
  tests/integration/docusaurus/deployment_patterns/aws_emr_serverless_deployment_patterns.py
  tests/integration/docusaurus/deployment_patterns/aws_emr_serverless_deployment_patterns_great_expectations.yaml
  tests/integration/test_script_runner.py
Labels: community, devrel

#5770 [MAINTENANCE] invoke docker --detach and more typing
  pyproject.toml
  scripts/check_type_hint_coverage.py
  tasks.py
Labels: core-team

#5771 [MAINTENANCE] In ParameterBuilder implementations, enhance handling of numpy.ndarray metric values, whose elements are or can be converted into datetime.datetime type.
  great_expectations/expectations/metrics/column_aggregate_metrics/column_partition.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/partition_parameter_builder.py
  great_expectations/util.py
  great_expectations/validator/metric_configuration.py
Labels: core-team

#5697 [MAINTENANCE] Config/Schema round_tripping
  great_expectations/core/configuration.py
  tests/core/test_serialization.py
  tests/datasource/test_datasource_serialization.py
Labels: core-team

#5774 [BUGFIX] Insure all estimators properly handle datetime-float conversion
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/estimators/exact_numeric_range_estimator.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/util.py
  tests/test_ge_utils.py
Labels: core-team

#5745 [DOCS] DOC-362: how to choose between working with a single or multiple batches of data
  docs/guides/connecting_to_your_data/how_to_choose_between_working_with_a_single_or_multiple_batches_of_data.md
  sidebars.js
Labels: devrel

#5782 Add experimental label to MetricStore Doc
  docs/guides/setup/configuring_metadata_stores/how_to_configure_a_metricsstore.md
Labels: devrel

#5776 [FEATURE] Example notebook for Onboarding DataAssistant - `postgres`
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running-OnboardingAssistant-Sql.ipynb
Labels: core-team

#5783 [BUGFIX] Return appropriate subquery type to Query Metrics for SA version
  great_expectations/expectations/metrics/query_metrics/query_column.py
  great_expectations/expectations/metrics/query_metrics/query_table.py
  great_expectations/util.py
Labels: devrel

#5784 [MAINTENANCE] Remove `GeCloudIdentifier` creation in `Checkpoint.run()`
  great_expectations/checkpoint/checkpoint.py
Labels: core-team

#5786 [BUGFIX] Enable "DataAssistantResult.__repr__()" to work properly in its subclasses.
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/data_assistant_result/onboarding_data_assistant_result.py
  great_expectations/rule_based_profiler/data_assistant_result/volume_data_assistant_result.py
  great_expectations/rule_based_profiler/helpers/util.py
Labels: core-team

#5780 [DOCS] Change the selectable to a list
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_max_to_be_between_custom.py
Labels: community, devrel

#5793 Remove xfail markers on cloud tests
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/test_base_data_context.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5616 [MAINTENANCE] build-gallery enhancements
  assets/scripts/AlgoliaScripts/README.md
  assets/scripts/build_gallery.py
  assets/scripts/trigger_algolia.sh
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines-docs-integration.yml
  azure-pipelines-expectation-gallery.yml
  contrib/cli/tests/test_package.py
  great_expectations/core/expectation_diagnostics/expectation_diagnostics.py
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  great_expectations/profile/basic_dataset_profiler.py
  great_expectations/profile/basic_suite_builder_profiler.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/self_check/util.py
  great_expectations/validator/validator.py
  scripts/check_type_hint_coverage.py
  setup.cfg
  tasks.py
  tests/conftest.py
  tests/expectations/test_expectation_diagnostics.py
  tests/expectations/test_run_diagnostics.py
  tests/test_definitions/column_aggregate_expectations/expect_column_quantile_values_to_be_between.json
Labels: devrel

#5743 [FEATURE] `query.pair_column` Metric
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_pair_values_to_have_diff.py
  great_expectations/expectations/metrics/query_metrics/__init__.py
  great_expectations/expectations/metrics/query_metrics/query_column_pair.py
Labels: devrel

#5796 [FEATURE] Enhance execution time measurement utility, and save `DomainBuilder` execution time per Rule of Rule-Based Profiler
  great_expectations/datasource/data_connector/runtime_data_connector.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_container.py
  great_expectations/rule_based_profiler/rule/rule.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/rule_based_profiler/rule_based_profiler_result.py
  great_expectations/rule_based_profiler/rule_state.py
  great_expectations/util.py
  great_expectations/validator/validator.py
  tests/datasource/data_connector/test_runtime_data_connector.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5792 [MAINTENANCE] Refactor `save_profiler` to remove explicit `name` and `ge_cloud_id` args
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/conftest.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/integration/profiling/rule_based_profiler/test_profiler_basic_workflows.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
Labels: core-team

#5803 [MAINTENANCE] Add v2_api flag for v2_api specific tests
  pyproject.toml
  tests/data_context/test_data_context.py
Labels: core-team

#5791 [MAINTENANCE] Clean up `ge_cloud_id` reference from `DataContext` `ExpectationSuite` CRUD
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
Labels: core-team

#5805 [MAINTENANCE] Refactor convert_dictionary_to_parameter_node
  great_expectations/rule_based_profiler/parameter_container.py
Labels: core-team

#5804 [MAINTENANCE] Remove `ge_cloud_id` from `DataContext.add_profiler()` signature
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/conftest.py
  tests/rule_based_profiler/test_rule_based_profiler.py
Labels: core-team

#5807 [DOCS] Fix how to create custom table expectation
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_table_expectations.md
Labels: community, devrel

#5808 [FEATURE] Support single-batch mode in MetricMultiBatchParameterBuilder
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/mean_table_columns_set_match_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/mean_unexpected_map_metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/rule_based_profiler_result.py
  tests/integration/profiling/rule_based_profiler/test_profiler_basic_workflows.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/parameter_builder/test_mean_unexpected_map_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/test_rule_based_profiler.py
Labels: core-team

#5726 [FEATURE] Inline `ExpectationSuite` Rendering
  great_expectations/core/expectation_suite.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/data_context/types/base.py
  great_expectations/render/renderer/inline_renderer.py
  pyproject.toml
  scripts/check_type_hint_coverage.py
  tests/checkpoint/test_checkpoint.py
  tests/checkpoint/test_simple_checkpoint.py
  tests/conftest.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_config_ui.py
  tests/data_context/test_data_context_v013.py
  tests/data_context/test_data_context_variables.py
  tests/render/test_inline_renderer.py
Labels: core-team

#5809 [MAINTENANCE] Remove "copy.deepcopy()" calls from ValidationGraph
  great_expectations/rule_based_profiler/builder.py
  great_expectations/rule_based_profiler/domain_builder/domain_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/validator/validation_graph.py
Labels: core-team

#5711 Add vectorized is_between for common numpy dtypes
  great_expectations/expectations/metrics/column_map_metrics/column_values_between.py
  great_expectations/self_check/util.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between__evaluation_parameters.json
Labels: core-team

#5810 [MAINTENANCE] Make partitioning directives of PartitionParameterBuilder configurable
  great_expectations/rule_based_profiler/parameter_builder/partition_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_partition_parameter_builder.py
Labels: core-team

#5815 [MAINTENANCE] Write E2E Cloud test for `RuleBasedProfiler` creation and retrieval
  great_expectations/data_context/data_context/data_context.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
Labels: core-team

#5817 [MAINTENANCE] Change recursion to iteration for function in parameter_container.py
  great_expectations/rule_based_profiler/parameter_container.py
Labels: core-team

#5819 [MAINTENANCE] add `pytest-mock` & `pytest-icdiff` plugins
  great_expectations/core/usage_statistics/package_dependencies.py
  pyproject.toml
  requirements-dev-lite.txt
Labels: core-team

#5779 [DOCS] DOC-363 how to configure a pandas datasource
  docs/guides/connecting_to_your_data/datasource_configuration/components/base_directory_for_filesystem.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/components/intro_for_single_or_multi_batch_configuration.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/components/tip_custom_data_connector_module_name.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/components/tip_more_info_on_regex.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/how_to_configure_a_pandas_datasource.md
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/configured_asset_data_connector.md
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/inferred_asset_data_connector.md
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/runtime_asset_data_connector.md
  sidebars.js
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_ConfiguredAssetFileSystemExample_Pandas.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_InferredAssetFileSystemExample_Pandas.ipynb
Labels: devrel

#5797 [MAINTENANCE] Surface cloud errors
  great_expectations/data_context/store/ge_cloud_store_backend.py
  tests/data_context/cloud_data_context/conftest.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/conftest.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
Labels: core-team

#5813 [BUGFIX] Ensure name not persisted
  great_expectations/core/serializer.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/datasource/datasource_serializer.py
  tests/data_context/abstract_data_context/test_list_datasources.py
  tests/data_context/conftest.py
  tests/data_context/store/conftest.py
  tests/data_context/store/test_datasource_store.py
Labels: core-team

#5823 [Maintenance] Clean up build_parameter_container_for_variables
  great_expectations/rule_based_profiler/parameter_container.py
Labels: core-team

#5814 Bugfix/snowflake temp table schema name
  great_expectations/datasource/data_connector/runtime_data_connector.py
  tests/datasource/data_connector/test_runtime_data_connector.py
Labels: devrel

#5826 [MAINTENANCE] Update `list_` methods on `DataContext` to emit names along with object ids
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/types/resource_identifiers.py
  scripts/check_docstring_coverage.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
Labels: core-team

#5820 [FEATURE] DataAssistants Example Notebook - Pandas
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running-OnboardingAssistant-Pandas.ipynb
Labels: core-team

#5828 [MAINTENANCE] xfail Cloud E2E tests due to schema issue with `DataContextVariables`
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/test_base_data_context.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5835 [MAINTENANCE] Clean up xfails in preparation for 0.15.20 release
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/test_base_data_context.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5837 [MAINTENANCE] Add back xfails for E2E Cloud tests that fail on env var retrieval in Docker
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5838 [MAINTENANCE] Unit Tests Pipeline step
  azure-pipelines-dependency-graph-testing.yml
  tasks.py
Labels: core-team

#5841 [MAINTENANCE] fix dg-test step
  azure-pipelines-dependency-graph-testing.yml
Labels: core-team

#5839 [MAINTENANCE] Unit tests to ensure coverage over `Datasource` caching in `DataContext`
  azure-pipelines-dependency-graph-testing.yml
  tests/data_context/test_data_context_datasources.py
Labels: core-team

#5833 [MAINTENANCE] Add entries to release schedule
  .github/release_schedule.json
Labels: core-team

#5845 [MAINTENANCE] Properly label `DataAssistant` tests with `@pytest.mark.integration`
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5844 [MAINTENANCE] Add additional unit tests around `Datasource` caching
  tests/data_context/test_data_context_datasources.py
Labels: core-team

#5846 [MAINTENANCE] Mark miscellaneous tests with `@pytest.mark.unit`
  tests/test_configs.py
  tests/test_ge_utils.py
  tests/test_the_utils_in_test_utils.py
Labels: core-team

#5824 [MAINTENANCE] `datasource`, `data_context`, `core` typing, lint fixes
  .gitignore
  great_expectations/core/__init__.py
  great_expectations/core/async_executor.py
  great_expectations/core/batch_spec.py
  great_expectations/core/config_peer.py
  great_expectations/core/evaluation_parameters.py
  great_expectations/core/expectation_suite.py
  great_expectations/core/id_dict.py
  great_expectations/core/run_identifier.py
  great_expectations/core/usage_statistics/events.py
  great_expectations/core/yaml_handler.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/store.py
  great_expectations/datasource/batch_kwargs_generator/table_batch_kwargs_generator.py
  great_expectations/datasource/data_connector/data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py
  great_expectations/datasource/data_connector/runtime_data_connector.py
  great_expectations/datasource/data_connector/util.py
  great_expectations/datasource/datasource.py
  great_expectations/datasource/datasource_serializer.py
  great_expectations/datasource/new_datasource.py
  great_expectations/datasource/simple_sqlalchemy_datasource.py
  great_expectations/datasource/sqlalchemy_datasource.py
  great_expectations/datasource/types/__init__.py
  great_expectations/profile/basic_dataset_profiler.py
  great_expectations/profile/basic_suite_builder_profiler.py
  pyproject.toml
  scripts/check_type_hint_coverage.py
  setup.cfg
  tasks.py
Labels: core-team

#5802 [MAINTENANCE] add --ignore-suppress and --ignore-only-for to build_gallery.py with bugfixes
  assets/scripts/build_gallery.py
  assets/scripts/build_package_gallery.py
  azure-pipelines-expectation-gallery.yml
  constraints-dev.txt
  contrib/cli/requirements.txt
  contrib/experimental/great_expectations_experimental/expectations/expect_column_minimum_bounding_radius_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_geometry_to_intersect_shape.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_imsi_belong_to_country_code.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_github_username.py
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/core/util.py
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/expectations/expectation.py
  great_expectations/self_check/util.py
  requirements-dev-all-contrib-expectations.txt
  setup.py
Labels: devrel

#5849 [MAINTENANCE] Remove pyparsing pin for <3.0
  requirements.txt
Labels: devrel

#5848 [MAINTENANCE] Finer type exclude
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/store/checkpoint_store.py
  pyproject.toml
  scripts/check_type_hint_coverage.py
Labels: core-team

#5775 [MAINTENANCE] use `id` instead `id_`
  great_expectations/checkpoint/checkpoint.py
  great_expectations/checkpoint/util.py
  great_expectations/core/configuration.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/_store_backend.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/in_memory_store_backend.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/data_context/store/profiler_store.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/types/base.py
  great_expectations/datasource/data_connector/configured_asset_azure_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_dbfs_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_filesystem_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_gcs_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_s3_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py
  great_expectations/datasource/data_connector/data_connector.py
  great_expectations/datasource/data_connector/file_path_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_azure_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_dbfs_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_file_path_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_filesystem_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_gcs_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_s3_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py
  great_expectations/datasource/data_connector/runtime_data_connector.py
  great_expectations/datasource/new_datasource.py
  great_expectations/rule_based_profiler/config/base.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/checkpoint/test_checkpoint.py
  tests/core/test_serialization.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_profilers.py
  tests/datasource/data_connector/test_data_connector_serialization.py
  tests/datasource/test_datasource_serialization.py
  tests/integration/profiling/rule_based_profiler/test_profiler_basic_workflows.py
  tests/rule_based_profiler/test_rule_based_profiler_serialization.py
Labels: in-progress, core-team

#5778 [MAINTENANCE] Add data connector names in datasource config
  great_expectations/core/configuration.py
  great_expectations/core/serializer.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/types/base.py
  great_expectations/datasource/datasource_serializer.py
  tests/conftest.py
  tests/core/test_serialization.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/conftest.py
  tests/data_context/store/conftest.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/test_data_context.py
  tests/datasource/test_datasource_serialization.py
Labels: core-team

#5854 [MAINTENANCE] init tests for dict and json serializers
  tests/core/test_serializers.py
Labels: core-team

#5862 [MAINTENANCE] Remove Partitioning and Quantiles metrics computations from DateTime Rule of OnboardingDataAssistant
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
Labels: core-team

#5836 [MAINTENANCE] Update `ExpectationSuite` CRUD on `DataContext` to recognize Cloud ids
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
Labels: core-team

#5863 [MAINTENANCE] Handle Pandas warnings in Data Assistant plots
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/data_assistant_result/plot_result.py
Labels: core-team

#5868 [MAINTENANCE] Misc cleanup of `test_expectation_suite_crud.py`
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
Labels: core-team

#5866 [MAINTENANCE] Remove vendored `marshmallow__shade`
  great_expectations/checkpoint/types/checkpoint_result.py
  great_expectations/core/configuration.py
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_suite.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/core/run_identifier.py
  great_expectations/core/serializer.py
  great_expectations/core/usage_statistics/execution_environment.py
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/data_asset/data_asset.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/types/base.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/datasource/batch_kwargs_generator/table_batch_kwargs_generator.py
  great_expectations/exceptions/exceptions.py
  great_expectations/marshmallow__shade/__init__.py
  great_expectations/marshmallow__shade/base.py
  great_expectations/marshmallow__shade/class_registry.py
  great_expectations/marshmallow__shade/decorators.py
  great_expectations/marshmallow__shade/error_store.py
  great_expectations/marshmallow__shade/exceptions.py
  great_expectations/marshmallow__shade/fields.py
  great_expectations/marshmallow__shade/orderedset.py
  great_expectations/marshmallow__shade/py.typed
  great_expectations/marshmallow__shade/schema.py
  great_expectations/marshmallow__shade/types.py
  great_expectations/marshmallow__shade/utils.py
  great_expectations/marshmallow__shade/validate.py
  great_expectations/marshmallow__shade/warnings.py
  great_expectations/render/types/__init__.py
  great_expectations/rule_based_profiler/config/base.py
  great_expectations/types/configurations.py
  great_expectations/validation_operators/types/validation_operator_result.py
  great_expectations/validator/validator.py
  pyproject.toml
  requirements.txt
  setup.cfg
  tests/core/test_serialization.py
  tests/core/test_serializers.py
  tests/data_context/store/test_configuration_store.py
  tests/data_context/store/test_html_site_store.py
  tests/data_context/test_data_context_profilers.py
  tests/rule_based_profiler/config/test_base.py
  tests/test_deprecation.py
Labels: core-team

#5871 [MAINTENANCE] don't force using the stand alone mock
  pyproject.toml
Labels: core-team

#5874 [MAINTENANCE] Update expectation_gallery pipeline
  azure-pipelines-expectation-gallery.yml
Labels: devrel

#5869 [MAINTENANCE] run unit-tests on a target package
  tasks.py
Labels: core-team

#5853 [FEATURE] Add `include_rendered_content` to `get_expectation_suite` and `get_validation_result`
  great_expectations/checkpoint/checkpoint.py
  great_expectations/checkpoint/util.py
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_suite.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/render/renderer/inline_renderer.py
  great_expectations/validator/validator.py
  tests/checkpoint/test_checkpoint.py
  tests/data_context/test_data_context.py
  tests/render/test_inline_renderer.py
Labels: core-team

#5878 [BUGFIX] Ensure that `delete_expectation_suite` returns proper boolean result
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
Labels: core-team

#5857 [MAINTENANCE] add `pytest-timeout`
  great_expectations/core/usage_statistics/package_dependencies.py
  requirements-dev-lite.txt
  tasks.py
Labels: dependencies, core-team

#5879 [MAINTENANCE] Label tests in `tests/core` with `@pytest.mark.unit` and `@pytest.mark.integration`
  tests/core/test_async_executor.py
  tests/core/test_batch_related_objects.py
  tests/core/test_evaluation_parameters.py
  tests/core/test_expectation_configuration.py
  tests/core/test_expectation_validation.py
  tests/core/test_identifiers.py
  tests/core/test_serialization.py
  tests/core/test_serializers.py
  tests/core/test_urn.py
  tests/core/test_util.py
  tests/core/test_yaml_handler.py
Labels: core-team
