Repository great-expectations/great_expectations, pull requests merged in 2022-12, with the labels that each got.

#6450 [BUGFIX] Support Table and Column Names Case Non-Sensitivity Relationship Between Snowflake, Oracle, DB2, etc. DBMSs (Upper Case) and SQLAlchemy (Lower Case) Representations
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_column_profiler_report.py
  great_expectations/expectations/metrics/column_aggregate_metric_provider.py
  great_expectations/expectations/metrics/import_manager.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/table_metrics/table_column_types.py
  great_expectations/expectations/metrics/util.py
  tests/expectations/metrics/test_core.py
  tests/expectations/metrics/test_map_metric.py
  tests/expectations/test_util.py
Labels: core-team

#6469 [MAINTENANCE] fixing type hints in metrics utils module
  great_expectations/expectations/metrics/util.py
Labels: core-team

#6459 Add docstring for context.sources.add_postgres
  great_expectations/experimental/datasources/metadatasource.py
  great_expectations/experimental/datasources/postgres_datasource.py
  great_expectations/experimental/datasources/sources.py
Labels: core-team

#6467 [BUGFIX] Add additional error checking to `ExpectationAnonymizer`
  great_expectations/core/usage_statistics/anonymizers/expectation_anonymizer.py
Labels: core-team

#6471 [BUGFIX] Contrib Expectation tracebacks
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/profile_numeric_columns_diff_expectation.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_in_set_spark_optimized.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_string_integers_increasing.py
  contrib/great_expectations_ethical_ai_expectations/great_expectations_ethical_ai_expectations/expectations/expect_table_binary_label_model_bias.py
  contrib/great_expectations_ethical_ai_expectations/great_expectations_ethical_ai_expectations/expectations/expect_table_linear_feature_importances_to_be.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_be_valid_mic.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_be_valid_mic_match_country_code.py
Labels: devrel

#6472 Add pretty representations for zep pydantic models
  great_expectations/experimental/datasources/experimental_base_model.py
  great_expectations/experimental/datasources/postgres_datasource.py
  tests/experimental/datasources/test_postgres_datasource.py
Labels: core-team

#6476 [RELEASE] 0.15.36
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team

#6473 [CONTRIB] Add uniqueness expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_list_to_be_unique.py
Labels: community

#6479 [MAINTENANCE] Misc updates to PR template
  .github/pull_request_template.md
Labels: core-team

#6478 [MAINTENANCE] Minor cleanup for better code readability
  great_expectations/rule_based_profiler/helpers/simple_semantic_type_filter.py
  great_expectations/validator/validator.py
Labels: core-team

#6477 [MAINTENANCE] Move zep method from datasource to data asset.
  great_expectations/experimental/datasources/postgres_datasource.py
  tests/experimental/datasources/test_postgres_datasource.py
Labels: core-team

#6480 [MAINTENANCE] Staging for build gallery
  assets/scripts/build_gallery.py
  assets/scripts/build_package_gallery.py
  assets/scripts/copy_s3_old_prod_to_prod.sh
  assets/scripts/copy_s3_staging_to_prod.sh
  azure-pipelines-expectation-gallery.yml
  azure-pipelines-manual-staging-json-to-prod.yml
Labels: devrel

#6423 [MAINTENANCE] Reformat core expectation docstrings
  assets/scripts/build_gallery.py
  great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_most_common_value_to_be_in_set.py
  great_expectations/expectations/core/expect_column_pair_values_a_to_be_greater_than_b.py
  great_expectations/expectations/core/expect_column_pair_values_to_be_equal.py
  great_expectations/expectations/core/expect_column_pair_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_to_exist.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_equal.py
  great_expectations/expectations/core/expect_column_value_z_scores_to_be_less_than.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_dateutil_parseable.py
  great_expectations/expectations/core/expect_column_values_to_be_decreasing.py
  great_expectations/expectations/core/expect_column_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/expectations/core/expect_column_values_to_be_increasing.py
  great_expectations/expectations/core/expect_column_values_to_be_json_parseable.py
  great_expectations/expectations/core/expect_column_values_to_be_null.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/core/expect_column_values_to_be_unique.py
  great_expectations/expectations/core/expect_column_values_to_match_json_schema.py
  great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py
  great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py
  great_expectations/expectations/core/expect_column_values_to_match_regex.py
  great_expectations/expectations/core/expect_column_values_to_match_regex_list.py
  great_expectations/expectations/core/expect_column_values_to_match_strftime_format.py
  great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_not_be_null.py
  great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern.py
  great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern_list.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex_list.py
  great_expectations/expectations/core/expect_compound_columns_to_be_unique.py
  great_expectations/expectations/core/expect_multicolumn_sum_to_equal.py
  great_expectations/expectations/core/expect_multicolumn_values_to_be_unique.py
  great_expectations/expectations/core/expect_select_column_values_to_be_unique_within_record.py
  great_expectations/expectations/core/expect_table_column_count_to_be_between.py
  great_expectations/expectations/core/expect_table_column_count_to_equal.py
  great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py
  great_expectations/expectations/core/expect_table_columns_to_match_set.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_equal.py
  great_expectations/expectations/core/expect_table_row_count_to_equal_other_table.py
Labels: devrel

#6482 Query the database for datetime column splitter defaults
  great_expectations/experimental/datasources/postgres_datasource.py
  tests/experimental/datasources/config.yaml
  tests/experimental/datasources/conftest.py
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_postgres_datasource.py
Labels: core-team

#6481 [BUGFIX] Support slack channel name with webhook also
  great_expectations/checkpoint/util.py
Labels: community

#6448 [FEATURE] Support to include ID/PK in validation result for each row - SQL
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/util.py
  tests/expectations/metrics/test_map_metric.py
  tests/expectations/metrics/test_metrics_util.py
  tests/test_sets/metrics_test.db
  tests/test_utils.py
Labels: core-team

#6489 [MAINTENANCE] Placing metrics test db under try-except
  tests/expectations/metrics/test_map_metric.py
Labels: core-team

#6491 [MAINTENANCE] Clean up tests for more formal Batch and Validator instantiation
  great_expectations/core/batch.py
  tests/conftest.py
  tests/expectations/metrics/test_map_metric.py
  tests/rule_based_profiler/conftest.py
  tests/validator/test_validator.py
Labels: core-team

#6474 [FEATURE] Build process and example API docs (part 1)
  docs/.gitignore
  docs/sphinx_api_docs_source/README.md
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
  docs/sphinx_api_docs_source/conf.py
  docs/sphinx_api_docs_source/data_context.md
  docs/sphinx_api_docs_source/index.md
  docs/sphinx_api_docs_source/requirements-dev-api-docs.txt
  docs/sphinx_api_docs_source/tasks.py
  docusaurus.config.js
  great_expectations/core/_docs_decorators.py
  great_expectations/core/util.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/data_context.py
  package.json
  pyproject.toml
  src/css/api_docs/README.md
  src/css/api_docs/api_docs.scss
  src/css/api_docs/basic-modified.scss
  src/css/api_docs/pydata-sphinx-theme-modified.scss
  src/css/api_docs/pygments.scss
  src/css/custom.scss
  tasks.py
  yarn.lock
Labels: core-team

#6303 [FEATURE] Add temp_table_schema_name support for BigQuery
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  tests/execution_engine/test_sqlalchemy_batch_data.py
Labels: DevRel Triage, community, devrel

#6500 [MAINTENANCE] Resolve `mypy` issues in `cli/docs.py`
  great_expectations/cli/docs.py
  pyproject.toml
Labels: core-team

#6509 Increase timeout to 15 minutes for the 2 jobs in manual-staging-json-to-prod pipeline
  azure-pipelines-manual-staging-json-to-prod.yml
Labels: devrel

#6496 [MAINTENANCE] Update Data Assistant plot color scheme and fonts
  great_expectations/rule_based_profiler/altair/themes.py
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  great_expectations/types/__init__.py
  great_expectations/types/color_palettes.py
  great_expectations/types/colors.py
  great_expectations/types/fonts.py
Labels: core-team

#6497 [FEATURE] Decorators for API docs (part 2)
  docs/sphinx_api_docs_source/requirements-dev-api-docs.txt
  docs/sphinx_api_docs_source/tasks.py
  great_expectations/core/_docs_decorators.py
  great_expectations/core/usage_statistics/package_dependencies.py
  reqs/requirements-dev-api-docs-test.txt
  reqs/requirements-dev-test.txt
  requirements-dev.txt
  tasks.py
  tests/core/test__docs_decorators.py
  tests/test_packaging.py
Labels: core-team

#6492 [MAINTENANCE] Message for how to install Great Expectations in Cloud Composer by pinning packages
  docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
Labels: core-team

#6460 [MAINTENANCE] Leverage `RendererConfiguration` in existing prescriptive templates (1 of 3)
  great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
  great_expectations/expectations/core/expect_column_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_be_null.py
  great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py
  great_expectations/expectations/core/expect_table_row_count_to_equal.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/util.py
  great_expectations/render/renderer/content_block/expectation_string.py
  great_expectations/render/renderer_configuration.py
  tests/expectations/snapshots/snap_test_expectation_atomic_renderers.py
  tests/render/test_inline_renderer.py
Labels: core-team

#6511 [MAINTENANCE] Clean up `teams.yml`
  .github/teams.yml
Labels: core-team, platform

#6505 [MAINTENANCE] Make Generated Integration Tests More Robust Using BatchDefinition and InMemoryDataContext In Validator and ExecutionEngine Instantiation
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_match_json_schema.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/rule_based_profiler/attributed_resolved_metrics.py
  great_expectations/rule_based_profiler/domain_builder/column_pair_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/multi_column_domain_builder.py
  great_expectations/self_check/util.py
  great_expectations/util.py
  reqs/requirements-dev-lite.txt
  tests/conftest.py
  tests/expectations/metrics/test_map_metric.py
  tests/test_definitions/test_expectations_v3_api.py
  tests/validator/test_metrics_calculator.py
Labels: core-team

#6510 [BUGFIX] Validator uses proper arguments to show progress bar at Metrics resolution-level
  great_expectations/validator/validator.py
Labels: community

#6504 [FEATURE] Decorators for API docs (part 3)
  great_expectations/core/_docs_decorators.py
  src/css/custom.scss
  tests/core/test__docs_decorators.py
Labels: core-team

#6513 [DOCS] fix(gh-6512): fix rendering of Batch definition
  docs/terms/execution_engine.md
Labels: community

#6501 [MAINTENANCE] Clean up GX Cloud environment variable usage (GREAT-1352)
  azure-pipelines-cloud-integration.yml
  great_expectations/checkpoint/actions.py
  great_expectations/checkpoint/checkpoint.py
  great_expectations/data_context/cloud_constants.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/migrator/cloud_migrator.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  great_expectations/data_context/store/data_context_store.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/gx_cloud_store_backend.py
  great_expectations/data_context/store/profiler_store.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/store/validations_store.py
  great_expectations/data_context/types/refs.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/render/renderer/site_builder.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/util.py
  great_expectations/validation_operators/validation_operators.py
  great_expectations/validator/validator.py
  tests/actions/conftest.py
  tests/actions/test_core_actions.py
  tests/conftest.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/migrator/test_cloud_migrator.py
  tests/data_context/store/test_checkpoint_store.py
  tests/data_context/store/test_configuration_store.py
  tests/data_context/store/test_data_context_store.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
  tests/data_context/test_base_data_context.py
  tests/data_context/test_data_context_datasources.py
  tests/data_context/test_data_context_ge_cloud_mode.py
  tests/data_context/test_data_context_variables.py
  tests/data_context/test_get_data_context.py
  tests/rule_based_profiler/test_rule_based_profiler.py
  tests/validator/test_validator.py
Labels: core-team

#6521 [MAINTENANCE] Update Data Assistant plot images
  docs/images/data_assistant_plot_expectations_and_metrics.png
  docs/images/data_assistant_plot_metrics.png
  readme_assets/data_assistant_plot_expectations_and_metrics.png
Labels: core-team, platform

#6522 [RELEASE] 0.15.37
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#6520 [BUGFIX] Patch broken Cloud E2E test around `Datasource` CRUD
  tests/data_context/cloud_data_context/test_datasource_crud.py
Labels: core-team, platform

#6523 [MAINTENANCE] Clean up type hints and make test generation more elegant
  great_expectations/rule_based_profiler/attributed_resolved_metrics.py
  great_expectations/rule_based_profiler/parameter_container.py
  tests/expectations/core/test_expect_column_value_z_scores_to_be_less_than.py
  tests/expectations/core/test_expect_column_values_to_be_in_type_list.py
  tests/expectations/core/test_expect_queried_column_value_frequency_to_meet_threshold.py
  tests/expectations/core/test_expect_queried_table_row_count_to_be.py
  tests/rule_based_profiler/parameter_builder/test_parameter_computations.py
  tests/test_definitions/test_expectations_v3_api.py
Labels: core-team, platform

#6517 [MAINTENANCE] Clean up `Datasource` instantiation logic in `DataContext`
  great_expectations/data_context/data_context/abstract_data_context.py
Labels: core-team, platform

#6529 [BUGFIX] Patch outdated `ge_cloud_id` attribute call in `ValidationOperator`
  great_expectations/validation_operators/validation_operators.py
Labels: core-team, platform

#6528 [MAINTENANCE] Update `Domain` computation in MetricConfiguration
  great_expectations/rule_based_profiler/parameter_container.py
  great_expectations/validator/metric_configuration.py
  tests/validator/test_metric_configuration.py
Labels: core-team, platform

#6536 [DOCS] Fix line numbers in snippets
  docs/terms/checkpoint.md
  docs/tutorials/getting_started/tutorial_create_expectations.md
  docs/tutorials/getting_started/tutorial_validate_data.md
Labels: core-team, dx

#6535 [BUGFIX] Revert refactor to `Datasource` instantiation logic in `DataContext`
  great_expectations/data_context/data_context/abstract_data_context.py
Labels: core-team, platform

#6537 [DOCS] Fix line numbers in snippets part 2
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
Labels: core-team, dx

#6534 v2 Docs link
  docs_rtd/_static/style.css
  docs_rtd/_templates/layout.html
  docusaurus.config.js
  static/img/gx-mark-120.png
  static/img/gx-mark-600.png
Labels: devrel

#6541 [DOCS] Convert nested snippets to named snippets
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_query_expectations.md
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_queried_column_value_frequency_to_meet_threshold.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_queried_table_row_count_to_be.py
Labels: core-team, dx

#6542 [BUGFIX] Patch faulty GX Cloud arg resolution logic
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/util.py
Labels: core-team, platform

#6544 [RELEASE] 0.15.38
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#6546 [BUGFIX] Fix resolution of cloud variables.
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/util.py
Labels: core-team, platform

#6538 [DOCS] Simplify snippet checker logic to catch stray tags in CI
  azure-pipelines-docs-integration.yml
  scripts/validate_docs_snippet_line_numbers.py
  scripts/validate_docs_snippets.py
Labels: core-team, platform

#6550 Fix logic around cloud_mode and ge_cloud_mode.
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/util.py
Labels: core-team, platform

#6551 [RELEASE] 0.15.39
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#6555 [BUGFIX] Patch additional deprecated call to `GXCloudIdentifier.ge_cloud_id` attr
  great_expectations/checkpoint/actions.py
  great_expectations/data_context/types/resource_identifiers.py
Labels: core-team, platform

#6559 [BUGFIX] Patch `packaging_and_installation` Azure pipeline test failures
  azure/dev-install-matrix.yml
Labels: core-team, platform

#6560 [BUGFIX] Fix dependency issues to reenable RTD builds
  docs_rtd/requirements.txt
Labels: core-team, platform

#6466 [DOCS] doc 383: bring sql datasource configuration examples under test
  docs/guides/connecting_to_your_data/datasource_configuration/sql_components/_config_for_assets_runtime.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/sql_components/_part_asset_keys_overview_configured.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/sql_components/_part_asset_keys_overview_inferred.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/sql_components/_part_assets_runtime.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/sql_components/_section_add_a_dictionary_as_the_value_of_the_data_connectors_key.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/sql_components/_section_add_the_execution_engine_to_your_datasource_configuration.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/sql_components/_tab_data_connector_example_configurations_configured.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/sql_components/_tab_data_connector_example_configurations_inferred.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/sql_components/_tab_data_connector_example_configurations_runtime.mdx
  tests/integration/docusaurus/connecting_to_your_data/datasource_configuration/full_datasource_configurations.py
  tests/integration/docusaurus/connecting_to_your_data/datasource_configuration/how_to_configure_a_sql_datasource.py
  tests/integration/test_script_runner.py
Labels: devrel

#6525 [FEATURE] F/great 1397/zep checkpoints
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/batch.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/postgres_datasource.py
  tests/experimental/datasources/test_integration_sql_datasource.py
  tests/experimental/datasources/test_postgres_datasource.py
Labels: core-team, platform

#6554 [MAINTENANCE] Improve DataAssistant Parameter Builder Naming/Sanitization Mechanism and Enhance TableDomainBuilder
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/rule_based_profiler/data_assistant/data_profiler_structured_data_assistant.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/rule_based_profiler/data_assistant/test_data_profiler_structured_data_assistant.py
  contrib/experimental/great_expectations_experimental/rule_based_profiler/data_assistant/growth_numeric_data_assistant.py
  contrib/experimental/great_expectations_experimental/rule_based_profiler/data_assistant/statistics_data_assistant.py
  contrib/experimental/great_expectations_experimental/tests/rule_based_profiler/data_assistant/test_growth_numeric_data_assistant.py
  contrib/experimental/great_expectations_experimental/tests/rule_based_profiler/data_assistant/test_statistics_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/domain_builder/column_pair_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/table_domain_builder.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_container.py
  great_expectations/validator/metric_configuration.py
  tests/conftest.py
  tests/expectations/metrics/test_map_metric.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/domain_builder/test_domain.py
  tests/rule_based_profiler/domain_builder/test_domain_builder.py
  tests/rule_based_profiler/parameter_builder/test_parameter_computations.py
  tests/validator/conftest.py
Labels: core-team, platform

#6563 [MAINTENANCE] Simplify computational graph assembly from metric configurations
  great_expectations/core/expectation_configuration.py
  great_expectations/validator/validation_graph.py
  great_expectations/validator/validator.py
  tests/validator/test_validation_graph.py
  tests/validator/test_validator.py
Labels: core-team, platform

#6515 [CONTRIB] fix observed value in custom expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_to_have_n_distinct_values_with_condition.py
Labels: community

#6564 [FEATURE] Add integration test for zep sqlalchemy datasource with renderering.
  tests/experimental/datasources/test_integration_sql_datasource.py
Labels: core-team, platform

#6569 [BUGFIX] Add missing `raise` statement in `RuntimeDataConnector` logic
  great_expectations/datasource/data_connector/runtime_data_connector.py
Labels: core-team, platform

#6566 [MAINTENANCE] Use MetricsCalculator methods for ValidationGraph construction and resolution operations in Validator
  great_expectations/execution_engine/execution_engine.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/validator/metrics_calculator.py
  great_expectations/validator/validator.py
  tests/rule_based_profiler/parameter_builder/test_regex_pattern_string_parameter_builder.py
Labels: core-team, platform

#6572 [MAINTENANCE] Cast type in `execution_environment.py` to bypass flaky `mypy` warnings
  great_expectations/core/usage_statistics/execution_environment.py
Labels: core-team, platform

#6574 [MAINTENANCE] Additional patch for `mypy` issue in `execution_environment.py`
  great_expectations/core/usage_statistics/execution_environment.py
Labels: core-team, platform

#6561 [MAINTENANCE] Clean up GX rename artifacts
  great_expectations/checkpoint/actions.py
  great_expectations/data_context/cloud_constants.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/render/renderer/site_builder.py
  great_expectations/util.py
  great_expectations/validator/validator.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/test_data_context_deprecation.py
Labels: core-team, platform

#6576 [RELEASE] 0.15.40
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#6502 Update json schema validation on usage stats to filter based on format.
  great_expectations/core/usage_statistics/schemas.py
  great_expectations/core/usage_statistics/usage_statistics.py
  great_expectations/core/usage_statistics/usage_statistics_record_schema.json
  tests/core/usage_statistics/test_schema_validation.py
  tests/core/usage_statistics/test_usage_statistics_handler_methods.py
  tests/core/usage_statistics/test_usage_stats_schema.py
Labels: core-team

#6575 [MAINTENANCE] Renaming Metric Name Suffixes using Enum Values for Better Code Readability
  great_expectations/execution_engine/execution_engine.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/validator/validator.py
  tests/conftest.py
  tests/execution_engine/test_sparkdf_execution_engine.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/expectations/metrics/test_core.py
  tests/expectations/metrics/test_map_metric.py
Labels: core-team, platform

#6543 M/great 1433/cloud tests to async
  azure-pipelines-cloud-integration.yml
  azure-pipelines.yml
Labels: core-team, platform

#6573 [MAINTENANCE] Add static type checking to `rule.py` and `rule_based_profiler_result.py`
  great_expectations/rule_based_profiler/rule/rule.py
  great_expectations/rule_based_profiler/rule_based_profiler_result.py
  pyproject.toml
Labels: core-team, platform

#6581 [MAINTENANCE] Update changelogs to reflect PyPI yanks (0.15.37-0.15.39)
  docs/changelog.md
  docs_rtd/changelog.rst
Labels: core-team, platform

#6533 [FEATURE] enable mostly for expect_compound_columns_to_be_unique
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/expectations/core/expect_compound_columns_to_be_unique.py
  tests/dataset/test_sqlalchemydataset.py
Labels: community

#6578 [MAINTENANCE] Refactor ExecutionEngine.resolve_metrics() for better code readability
  great_expectations/execution_engine/bundled_metric_configuration.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/column_aggregate_metric_provider.py
Labels: core-team, platform

#6584 adding googletag manager to docusaurus
  docusaurus.config.js
  package.json
  yarn.lock
Labels: devrel

#6585 [MAINTENANCE] typo in method name
  great_expectations/execution_engine/execution_engine.py
Labels: core-team, platform

#6579 [BUGFIX] Return unique list of batch_definitions
  great_expectations/datasource/data_connector/file_path_data_connector.py
  tests/datasource/data_connector/test_configured_asset_filesystem_data_connector.py
Labels: community

#6553 [BUGFIX] convert_to_json_serializable does not accept numpy datetime
  great_expectations/core/util.py
  tests/core/test_convert_to_json_serializable.py
Labels: community

#6587 [MAINTENANCE] Small refactor of ExecutionEngine.resolve_metrics() for better code readability (and miscellaneous additional clean up)
  great_expectations/core/batch_manager.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/pandas_execution_engine.py
Labels: core-team, platform

#6592 [MAINTENANCE] Remove `ExplorerDataContext`
  great_expectations/data_asset/data_asset.py
  great_expectations/data_context/__init__.py
  great_expectations/data_context/data_context/__init__.py
  great_expectations/data_context/data_context/explorer_data_context.py
  great_expectations/validator/validator.py
  tests/data_context/test_data_context.py
Labels: core-team, platform

#6488 [MAINTENANCE] Leverage `RendererConfiguration` in existing prescriptive templates (2 of 3)
  great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_most_common_value_to_be_in_set.py
  great_expectations/expectations/core/expect_column_pair_cramers_phi_value_to_be_less_than.py
  great_expectations/expectations/core/expect_column_pair_values_a_to_be_greater_than_b.py
  great_expectations/expectations/core/expect_column_pair_values_to_be_equal.py
  great_expectations/expectations/core/expect_column_pair_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_to_exist.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_equal.py
  great_expectations/expectations/core/expect_column_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_be_null.py
  great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py
  great_expectations/expectations/core/expect_table_row_count_to_equal.py
  great_expectations/expectations/expectation.py
  great_expectations/render/exceptions.py
  great_expectations/render/renderer_configuration.py
  tests/expectations/snapshots/snap_test_expectation_atomic_renderers.py
  tests/render/test_inline_renderer.py
Labels: core-team

#6580 [FEATURE] ZEP - PG `BatchSorter` loading + dumping
  great_expectations/experimental/datasources/postgres_datasource.py
  tests/experimental/datasources/config.yaml
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_postgres_datasource.py
Labels: core-team, platform

#6593 [RELEASE] 0.15.41
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#6571 [BUGFIX] Support non-string `datetime` evaluation parameters
  great_expectations/core/evaluation_parameters.py
  great_expectations/validator/validator.py
  tests/core/test_evaluation_parameters.py
  tests/data_asset/test_parameter_substitution.py
  tests/test_definitions/column_aggregate_expectations/expect_column_max_to_be_between.json
Labels: core-team, platform

#6530 [MAINTENANCE] Leverage `RendererConfiguration` in existing prescriptive templates (3 of 3)
  contrib/experimental/great_expectations_experimental/expectations/expect_column_discrete_entropy_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_distribution_to_match_benfords_law.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_kurtosis_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_pair_values_to_have_difference_of_custom_percentage.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_skew_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_sum_to_be.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_edtf_parseable.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_hexadecimal.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_in_set_spark_optimized.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_normally_distributed.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_crc32.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_github_username.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_iata_code.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_json.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_powers_of_base.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_xml_schema.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_wasserstein_distance_to_be_less_than.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_pair_values_to_have_diff.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_value_frequency_to_meet_threshold.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_table_row_count_to_be.py
  contrib/experimental/great_expectations_experimental/expectations/expect_table_checksum_to_equal_other_table.py
  contrib/great_expectations_zipcode_expectations/great_expectations_zipcode_expectations/expectations/expect_column_values_to_be_valid_florida_zip.py
  contrib/great_expectations_zipcode_expectations/great_expectations_zipcode_expectations/expectations/expect_column_values_to_be_valid_general_zipcode.py
  contrib/great_expectations_zipcode_expectations/great_expectations_zipcode_expectations/expectations/expect_column_values_to_be_valid_idaho_zip.py
  contrib/great_expectations_zipcode_expectations/great_expectations_zipcode_expectations/expectations/expect_column_values_to_be_valid_kansas_zip.py
  contrib/great_expectations_zipcode_expectations/great_expectations_zipcode_expectations/expectations/expect_column_values_to_be_valid_new_mexico_zip.py
  contrib/great_expectations_zipcode_expectations/great_expectations_zipcode_expectations/expectations/expect_column_values_to_be_valid_north_carolina_zip.py
  contrib/great_expectations_zipcode_expectations/great_expectations_zipcode_expectations/expectations/expect_column_values_to_be_valid_utah_zip.py
  great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/expectations/core/expect_column_values_to_be_null.py
  great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex_list.py
  great_expectations/expectations/core/expect_table_row_count_to_equal.py
  great_expectations/expectations/expectation.py
  great_expectations/render/components.py
  great_expectations/render/renderer_configuration.py
  tests/expectations/core/test_expect_column_values_to_match_regex_parameterized.py
  tests/expectations/snapshots/snap_test_expectation_atomic_renderers.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_max_to_be_between_custom.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_pair_values_to_have_a_difference_of_three.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_multicolumn_values_to_be_multiples_of_three.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_queried_column_value_frequency_to_meet_threshold.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_queried_table_row_count_to_be.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_table_columns_to_be_unique.py
  tests/integration/docusaurus/expectations/examples/query_expectation_template.py
  tests/render/test_inline_renderer.py
  tests/render/test_renderer_configuration.py
Labels: core-team, platform

#6594 [MAINTENANCE] Add docs snippet checker to `dev` CI
  azure-pipelines-dev.yml
Labels: core-team, platform

#6590 [BUGFIX] Use v3.3.6 or higher of google-cloud-bigquery (with shapely bugfix)
  constraints-dev.txt
  great_expectations/core/usage_statistics/package_dependencies.py
  reqs/requirements-dev-bigquery.txt
Labels: core-team, dx

#6596 [MAINTENANCE] Utilize a `StrEnum` for `ConfigPeer` modes
  great_expectations/core/config_peer.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  pyproject.toml
Labels: core-team, platform

#6597 [BUGFIX] Remove rendered header from Cloud-rendering tests
  tests/data_context/cloud_data_context/test_include_rendered_content.py
Labels: core-team, platform

#6606 [DOCS] Patch broken snippet around Validation Actions
  docs/guides/validation/advanced/how_to_get_data_docs_urls_for_custom_validation_actions.md
Labels: core-team, platform

#6603 [DOCS] Fix formatting of 0.15.35 and 0.15.36 in changelogs
  docs/changelog.md
Labels: core-team, platform

#6605 [BUGFIX] Patch broken `Validator` test after `DataContext` refactor
  tests/validator/test_validator.py
Labels: core-team, platform

#6604 [BUGFIX] Column value counts metric `dtype` inference due to `numpy` deprecation of `object` `dtype`
  great_expectations/expectations/metrics/column_aggregate_metrics/column_value_counts.py
  tests/expectations/metrics/test_core.py
Labels: core-team, platform

#6607 [MAINTENANCE] flake8 coverage - `render`, `juptyer_ux`, `checkpoint` sub-packages
  great_expectations/checkpoint/actions.py
  great_expectations/jupyter_ux/expectation_explorer.py
  great_expectations/render/renderer/checkpoint_new_notebook_renderer.py
  great_expectations/render/renderer/page_renderer.py
  great_expectations/render/renderer/site_builder.py
  great_expectations/render/renderer/slack_renderer.py
  setup.cfg
Labels: core-team, platform

#6602 [MAINTENANCE] filter `RemovedInMarshmallow4` warnings
  great_expectations/data_context/types/base.py
  pyproject.toml
Labels: core-team, platform

#6595 [FEATURE] ZEP - PG `SqlYearMonthSplitter` serialization + deserialization
  great_expectations/experimental/datasources/postgres_datasource.py
  tests/experimental/datasources/config.yaml
  tests/experimental/datasources/test_config.py
Labels: core-team, platform

#6611 [DOCS] Convert broken snippet to named snippets
  docs/guides/validation/advanced/how_to_get_data_docs_urls_for_custom_validation_actions.md
  great_expectations/checkpoint/actions.py
Labels: core-team, dx

#6600 [MAINTENANCE] Generate public API candidates
  docs/sphinx_api_docs_source/tasks.py
  scripts/public_api_report.py
  tests/scripts/test_public_api_report.py
Labels: core-team, dx

#6586 [FEATURE] ID/PK - `unexpected_index_list` updated to include actual unexpected value, and EVR to include `unexpected_index_column_names`
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/map_metric_provider.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/expectations/metrics/column_map_metrics/test_unexpected_indices_and_query.py
Labels: core-team, dx

#6601 [BUGFIX] `delete_datasource()` was getting passed in incorrect parameter for Spark Docs test
  tests/integration/docusaurus/connecting_to_your_data/datasource_configuration/how_to_configure_a_spark_datasource.py
Labels: core-team, dx

#6335 [MAINTENANCE] partial `cli` + `usage_stats` typing
  great_expectations/cli/batch_request.py
  great_expectations/cli/datasource.py
  great_expectations/cli/project.py
  great_expectations/cli/python_subprocess.py
  great_expectations/cli/store.py
  great_expectations/cli/suite.py
  great_expectations/cli/toolkit.py
  great_expectations/cli/util.py
  great_expectations/cli/v012/datasource.py
  great_expectations/cli/v012/init.py
  great_expectations/cli/v012/suite.py
  great_expectations/cli/v012/validation_operator.py
  great_expectations/core/usage_statistics/util.py
  great_expectations/datasource/simple_sqlalchemy_datasource.py
  pyproject.toml
  setup.cfg
Labels: core-team

#6232 [FEATURE] Atomic rendering of Evaluation Parameters
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/registry.py
  great_expectations/render/exceptions.py
  great_expectations/render/renderer/inline_renderer.py
  great_expectations/render/renderer_configuration.py
  great_expectations/validator/validator.py
  tests/expectations/snapshots/snap_test_expectation_atomic_renderers.py
  tests/render/test_inline_renderer.py
  tests/validator/test_validator.py
Labels: core-team

#6609 [MAINTENANCE] update pip installs in pipelines
  azure-pipelines-contrib.yml
  azure-pipelines-dev.yml
  azure-pipelines-docs-integration.yml
  azure-pipelines-gcp-integration.yml
  azure-pipelines-os-integration.yml
  azure-pipelines.yml
  setup.py
Labels: core-team, dx

#6614 [BUGFIX] Stop overwriting query with static string in RuntimeBatchRequests for SQL
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
Labels: devrel

#6610 [BUGFIX] Simplify metric results processing and improve detection of Decimal types in columns
  great_expectations/rule_based_profiler/attributed_resolved_metrics.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/util.py
  tests/conftest.py
  tests/experimental/datasources/test_integration_sql_datasource.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant_happy_paths.py
  tests/test_sets/taxi_yellow_tripdata_samples/samples_2021/yellow_tripdata_sample_2021.csv
Labels: core-team, platform

#6612 [FEATURE] Add zep datasource data assistant e2e tests.
  great_expectations/experimental/datasources/postgres_datasource.py
  tests/experimental/datasources/conftest.py
  tests/experimental/datasources/test_integration_sql_datasource.py
  tests/experimental/datasources/test_postgres_datasource.py
Labels: core-team, platform

#6621 [MAINTENANCE] create cache as part of `--ci` type-checking step
  azure-pipelines-dev.yml
  azure-pipelines.yml
  tasks.py
Labels: core-team, platform

#6616 [MAINTENANCE] Add `row_condition` logic to `RendererConfiguration` and remove from atomic renderer implementations
  great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_most_common_value_to_be_in_set.py
  great_expectations/expectations/core/expect_column_pair_values_a_to_be_greater_than_b.py
  great_expectations/expectations/core/expect_column_pair_values_to_be_equal.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_equal.py
  great_expectations/expectations/core/expect_column_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_be_null.py
  great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py
  great_expectations/expectations/expectation.py
  great_expectations/render/renderer_configuration.py
  tests/validator/test_validator.py
Labels: core-team, platform

#6624 [MAINTENANCE] install `pydantic` in develop pipeline
  azure-pipelines.yml
Labels: core-team, platform

#6623 [FEATURE] F/great 1400/sql datasource
  great_expectations/experimental/datasources/postgres_datasource.py
  great_expectations/experimental/datasources/sql_datasource.py
  great_expectations/experimental/datasources/type_lookup.py
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_postgres_datasource.py
  tests/experimental/datasources/test_type_lookup.py
Labels: core-team, platform

#6613 [FEATURE] Accept a `pathlib.Path` `context_root_dir`
  great_expectations/alias_types.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context/serializable_data_context.py
  great_expectations/util.py
  tests/data_context/test_data_context_variables.py
  tests/data_context/test_get_data_context.py
  tests/test_utils.py
Labels: core-team, platform, dx

#6628 [MAINTENANCE] Fix develop static type-check stage
  reqs/requirements-dev-contrib.txt
Labels: core-team, platform

#6627 [FEATURE] Atomic rendering of meta notes
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_dateutil_parseable.py
  great_expectations/expectations/core/expect_column_values_to_be_decreasing.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/expectations/core/expect_column_values_to_be_increasing.py
  great_expectations/expectations/core/expect_column_values_to_be_json_parseable.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/core/expect_column_values_to_be_unique.py
  great_expectations/expectations/core/expect_column_values_to_match_json_schema.py
  great_expectations/expectations/core/expect_column_values_to_match_regex.py
  great_expectations/expectations/core/expect_column_values_to_match_regex_list.py
  great_expectations/expectations/core/expect_column_values_to_match_strftime_format.py
  great_expectations/expectations/core/expect_column_values_to_not_be_null.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex_list.py
  great_expectations/expectations/core/expect_compound_columns_to_be_unique.py
  great_expectations/expectations/core/expect_multicolumn_values_to_be_unique.py
  great_expectations/expectations/core/expect_select_column_values_to_be_unique_within_record.py
  great_expectations/expectations/core/expect_table_column_count_to_be_between.py
  great_expectations/expectations/core/expect_table_column_count_to_equal.py
  great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py
  great_expectations/expectations/core/expect_table_columns_to_match_set.py
  great_expectations/expectations/core/expect_table_row_count_to_equal_other_table.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/regex_based_column_map_expectation.py
  great_expectations/expectations/set_based_column_map_expectation.py
  great_expectations/profile/base.py
  great_expectations/profile/basic_suite_builder_profiler.py
  great_expectations/profile/json_schema_profiler.py
  great_expectations/render/components.py
  great_expectations/render/renderer_configuration.py
  tests/conftest.py
  tests/profile/test_basic_suite_builder_profiler.py
  tests/profile/test_jsonschema_profiler.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
  tests/render/test_column_section_renderer.py
  tests/render/test_default_markdown_view.py
  tests/render/test_inline_renderer.py
  tests/render/test_page_renderer.py
Labels: core-team, platform

#6626 [DOCS] - add anonymous_usage_statistics configutation in documentation
  docs/deployment_patterns/how_to_use_great_expectations_in_aws_glue.md
  tests/integration/docusaurus/deployment_patterns/aws_glue_deployment_patterns_great_expectations.yaml
Labels: community

#6619 [BUGFIX] Do not round output of proportion computing metrics
  great_expectations/rule_based_profiler/attributed_resolved_metrics.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/validator/metrics_calculator.py
  pyproject.toml
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant_happy_paths.py
Labels: core-team, platform

#6634 [MAINTENANCE] Unexpected Counts table in DataDocs able to show counts for sampled values
  great_expectations/expectations/expectation.py
  tests/render/fixtures/ValidationResultsPageRenderer_render_with_run_info_at_end.json
  tests/render/fixtures/ValidationResultsPageRenderer_render_with_run_info_at_start.json
  tests/render/test_render_ValidationResultsTableContentBlockRenderer.py
Labels: core-team, dx

#6639 [MAINTENANCE] CI - install from `requirements-types.txt`
  azure-pipelines-dev.yml
  azure-pipelines.yml
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/data_context/types/base.py
  great_expectations/render/components.py
  great_expectations/util.py
  reqs/requirements-dev-contrib.txt
  reqs/requirements-dev-lite.txt
  requirements-types.txt
Labels: core-team, platform

#6599 [DOCS] fixing wrong line reference on docs
  docs/guides/connecting_to_your_data/how_to_configure_a_runtimedataconnector.md
Labels: community

#6638 [FEATURE] Docstring linter for public api
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/data_context/data_context/abstract_data_context.py
  pyproject.toml
  reqs/requirements-dev-lite.txt
  scripts/check_public_api_docstrings.py
  scripts/public_api_report.py
  tasks.py
  tests/scripts/test_public_api_report.py
Labels: core-team, dx

#6635 [BUGFIX] Add sqrt on connect to sqlite database.
  azure-pipelines.yml
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  tests/datasource/conftest.py
  tests/experimental/datasources/test_integration_sql_datasource.py
Labels: core-team, platform

#6641 [MAINTENANCE] Add docstring linter for public api to CI
  azure-pipelines-dev.yml
  azure-pipelines.yml
Labels: core-team, dx

#6631 [FEATURE] ZEP - Load/dump new style config from DataContext
  great_expectations/cli/toolkit.py
  great_expectations/data_context/config_validator/yaml_config_validator.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context/serializable_data_context.py
  great_expectations/data_context/types/base.py
  great_expectations/experimental/datasources/config.py
  pyproject.toml
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_viral_snippets.py
  tests/experimental/datasources/zep_config.yaml
Labels: core-team, platform, dx

#6642 [FEATURE] Use docstring linter for public api to catch missing parameters
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/data_context/config_validator/yaml_config_validator.py
  great_expectations/data_context/data_context/abstract_data_context.py
  pyproject.toml
  reqs/requirements-dev-lite.txt
  scripts/check_public_api_docstrings.py
  tasks.py
Labels: core-team, dx

#6643 Skip postgres tests in spark.
  azure-pipelines.yml
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant_happy_paths.py
Labels: core-team, platform

#6629 [MAINTENANCE] Enrich `RendererConfiguration` primitive types
  great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_most_common_value_to_be_in_set.py
  great_expectations/expectations/core/expect_column_pair_cramers_phi_value_to_be_less_than.py
  great_expectations/expectations/core/expect_column_pair_values_a_to_be_greater_than_b.py
  great_expectations/expectations/core/expect_column_pair_values_to_be_equal.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_to_exist.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_equal.py
  great_expectations/expectations/core/expect_column_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_be_null.py
  great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_equal.py
  great_expectations/expectations/expectation.py
  great_expectations/render/components.py
  great_expectations/render/renderer_configuration.py
  great_expectations/render/types/__init__.py
  pyproject.toml
  tests/render/test_renderer_configuration.py
Labels: core-team, platform

#6632 [BUGFIX] `RendererConfiguration` `min_value` and `max_value` with `datetime`s
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/render/renderer_configuration.py
Labels: core-team, platform

#6644 [MAINTENANCE] M/great 1225/async builds branch
  azure-pipelines.yml
Labels: core-team, platform

#6648 [MAINTENANCE] Comment out calling _disable_progress_bars in build_gallery.py
  assets/scripts/build_gallery.py
Labels: core-team, dx

#6650 [BUGFIX] Fix a typo in contrib queried expectation (and add type hints to its implementation)
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_slowly_changing_table_to_have_no_gaps.py
Labels: core-team, platform

#6649 [DOCS] Sidebar changes for Integrations and how-tos
  docs/deployment_patterns/integrations_and_howtos_overview.md
  sidebars.js
  static/_redirects
Labels: devrel

#6646 [DOCS] edit term(data_conext, checkpoints)-link in with airflow
  docs/deployment_patterns/how_to_use_great_expectations_with_airflow.md
Labels: community

#6651 [MAINTENANCE] Update generate_expectation_tests func to only log an ERROR message if there is an error
  great_expectations/self_check/util.py
Labels: core-team, dx

#6652 [MAINTENANCE] Use the correct test for positive_test__exact_min_and_max on trino
  tests/test_definitions/column_aggregate_expectations/expect_column_stdev_to_be_between.json
Labels: core-team, dx

#6653 [MAINTENANCE] Update evaluate_json_test_v3_api func to use the debug_logger with useful info when exception occurs
  great_expectations/expectations/expectation.py
  great_expectations/self_check/util.py
Labels: core-team, dx

#6661 [MAINTENANCE] Make only column y data_alt different in col_pair_equal tests
  tests/test_definitions/column_pair_map_expectations/expect_column_pair_values_to_be_equal.json
Labels: core-team, dx

#6658 [MAINTENANCE] Add separate tests for exact stdev for redshift and snowflake
  tests/test_definitions/column_aggregate_expectations/expect_column_stdev_to_be_between.json
Labels: core-team, dx

#6659 [MAINTENANCE] Add redshift/snowflake casting for sample data on expect_column_values_to_be_of_type
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_of_type.json
Labels: core-team, dx

#6655 [FEATURE] ZEP - load from shared config
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context/serializable_data_context.py
  great_expectations/data_context/types/base.py
  great_expectations/experimental/datasources/config.py
  great_expectations/experimental/datasources/experimental_base_model.py
  tests/experimental/datasources/great_expectations.yml
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_viral_snippets.py
Labels: core-team, platform, dx

#6622 [FEATURE] Added new expectation: ExpectYesterdayCountComparedToAvgEquivalentDaysOfWeek…
  contrib/experimental/great_expectations_experimental/expectations/expect_yesterday_count_compared_to_avg_equivalent_days_of_week.py
Labels: community

#6667 [DOCS] DOC-400 remove an outdated video link
  docs/guides/setup/configuring_data_contexts/how_to_instantiate_a_data_context_without_a_yml_file.md
Labels: devrel

#6666 [DOCS] doc-356 importable prerequisite box with correct theme applied and default entries
  docs/components/_prerequisites.jsx
Labels: devrel

#6657 [FEATURE] Add sqlite datasource
  great_expectations/experimental/datasources/__init__.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/sql_datasource.py
  great_expectations/experimental/datasources/sqlite_datasource.py
  tests/experimental/datasources/test_integration_sql_datasource.py
  tests/experimental/datasources/test_sqlite_datasource.py
Labels: core-team, platform

#6668 [MAINTENANCE] Add redshift/snowflake casting for sample data on expect_column_values_to_be_in_type_list
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_in_type_list.json
Labels: core-team, dx

#6670 [MAINTENANCE] Make only column y data_alt different in col_pair_in_set tests
  tests/test_definitions/column_pair_map_expectations/expect_column_pair_values_to_be_in_set.json
Labels: core-team, dx

#6675 [BUGFIX] Avoid key collisions between Rule-Based Profiler terminal literals and MetricConfiguration value keys
  great_expectations/core/expectation_suite.py
  great_expectations/rule_based_profiler/parameter_container.py
Labels: core-team, platform

#6669 [MAINTENANCE] Only spark v2 for special test in not_be_in_set
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_be_in_set.json
  tests/test_definitions/test_expectations_v2_api.py
Labels: core-team, dx

#6663 [BUGFIX] Add connect args to execution engine schema
  great_expectations/data_context/types/base.py
Labels: community

#6664 [Feature] ExpectDaySumToBeCloseToEquivalentWeekDayMean
  contrib/experimental/great_expectations_experimental/expectations/expect_day_sum_to_be_close_to_equivalent_week_day_mean.py
Labels: community

#6660 [FEATURE] ID/PK flag `return_unexpected_index_query` that allows `QUERY` output to be suppressed
  great_expectations/expectations/metrics/map_metric_provider.py
  tests/checkpoint/test_checkpoint_result_format.py
Labels: core-team, dx

#6674 [FEATURE] F/great 1400/postgres constr
  great_expectations/experimental/datasources/postgres_datasource.py
  tests/experimental/datasources/great_expectations.yml
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_postgres_datasource.py
  tests/experimental/datasources/test_sqlite_datasource.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant_happy_paths.py
Labels: core-team, platform

#6656 [FEATURE] Ensure Pandas ID/PK can use named indices
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/util.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/expectations/metrics/test_metrics_util.py
Labels: core-team, dx

#6672 [MAINTENANCE] Don't attempt any regex Expectation tests with snowflake
  great_expectations/expectations/metrics/util.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_regex.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_regex_list.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_match_regex.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_match_regex_list.json
Labels: core-team, dx
