Repository great-expectations/great_expectations, pull requests merged in 2022-04, with the labels that each got.

#4594 [BUGFIX] Adjust output of `regex` ParameterBuilder to match Expectation
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  tests/conftest.py
  tests/rule_based_profiler/parameter_builder/test_regex_pattern_string_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_simple_date_format_string_parameter_builder.py
  tests/test_fixtures/rule_based_profiler/bobby_user_workflow_verbose_profiler_config.yml
Labels: core-team

#4614 [BUGFIX] Rule-Based Profiler: Only primitive type based BatchRequest is allowed for Builder classes
  great_expectations/checkpoint/checkpoint.py
  great_expectations/checkpoint/util.py
  great_expectations/core/batch.py
  great_expectations/data_context/data_context.py
  great_expectations/data_context/types/base.py
  great_expectations/rule_based_profiler/domain_builder/domain_builder.py
  great_expectations/rule_based_profiler/expectation_configuration_builder/expectation_configuration_builder.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/rule/rule.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/rule_based_profiler/types/builder.py
  great_expectations/validator/validator.py
  tests/rule_based_profiler/domain_builder/test_domain_builder.py
  tests/rule_based_profiler/test_rule_based_profiler.py
Labels: core-team

#4622 [MAINTENANCE] Simplify ParameterBuilder.build_parameter() interface
  great_expectations/rule_based_profiler/expectation_configuration_builder/expectation_configuration_builder.py
  great_expectations/rule_based_profiler/parameter_builder/mean_unexpected_map_metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/rule/rule.py
  tests/rule_based_profiler/expectation_configuration_builder/test_default_expectation_configuration_builder.py
  tests/rule_based_profiler/parameter_builder/test_mean_unexpected_map_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_regex_pattern_string_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_simple_date_format_string_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_value_set_multi_batch_parameter_builder.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/BasicExample_RBP_Instantiation_and_running.ipynb
Labels: core-team

#4567 [MAINTENANCE] EOL Python 3.6
  .github/workflows/test-pep273-compatibility.yml
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
  constraints_py36.txt
  contrib/experimental/setup.py
  docker/build.py
  docs/contributing/contributing_setup.md
  docs/guides/setup/setup_overview.md
  great_expectations/core/expectation_diagnostics/expectation_diagnostics.py
  great_expectations/core/expectation_diagnostics/supporting_types.py
  great_expectations/core/usage_statistics/package_dependencies.py
  requirements.txt
  setup.py
  tests/conftest.py
  tests/rule_based_profiler/conftest.py
  tests/rule_based_profiler/parameter_builder/test_parameter_computations.py
Labels: core-team

#4572 [MAINTENANCE] War on Warnings - DataContext
  great_expectations/data_context/store/database_store_backend.py
  great_expectations/expectations/metrics/column_map_metrics/column_value_lengths.py
  great_expectations/util.py
  tests/data_context/test_data_context_test_yaml_config.py
  tests/data_context/test_data_context_v013.py
Labels: core-team

#4662 [MAINTENANCE] Provide cardinality limit modes from CategoricalColumnDomainBuilder
  great_expectations/rule_based_profiler/domain_builder/categorical_column_domain_builder.py
  great_expectations/rule_based_profiler/helpers/cardinality_checker.py
  tests/rule_based_profiler/domain_builder/test_categorical_column_domain_builder.py
Labels: core-team

#4670 [MAINTENANCE] Rule-Based Profiler: Rname Rule.generate() to Rule.run()
  great_expectations/rule_based_profiler/rule/rule.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
Labels: core-team

#4687 [MAINTENANCE] Refactor ValidationParameter computation (to be more elegant/compact) and fix a type hint in SimpleDateFormatStringParameterBuilder
  great_expectations/rule_based_profiler/expectation_configuration_builder/expectation_configuration_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
Labels: core-team

#4681 [MAINTENANCE] Remove `pybigquery` check that is no longer needed
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/metrics/util.py
  great_expectations/self_check/util.py
Labels: core-team

#4678 [BUGFIX] Fix DataContext templates test
  tests/data_context/test_templates.py
Labels: core-team

#4693 [FEATURE] More package contrib info
  contrib/capitalone_dataprofiler_expectations/package_info.yml
  contrib/capitalone_dataprofiler_expectations/requirements.txt
  contrib/cli/great_expectations_contrib/package.py
Labels: devrel

#4694 [DOCS] Fixes import statement.
  docs/guides/setup/configuring_data_contexts/how_to_instantiate_a_data_context_without_a_yml_file.md
Labels: devrel

#4592 [HACKATHON] ExpectColumnValuesToBeValidPhonenumber
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_phonenumber.py
Labels: community, devrel, hackathon-2022

#4591 [HACKATHON] ExpectColumnValuesToBePolygonAreaBetween
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_polygon_area_between.py
Labels: community, devrel, hackathon-2022

#4698 [MAINTENANCE] Rule-Based Profiler: Allow ExpectationConfigurationBuilder to be Optional
  great_expectations/rule_based_profiler/config/base.py
  great_expectations/rule_based_profiler/rule/rule.py
  tests/rule_based_profiler/config/test_base.py
  tests/rule_based_profiler/conftest.py
Labels: core-team

#4699 [MAINTENANCE] Slightly Clean Up NumericMetricRangeMultiBatchParameterBuilder
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
Labels: core-team

#4701 [MAINTENANCE] ParameterBuilder must not recompute its value, if it already exists in RuleState (ParameterContainer for its Domain).
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
Labels: core-team

#4704 [FEATURE] Introducing RuleState class and RuleOutput class for Rule-Based Profiler in support of richer use cases (such as DataAssistant).
  great_expectations/rule_based_profiler/expectation_configuration_builder/expectation_configuration_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/rule/__init__.py
  great_expectations/rule_based_profiler/rule/rule.py
  great_expectations/rule_based_profiler/rule/rule_output.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/rule_based_profiler/types/__init__.py
  great_expectations/rule_based_profiler/types/rule_state.py
  great_expectations/validator/validator.py
  tests/integration/profiling/rule_based_profilers/test_profiler_basic_workflows.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/integration/profiling/rule_based_profilers/test_rule_based_profiler.py
  tests/rule_based_profiler/conftest.py
  tests/rule_based_profiler/test_rule.py
  tests/rule_based_profiler/test_rule_based_profiler.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/BasicExample_RBP_Instantiation_and_running.ipynb
Labels: core-team

#4742 [MAINTENANCE] Remove unused bootstrap methods that were migrated to ML Flow
  great_expectations/rule_based_profiler/helpers/util.py
  tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py
Labels: core-team

#4773 [FEATURE] Add support for returning fully-qualified parameters names/values from RuleOutput object
  great_expectations/rule_based_profiler/rule/rule_output.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/rule_based_profiler/types/domain.py
  great_expectations/rule_based_profiler/types/parameter_container.py
  great_expectations/rule_based_profiler/types/rule_state.py
  great_expectations/validator/validator.py
  tests/rule_based_profiler/conftest.py
  tests/rule_based_profiler/test_rule_output.py
Labels: core-team

#4818 [MAINTENANCE] Remove bootstrap tests that are no longer needed
  tests/rule_based_profiler/parameter_builder/test_parameter_computations.py
Labels: core-team

#4762 [HACKATHON] ExpectColumnValuesToBeValidEthAddress
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_eth_address.py
Labels: community, devrel, hackathon-2022

#4673 [HACKATHON] ExpectColumnValuesToBeValidDoi
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_doi.py
Labels: community, devrel, hackathon-2022

#4672 [HACKATHON] ExpectColumnValuesToBeValidArxivId
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_arxiv_id.py
Labels: community, devrel, hackathon-2022

#4669 [HACKATHON] ExpectColumnValuesToBeValidTemperature
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_temperature.py
Labels: community, devrel, hackathon-2022

#4668 [HACKATHON] ExpectColumnValuesToBeValidIsbn13
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_isbn13.py
Labels: community, devrel, hackathon-2022

#4684 [HACKATHON] add expect_column_values_to_be_valid_country_fip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_country_fip.py
Labels: community, devrel, hackathon-2022

#4689 [HACKATHON] Expect column values to be valid us county name
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_us_county_name.py
Labels: community, devrel, hackathon-2022

#4696 [HACKATHON] add expect_column_values_to_be_valid_us_county_fip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_us_county_fip.py
Labels: community, devrel, hackathon-2022

#4697 [HACKATHON] add expect_column_values_to_be_valid_city_name
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_city_name.py
Labels: community, devrel, hackathon-2022

#4705 [HACKATHON] Expect column values to be valid ks state zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_kansas_zip.py
Labels: community, devrel, hackathon-2022

#4714 [HACKATHON] add expect_column_values_to_be_valid_md_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_maryland_zip.py
Labels: community, devrel, hackathon-2022

#4715 [HACKATHON] add expect_column_values_to_be_valid_ca_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_california_zip.py
Labels: community, devrel, hackathon-2022

#4716 [HACKATHON] add expect_column_values_to_be_valid_az_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_arizona_zip.py
Labels: community, devrel, hackathon-2022

#4717 [HACKATHON] Expect column values to be valid al zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_alabama_zip.py
Labels: community, devrel, hackathon-2022

#4814 [FEATURE] Additional Rule-Based Profiler Parameter/Variable Access Methods
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_in_set.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py
  great_expectations/rule_based_profiler/expectation_configuration_builder/default_expectation_configuration_builder.py
  great_expectations/rule_based_profiler/helpers/simple_semantic_type_filter.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/mean_unexpected_map_metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/rule/rule_output.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/rule_based_profiler/types/__init__.py
  great_expectations/rule_based_profiler/types/domain.py
  great_expectations/rule_based_profiler/types/parameter_container.py
  tests/conftest.py
  tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py
  tests/integration/profiling/rule_based_profilers/test_profiler_basic_workflows.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/integration/profiling/rule_based_profilers/test_rule_based_profiler.py
  tests/rule_based_profiler/domain_builder/test_cardinality_checker.py
  tests/rule_based_profiler/domain_builder/test_categorical_column_domain_builder.py
  tests/rule_based_profiler/domain_builder/test_domain.py
  tests/rule_based_profiler/parameter_builder/test_mean_unexpected_map_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_value_set_multi_batch_parameter_builder.py
  tests/rule_based_profiler/test_rule_based_profiler.py
  tests/rule_based_profiler/test_rule_output.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/BasicExample_RBP_Instantiation_and_running.ipynb
Labels: core-team

#4720 [HACKATHON] add expect_column_values_to_be_valid_co_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_colorado_zip.py
Labels: community, devrel, hackathon-2022

#4722 [HACKATHON] add expect_column_values_to_be_valid_de_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_delaware_zip.py
Labels: community, devrel, hackathon-2022

#4723 [HACKATHON] add expect_column_values_to_be_valid_fl_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_florida_zip.py
Labels: community, devrel, hackathon-2022

#4724 [HACKATHON] add expect_column_values_to_be_valid_ga_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_georgia_zip.py
Labels: community, devrel, hackathon-2022

#4725 [HACKATHON] ass expect_column_values_to_be_valid_hi_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_hawaii_zip.py
Labels: community, devrel, hackathon-2022

#4726 [HACKATHON] add expect_column_values_to_be_valid_id_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_idaho_zip.py
Labels: community, devrel, hackathon-2022

#4727 [HACKATHON] add expect_column_values_to_be_valid_il_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_illinois_zip.py
Labels: community, devrel, hackathon-2022

#4728 [HACKATHON] add expect_column_values_to_be_valid_in_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_indiana_zip.py
Labels: community, devrel, hackathon-2022

#4729 [HACKATHON] add expect_column_values_to_be_valid_ia_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_iowa_zip.py
Labels: community, devrel, hackathon-2022

#4647 [HACKATHON] ColumnValuesLinestringKMDistanceBetween
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_line_km_distance_between.py
Labels: community, devrel, hackathon-2022

#4651 [HACKATHON] add ExpectColumnValuesLinestringMilesDistanceBetween
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_line_miles_distance_between.py
Labels: community, devrel, hackathon-2022

#4712 [HACKATHON] add expect_column_values_to_be_valid_va_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_virginia_zip.py
Labels: community, devrel, hackathon-2022

#4667 [HACKATHON] ExpectColumnValuesToBeValidIsbn10
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_isbn10.py
Labels: community, devrel, hackathon-2022

#4685 [HACKATHON] ExpectColumnValuesToBeValidHashtag
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_hashtag.py
Labels: community, devrel, hackathon-2022

#4741 [HACKATHON] ExpectColumnValuesToBeValidNasdaqTicker
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_nasdaq_ticker.py
Labels: community, devrel, hackathon-2022

#4743 [HACKATHON] ExpectColumnValuesToBeValidSp500Ticker
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_sp500_ticker.py
Labels: community, devrel, hackathon-2022

#4739 [HACKATHON] ExpectColumnValuesToBeValidDowTicker
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_dow_ticker.py
Labels: community, devrel, hackathon-2022

#4730 [HACKATHON] add expect_column_values_to_be_valid_ky_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_kentucky_zip.py
Labels: community, devrel, hackathon-2022

#4740 [HACKATHON] ExpectColumnPairValuesLatLngMatchesGeohash
  contrib/experimental/great_expectations_experimental/expectations/expect_column_pair_values_lat_lng_matches_geohash.py
Labels: community, devrel, hackathon-2022

#4578 [HACKATHON] ExpectColumnValuesToBeValidGeohash
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_geohash.py
Labels: community, devrel, hackathon-2022

#4713 [HACKATHON] add expect_column_values_to_be_valid_ny_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_new_york_state_zip.py
Labels: community, devrel, hackathon-2022

#4719 [HACKATHON] add expect_column_values_to_be_valid_ar_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_arkansas_zip.py
Labels: community, devrel, hackathon-2022

#4718 [HACKATHON] add expect_column_values_to_be_valid_ak_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_alaska_zip.py
Labels: community, devrel, hackathon-2022

#4721 [HACKATHON] add expect_column_values_to_be_valid_ct_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_connecticut_zip.py
Labels: community, devrel, hackathon-2022

#4823 [MAINTENANCE] Refactor Rule-Based Profiler instantiation in Validator to make it available as a public method
  great_expectations/validator/validator.py
Labels: core-team

#4810 {HACKATHON expect column values to have elevation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_have_elevation.py
Labels: community, devrel, hackathon-2022

#4797 [HACKATHON] add expect_column_values_to_be_valid_texas_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_texas_zip.py
Labels: community, devrel, hackathon-2022

#4796 [HACKATHON] add expect_column_values_to_be_tennessee_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_tennessee_zip.py
Labels: community, devrel, hackathon-2022

#4795 [HACKATHON] expect_column_values_to_be_valid_south_dakota_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_south_dakota_zip.py
Labels: community, devrel, hackathon-2022

#4794 [HACKATHON] add expect_column_values_to_be_valid_south_carolina_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_south_carolina_zip.py
Labels: community, devrel, hackathon-2022

#4793 [HACKATHON] add expect_column_values_to_be_valid_rhode_island_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_rhode_island_zip.py
Labels: community, devrel, hackathon-2022

#4792 [HACKATHON] add expect_column_values_to_be_valid_pennsylvania_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_pennsylvania_zip.py
Labels: community, devrel, hackathon-2022

#4789 [HACKATHON] add expect_column_values_to_be_valid_ohio_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_ohio_zip.py
Labels: community, devrel, hackathon-2022

#4788 [HACKATHON] add expect_column_values_to_be_valid_north_dakota_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_north_dakota_zip.py
Labels: community, devrel, hackathon-2022

#4779 [HACKATHON] add expect_column_values_to_be_valid_new_mexico_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_new_mexico_zip.py
Labels: community, devrel, hackathon-2022

#4775 [HACKATHON] add expect_column_values_to_be_valid_new_hampshire_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_new_hampshire_zip.py
Labels: community, devrel, hackathon-2022

#4772 Expect column values to be valid nebraska zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_nebraska_zip.py
Labels: community, devrel, hackathon-2022

#4765 Expect column values to be valid montana zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_montana_zip.py
Labels: community, devrel, hackathon-2022

#4764 Expect column values to be valid missouri zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_missouri_zip.py
Labels: community, devrel, hackathon-2022

#4761 [HACKATHON] add expect_column_values_to_be_valid_minnesota_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_minnesota_zip.py
Labels: community, devrel, hackathon-2022

#4757 [HACKATHON] expect column_values_to_be_valid_michigan_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_michigan_zip.py
Labels: community, devrel, hackathon-2022

#4745 [HACKATHON] add expect_column_values_to_be_valid_louisiana_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_louisiana_zip.py
Labels: community, devrel, hackathon-2022

#4664 [HACKATHON] add expect_column_values_to_be_valid_barcode
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_barcode.py
Labels: community, devrel, hackathon-2022

#4665 [HACKATHON] add expect_column_values_to_be_valid_http_method
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_http_method.py
Labels: community, devrel, hackathon-2022

#4666 [HACKATHON] ExceptColumnValuesUrlIsAvailable
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_url_is_available.py
Labels: community, devrel, hackathon-2022

#4683 [HACKATHON] ExceptColumnValuesToBePrimeNumber
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_prime_number.py
Labels: community, devrel, hackathon-2022

#4695 [HACKATHON] ExpectColumnValuesToBeNotHoliday
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_not_holiday.py
Labels: community, devrel, hackathon-2022

#4703 [HACKATHON] ExceptColumnValuesToBeValidDate
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_date.py
Labels: community, devrel, hackathon-2022

#4746 [HACKATHON] ExceptColumnValuesToBeValidIsan
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_isan.py
Labels: community, devrel, hackathon-2022

#4747 [HACKATHON] ExceptColumnToBeValidIsmn
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_ismn.py
Labels: community, devrel, hackathon-2022

#4752 [HACKATHON] ExceptColumnValuesToBeValidImsi
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_imsi.py
Labels: community, devrel, hackathon-2022

#4753 [HACKATHON] ExceptColumnValuesToBeValidImei
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_imei.py
Labels: community, devrel, hackathon-2022

#4754 [HACKATHON] ExceptColumnValuesToBeValidMeid
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_meid.py
Labels: community, devrel, hackathon-2022

#4756 [HACKATHON] ExceptColumnToBeValidIsin
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_isin.py
Labels: community, devrel, hackathon-2022

#4758 [HACKATHON] ExceptColumnValuesToBeValidEan
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_ean.py
Labels: community, devrel, hackathon-2022

#4760 [HACKATHON] expect_column_values_to_be_valid_bitcoin_address
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_bitcoin_address.py
Labels: community, devrel, hackathon-2022

#4766 [HACKATHON] expect_column_values_to_be_valid_bch_address
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_bch_address.py
Labels: community, devrel, hackathon-2022

#4809 [HACKATHON] Added ExpectColumnValuesLatLonToBeLandOrOcean
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_lat_lon_to_be_land_or_ocean.py
Labels: community, devrel, hackathon-2022

#4827 [MAINTENANCE] String Type is not needed as Return Type from DomainBuilder.domain_type()
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_lat_lon_to_be_land_or_ocean.py
  great_expectations/rule_based_profiler/domain_builder/categorical_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/column_pair_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/multi_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/table_domain_builder.py
  tests/test_fixtures/rule_based_profiler/plugins/my_custom_semantic_type_column_domain_builder.py
Labels: core-team

#4770 [HACKATHON] expect_column_values_to_be_valid_dot_address
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_dot_address.py
Labels: community, devrel, hackathon-2022

#4680 [HACKATHON] ExceptColumnValuesIpIsNotBlacklisted
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_ip_is_not_blacklisted.py
Labels: community, devrel, hackathon-2022

#4767 [HACKATHON] expect_column_values_to_be_valid_ltc_address
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_ltc_address.py
Labels: community, devrel, hackathon-2022

#4786 [HACKATHON] expect_column_values_to_be_valid_north_carolina_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_north_carolina_zip.py
Labels: community, devrel, hackathon-2022

#4749 [HACKATHON] add expect_column_values_to_be_valid_maine_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_maine_zip.py
Labels: community, devrel, hackathon-2022

#4755 [HACKATHON] add expect_column_values_to_be_valid_massachusetts_zip
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_massachusetts_zip.py
Labels: community, devrel, hackathon-2022

#4783 [HACKATHON] ExpectColumnValuesImsiBelongToCountryCode
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_imsi_belong_to_country_code.py
Labels: community, devrel, hackathon-2022

#4581 [HACKATHON] ExpectColumnValuesToBeLatLonInTimezone
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_lat_lon_in_timezone.py
Labels: community, devrel, hackathon-2022

#4768 [HACKATHON] expect_column_values_to_be_valid_doge_address
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_doge_address.py
Labels: community, devrel, hackathon-2022

#4808 [HACKATHON] ExpectColumnValuesToBeValidGeojson
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_geojson.py
Labels: community, devrel, hackathon-2022

#4829 [BUGFIX] Linting error from hackathon automerge
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_geojson.py
Labels: devrel

#4777 [HACKATHON] ExpectColumnValuesEthAddressPositiveBalance
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_eth_address_positive_balance.py
Labels: community, devrel, hackathon-2022

#4776 [HACKATHON] ExceptColumnValuesBitcoinAddressPositiveBalance
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_bitcoin_address_positive_balance.py
Labels: community, devrel, hackathon-2022

#4769 [HACKATHON] expect_column_values_to_be_valid_dash_address
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_dash_address.py
Labels: community, devrel, hackathon-2022

#4686 [HACKATHON] Added prescriptive renderers to 6 geospatial expectations
  contrib/experimental/great_expectations_experimental/expectations/expect_column_average_to_be_within_range_of_given_point.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_point_within_geo_region.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_lat_lon_coordinates_in_range_of_given_point.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_polygon_area_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_us_zipcode_within_mile_radius_of_given_zipcode.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_degree_decimal_coordinates.py
Labels: community, devrel, hackathon-2022

#4771 [HACKATHON] expect_column_values_to_be_valid_stellar_address
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_stellar_address.py
Labels: community, devrel, hackathon-2022

#4787 [HACKATHON] ExceptColumnValuesToBeValidMicMatchCountryCode
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_mic_match_country_code.py
Labels: community, devrel, hackathon-2022

#4785 [HACKATHON] ExpectColumnValuesToBeValidViesVat
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_vies_vat.py
Labels: community, devrel, hackathon-2022

#4691 [FEATURE] add icd10 regex expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_have_valid_icd10_code_format.py
Labels: community, devrel, hackathon-2022

#4690 [FEATURE] Expect column values to be http method
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_http_methods.py
Labels: community, devrel, hackathon-2022

#4784 [HACKATHON] ExpectColumnValuesToBeValidFormattedVat
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_formatted_vat.py
Labels: community, devrel, hackathon-2022

#4782 [HACKATHON] ExceptColumnValuesToBeGtinVariableMeasureTradeItem
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_gtin_variable_measure_trade_item.py
Labels: community, devrel, hackathon-2022

#4805 [HACKATHON] Added ExpectColumnValuesGeometryToBeOfType
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_geometry_to_be_of_type.py
Labels: community, devrel, hackathon-2022

#4806 [HACKATHON] Added ExpectColumnValuesToBeNonemptyGeometries
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_nonempty_geometries.py
Labels: community, devrel, hackathon-2022

#4781 [HACKATHON] ExpectColumnValuesToBeGtinBaseUnit
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_gtin_base_unit.py
Labels: community, devrel, hackathon-2022

#4630 [HACKATHON] add expect_column_values_to_be_valid_tld
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_tld.py
Labels: community, devrel, hackathon-2022

#4778 [HACKATHON] ExceptColumnValuesBitcoinTxIsConfirmed
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_bitcoin_tx_is_confirmed.py
Labels: community, devrel, hackathon-2022

#4807 [HACKATHON] ExpectColumnValuesReverseGeocodedLatLonToContain expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_reverse_geocoded_lat_lon_to_contain.py
Labels: community, devrel, hackathon-2022

#4688 [HACKATHON] Add ExpectColumnMiminumBoundingRadiusToBeBetween
  contrib/experimental/great_expectations_experimental/expectations/expect_column_minimum_bounding_radius_to_be_between.py
Labels: community, devrel, hackathon-2022

#4835 Fix Typo in Checkpoint Readme
  docs/guides/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config.md
Labels: community, devrel

#4838 [BUGFIX] Cleanup contrib
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_geometry_centroids_to_be_within_shape.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_geometry_to_be_near_shape.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_geometry_to_be_within_shape.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_geometry_to_intersect_shape.py
Labels: core-team

#4833 Fix links within datasource new notebook
  great_expectations/render/renderer/datasource_new_notebook_renderer.py
  tests/render/renderer/test_datasource_new_notebook_renderer.py
Labels: community, devrel

#4839 Adds missing dependency, which is breaking CLI workflows
  requirements.txt
Labels: devrel

#4841 [DOCS] Update all tutorial redirect fix
  docs/deployment_patterns/how_to_instantiate_a_data_context_hosted_environments.md
  docs/deployment_patterns/how_to_use_great_expectations_in_flyte.md
  docs/deployment_patterns/how_to_use_great_expectations_with_airflow.md
  docs/deployment_patterns/how_to_use_great_expectations_with_prefect.md
  docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_a_file_system_or_blob_store.md
  docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_tables_in_sql.md
  docs/guides/connecting_to_your_data/components/prerequisites.jsx
  docs/guides/connecting_to_your_data/database/athena.md
  docs/guides/connecting_to_your_data/how_to_configure_a_dataconnector_to_introspect_and_partition_a_file_system_or_blob_store.md
  docs/guides/connecting_to_your_data/how_to_configure_a_dataconnector_to_introspect_and_partition_tables_in_sql.md
  docs/guides/connecting_to_your_data/how_to_create_a_batch_of_data_from_an_in_memory_spark_or_pandas_dataframe.md
  docs/guides/connecting_to_your_data/how_to_get_a_batch_of_data_from_a_configured_datasource.md
  docs/guides/expectations/advanced/how_to_add_comments_to_expectations_and_display_them_in_data_docs.md
  docs/guides/expectations/advanced/how_to_create_renderers_for_custom_expectations.md
  docs/guides/expectations/how_to_create_and_edit_expectations_based_on_domain_knowledge_without_inspecting_data_directly.md
  docs/guides/expectations/how_to_create_and_edit_expectations_with_a_profiler.md
  docs/guides/expectations/how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data.md
  docs/guides/miscellaneous/how_to_quickly_explore_expectations_in_a_notebook.md
  docs/guides/setup/components/defaultPrerequisiteItems.jsx
  docs/guides/setup/components/install_prereq.jsx
  docs/guides/setup/configuring_data_contexts/how_to_configure_a_new_data_context_with_the_cli.md
  docs/guides/setup/configuring_data_contexts/how_to_configure_credentials.md
  docs/guides/setup/configuring_data_contexts/how_to_configure_datacontext_components_using_test_yaml_config.md
  docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_a_filesystem.md
  docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_amazon_s3.md
  docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_azure_blob_storage.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_amazon_s3.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_azure_blob_storage.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_gcs.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_on_a_filesystem.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_to_postgresql.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_amazon_s3.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_azure_blob_storage.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_gcs.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_on_a_filesystem.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_to_postgresql.md
  docs/guides/validation/advanced/how_to_deploy_a_scheduled_checkpoint_with_cron.md
  docs/guides/validation/advanced/how_to_implement_custom_notifications.md
  docs/guides/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config.md
  docs/guides/validation/checkpoints/how_to_create_a_new_checkpoint.md
  docs/guides/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.md
  docs/reference/customize_your_deployment.md
  docs/tutorials/getting_started/check_out_data_docs.md
  docs/tutorials/getting_started/connect_to_data.md
  docs/tutorials/getting_started/create_your_first_expectations.md
  docs/tutorials/getting_started/customize_your_deployment.md
  docs/tutorials/getting_started/initialize_a_data_context.md
  docs/tutorials/getting_started/intro.md
  docs/tutorials/getting_started/tutorial_review.md
  docs/tutorials/getting_started/validate_your_data.md
  sidebars.js
  static/_redirects
Labels: devrel

#4842 [BUGFIX] Add `notebook` to `GE_REQUIRED_DEPENDENCIES`
  great_expectations/core/usage_statistics/package_dependencies.py
Labels: core-team

#4840 [BUGFIX] ParameterContainer return value formatting bug fix
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/rule/rule.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/rule_based_profiler/types/__init__.py
  great_expectations/rule_based_profiler/types/parameter_container.py
Labels: core-team

#4843 [BUGFIX] Ensure that Parameter Validation/Configuration Dependency Configurations are included in Serialization
  great_expectations/rule_based_profiler/expectation_configuration_builder/default_expectation_configuration_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  tests/conftest.py
  tests/rule_based_profiler/parameter_builder/test_mean_unexpected_map_metric_multi_batch_parameter_builder.py
Labels: core-team

#4844 [FEATURE] DataAssistant and VolumeDataAssistant classes (initial implementation -- to be enhanced as part of subsequent work)
  great_expectations/rule_based_profiler/data_assistant/__init__.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  tests/rule_based_profiler/data_assistant/__init__.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#4848 [FEATURE] Add Support for Returning Parameters and Metrics as DataAssistantResult class
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/rule_based_profiler/types/__init__.py
  great_expectations/rule_based_profiler/types/data_assistant_result.py
  tests/conftest.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#4618 [BUGFIX] Correctly handle SQLA unexpected count metric for empty tables
  great_expectations/expectations/metrics/map_metric_provider.py
  tests/expectations/metrics/test_core.py
Labels: community, devrel

#4852 [MAINTENANCE] Update testing and documentation for `oneshot` estimation method
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
Labels: core-team

#4853 [MAINTENANCE] Refactor `Datasource` tests that work with `RuntimeDataConnector` by backend.
  tests/conftest.py
  tests/data_context/test_data_context_datasource_runtime_data_connector.py
  tests/datasource/test_new_datasource_with_runtime_data_connector.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_pandas_execution_engine.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_sparkdf_execution_engine.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_sql_execution_engine.py
  tests/datasource/test_new_datasource_with_sql_data_connector.py
Labels: core-team

#4854 [FEATURE] DataAssistantResult Includes Underlying Profiler Execution Time
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/domain_builder/domain_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/types/data_assistant_result.py
  great_expectations/util.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#4857 [MAINTENANCE] Update DataAssistant interfaces
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#4859 [MAINTENANCE] Improve types returned by DataAssistant interface methods
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
Labels: core-team

#4858 [MAINTENANCE] Refactor `DataContext` tests that work with RuntimeDataConnector by backend
  tests/data_context/datasource/__init__.py
  tests/data_context/datasource/test_data_context_datasource_non_sql_methods.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_pandas_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_sparkdf_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_sqlalchemy_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_sql_methods.py
  tests/data_context/test_data_context_datasource_runtime_data_connector.py
Labels: core-team

#4860 [FEATURE] Add batch_id for every resolved metric_value to ParameterBuilder.get_metrics() result object
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
Labels: core-team

#4861 [FEATURE] `RuntimeDataConnector` able to specify `Assets`
  great_expectations/data_context/types/base.py
  great_expectations/datasource/data_connector/asset/asset.py
  great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py
  great_expectations/datasource/data_connector/runtime_data_connector.py
  great_expectations/datasource/data_connector/util.py
  tests/conftest.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_pandas_execution_engine.py
  tests/datasource/data_connector/test_runtime_data_connector.py
Labels: core-team

#4869 [BUGFIX] Temporarily adjust Deprecation Warning Count
  great_expectations/datasource/data_connector/runtime_data_connector.py
  tests/test_deprecation.py
Labels: core-team

#4862 [FEATURE] RuleBasedProfiler/DataAssistant/MetricMultiBatchParameterBuilder: Enable Returning Metric Computation Results with batch_id Attribution
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/parameter_builder/mean_unexpected_map_metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/types/__init__.py
  great_expectations/rule_based_profiler/types/parameter_container.py
  tests/conftest.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#4872 [MAINTENANCE] Use defined constants for ParameterNode accessor keys
  great_expectations/rule_based_profiler/parameter_builder/mean_unexpected_map_metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
Labels: core-team

#4871 [FEATURE] Split data assets using sql datetime columns
  great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  tests/integration/db/test_sql_data_splitting.py
  tests/integration/fixtures/split_data/bigquery_connection_string.yml
  tests/integration/fixtures/split_data/mssql_connection_string.yml
  tests/integration/fixtures/split_data/mysql_connection_string.yml
  tests/integration/fixtures/split_data/postgres_connection_string.yml
  tests/integration/fixtures/split_data/snowflake_connection_string.yml
  tests/integration/test_script_runner.py
  tests/test_utils.py
Labels: core-team

#4875 [MAINTENANCE] Add Tanner to CODEOWNERS for schemas.py
  CODEOWNERS
Labels: core-team

#4881 [MAINTENANCE] `DataAssistantResult.plot()` conditional formatting and tooltips
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/types/altair_configuration.py
  great_expectations/rule_based_profiler/types/data_assistant_result.py
Labels: core-team

#4884 [MAINTENANCE] Add CI stage importing GE with only required dependencies installed
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
Labels: core-team
