Repository great-expectations/great_expectations, pull requests merged in 2022-10, with the labels that each got.

#6082 [MAINTENANCE] Bump version of `sqlalchemy-redshift` from `0.7.7` to `0.8.8`
  requirements-dev-redshift.txt
Labels: core-team

#6126 [MAINTENANCE] self_check linting & initial type-checking
  great_expectations/self_check/util.py
  great_expectations/util.py
  pyproject.toml
  setup.cfg
Labels: core-team

#6128 Update per Clickhouse multiple same aliases Bug
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
Labels: community, devrel

#6091 [MAINTENANCE] Only update existing `rendered_content` if rendering does not fail with new `InlineRenderer` failure message
  great_expectations/core/expectation_suite.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/registry.py
  great_expectations/render/renderer/inline_renderer.py
  great_expectations/render/types/__init__.py
  tests/data_context/test_data_context.py
  tests/expectations/test_run_diagnostics.py
  tests/rule_based_profiler/data_assistant/test_data_assistant_runner.py
Labels: core-team

#6149 [BUGFIX] Regression due to `GESqlDialect` `Enum` for Hive
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/execution_engine/sqlalchemy_dialect.py
  tests/execution_engine/test_sqlalchemy_dialect.py
Labels: core-team

#6154 [DOCS] Clarify wording for interactive mode in databricks
  docs/deployment_patterns/how_to_use_great_expectations_in_databricks.md
Labels: core-team

#6152 [RELEASE] 0.15.27
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team

#6155 [MAINTENANCE] Minor cleanup in preparation for Validator refactoring into separate concerns
  great_expectations/core/batch.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/pandas_batch_data.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sparkdf_batch_data.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/self_check/util.py
  great_expectations/validator/validator.py
  tests/execution_engine/test_execution_engine.py
Labels: core-team

#6122 [MAINTENANCE] add the internal `GE_DATA_CONTEXT_ID` env var to the docker file
  docker/Dockerfile.tests
Labels: core-team

#6153 [FEATURE] Initial zep datasource protocol.
  great_expectations/zep/interfaces.py
Labels: core-team

#6163 [MAINTENANCE] Rollback setting GE_DATA_CONTEXT_ID in docker image.
  docker/Dockerfile.tests
Labels: core-team

#6156 [FEATURE] Introduce BatchManager to manage Batch objects used by Validator and BatchData used by ExecutionEngine
  great_expectations/core/batch.py
  great_expectations/core/batch_manager.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/table_metrics/table_column_types.py
  great_expectations/self_check/util.py
  great_expectations/validator/validator.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/test_definitions/test_expectations_cfe.py
  tests/validator/test_validator.py
Labels: core-team

#6159 [BUGFIX] SQLAlchemy selectable Bug fix
  great_expectations/expectations/metrics/util.py
Labels: community

#6145 [FEATURE] Add support for Vertica dialect
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/execution_engine/sqlalchemy_dialect.py
  requirements-dev-sqlalchemy.txt
  requirements-dev-vertica.txt
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
  tests/test_packaging.py
Labels: community

#6165 [FEATURE] Introduce MetricsCalculator and Refactor Redundant Code out of Validator
  great_expectations/core/batch_manager.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/profile/user_configurable_profiler.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/validator/metrics_calculator.py
  great_expectations/validator/validation_graph.py
  great_expectations/validator/validator.py
  pyproject.toml
  scripts/check_type_hint_coverage.py
  tests/core/test_evaluation_parameters.py
  tests/core/test_metrics_calculator.py
  tests/validator/test_validator.py
Labels: core-team

#6169 [BUGFIX] Parameterize usage stats endpoint in test dockerfile.
  azure-pipelines.yml
  docker/Dockerfile.tests
  docker/README.md
Labels: core-team

#6170 [BUGFIX] B/great 1305/usage stats endpoint
  azure-pipelines-dev.yml
Labels: core-team

#6171 [MAINTENANCE] Re-add missing Expectations to gallery and include package names
  assets/scripts/build_gallery.py
  azure-pipelines-expectation-gallery.yml
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_be_xml_parseable.py
Labels: devrel

#6127 [MAINTENANCE] Use `from __future__ import annotations` to clean up type hints
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/data_context_key.py
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/data_context/migrator/cloud_migrator.py
  great_expectations/data_context/types/base.py
  great_expectations/profile/base.py
  great_expectations/rule_based_profiler/config/base.py
  great_expectations/rule_based_profiler/rule/rule_output.py
  great_expectations/rule_based_profiler/rule_state.py
  scripts/validate_docs_snippet_line_numbers.py
Labels: core-team

#6177 Make sure that quick stage check returns 0 if there are no problems
  azure-pipelines-expectation-gallery.yml
Labels: devrel

#6181 [DOCS] Update version in `runtime.txt` to fix breaking Netlify builds
  runtime.txt
Labels: core-team

#6180 [MAINTENANCE] Remove SQL for expect_column_discrete_entropy_to_be_between
  contrib/experimental/great_expectations_experimental/expectations/expect_column_discrete_entropy_to_be_between.py
Labels: devrel

#6172 [BUGFIX] Ensure that spaces are recognized in named snippets
  scripts/remark-named-snippets/index.js
Labels: core-team

#6142 [DOCS] Clean up snippets and line number validation in docs
  docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/guides/connecting_to_your_data/cloud/azure/pandas.md
  docs/guides/connecting_to_your_data/cloud/gcs/spark.md
  docs/guides/connecting_to_your_data/database/bigquery.md
  docs/guides/connecting_to_your_data/how_to_configure_a_dataconnector_to_introspect_and_partition_tables_in_sql.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_pair_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_parameterized_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_query_expectations.md
  docs/guides/miscellaneous/how_to_write_a_how_to_guide.md
  docs/guides/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.md
  docs/reference/checkpoints_and_actions.md
  docs/terms/checkpoint.md
  scripts/validate_docs_snippet_line_numbers.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_be_in_solfege_scale_set.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_only_contain_vowels.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_queried_column_value_frequency_to_meet_threshold.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_queried_table_row_count_to_be.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_table_columns_to_be_unique.py
  tests/integration/docusaurus/expectations/examples/query_expectation_template.py
Labels: core-team

#6179 [MAINTENANCE] Add unit test for MetricsCalculator.get_metric() Method -- as an example template
  tests/validator/test_metrics_calculator.py
Labels: core-team

#6178 [MAINTENANCE] ZEP MetaDatasource POC
  great_expectations/zep/__init__.py
  great_expectations/zep/interfaces.py
  great_expectations/zep/metadatasource.py
Labels: core-team

#6183 [RELEASE] 0.15.28
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team

#5487 [MAINTENANCE] Move test_yaml_config to a separate class
  great_expectations/core/usage_statistics/usage_statistics.py
  great_expectations/data_context/config_validator/__init__.py
  great_expectations/data_context/config_validator/yaml_config_validator.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  tests/data_context/test_data_context_test_yaml_config.py
  tests/integration/usage_statistics/test_usage_statistics_messages.py
Labels: core-team

#6189 Changed profiler to Data Assistant in CLI, docs, and tests
  docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_use_the_cli_to_begin_the_interactive_process_of_creating_expectations.mdx
  docs/tutorials/getting_started/tutorial_create_expectations.md
  docs_pending/tutorial_create_expectations_onboarding_assistant.md
  docs_rtd/guides/tutorials/getting_started_v3_api/create_your_first_expectations.rst
  great_expectations/cli/suite.py
  tests/cli/test_suite.py
Labels: core-team

#6192 [MAINTENANCE] Update default GE_USAGE_STATISTICS_URL in test docker image.
  docker/Dockerfile.tests
Labels: core-team

#6182 [MAINTENANCE] Re-add a renamed test definition file
  tests/render/test_render_BulletListContentBlock.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between.json
Labels: devrel

#6191 [MAINTENANCE] Refactor method `parse_evaluation_parameter`
  great_expectations/core/evaluation_parameters.py
Labels: core-team

#6188 [MAINTENANCE] Migrate methods from `BaseDataContext` to `AbstractDataContext`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
Labels: core-team

#6198 [MAINTENANCE] Test Trino doc examples with test_script_runner.py
  tests/integration/docusaurus/connecting_to_your_data/database/trino_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/trino_yaml_example.py
  tests/integration/test_script_runner.py
Labels: devrel

#5123 [FEATURE] Add support to AWS Glue Data Catalog
  great_expectations/core/batch_spec.py
  great_expectations/data_context/types/base.py
  great_expectations/datasource/data_connector/__init__.py
  great_expectations/datasource/data_connector/configured_asset_aws_glue_data_catalog_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_aws_glue_data_catalog_data_connector.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  requirements-dev-lite.txt
  requirements.txt
  tests/conftest.py
  tests/datasource/conftest.py
  tests/datasource/data_connector/test_configured_asset_glue_catalog_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_glue_catalog_data_connector.py
  tests/datasource/test_new_datasource_with_aws_glue_data_connector.py
Labels: community

#6196 [MAINTENANCE] Cleanup of Regex ParameterBuilder
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/rule_based_profiler/parameter_builder/test_regex_pattern_string_parameter_builder.py
Labels: core-team

#6204 [BUGFIX] Fix `test_package_dependencies.py` to include `py` lib
  great_expectations/core/usage_statistics/package_dependencies.py
Labels: core-team

#6203 [MAINTENANCE] Remove version matrix from `dev` CI pipeline to improve performance
  azure-pipelines-dev.yml
Labels: core-team

#6206 [MAINTENANCE] Rename `CloudMigrator.retry_unsuccessful_validations`
  great_expectations/data_context/migrator/cloud_migrator.py
  tests/data_context/migrator/test_cloud_migrator.py
Labels: core-team

#6209 [MAINTENANCE] Add validate_configuration method to expect_table_row_count_to_equal_other_table
  great_expectations/expectations/core/expect_table_row_count_to_equal_other_table.py
Labels: devrel

#6205 [MAINTENANCE] Replace deprecated `iteritems` with `items`
  great_expectations/core/util.py
  great_expectations/data_asset/util.py
Labels: core-team

#6211 [MAINTENANCE] Add instructions for setting up the test_ci database
  assets/docker/mssql/README.md
Labels: core-team

#6208 [BUGFIX] Fix logic in ExpectationDiagnostics._check_renderer_methods method
  great_expectations/core/expectation_diagnostics/expectation_diagnostics.py
  tests/expectations/test_generate_diagnostic_checklist.py
Labels: devrel

#6186 [MAINTENANCE] Add E2E tests for Cloud-backed `Datasource` CRUD
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/datasource_store.py
  scripts/check_docstring_coverage.py
  tests/data_context/abstract_data_context/test_datasource_delete.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/store/test_datasource_store.py
Labels: core-team

#6097 [FEATURE]/ Added pairwise expectation 'expect_column_pair_values_to_be_in_set'
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/self_check/util.py
  tests/test_definitions/column_pair_map_expectations/expect_column_pair_values_to_be_in_set.json
  tests/test_definitions/test_expectations_v2_api.py
Labels: community

#6210 [MAINTENANCE] Execution Engine linting & partial typing
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/split_and_sample/data_sampler.py
  great_expectations/execution_engine/split_and_sample/pandas_data_splitter.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_splitter.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/execution_engine/sqlalchemy_dialect.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/execution_engine/util.py
  pyproject.toml
  setup.cfg
Labels: core-team

#6216 [BUGFIX] Patch issue with empty config variables file raising `TypeError`
  great_expectations/data_context/data_context/abstract_data_context.py
Labels: core-team

#6207 [MAINTENANCE] Test definition for `ExpectColumnValuesToBeJsonParsable`, including a fix for Spark
  great_expectations/expectations/metrics/column_map_metrics/column_values_json_parseable.py
  tests/render/test_render_BulletListContentBlock.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_json_parseable.json
Labels: core-team

#6201 [MAINTENANCE] Port over usage statistics enabled methods from `BaseDataContext` to `AbstractDataContext`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/data_context.py
  tests/data_context/abstract_data_context/test_abstract_data_context_datasource_crud.py
Labels: core-team

#6217 [MAINTENANCE] Remove temporary dependency on `py`
  requirements-dev-contrib.txt
Labels: core-team

#6212 [DOCS] doc-297: update the create Expectations overview page for Data Assistants
  docs/guides/expectations/create_expectations_overview.md
  docs/images/universal_map/overviews/where_expectations_come_from.png
Labels: devrel

#6224 [MAINTENANCE] Adding type hints to DataAssistant implementations
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
Labels: core-team

#6227 [MAINTENANCE] Remove AWS config file dependencies and use existing env vars in CI/CD
  azure-pipelines-docs-integration.yml
  azure-pipelines-expectation-gallery.yml
  azure-pipelines.yml
Labels: core-team

#6225 [MAINTENANCE] Make `UsageStatsEvents` a `StrEnum`
  contrib/experimental/great_expectations_experimental/tests/rule_based_profiler/data_assistant/test_growth_numeric_data_assistant.py
  great_expectations/checkpoint/checkpoint.py
  great_expectations/cli/datasource.py
  great_expectations/cli/init.py
  great_expectations/cli/project.py
  great_expectations/cli/toolkit.py
  great_expectations/core/expectation_suite.py
  great_expectations/core/usage_statistics/events.py
  great_expectations/core/usage_statistics/schemas.py
  great_expectations/core/usage_statistics/usage_statistics.py
  great_expectations/data_asset/data_asset.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/migrator/cloud_migrator.py
  great_expectations/datasource/sqlalchemy_datasource.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/profile/user_configurable_profiler.py
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/rule_based_profiler/rule_based_profiler_result.py
  tests/core/test_expectation_suite.py
  tests/core/usage_statistics/test_usage_stats_schema.py
  tests/data_context/migrator/test_cloud_migrator.py
  tests/integration/profiling/rule_based_profiler/test_rule_based_profiler.py
  tests/integration/usage_statistics/example_events/cloud_migrate_example_events.py
  tests/integration/usage_statistics/test_usage_statistics_messages.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#6223 [MAINTENANCE] Move all `requirements-dev*.txt` files to separate dir
  azure-pipelines-dev.yml
  azure-pipelines-expectation-gallery.yml
  azure-pipelines-gcp-integration.yml
  azure-pipelines-os-integration.yml
  azure-pipelines.yml
  azure/dev-install-matrix.yml
  constraints-dev.txt
  docker/Dockerfile.tests
  docs/contributing/contributing_setup.md
  great_expectations/core/usage_statistics/package_dependencies.py
  reqs/requirements-dev-all-contrib-expectations.txt
  reqs/requirements-dev-arrow.txt
  reqs/requirements-dev-athena.txt
  reqs/requirements-dev-azure.txt
  reqs/requirements-dev-bigquery.txt
  reqs/requirements-dev-contrib.txt
  reqs/requirements-dev-dremio.txt
  reqs/requirements-dev-excel.txt
  reqs/requirements-dev-hive.txt
  reqs/requirements-dev-lite.txt
  reqs/requirements-dev-mssql.txt
  reqs/requirements-dev-mysql.txt
  reqs/requirements-dev-pagerduty.txt
  reqs/requirements-dev-postgresql.txt
  reqs/requirements-dev-redshift.txt
  reqs/requirements-dev-snowflake.txt
  reqs/requirements-dev-spark.txt
  reqs/requirements-dev-sqlalchemy.txt
  reqs/requirements-dev-teradata.txt
  reqs/requirements-dev-test.txt
  reqs/requirements-dev-tools.txt
  reqs/requirements-dev-trino.txt
  reqs/requirements-dev-vertica.txt
  requirements-dev-vertica.txt
  requirements-dev.txt
  setup.py
  tests/test_packaging.py
Labels: core-team

#6233 [BUGFIX] Release patch for Azure env vars
  azure-pipelines-docs-integration.yml
  azure-pipelines-expectation-gallery.yml
  azure-pipelines.yml
Labels: core-team

#6141 [DOCS] DOC-378: bring example scripts for pandas configuration guide under test
  docs/guides/connecting_to_your_data/datasource_configuration/components/_part_base_directory_for_filesystem.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/components/_part_batch_spec_passthrough.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/components/_part_glob_directive_details.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/components/_section_add_your_new_datasource_to_your_data_context.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/components/_section_create_a_new_datasource_configuration.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/components/_section_name_your_datasource.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/components/_section_specify_the_datasource_class_and_module.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/components/_section_test_your_configuration_with_test_yaml_config.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/filesystem_components/_config_for_assets_configured_multi.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/filesystem_components/_config_for_assets_configured_single.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/filesystem_components/_config_for_assets_inferred_multi.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/filesystem_components/_config_for_assets_inferred_single.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/filesystem_components/_config_for_assets_runtime.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/filesystem_components/_section_import_necessary_modules_and_initialize_your_data_context.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/how_to_configure_a_pandas_datasource.md
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_part_assets_configured.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_part_assets_inferred.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_part_assets_runtime.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_part_glob_directive_details.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_section_add_a_dictionary_as_the_value_of_the_data_connectors_key.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_section_add_the_execution_engine_to_your_datasource_configuration.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_section_configure_batch_spec_passthrough.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_section_configure_your_data_assets.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_section_data_connector_example_configurations.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_section_prerequisites.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_tab_data_connector_example_configurations_configured.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_tab_data_connector_example_configurations_inferred.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/_tab_data_connector_example_configurations_runtime.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/pandas_components/runtime_asset_data_connector.md
  tests/integration/docusaurus/connecting_to_your_data/datasource_configuration/how_to_configure_a_pandas_datasource.py
  tests/integration/test_script_runner.py
  yarn.lock
Labels: devrel

#6234 [BUGFIX] Cloud Data Context should overwrite existing suites based on `ge_cloud_id` instead of name
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/types/resource_identifiers.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
Labels: core-team

#6239 [BUGFIX] Add env vars to Pytest min versions Azure stage
  azure-pipelines.yml
Labels: core-team

#6241 M/none/dc types
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/usage_statistics/usage_statistics.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
Labels: core-team

#6244 [RELEASE] 0.15.29
  .github/teams.yml
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team

#5885 [DOCS] Updates package contribution references
  docs/contributing/contributing_package.md
  docs/guides/expectations/contributing/how_to_contribute_a_custom_expectation_to_great_expectations.md
Labels: devrel

#6220 [MAINTENANCE] Refactor instances of `noqa: F821` Flake8 directive
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/usage_statistics/usage_statistics.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_splitter.py
  great_expectations/expectations/registry.py
  great_expectations/rule_based_profiler/config/base.py
  great_expectations/rule_based_profiler/domain.py
  great_expectations/rule_based_profiler/expectation_configuration_builder/expectation_configuration_builder.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_counts_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/self_check/util.py
Labels: core-team

#6246 [MAINTENANCE] Logo URI ref in `data_docs`
  great_expectations/render/view/templates/top_navbar.j2
Labels: devrel

#6247 [MAINTENANCE] fix typos in docstrings
  great_expectations/render/view/templates/top_navbar.j2
  tests/expectations/metrics/test_core.py
  tests/validator/test_metrics_calculator.py
Labels: core-team

#6231 [MAINTENANCE] Isolate Trino/MSSQL/MySQL tests in `dev` CI
  azure-pipelines-dev.yml
  azure-pipelines.yml
Labels: core-team

#6245 [MAINTENANCE] Split up `compatability` and `comprehensive` stages in `dev` CI to improve performance
  azure-pipelines-dev.yml
Labels: core-team

#6194 [MAINTENANCE] ZEP POC - Asset Type Registration
  great_expectations/zep/context.py
  great_expectations/zep/demos.py
  great_expectations/zep/interfaces.py
  great_expectations/zep/metadatasource.py
  great_expectations/zep/type_lookup.py
  great_expectations/zep/util.py
  tests/zep/__init__.py
  tests/zep/test_metadatasource.py
  tests/zep/test_type_lookup.py
Labels: core-team

#6243 [BUGFIX] Iterate through `GeCloudIdentifiers` to find the suite ID from the name
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
Labels: core-team

#6176 [BUGFIX] Update default base url for cloud API
  great_expectations/data_context/cloud_constants.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  tests/data_context/store/test_ge_cloud_store_backend.py
  tests/data_context/test_data_context_ge_cloud_mode.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#6257 [BUGFIX] Pin `termcolor` to below `2.1.0` due to breaking changes in lib's TTY parsing logic
  requirements.txt
Labels: core-team

#6255 [FEATURE] Add zep datasources to data context.
  great_expectations/zep/context.py
  great_expectations/zep/metadatasource.py
Labels: core-team
