Repository great-expectations/great_expectations, pull requests merged in 2022-05, with the labels that each got.

#4986 [FEATURE] Enable self-initializing `ExpectColumnMeanToBeBetween`
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
Labels: core-team

#4987 [FEATURE] Enable self-initializing `ExpectColumnMedianToBeBetween`
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
Labels: core-team

#5001 [MAINTENANCE] Update `autoupdate` GitHub action
  .github/workflows/autoupdate.yml
Labels: core-team

#4988 [FEATURE] Enable self-initializing `ExpectColumnSumToBeBetween`
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
Labels: core-team

#4991 [MAINTENANCE] Move `DataAssistant` registry capabilities into `DataAssistantRegistry` to enable user aliasing
  great_expectations/expectations/registry.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_dispatcher.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
Labels: core-team

#4999 [BUGFIX] RBP Profiling Dataset ProgressBar Fix
  great_expectations/rule_based_profiler/rule_based_profiler.py
Labels: core-team

#5003 [FEATURE] New MetricSingleBatchParameterBuilder for specifically single-Batch Rule-Based Profiler scenarios
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/rule_based_profiler/parameter_builder/__init__.py
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  tests/conftest.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/integration/profiling/rule_based_profilers/test_rule_based_profiler.py
  tests/rule_based_profiler/parameter_builder/test_simple_date_format_string_parameter_builder.py
  tests/test_fixtures/rule_based_profiler/alice_user_workflow_verbose_profiler_config.yml
Labels: core-team

#4978 [DOCS] Update slack notification guide to not use validation operators.
  docs/guides/validation/validation_actions/how_to_trigger_slack_notifications_as_a_validation_action.md
Labels: devrel

#5005 [MAINTENANCE] Clean up unused imports and enforce through `flake8` in CI/CD
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
  great_expectations/cli/batch_request.py
  great_expectations/cli/v012/datasource.py
  great_expectations/data_context/data_context/explorer_data_context.py
  great_expectations/data_context/store/query_store.py
  great_expectations/dataset/sparkdf_dataset.py
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/dataset/util.py
  great_expectations/datasource/batch_kwargs_generator/databricks_batch_kwargs_generator.py
  great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/execution_engine/util.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_be_json_parseable.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/core/expect_column_values_to_be_unique.py
  great_expectations/expectations/core/expect_column_values_to_match_json_schema.py
  great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex.py
  great_expectations/expectations/metrics/column_aggregate_metric.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_bootstrapped_ks_test_p_value.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_parameterized_distribution_ks_test_p_value.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_standard_deviation.py
  great_expectations/expectations/metrics/map_metric.py
  great_expectations/expectations/metrics/table_metric.py
  great_expectations/expectations/metrics/util.py
  great_expectations/expectations/regex_based_column_map_expectation.py
  great_expectations/expectations/set_based_column_map_expectation.py
  great_expectations/render/renderer/content_block/profiling_column_properties_table_content_block.py
  great_expectations/render/renderer/content_block/validation_results_table_content_block.py
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/table_domain_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  great_expectations/self_check/util.py
  scripts/check_type_hint_coverage.py
Labels: core-team

#5006 [MAINTENANCE] Clean up type hints in CLI
  great_expectations/cli/checkpoint.py
  great_expectations/cli/cli.py
  great_expectations/cli/cli_logging.py
  great_expectations/cli/datasource.py
  great_expectations/cli/docs.py
  great_expectations/cli/init.py
  great_expectations/cli/pretty_printing.py
  great_expectations/cli/project.py
  great_expectations/cli/store.py
  great_expectations/cli/suite.py
  great_expectations/cli/upgrade_helpers/upgrade_helper_v11.py
  great_expectations/cli/upgrade_helpers/upgrade_helper_v13.py
  scripts/check_type_hint_coverage.py
Labels: core-team

#5008 [FEATURE] Enable Pandas DataFrame and Series as MetricValues Output of Metric ParameterBuilder Classes
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
Labels: core-team

#5009 [MAINTENANCE] Making ParameterBuilder metric computations robust to failures through logging and exception handling
  great_expectations/rule_based_profiler/parameter_builder/metric_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  great_expectations/validator/validator.py
  tests/rule_based_profiler/parameter_builder/test_regex_pattern_string_parameter_builder.py
Labels: core-team

#5010 [FEATURE] Notebook for `VolumeDataAssistant` Example
  tests/integration/profiling/rule_based_profilers/test_run_profiler_notebook.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running.ipynb
Labels: core-team

#5011 [FEATURE] Histogram/Partition Single-Batch ParameterBuilder
  great_expectations/rule_based_profiler/parameter_builder/__init__.py
  great_expectations/rule_based_profiler/parameter_builder/partition_parameter_builder.py
  great_expectations/validator/validator.py
  tests/rule_based_profiler/parameter_builder/test_partition_parameter_builder.py
Labels: core-team

#4962 [FEATURE] Update `DataAssistantResult.plot()` return value to emit `PlotResult` wrapper dataclass
  great_expectations/rule_based_profiler/types/altair/themes.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/plot_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/volume_data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/test_utils.py
Labels: core-team

#5019 [MAINTENANCE] Update version of `black` in pre-commit config
  .pre-commit-config.yaml
Labels: core-team

#5020 [BUGFIX] Fix DataAssistantResult serialization issue
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5023 [MAINTENANCE] Enhance configuring serialization for DotDict type classes
  great_expectations/rule_based_profiler/parameter_builder/partition_parameter_builder.py
  great_expectations/rule_based_profiler/types/domain.py
  great_expectations/types/__init__.py
  tests/rule_based_profiler/parameter_builder/test_partition_parameter_builder.py
Labels: core-team

#5021 [FEATURE] trino support
  assets/docker/starburst/docker-compose.yml
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines-docs-integration.yml
  azure-pipelines-os-integration.yml
  azure-pipelines.yml
  great_expectations/core/expectation_diagnostics/expectation_test_data_cases.py
  great_expectations/expectations/metrics/util.py
  great_expectations/self_check/util.py
  requirements-dev-sqlalchemy.txt
  requirements-dev-trino.txt
  setup.py
  tests/conftest.py
  tests/expectations/test_run_diagnostics.py
  tests/expectations/test_run_diagnostics_supporting_methods.py
  tests/expectations/test_util.py
  tests/test_definitions/column_aggregate_expectations/expect_column_mean_to_be_between.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_in_set.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_in_type_list.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_of_type.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_unique.json
  tests/test_definitions/column_pair_map_expectations/expect_column_pair_values_to_be_equal.json
  tests/test_definitions/column_pair_map_expectations/expect_column_pair_values_to_be_in_set.json
  tests/test_definitions/test_expectations.py
  tests/test_definitions/test_expectations_cfe.py
  tests/test_packaging.py
Labels: devrel

#5028 [MAINTENANCE] Pyarrow upper bound
  requirements-dev-arrow.txt
  requirements-dev-dremio.txt
Labels: core-team

#5029 release candidate 2022-05-05
  docs/changelog.md
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team

#5048 [BUGFIX] Patch broken usage stats test around dependency tracking
  azure-pipelines-dependency-graph-testing.yml
  great_expectations/core/usage_statistics/package_dependencies.py
Labels: core-team

#5049 [FEATURE] Add subset operation to Domain class
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/domain_builder/column_pair_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/multi_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/table_domain_builder.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/types/domain.py
  great_expectations/util.py
  tests/conftest.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/rule_based_profiler/conftest.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/domain_builder/test_categorical_column_domain_builder.py
  tests/rule_based_profiler/domain_builder/test_domain.py
  tests/rule_based_profiler/domain_builder/test_map_metric_column_domain_builder.py
  tests/rule_based_profiler/expectation_configuration_builder/test_default_expectation_configuration_builder.py
  tests/rule_based_profiler/parameter_builder/test_mean_unexpected_map_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_parameter_container.py
  tests/rule_based_profiler/parameter_builder/test_partition_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_regex_pattern_string_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_simple_date_format_string_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_value_set_multi_batch_parameter_builder.py
  tests/rule_based_profiler/test_rule_output.py
Labels: core-team

#5057 [FEATURE] In DataAssistant: Use Domain instead of domain_type as key for Metrics Parameter Builders
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
Labels: core-team

#5060 [MAINTENANCE] Sync `main` and `develop` branches
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/domain_builder/column_pair_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/multi_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/table_domain_builder.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/types/domain.py
  great_expectations/util.py
  tests/conftest.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/rule_based_profiler/conftest.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/domain_builder/test_categorical_column_domain_builder.py
  tests/rule_based_profiler/domain_builder/test_domain.py
  tests/rule_based_profiler/domain_builder/test_map_metric_column_domain_builder.py
  tests/rule_based_profiler/expectation_configuration_builder/test_default_expectation_configuration_builder.py
  tests/rule_based_profiler/parameter_builder/test_mean_unexpected_map_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_parameter_container.py
  tests/rule_based_profiler/parameter_builder/test_partition_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_regex_pattern_string_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_simple_date_format_string_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_value_set_multi_batch_parameter_builder.py
  tests/rule_based_profiler/test_rule_output.py
Labels: core-team

#5053 [MAINTENANCE] Saved output of usage stats schema script in repo
  great_expectations/core/usage_statistics/schemas.py
  great_expectations/core/usage_statistics/usage_statistics_record_schema.json
  tests/core/usage_statistics/test_usage_stats_schema.py
Labels: core-team

#5044 [MAINTENANCE] Apply Altair custom themes to return objects
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/volume_data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5065 [FEATURE] Self-initializing `ExpectColumnStddevToBeBetween`
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
Labels: core-team

#5061 [MAINTENANCE] Introducing RuleBasedProfilerResult -- neither expectation suite name nor expectation suite must be passed to RuleBasedProfiler.run()
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/rule_based_profiler/__init__.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/rule_based_profiler/rule_based_profiler_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/volume_data_assistant_result.py
  great_expectations/validator/validator.py
  scripts/check_type_hint_coverage.py
  tests/data_context/test_data_context_profilers.py
  tests/integration/profiling/rule_based_profilers/test_profiler_basic_workflows.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/integration/profiling/rule_based_profilers/test_rule_based_profiler.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/test_rule_based_profiler.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/BasicExample_RBP_Instantiation_and_running.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running.ipynb
Labels: core-team

#5026 [BUGFIX] Splitting Support at Asset level
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/types/base.py
  tests/datasource/test_new_datasource_with_sql_data_connector.py
  tests/integration/db/test_sql_data_splitting.py
  tests/integration/fixtures/split_and_sample_data/splitter_test_cases_and_fixtures.py
Labels: core-team

#5022 [MAINTENANCE] Refactor `DataAssistant` plotting to leverage utility dataclasses
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/plot_components.py
  great_expectations/rule_based_profiler/types/data_assistant_result/volume_data_assistant_result.py
Labels: core-team

#5071 [MAINTENANCE] Check that a passed string is parseable as an integer
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_sampler.py
Labels: core-team

#4994 [BUGFIX] databricks engine create temporary view
  great_expectations/dataset/sqlalchemy_dataset.py
Labels: community, devrel

#5074 [MAINTENANCE] Clean up mssql limit sampling code path and comments
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_sampler.py
Labels: core-team

#5073 [FEATURE] Enum used by DateSplitter able to be represented as YAML
  great_expectations/execution_engine/split_and_sample/data_splitter.py
  tests/integration/fixtures/split_and_sample_data/splitter_test_cases_and_fixtures.py
Labels: core-team

#5075 [MAINTENANCE] Make saving bootstraps histogram for NumericMetricRangeMultiBatchParameterBuilder optional (absent by default)
  great_expectations/core/expectation_validation_result.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/expectations/expectation.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  tests/conftest.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/test_rule_based_profiler.py
  tests/test_fixtures/rule_based_profiler/bobster_user_workflow_verbose_profiler_config.yml
  tests/test_fixtures/rule_based_profiler/quentin_user_workflow_verbose_profiler_config.yml
Labels: core-team

#5076 [MAINTENANCE] Make self-initializing expectations return estimated kwargs with auto-generation timestamp and Great Expectation version
  great_expectations/core/expectation_validation_result.py
Labels: core-team

#5037 [DOCS] Update process and config examples in Opsgenie guide
  docs/guides/validation/validation_actions/how_to_trigger_opsgenie_notifications_as_a_validation_action.md
Labels: devrel

#5041 [DOCS] Correct name of `openlineage-integration-common` package
  docs/guides/validation/validation_actions/how_to_collect_openlineage_metadata_using_a_validation_action.md
Labels: community, devrel

#5077 [FEATURE] Implementation of auto-complete for DataAssistant class names in Jupyter notebooks
  great_expectations/rule_based_profiler/data_assistant/data_assistant_dispatcher.py
Labels: core-team

#5086 [FEATURE] Provide display ("friendly") names for batch identifiers
  great_expectations/core/expectation_validation_result.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5087 [MAINTENANCE] Adding a unit test for batch_id mapping to batch display names
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5093 [MAINTENANCE] `pypandoc` version constraint added (`< 1.8`)
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
  constraints-dev.txt
  setup.py
Labels: core-team

#5092 [BUGFIX] Sampling support at asset level
  great_expectations/data_context/types/base.py
  tests/datasource/test_new_datasource_with_sql_data_connector.py
Labels: core-team

#5089 [MAINTENANCE] Utilize Rule objects in Profiler construction in DataAssistant
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5101 [FEATURE] Onboarding DataAssistant -- Initial Rule Implementations (Data Aspects)
  great_expectations/rule_based_profiler/data_assistant/__init__.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/rule_based_profiler/types/data_assistant_result/__init__.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/onboarding_data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5080 [MAINTENANCE] Turn off metric calculation progress bars in `RuleBasedProfiler` and `DataAssistant` workflows
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/util.py
  great_expectations/validator/validator.py
Labels: core-team

#5103 [MAINTENANCE] Convenience method refactor for Onboarding DataAssistant
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
Labels: core-team

#5104 [FEATURE] OnboardingDataAssistant: Implement Nullity/Non-nullity Rules and Associated Metrics
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
Labels: core-team

#5108 [MAINTENANCE] DataAssistant: Refactoring Access to common ParameterBuilder instances
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
Labels: core-team

#5100 [MAINTENANCE] Refactor of`MetricTypes` and `AttributedResolvedMetrics`
  great_expectations/rule_based_profiler/parameter_builder/__init__.py
  great_expectations/rule_based_profiler/parameter_builder/mean_unexpected_map_metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/types/__init__.py
  great_expectations/rule_based_profiler/types/attributed_resolved_metrics.py
  great_expectations/rule_based_profiler/types/data_assistant_result/volume_data_assistant_result.py
  great_expectations/rule_based_profiler/types/metric_computation_result.py
Labels: core-team

#5111 [MAINTENANCE] Remove references to show_cta_footer except in schemas.py
  great_expectations/core/usage_statistics/anonymizers/data_docs_anonymizer.py
  tests/core/usage_statistics/test_schema_validation.py
  tests/data_context/test_configuration_storage.py
  tests/integration/usage_statistics/test_integration_usage_statistics.py
  tests/integration/usage_statistics/test_usage_statistics_messages.py
Labels: core-team

#5024 [FEATURE] Splitters and limit sample work on AWS Athena
  azure-pipelines-docs-integration.yml
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_splitter.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
  tests/integration/db/test_sql_data_sampling.py
  tests/integration/db/test_sql_data_splitting.py
  tests/integration/fixtures/split_and_sample_data/awsathena_connection_string.yml
  tests/integration/test_script_runner.py
  tests/test_the_utils_in_test_utils.py
  tests/test_utils.py
Labels: core-team

#5109 [MAINTENANCE] Adding unit tests for sqlalchemy limit sampler part 1
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_sampler.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/execution_engine/sqlalchemy_dialect.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
Labels: core-team

#5112 [BUGFIX] Insure that Batch IDs are accessible in the order in which they were loaded in Validator
  great_expectations/core/batch.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/types/attributed_resolved_metrics.py
  great_expectations/validator/validator.py
  tests/conftest.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5091 [FEATURE] Use `batch_identifiers` in plot tooltips
  great_expectations/rule_based_profiler/types/altair/themes.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/plot_components.py
  great_expectations/rule_based_profiler/types/data_assistant_result/volume_data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5115 [MAINTENANCE] Don't re-raise connection errors in CI
  great_expectations/exceptions/exceptions.py
  tests/test_utils.py
Labels: core-team

#5117 [FEATURE] Updated `DataAssistantResult` plotting API
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/plot_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/volume_data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5118 [BUGFIX] Update `DataAssistant` notebook for new plotting API
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running.ipynb
Labels: core-team

#5120 [FEATURE] Onboarding DataAssistant: Numeric Rules and Relevant Metrics
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/types/data_assistant_result/onboarding_data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5119 [MAINTENANCE] Sqlite specific tests for splitting and sampling
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
Labels: core-team

#5127 [BUGFIX] CategoricalColumnDomainBuilder needs to accept limit_mode with dictionary type
  great_expectations/rule_based_profiler/domain_builder/categorical_column_domain_builder.py
  great_expectations/rule_based_profiler/helpers/cardinality_checker.py
  tests/rule_based_profiler/domain_builder/test_categorical_column_domain_builder.py
Labels: core-team

#5134 [FEATURE] Categorical Rule is added to OnboardingDataAssistant
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
Labels: core-team

#5136 [FEATURE] Giving the "expect_table_columns_to_match_set" Expectation Self-Initializing Capabilities.
  great_expectations/expectations/core/expect_table_columns_to_match_set.py
  great_expectations/rule_based_profiler/parameter_builder/mean_table_columns_set_match_multi_batch_parameter_builder.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/rule_based_profiler/parameter_builder/test_mean_table_columns_set_match_multi_batch_parameter_builder.py
Labels: core-team

#4985 [FEATURE] Enable self-initializing `ExpectColumnValueLengthsToBeBetween`
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
Labels: core-team

#5140 [MAINTENANCE] Move upper bound on sqlalchemy to <2.0.0.
  requirements-dev-lite.txt
Labels: core-team

#5126 [FEATURE] `DataAssistant` plotting for non-sequential batches
  great_expectations/rule_based_profiler/types/altair/themes.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/plot_components.py
  great_expectations/rule_based_profiler/types/data_assistant_result/volume_data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5128 [MAINTENANCE] Update primary pipeline to cut releases with tags
  azure-pipelines.yml
Labels: core-team

#5142 [BUGFIX] Use RANDOM_STATE in fixture to make tests deterministic
  tests/conftest.py
Labels: core-team

#5147 [BUGFIX] Read deployment_version instead of using versioneer in deprecation tests
  tests/test_deprecation.py
Labels: core-team

#5146 [MAINTENANCE] Improve handling of "expect_column_unique_values_count_to_be_between" in VolumeDataAssistant
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/domain_builder/categorical_column_domain_builder.py
  great_expectations/rule_based_profiler/helpers/cardinality_checker.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/domain_builder/test_categorical_column_domain_builder.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/BasicExample_RBP_Instantiation_and_running.ipynb
Labels: core-team

#5148 [MAINTENANCE] Simplify DataAssistant Operation to not Depend on Self-Initializing Expectations
  great_expectations/expectations/core/expect_table_columns_to_match_set.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5152 [MAINTENANCE] Improvements to Trino support
  .gitignore
  assets/docker/trino/docker-compose.yml
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/util.py
  scripts/check_type_hint_coverage.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_like_pattern.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_like_pattern_list.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_match_like_pattern.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_match_like_pattern_list.json
Labels: devrel

#5163 [RELEASE] 0.15.6
  docs/changelog.md
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team

#5159 [FEATURE] Helper method to determine whether Expectation is self-initializing
  great_expectations/exceptions/exceptions.py
  great_expectations/expectations/expectation.py
  tests/expectations/test_expectation_self_initializing.py
Labels: core-team

#5145 [FEATURE] OnboardingDataAssistantResult plotting feature parity with VolumeDataAssistantResult
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/onboarding_data_assistant_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/volume_data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
Labels: core-team

#5166 [BUGFIX] Insure TABLE Domain Metrics Do Not Get Column Key From Column Type Rule Domain Builder
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5169 [FEATURE] Example Notebook for self-initializing `Expectations`
  tests/integration/profiling/rule_based_profilers/test_run_profiler_notebook.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/SelfInitializingExpectations.ipynb
Labels: core-team

#5155 [DOCS] Update ToC with category links
  docs/deployment_patterns/reference_architecture_overview.md
  docs/reference/reference_overview.md
  sidebars.js
Labels: devrel

#5171 [MAINTENANCE] Helper method for RBP Notebook tests that does clean-up
  tests/integration/profiling/rule_based_profilers/test_run_profiler_notebook.py
Labels: core-team

#5175 [MAINTENANCE] Increase timeout for longer stages in Azure pipelines
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
Labels: core-team

#5173 [MAINTENANCE] Rule-Based Profiler -- In ParameterBuilder insure that metrics are validated for conversion to numpy array (to avoid deprecation warnings)
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/mean_table_columns_set_match_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/partition_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/types/attributed_resolved_metrics.py
  great_expectations/rule_based_profiler/types/metric_computation_result.py
Labels: core-team

#5178 [MAINTENANCE] Increase timeout in packaging & installation pipeline
  azure-pipelines-packaging.yml
Labels: core-team

#5170 [MAINTENANCE] OnboardingDataAssistant handle multiple expectations per domain
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
Labels: core-team

#5172 [MAINTENANCE] Error message when `Validator` is instantiated with Incorrect `BatchRequest`
  great_expectations/data_context/data_context/base_data_context.py
  tests/data_context/datasource/test_data_context_datasource_non_sql_methods.py
  tests/data_context/datasource/test_data_context_datasource_sql_methods.py
  tests/validator/test_validator.py
Labels: core-team

#5190 [MAINTENANCE] Don't include infinity in rendered string for diagnostics
  great_expectations/expectations/expectation.py
Labels: devrel

#5186 [MAINTENANCE] Mark Great Expectations Cloud tests and add stage to CI/CD
  azure-pipelines-dependency-graph-testing.yml
  tests/actions/test_core_actions.py
  tests/cli/test_toolkit.py
  tests/core/test_expectation_suite_crud_methods.py
  tests/data_context/store/test_evaluation_parameter_store.py
  tests/data_context/test_data_context_ge_cloud_mode.py
  tests/data_context/test_data_context_utils.py
  tests/rule_based_profiler/test_rule_based_profiler.py
  tests/validator/test_validator.py
Labels: core-team

#5187 [FEATURE] DataAssistant: Enable passing directives to run() method using runtime_environment argument
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py
  great_expectations/rule_based_profiler/helpers/runtime_environment.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/test_fixtures/rule_based_profiler/bobby_user_workflow_verbose_profiler_config.yml
Labels: core-team

#5191 [FEATURE] Adding DataAssistantResult.get_expectation_suite(expectation_suite_name) method
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5181 [FEATURE] Cronjob to automatically create release PR
  .github/release_schedule.json
  .github/workflows/release-prep.yml
  azure-pipelines-dependency-graph-testing.yml
  tests/test_release.py
Labels: core-team

#5192 [MAINTENANCE] Trigger expectation gallery build with scheduled CI/CD runs
  azure-pipelines.yml
Labels: core-team

#5193 [BUGFIX] Update name for stdev expectation in `OnboardingDataAssistant` backend
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
Labels: core-team

#5194 [MAINTENANCE] `expectation_gallery` Azure pipeline
  azure-pipelines-expectation-gallery.yml
  azure-pipelines.yml
Labels: core-team

#5150 [DOCS] update on availability and parameters of conditional expectations
  docs/reference/expectations/conditional_expectations.md
Labels: devrel

#5199 [BUGFIX] Insure that Histogram Metric in Pandas operates on numerical columns that do not have NULL values
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py
  great_expectations/expectations/metrics/map_metric_provider.py
Labels: core-team

#5202 [BUGFIX] RuleBasedProfiler: Ensure that run() method runtime environment directives are handled correctly when existing setting is None (by default)
  great_expectations/core/config_peer.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
Labels: core-team

#5198 [MAINTENANCE] General cleanup/refactor of `DataAssistantResult`
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
Labels: core-team

#5207 [BUGFIX] In aggregate metrics, Spark Implementation already gets Column type as argument -- no need for F.col() as the operand is not a string.
  great_expectations/expectations/metrics/column_aggregate_metrics/column_values_length_max.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_values_length_min.py
Labels: core-team

#5210 [RELEASE] 0.15.7
  docs/changelog.md
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team

#5212 [FEATURE] `OnboardingDataAssistant` plots for `expect_table_row_count_to_be_between` non-sequential batches
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
Labels: core-team

#5213 [MAINTENANCE] suppressing type hints in ill-defined situations
  great_expectations/data_context/types/base.py
  scripts/check_type_hint_coverage.py
Labels: core-team

#5201 [FEATURE] Limit sampling for spark and pandas
  great_expectations/exceptions/exceptions.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/split_and_sample/data_sampler.py
  great_expectations/execution_engine/split_and_sample/pandas_data_sampler.py
  great_expectations/execution_engine/split_and_sample/sparkdf_data_sampler.py
  tests/execution_engine/conftest.py
  tests/execution_engine/split_and_sample/test_pandas_execution_engine_sampling.py
  tests/execution_engine/split_and_sample/test_pandas_execution_engine_splitting.py
  tests/execution_engine/split_and_sample/test_sparkdf_execution_engine_sampling.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
Labels: core-team

#5203 [FEATURE] Groundwork for DataContext Refactor
  great_expectations/core/config_peer.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
Labels: core-team

#5215 [MAINTENANCE] Change CategoricalColumnDomainBuilder property name from "limit_mode" to "cardinality_limit_mode".
  great_expectations/data_context/types/base.py
  great_expectations/rule_based_profiler/config/base.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/domain_builder/categorical_column_domain_builder.py
  great_expectations/rule_based_profiler/helpers/cardinality_checker.py
  great_expectations/rule_based_profiler/helpers/runtime_environment.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/conftest.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/domain_builder/test_cardinality_checker.py
  tests/rule_based_profiler/domain_builder/test_categorical_column_domain_builder.py
  tests/test_fixtures/rule_based_profiler/alice_user_workflow_verbose_profiler_config.yml
  tests/test_fixtures/rule_based_profiler/bobby_user_workflow_verbose_profiler_config.yml
  tests/test_fixtures/rule_based_profiler/example_notebooks/BasicExample_RBP_Instantiation_and_running.ipynb
Labels: core-team

#5214 [DOCS] Remove leading underscore from sampling docs
  docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_a_file_system_or_blob_store.md
  docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_tables_in_sql.md
Labels: core-team

#5197 [MAINTENANCE] Update Note in BigQuery Docs
  docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/guides/connecting_to_your_data/database/bigquery.md
Labels: core-team

#5217 [MAINTENANCE] Sampling cleanup refactor (use BatchSpec in sampling methods)
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/split_and_sample/data_sampler.py
  great_expectations/execution_engine/split_and_sample/pandas_data_sampler.py
  great_expectations/execution_engine/split_and_sample/sparkdf_data_sampler.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_sampler.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
Labels: core-team

#5218 [FEATURE] Implement ability to change rule variable values through DataAssistant run() method arguments at runtime
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/helpers/runtime_environment.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5222 [MAINTENANCE] Globally increase Azure timeouts to 120 mins
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
  azure/dev-install-matrix.yml
Labels: core-team
