Repository great-expectations/great_expectations, pull requests merged in 2022-02, with the labels that each got.

#4044 [FEATURE][BUGFIX] Support nullable int column types
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/profile/base.py
  tests/expectations/core/test_expect_column_values_to_be_in_type_list.py
  tests/profile/test_jsonschema_profiler.py
Labels: bug, community, devrel

#4042 [BUGFIX] Fix s3 path suffix bug on windows
  great_expectations/datasource/data_connector/configured_asset_s3_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_s3_data_connector.py
  tests/datasource/data_connector/test_configured_asset_s3_data_connector.py
Labels: bug, community, devrel

#3972 [FEATURE] Add read_sas function
  great_expectations/__init__.py
  great_expectations/cli/v012/datasource.py
  great_expectations/datasource/pandas_datasource.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/util.py
  tests/datasource/test_pandas_datasource.py
  tests/execution_engine/test_pandas_execution_engine.py
  tests/test_great_expectations.py
  tests/test_sets/Titanic.sas7bdat
Labels: community, devrel, feature

#2619 [BUGFIX] custom notebook templates
  docs_rtd/changelog.rst
  docs_rtd/guides/how_to_guides/configuring_generated_notebooks/how_to_configure_suite_edit_generated_notebooks.rst
  great_expectations/data_context/types/base.py
  tests/conftest.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/test_fixtures/great_expectations_custom_notebooks_defaults.yml
Labels: community

#4163 [DOCS] Update changelog.rst to fix error in 0.10.8 release notes
  docs_rtd/changelog.rst
Labels: community, devrel

#4189 [DOCS] Fixes two references to the Getting Started tutorial
  docs/intro.md
  docusaurus.config.js
Labels: docs

#2520 [ENHANCEMENT] Allow users to pass in any set of polygon points in expectation for point to be within region
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_point_within_geo_region.py
Labels: community

#2624 [ENHANCEMENT] Better support Hive, better support BigQuery.
  great_expectations/cli/batch_request.py
  great_expectations/cli/v012/datasource.py
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/datasource/batch_kwargs_generator/table_batch_kwargs_generator.py
Labels: community, devrel

#4169 [DOCS] Deepnote Deployment Pattern Guide
  docs/deployment_patterns/how_to_use_great_expectations_in_deepnote.md
  docs/deployment_patterns/images/datadocs.png
  docs/deployment_patterns/images/dataframe.png
  sidebars.js
Labels: docs

#3102 [FEATURE] experimental column map expectation checking for vectors
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_vectors.py
Labels: community, devrel

#4224 [BUGFIX] Add support for SqlAlchemyQueryStore connection_string credentials
  great_expectations/data_context/store/query_store.py
  tests/conftest.py
  tests/data_context/store/test_query_store.py
Labels: community
