Repository great-expectations/great_expectations, pull requests merged in 2022-07, with the labels that each got.

#5423 [MAINTENANCE] Ensure that `BaseDataContext` does not persist `Datasource` changes by default
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/store/inline_store_backend.py
Labels: core-team

#5369 [FEATURE] Add atomic `rendered_content` to `ExpectationValidationResult` and `ExpectationConfiguration`
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/registry.py
  great_expectations/render/renderer/inline_renderer.py
  great_expectations/render/types/__init__.py
  great_expectations/validator/validator.py
  scripts/check_docstring_coverage.py
  tests/expectations/snapshots/snap_test_expectation_atomic_renderers.py
  tests/expectations/test_expectation_atomic_renderers.py
  tests/expectations/test_run_diagnostics.py
  tests/render/fixtures/ValidationResultsPageRenderer_render_with_run_info_at_end.json
  tests/render/fixtures/ValidationResultsPageRenderer_render_with_run_info_at_start.json
  tests/render/test_page_renderer.py
  tests/validator/test_validator.py
Labels: core-team

#5417 [FEATURE] Add `DataContext.update_datasource` CRUD method
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/store/datasource_store.py
  scripts/check_type_hint_coverage.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/test_data_context.py
Labels: core-team

#5385 [MAINTENANCE] Migration of `project_config_with_variables_substituted` to `AbstractDataContext`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
Labels: core-team

#5427 [MAINTENANCE] Improve type hinting in `GeCloudStoreBackend`
  great_expectations/data_context/store/ge_cloud_store_backend.py
  scripts/check_type_hint_coverage.py
Labels: core-team

#5430 [FEATURE] Refactor Splitter Testing Modules so as to Make them More General and Add Unit and Integration Tests for "split_on_whole_table" and "split_on_column_value" on SQLite and All Supported Major SQL Backends
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
  tests/integration/db/taxi_data_utils.py
  tests/integration/db/test_sql_data_split_on_column_value.py
  tests/integration/db/test_sql_data_split_on_datetime_and_day_part.py
  tests/integration/db/test_sql_data_split_on_whole_table.py
  tests/integration/fixtures/split_and_sample_data/splitter_test_cases_and_fixtures.py
  tests/integration/test_script_runner.py
Labels: core-team

#5326 [DOCS] DOC-322 update terminology to v3
  docs/reference/expectations/standard_arguments.md
Labels: devrel

#5438 [MAINTENANCE] Test serialization of text, table, and bulleted list `rendered_content` in `ExpectationValidationResult`
  tests/render/test_inline_renderer.py
Labels: core-team

#5440 [MAINTENANCE] Refactor `datasource_name` out of `DataContext.update_datasource`
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/data_context.py
  tests/data_context/test_data_context.py
Labels: core-team

#5442 [MAINTENANCE] Add checkpoint name to validation results
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/validation_operators/validation_operators.py
  great_expectations/validator/validator.py
  tests/checkpoint/test_checkpoint.py
Labels: core-team

#5445 [MAINTENANCE] Remove checkpoint from top level of schema since it is captured in `meta`
  great_expectations/core/expectation_validation_result.py
Labels: core-team

#5449 [MAINTENANCE] Add unit and integration tests for Splitting on Divided Integer
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/execution_engine/util.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
  tests/integration/db/test_sql_data_split_on_divided_integer.py
  tests/integration/fixtures/split_and_sample_data/splitter_test_cases_and_fixtures.py
  tests/integration/test_script_runner.py
Labels: core-team

#5456 [BUGFIX] Typo in core-team username causing manual cleanup step in release process
  .github/teams.yml
Labels: core-team

#5426 [DOCS] DOC-341 partition how to configure a new data context with the cli guide
  docs/guides/components/congrats.mdx
  docs/guides/setup/components_index/_data_contexts.mdx
  docs/guides/setup/components_index/_data_docs.mdx
  docs/guides/setup/components_index/_expectation_stores.mdx
  docs/guides/setup/components_index/_installation.mdx
  docs/guides/setup/components_index/_metric_stores.mdx
  docs/guides/setup/components_index/_miscellaneous.mdx
  docs/guides/setup/components_index/_validation_result_stores.mdx
  docs/guides/setup/configuring_data_contexts/components_how_to_configure_a_new_data_context_with_the_cli/_data_context_next_steps.mdx
  docs/guides/setup/configuring_data_contexts/components_how_to_configure_a_new_data_context_with_the_cli/_initialize_data_context_with_the_cli.mdx
  docs/guides/setup/configuring_data_contexts/components_how_to_configure_a_new_data_context_with_the_cli/_preface.mdx
  docs/guides/setup/configuring_data_contexts/components_how_to_configure_a_new_data_context_with_the_cli/_verify_data_context_initialization.mdx
  docs/guides/setup/configuring_data_contexts/how_to_configure_a_new_data_context_with_the_cli.md
  docs/guides/setup/index.md
Labels: devrel

#5451 [MAINTENANCE] Update automated release schedule
  .github/release_schedule.json
Labels: core-team

#5457 [MAINTENANCE] Update `teams.yml`
  .github/teams.yml
Labels: core-team

#5448 [DOCS] DOC-349 re-write and partition interactive mode expectations guide
  docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_congrats.mdx
  docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_continue_the_workflow_within_a_jupyter_notebook.mdx
  docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_optional_edit_an_existing_expectation_suite_in_interactive_mode.mdx
  docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_optional_profile_your_data_to_generate_expectations_then_edit_them_in_interactive_mode.mdx
  docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_preface.mdx
  docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_save_a_batch_request_to_reuse_when_editing_an_expectation_suite_in_interactive_mode.mdx
  docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_specify_a_datasource_if_multiple_are_available.mdx
  docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_specify_the_name_of_your_new_expectation_suite.mdx
  docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_use_the_builtin_help_to_review_the_clis_suite_new_optional_flags.mdx
  docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_use_the_cli_to_begin_the_interactive_process_of_creating_expectations.mdx
  docs/guides/expectations/how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data.md
  docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_a_edit_the_configuration.mdx
  docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_additional_resources.mdx
  docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_b_test_your_config_using_contexttest_yaml_config.mdx
  docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_c_store_your_checkpoint_config.mdx
  docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_d_optional_check_your_stored_checkpoint_config.mdx
  docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_e_optional_test_run_the_new_checkpoint_and_open_data_docs.mdx
  docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_preface.mdx
  docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_steps_for_checkpoints_.mdx
  docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_use_the_cli_to_open_a_jupyter_notebook_for_creating_a_new_checkpoint.mdx
  docs/guides/validation/checkpoints/how_to_create_a_new_checkpoint.md
  docs_pending/_tips/_create_an_empty_expectation_suite_with_the_cli_and_no_jupyter_flag.mdx
Labels: devrel

#5441 [MAINTENANCE] Remove `InlineRenderer` invocation feature flag from `ExpectationValidationResult`
  great_expectations/checkpoint/checkpoint.py
  great_expectations/checkpoint/util.py
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/expectations/expectation.py
  great_expectations/render/types/__init__.py
  great_expectations/validator/validator.py
  scripts/check_docstring_coverage.py
  scripts/check_type_hint_coverage.py
  tests/checkpoint/test_checkpoint.py
  tests/expectations/snapshots/snap_test_expectation_atomic_renderers.py
  tests/expectations/test_run_diagnostics.py
  tests/render/test_inline_renderer.py
  tests/validator/test_validator.py
Labels: core-team

#5463 [BUGFIX] Snowflake Docs Integration Test Fix
  tests/integration/db/awsathena.py
  tests/integration/docusaurus/connecting_to_your_data/database/snowflake_yaml_example.py
Labels: core-team

#5428 [DOCS] DOC-342 partition how to configure a validation result store in amazon s3 guide
  docs/guides/setup/components/_congrats.mdx
  docs/guides/setup/configuring_metadata_stores/components/_install_boto3_with_pip.mdx
  docs/guides/setup/configuring_metadata_stores/components/_verify_aws_credentials_are_configured_properly.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_confirm_that_the_new_validation_results_store_has_been_added_by_running_great_expectations_store_list.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_confirm_that_the_validations_results_store_has_been_correctly_configured.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_copy_existing_validation_results_to_the_s_bucket_this_step_is_optional.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_identify_your_data_context_validation_results_store.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_preface.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_update_your_configuration_file_to_include_a_new_store_for_validation_results_on_s.mdx
  docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_amazon_s3.md
Labels: devrel

#5446 [MAINTENANCE] Refactor `DataContextVariables` to leverage `@property` and `@setter`
  great_expectations/data_context/data_context_variables.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5468 [BUGFIX] DataProfiler Linting Fix
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/__init__.py
Labels: devrel

#5469 [DOCS] link fix in onboarding data assistant guide
  docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.md
Labels: devrel

#5223 [FEATURE] QueryExpectations
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_value_frequency_to_meet_threshold.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_table_row_count_to_be.py
  examples/expectations/query_expectation_template.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/__init__.py
  great_expectations/expectations/metrics/query_metric_provider.py
  great_expectations/expectations/metrics/query_metrics/__init__.py
  great_expectations/expectations/metrics/query_metrics/query_column.py
  great_expectations/expectations/metrics/query_metrics/query_table.py
  great_expectations/expectations/util.py
  tests/expectations/core/test_expect_queried_column_value_frequency_to_meet_threshold.py
  tests/expectations/core/test_expect_queried_table_row_count_to_be.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_queried_column_value_frequency_to_meet_threshold.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_queried_table_row_count_to_be.py
  tests/integration/docusaurus/expectations/examples/query_expectation_template.py
Labels: devrel

#5465 [MAINTENANCE] Make `DataAssistantResult` fixtures module scoped
  tests/conftest.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#4568 [DOCS] Integrate great-expectation with ydata-synthetic
  docs/deployment_patterns/how_to_use_great_expectations_with_ydata_synthetic.md
  docs/deployment_patterns/images/ydata-synthetic-1.png
  docs/deployment_patterns/images/ydata-synthetic-2.png
  docs/deployment_patterns/images/ydata-synthetic-3.png
  docs/deployment_patterns/index.md
  sidebars.js
Labels: community, devrel

#5470 [MAINTENANCE] Add unit tests for Splitting on Converted DateTime
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_splitter.py
  tests/conftest.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
  tests/integration/fixtures/split_and_sample_data/splitter_test_cases_and_fixtures.py
  tests/integration/test_script_runner.py
  tests/render/test_inline_renderer.py
  tests/test_utils.py
Labels: core-team

#5471 [MAINTENANCE] Rearrange integration tests to insure categorization into proper deployment-style based lists
  tests/integration/test_script_runner.py
Labels: core-team

#5473 [MAINTENANCE] Provide better error messaging if batch_request is not supplied to DataAssistant.run()
  great_expectations/exceptions/exceptions.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
Labels: core-team

#5474 [BUGFIX] Update renderer snapshots with `None` values removed
  tests/expectations/snapshots/snap_test_expectation_atomic_renderers.py
Labels: core-team

#5475 [BUGFIX] Rendering Test failures
  great_expectations/render/types/__init__.py
  tests/render/fixtures/ValidationResultsPageRenderer_render_with_run_info_at_end.json
  tests/render/fixtures/ValidationResultsPageRenderer_render_with_run_info_at_start.json
  tests/render/test_page_renderer.py
  tests/render/test_render_ValidationResultsTableContentBlockRenderer.py
Labels: core-team

#5477 [BUGFIX] Update `dependency-graph` pipeline YAML to ensure `--spark` gets passed to `dgtest`
  azure-pipelines-dependency-graph-testing.yml
Labels: core-team

#5415 [DOCS] Add 'test' extra to setup.py with docs
  docs/contributing/contributing_setup.md
  setup.py
Labels: devrel

#5485 Adds run time envvar for Snowflake Partner ID
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
Labels: devrel

#5429 [DOCS] DOC-343 partition how to configure expectation store for aws s3 guide
  docs/guides/setup/configuring_metadata_stores/components/_install_boto3_with_pip.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_configure_boto_to_connect_to_the_amazon_s_bucket_where_expectations_will_be_stored.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_confirm_that_expectations_can_be_accessed_from_amazon_s_by_running_great_expectations_suite_list.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_confirm_that_the_new_expectations_store_has_been_added_by_running_great_expectations_store_list.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_copy_existing_expectation_json_files_to_the_s_bucket_this_step_is_optional.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_identify_your_data_context_expectations_store.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_preface.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_update_your_configuration_file_to_include_a_new_store_for_expectations_on_s.mdx
  docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_amazon_s3.md
Labels: devrel

#5458 [DOCS] DOC-357 partition the how to create a new checkpoint guide
  docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_a_edit_the_configuration.mdx
Labels: devrel

#5491 [BUGFIX] Make sure the profileReport obj does not have defaultdicts (breaks gallery JSON)
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_column_values_to_be_equal_to_or_greater_than_profile_min.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_column_values_to_be_equal_to_or_less_than_profile_max.py
Labels: devrel

#5496 [MAINTENANCE] Remove pyspark<3.0.0 constraint for python 3.7
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines-expectation-gallery.yml
  azure-pipelines.yml
Labels: core-team

#5500 [MAINTENANCE] Ensure that `parter-integration` pipeline only runs on cronjob
  azure-pipelines-partner-integration.yml
Labels: core-team

#5502 [BUGFIX] Use Pandas.isnull() instead of NumPy.isnan() to check for empty values in TableExpectation._validate_metric_value_between(), due to wider types applicability.
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/expectation.py
  great_expectations/profile/user_configurable_profiler.py
Labels: core-team

#5486 [MAINTENANCE] Adding fixtures Query Expectations tests
  tests/expectations/core/conftest.py
  tests/expectations/core/test_expect_queried_column_value_frequency_to_meet_threshold.py
  tests/expectations/core/test_expect_queried_table_row_count_to_be.py
Labels: core-team

#5497 [MAINTENANCE] Misc updates to `GeCloudStoreBackend` to better integrate with GE Cloud
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/util.py
  scripts/check_type_hint_coverage.py
Labels: core-team

#5484 [DOCS] Remove outdated release process docs.
  docs/contributing/contributing_checklist.md
  docs/contributing/contributing_misc.md
Labels: core-team

#5488 [MAINTENANCE] Update automated release schedule
  .github/release_schedule.json
Labels: core-team

#5501 [MAINTENANCE] Remove pypandoc pin in constraints-dev.txt.
  constraints-dev.txt
Labels: core-team

#5490 [BUGFIX] Spark Schema has unexpected field for `spark.sql.warehouse.dir`
  .github/release_schedule.json
  great_expectations/data_context/types/base.py
  tests/datasource/test_sparkdf_datasource.py
Labels: core-team

#5482 [MAINTENANCE] Ensure that `add_datasource` method on `AbstractDataContext` does not persist by default
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/data_context.py
  tests/datasource/test_sparkdf_datasource.py
Labels: core-team

#5508 [BUGFIX] Conditionally pop `spark.sql.warehouse.dir` from test Spark configs
  tests/datasource/test_sparkdf_datasource.py
Labels: core-team

#5466 [FEATURE] Integrate `DataContextVariables` with `DataContext`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/render/renderer/suite_edit_notebook_renderer.py
  great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py
  tests/conftest.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_data_docs_api.py
  tests/render/test_data_documentation_site_builder.py
Labels: core-team

#5509 [MAINTENANCE] Clean up payload for `/data-context-variables` endpoint to adhere to desired chema
  great_expectations/checkpoint/checkpoint.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  great_expectations/data_context/store/data_context_store.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/validations_store.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/render/renderer/site_builder.py
  great_expectations/validation_operators/validation_operators.py
  scripts/check_type_hint_coverage.py
  tests/actions/conftest.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5472 [MAINTENANCE] DataContext Refactor: DataAssistants
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/types/base.py
  scripts/check_docstring_coverage.py
Labels: core-team

#5425 [DOCS] DOC-340 partition local installation guide
  docs/guides/connecting_to_your_data/database/athena.md
  docs/guides/setup/installation/components_local/_check_python_version.mdx
  docs/guides/setup/installation/components_local/_choose_installation_method.mdx
  docs/guides/setup/installation/components_local/_create_an_venv_with_anaconda.mdx
  docs/guides/setup/installation/components_local/_create_an_venv_with_pip.mdx
  docs/guides/setup/installation/components_local/_ensure_latest_anaconda.mdx
  docs/guides/setup/installation/components_local/_ensure_latest_pip.mdx
  docs/guides/setup/installation/components_local/_install_ge_with_anaconda.mdx
  docs/guides/setup/installation/components_local/_install_ge_with_pip.mdx
  docs/guides/setup/installation/components_local/_install_great_expectations.mdx
  docs/guides/setup/installation/components_local/_preface.mdx
  docs/guides/setup/installation/components_local/_verify_ge_install_succeeded.mdx
  docs/guides/setup/installation/local.md
Labels: devrel

#5510 [MAINTENANCE] Ensure that validation operators are omitted from Cloud variables payload
  great_expectations/data_context/store/data_context_store.py
Labels: core-team

#5517 [MAINTENANCE] Add end-to-end tests for multicolumn map expectations
  tests/test_definitions/multicolumn_map_expectations/expect_multicolumn_sum_to_equal.json
  tests/test_definitions/multicolumn_map_expectations/expect_select_column_values_to_be_unique_within_record.json
  tests/test_definitions/test_expectations.py
  tests/test_definitions/test_expectations_cfe.py
Labels: core-team

#5519 [MAINTENANCE] Ensure that *_store_name attrs are omitted from Cloud variables payload
  great_expectations/data_context/store/data_context_store.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5518 [DOCS] toc update for DataHub integration doc
  docs/integrations/index.md
  sidebars.js
Labels: devrel

#5511 [MAINTENANCE] Refactor `key` arg out of `Store.serialize/deserialize`
  great_expectations/data_context/store/configuration_store.py
  great_expectations/data_context/store/data_context_store.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/json_site_store.py
  great_expectations/data_context/store/metric_store.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/store/validations_store.py
Labels: core-team

#5177 Fix links to documentation
  great_expectations/data_context/util.py
  tests/data_context/test_data_context_config_variables.py
  tests/data_context/test_data_context_on_teams.py
Labels: community, devrel

#4953 [DOCS] Updating discourse to GitHub Discussions in Docs
  docs/intro.md
  docs_rtd/_templates/layout.html
  docs_rtd/guides/how_to_guides/creating_and_editing_expectations/how_to_create_expectations_that_span_multiple_batches_using_evaluation_parameters.rst
  docs_rtd/guides/tutorials/getting_started/customize_your_deployment.rst
  docs_rtd/guides/tutorials/getting_started_v3_api/customize_your_deployment.rst
  docs_rtd/index.rst
  docusaurus.config.js
Labels: devrel

#4952 Readme Update
  README.md
Labels: devrel

#5516 [MAINTENANCE] E2E test for `FileDataContextVariables`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/store/inline_store_backend.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5523 [MAINTENANCE] Cleanup/refactor prerequisite for group/filter/sort Expectations by domain
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_suite.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/types/domain.py
Labels: core-team

#5527 [MAINTENANCE] Refactor `GeCloudStoreBackend` to use PUT and DELETE HTTP verbs instead of PATCH
  great_expectations/data_context/store/ge_cloud_store_backend.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5530 [MAINTENANCE] Move MetricDomainTypes to core (it is used more widely now than previously).
  great_expectations/core/metric_domain_types.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_value_counts.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_values_between_count.py
  great_expectations/expectations/metrics/query_metrics/query_column.py
  great_expectations/expectations/metrics/query_metrics/query_table.py
  great_expectations/expectations/metrics/table_metrics/table_column_types.py
  great_expectations/expectations/metrics/table_metrics/table_head.py
  great_expectations/rule_based_profiler/domain_builder/categorical_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/column_pair_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/multi_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/table_domain_builder.py
  great_expectations/rule_based_profiler/helpers/runtime_environment.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/types/domain.py
  great_expectations/validator/validator.py
  tests/conftest.py
  tests/execution_engine/test_pandas_execution_engine.py
  tests/execution_engine/test_sparkdf_execution_engine.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/integration/profiling/rule_based_profiler/test_profiler_basic_workflows.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/rule_based_profiler/conftest.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/domain_builder/test_categorical_column_domain_builder.py
  tests/rule_based_profiler/domain_builder/test_domain_builder.py
  tests/rule_based_profiler/domain_builder/test_map_metric_column_domain_builder.py
  tests/rule_based_profiler/expectation_configuration_builder/test_default_expectation_configuration_builder.py
  tests/rule_based_profiler/parameter_builder/test_mean_table_columns_set_match_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_mean_unexpected_map_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_parameter_container.py
  tests/rule_based_profiler/parameter_builder/test_partition_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_regex_pattern_string_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_simple_date_format_string_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_value_set_multi_batch_parameter_builder.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/BasicExample_RBP_Instantiation_and_running.ipynb
  tests/test_fixtures/rule_based_profiler/plugins/my_custom_semantic_type_column_domain_builder.py
Labels: core-team

#5532 [FEATURE] Provide methods for returning ExpectationConfiguration list grouped by expectation_type and by domain_type
  great_expectations/core/expectation_suite.py
  great_expectations/util.py
  tests/core/test_expectation_suite.py
Labels: core-team

#5229 [FEATURE] add support for Azure authentication methods
  docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_azure_blob_storage.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_azure_blob_storage.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_azure_blob_storage.md
  great_expectations/data_context/store/tuple_store_backend.py
  requirements-dev-azure.txt
  tests/data_context/store/test_store_backends.py
Labels: community, devrel

#5506 [MAINTENANCE] use invoke for common contrib/dev tasks
  .gitignore
  azure-pipelines.yml
  docs/contributing/style_guides/code_style.md
  great_expectations/core/usage_statistics/package_dependencies.py
  requirements-dev-contrib.txt
  scripts/check_type_hint_coverage.py
  tasks.py
Labels: core-team

#5539 [FEATURE] Show grouped sorted expectations by Domain and by expectation_type
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_suite.py
  great_expectations/util.py
Labels: core-team

#5526 [MAINTENANCE] enforce pre-commit in ci
  .pre-commit-config.yaml
  docs/contributing/style_guides/code_style.md
  tasks.py
Labels: core-team

#5542 [MAINTENANCE] Providing more robust error handling for determining `domain_type` of an `ExpectationConfiguration` object
  great_expectations/core/expectation_configuration.py
  great_expectations/data_context/data_context/abstract_data_context.py
Labels: core-team

#5545 [MAINTENANCE] Remove extra indentation from store backend test
  tests/data_context/store/test_store_backends.py
Labels: core-team

#5528 [MAINTENANCE] Plot-level dropdown for `DataAssistantResult` display charts
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/exceptions/exceptions.py
  great_expectations/rule_based_profiler/types/altair/themes.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  requirements-dev-lite.txt
  requirements.txt
Labels: core-team

#5546 [BUGFIX] Use string dialect name if not found in enum
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/execution_engine/sqlalchemy_dialect.py
  tests/execution_engine/test_sqlalchemy_dialect.py
Labels: core-team

#5549 [MAINTENANCE] Make DataAssistantResult.batch_id_to_batch_identifier_display_name_map private (in order to optimize auto-complete for ease of use)
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5550 [BUGFIX] Add `try/except` around `DataContext._save_project_config` to mitigate issues with permissions
  great_expectations/data_context/data_context/base_data_context.py
Labels: core-team

#5541 [MAINTENANCE] Initial Dockerfile for running tests and associated README.
  docker/Dockerfile.tests
  docker/Dockerfile.tests.dockerignore
  docker/README.md
Labels: core-team

#5548 [BUGFIX] Explicitly pass in mostly as 1 if not set in configuration.
  great_expectations/expectations/expectation.py
Labels: core-team

#5551 [FEATURE] Categorical Rule in VolumeDataAssistant Should Use Same Cardinality As Categorical Rule in OnboardingDataAssistant
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  tests/cli/test_suite.py
  tests/integration/docusaurus/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/test_utils.py
Labels: core-team

#5552 [BUGFIX] Increase precision for categorical rule for fractional comparisons
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
Labels: core-team

#5554 [BUGFIX] Remove `ipywidgets` from dev package dependencies
  great_expectations/core/usage_statistics/package_dependencies.py
Labels: core-team

#5555 [BUGFIX] Update logic used in `DataContext.__init__()` to persist `data_context_id`
  great_expectations/data_context/data_context/data_context.py
  tests/data_context/test_data_context.py
Labels: core-team

#5543 [MAINTENANCE] Ensure that each class in the `DataContext` hierachy has implemented `_init_datasource_store`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/store.py
  tests/conftest.py
  tests/data_context/test_data_context_datasources.py
Labels: core-team

#5521 [DOCS] Add mostly docs for MultiColumnMapExpectation
  docs/reference/expectations/standard_arguments.md
  docs_rtd/reference/core_concepts/expectations/standard_arguments.rst
Labels: core-team

#5557 [MAINTENANCE] Refactor for a more general parametrization of CategoricalDomainBuilder in DataAssistant implementations
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/expectation.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/util.py
  scripts/check_type_hint_coverage.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5561 [DOCS] Added docstring for isclose() utility method
  great_expectations/util.py
Labels: core-team

#5559 [MAINTENANCE] Refactor `DataContext.__init__` to initialize datasources utilizing a given `DataContextConfig`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  tests/data_context/test_data_context_datasources.py
Labels: core-team

#5566 [MAINTENANCE] Update `DataContextVariables` `__str__` and `__repr__` to only include config
  great_expectations/data_context/data_context_variables.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5569 Enable Stale
  .github/workflows/stale.yml
Labels: devrel, maintenance

#5563 [FEATURE] Multi-Batch Example Notebook - Configured and InferredAssetDataConnector examples
  tests/integration/profiling/rule_based_profiler/test_run_profiler_notebook.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_ConfiguredAssetFileSystemExample.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_InferredAssetFileSystemExample.ipynb
Labels: core-team

#5570 [MAINTENANCE] Add AbstractConfig
  great_expectations/core/configuration.py
Labels: core-team

#5571 [MAINTENANCE] Delete usage_statistics_handler from the set of RuleBasedProfilerResult and DataAssistantResult object serialization keys
  great_expectations/rule_based_profiler/rule_based_profiler_result.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: core-team

#5572 [BUGFIX] Ensure that `DataContext.list_datasources()` iterates through config instead of relying on `DatasourceStore` requests
  great_expectations/data_context/data_context/abstract_data_context.py
Labels: core-team

#5540 [MAINTENANCE] begin static type-checking
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
  docs/contributing/style_guides/code_style.md
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/profile/base.py
  great_expectations/profile/json_schema_profiler.py
  great_expectations/profile/user_configurable_profiler.py
  mypy.ini
  requirements-dev-contrib.txt
  tasks.py
Labels: core-team

#5568 [MAINTENANCE] Confirm E2E workflow for Cloud-enabled `DataContext` integration with `DataContextVariables`
  azure-pipelines-dependency-graph-testing.yml
  azure-pipelines.yml
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  tests/conftest.py
  tests/data_context/test_data_context_ge_cloud_mode.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5558 [FEATURE] expect_profile_numeric_columns_percent_diff_(less/greater)_than_threshold
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/__init__.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_greater_than_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_less_than_threshold.py
Labels: community, devrel

#5560 [MAINTENANCE] Add name and id to DatasourceConfig
  great_expectations/data_context/types/base.py
  tests/datasource/test_datasource_serialization.py
  tests/integration/test_script_runner.py
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/postgresql/v3/great_expectations/great_expectations.yml
Labels: core-team

#5588 [MAINTENANCE] Clear datasources in `test_data_context_datasources` to improve test performance and narrow test scope
  tests/data_context/test_data_context_datasources.py
Labels: core-team

#5589 [MAINTENANCE] Fix tests that rely on guessing pytest generated random file paths.
  tests/data_context/store/test_expectations_store.py
  tests/data_context/store/test_html_site_store.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/store/test_validations_store.py
  tests/data_context/test_data_context.py
Labels: core-team

#5592 [MAINTENANCE] Do not set google cloud credentials for lifetime of pytest process.
  tests/data_context/test_data_context_v013.py
  tests/datasource/data_connector/test_configured_asset_dbfs_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_dbfs_data_connector.py
  tests/integration/common_workflows/pandas_execution_engine_with_gcp_installed.py
Labels: core-team

#5584 [MAINTENANCE] Misc updates to `Datasource` CRUD on `DataContext` to ensure consistent behavior
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/data_context.py
Labels: core-team

#5595 [BUGFIX] Pass cloud base url to datasource store
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  tests/conftest.py
  tests/data_context/test_data_context_ge_cloud_mode.py
Labels: core-team

#5590 [MAINTENANCE] Add id to `RuleBasedProfiler` config
  great_expectations/rule_based_profiler/config/base.py
  tests/rule_based_profiler/test_rule_based_profiler_serialization.py
Labels: core-team

#5587 [MAINTENANCE] refactor to enable customization of quantile bias correction threshold for bootstrap estimation method
  great_expectations/datasource/data_connector/util.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/volume_data_assistant.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/util.py
  tests/conftest.py
  tests/datasource/batch_kwarg_generator/test_s3_subdir_reader_generator.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/parameter_builder/test_parameter_computations.py
  tests/test_fixtures/rule_based_profiler/bobster_user_workflow_verbose_profiler_config.yml
  tests/test_fixtures/rule_based_profiler/example_notebooks/SelfInitializingExpectations.ipynb
  tests/test_fixtures/rule_based_profiler/quentin_user_workflow_verbose_profiler_config.yml
Labels: core-team

#5606 [BUGFIX] Temporarily disable Trino `0.315.0` from requirements
  requirements-dev-trino.txt
Labels: core-team

#5591 [MAINTENANCE] Create datasource with id
  great_expectations/core/configuration.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/data_context/types/base.py
  great_expectations/datasource/new_datasource.py
  great_expectations/rule_based_profiler/config/base.py
  scripts/check_type_hint_coverage.py
  tests/data_context/cloud_data_context/__init__.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/conftest.py
  tests/data_context/store/conftest.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
  tests/data_context/test_data_context.py
  tests/datasource/test_datasource_serialization.py
  tests/rule_based_profiler/test_rule_based_profiler_serialization.py
Labels: core-team

#5594 [MAINTENANCE] Enable Azure blob storage integration tests
  azure-pipelines-docs-integration.yml
  great_expectations/self_check/util.py
  tests/conftest.py
  tests/integration/test_script_runner.py
  tests/integration/usage_statistics/test_integration_usage_statistics.py
Labels: core-team

#5608 [MAINTENANCE] Increase expectation kwarg line stroke width
  great_expectations/rule_based_profiler/types/altair/themes.py
  great_expectations/rule_based_profiler/types/data_assistant_result/data_assistant_result.py
Labels: core-team

#5604 [BUGFIX] Support `ExpectationSuite` CRUD at `BaseDataContext` level
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  tests/data_context/test_base_data_context.py
  tests/expectations/test_expectation_arguments.py
Labels: core-team

#5615 [MAINTENANCE] Handle `numpy` deprecation warnings
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/types/numeric_range_estimation_result.py
  great_expectations/util.py
  tests/rule_based_profiler/parameter_builder/conftest.py
Labels: core-team

#5610 [FEATURE] DataConnector Query enabled for `SimpleSqlDatasource`
  great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py
  tests/datasource/data_connector/test_data_connector_query.py
  tests/datasource/data_connector/test_data_connector_query_filesystem.py
  tests/datasource/data_connector/test_data_connector_query_sql.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_SqlExample.ipynb
Labels: core-team

#5618 [MAINTENANCE] remove approximate comparisons -- they will be replaced by estimator alternatives
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_between.py
Labels: core-team

#5620 [FEATURE] Implement the exact metric range estimate for NumericMetricRangeMultiBatchParameterBuilder
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/partition_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
Labels: core-team

#5514 [MAINTENANCE] Making the dependency on dev-lite clearer
  requirements-dev.txt
Labels: core-team

#5611 [MAINTENANCE] Fix tests in tests/integration/profiling/rule_based_profiler/ and tests/render/renderer/
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/test_fixtures/great_expectations_custom_notebooks.yml
Labels: core-team

#5617 [FEATURE] Ensure that `id` propogates from `RuleBasedProfilerConfig` to `RuleBasedProfiler`
  great_expectations/data_context/store/profiler_store.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
Labels: core-team

#5624 [BUGFIX] Update test due to change in postgres stdev calculation method
  tests/test_definitions/column_aggregate_expectations/expect_column_stdev_to_be_between.json
  tests/test_definitions/test_expectations_cfe.py
Labels: core-team

#5625 [MAINTENANCE] DataContext in cloud mode test add_datasource
  tests/conftest.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
Labels: core-team

#5619 [BUGFIX] Patch issue with `get_validator` on Cloud-backed `DataContext`
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  scripts/check_type_hint_coverage.py
  tests/data_context/test_base_data_context.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5629 [BUGFIX] Patch flaky E2E GX Cloud tests
  azure-pipelines.yml
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  tests/conftest.py
  tests/data_context/test_base_data_context.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#5602 [MAINTENANCE] Update stale.yml
  .github/workflows/stale.yml
Labels: devrel, maintenance

#5628 [FEATURE] Improve estimation histogram computation in NumericMetricRangeMultiBatchParameterBuilder to include both counts and bin edges
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/types/numeric_range_estimation_result.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
Labels: core-team

#5603 [MAINTENANCE] Add `id` to `CheckpointValidationConfig`
  great_expectations/data_context/types/base.py
  tests/core/test_serialization.py
Labels: core-team

#5632 [BUGFIX] Pass `--cloud` flag to `dgtest-cloud-overrides` section of Azure YAML
  azure-pipelines-dependency-graph-testing.yml
  tests/conftest.py
Labels: core-team

#5635 [MAINTENANCE] Better error message for RuntimeDataConnector for BatchIdentifiers
  great_expectations/datasource/data_connector/runtime_data_connector.py
  tests/datasource/data_connector/test_runtime_data_connector.py
Labels: core-team
