Repository great-expectations/great_expectations, pull requests merged in 2022-11, with the labels that each got.

#6215 Add Trino CLI support and bump Trino version
  assets/docker/trino/docker-compose.yml
  azure-pipelines-dev.yml
  azure-pipelines-docs-integration.yml
  azure-pipelines-expectation-gallery.yml
  azure-pipelines-os-integration.yml
  azure-pipelines.yml
  great_expectations/cli/datasource.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_in_set.py
  reqs/requirements-dev-trino.txt
  scripts/check_docstring_coverage.py
  tests/cli/test_datasource_sqlite.py
Labels: community

#6264 [MAINTENANCE] Delete unneeded Rule attribute property
  great_expectations/rule_based_profiler/rule/rule.py
Labels: core-team

#6213 [MAINTENANCE] Small clean-up of `Marshmallow` warnings (`missing` parameter changed to `load_default` as of 3.13)
  great_expectations/data_context/types/base.py
  requirements.txt
Labels: core-team

#6166 [BUGFIX] `InferredAssetSqlDataConnector` `include_schema_name` introspection of identical table names in different schemas
  great_expectations/datasource/data_connector/asset/asset.py
  great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py
  great_expectations/self_check/util.py
  tests/conftest.py
  tests/datasource/conftest.py
  tests/datasource/data_connector/test_sql_data_connector.py
  tests/datasource/test_new_datasource_with_sql_data_connector.py
Labels: core-team

#6249 [MAINTENANCE] Move `.png` files out of project root
  README.md
  docs_rtd/conf.py
  static/img/generic_dickens_protagonist.png
  static/img/packages_great_expectations.png
  static/img/pip-logo.png
Labels: core-team

#6265 [MAINTENANCE] Cleanup `expectation.py` attributes
  great_expectations/core/expectation_diagnostics/supporting_types.py
  great_expectations/expectations/expectation.py
Labels: core-team

#6267 [MAINTENANCE] Further parallelize test runs in `dev` CI
  azure-pipelines-dev.yml
Labels: core-team

#6259 [MAINTENANCE] GCP Integration Pipeline fix
  azure-pipelines-gcp-integration.yml
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_informed.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_like_pattern.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_match_like_pattern.json
Labels: core-team

#6270 [MAINTENANCE] mypy `warn_unused_ignores`
  azure-pipelines-dev.yml
  azure-pipelines-expectation-gallery.yml
  azure-pipelines-os-integration.yml
  azure-pipelines.yml
  great_expectations/core/evaluation_parameters.py
  great_expectations/core/expectation_suite.py
  great_expectations/data_context/config_validator/yaml_config_validator.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/profiler_store.py
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/data_context/store/validations_store.py
  great_expectations/data_context/types/base.py
  great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py
  great_expectations/render/__init__.py
  great_expectations/render/renderer/inline_renderer.py
  great_expectations/self_check/util.py
  great_expectations/types/__init__.py
  great_expectations/util.py
  great_expectations/zep/context.py
  tasks.py
Labels: core-team

#6268 [BUGFIX] Fix`docs-integration` tests, and temporarily pin `sqlalchemy`
  reqs/requirements-dev-lite.txt
Labels: core-team

#6263 [MAINTENANCE] ZEP - Datasource base class
  great_expectations/zep/context.py
  great_expectations/zep/demos.py
  great_expectations/zep/interfaces.py
  great_expectations/zep/metadatasource.py
  great_expectations/zep/sources.py
  tests/zep/test_metadatasource.py
Labels: core-team

#6271 [MAINTENANCE] Reverting `marshmallow` version bump
  great_expectations/data_context/types/base.py
  requirements.txt
Labels: core-team

#6272 [MAINTENANCE] type hints cleanup in Rule-Based Profiler
  great_expectations/rule_based_profiler/builder.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_dispatcher.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/domain_builder/categorical_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/column_pair_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/map_metric_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/multi_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/table_domain_builder.py
  great_expectations/rule_based_profiler/expectation_configuration_builder/default_expectation_configuration_builder.py
  great_expectations/rule_based_profiler/expectation_configuration_builder/expectation_configuration_builder.py
  great_expectations/rule_based_profiler/helpers/simple_semantic_type_filter.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/histogram_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/mean_table_columns_set_match_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/mean_unexpected_map_metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_counts_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/test_rule_based_profiler.py
Labels: core-team

#6248 [MAINTENANCE] Remove unused f-strings
  great_expectations/checkpoint/actions.py
  great_expectations/checkpoint/checkpoint.py
  great_expectations/expectations/core/expect_compound_columns_to_be_unique.py
  great_expectations/expectations/core/expect_multicolumn_values_to_be_unique.py
  great_expectations/expectations/core/expect_select_column_values_to_be_unique_within_record.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
Labels: core-team

#6266 [BUGFIX] Fix serialization for contrib packages
  assets/scripts/build_package_gallery.py
  contrib/cli/great_expectations_contrib/commands.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/zip_codes/__init__.py
  great_expectations/core/util.py
  tests/core/test_convert_to_json_serializable.py
Labels: core-team

#6273 [MAINTENANCE] Make ParameterBuilder.resolve_evaluation_dependencies() into instance (rather than utility) method
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
Labels: core-team

#6229 [MAINTENANCE] Test definition for `ExpectColumnValueZScoresToBeLessThan`
  great_expectations/self_check/util.py
  tests/render/test_render_BulletListContentBlock.py
  tests/test_definitions/column_map_expectations/expect_column_value_z_scores_to_be_less_than.json
Labels: core-team

#6275 [MAINTENANCE] Make RuleState constructor argument ordering consistent with standard pattern.
  great_expectations/rule_based_profiler/rule_state.py
  tests/rule_based_profiler/conftest.py
Labels: core-team

#6254 [BUGFIX] Ensure that `Datasource` credentials are not persisted to Cloud/disk
  great_expectations/data_context/config_validator/yaml_config_validator.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/datasource/datasource.py
  great_expectations/datasource/new_datasource.py
  tests/data_context/abstract_data_context/test_abstract_data_context_datasource_crud.py
  tests/data_context/test_data_context_test_yaml_config.py
Labels: core-team

#6280 [RELEASE] 0.15.30
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team

#6283 [DOCS] Updates outdated batch_request snippet in Terms
  docs/terms/_batches_and_batch_requests.mdx
Labels: devrel

#6279 [DOCS] Update Conditional Expectations doc w/ current availability
  docs/reference/expectations/conditional_expectations.md
  docs/terms/expectation.md
Labels: devrel

#6284 [MAINTENANCE] Move RuleState into rule directory.
  great_expectations/rule_based_profiler/domain.py
  great_expectations/rule_based_profiler/parameter_container.py
  great_expectations/rule_based_profiler/rule/rule.py
  great_expectations/rule_based_profiler/rule/rule_output.py
  great_expectations/rule_based_profiler/rule/rule_state.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  pyproject.toml
  tests/rule_based_profiler/conftest.py
Labels: core-team

#6292 [BUGFIX] Include all requirement files in the sdist
  MANIFEST.in
Labels: community

#6288 [DOCS] Remove outdated Data Discovery page and all references
  docs/reference/core_concepts.md
  docs/reference/data_discovery.md
  docs/reference/reference_overview.md
  docs/reference/supplemental_documentation.md
  sidebars.js
  static/_redirects
Labels: devrel

#6294 [DOCS] Remove reference/evaluation_parameters page and all references
  docs/reference/checkpoints_and_actions.md
  docs/reference/core_concepts.md
  docs/reference/evaluation_parameters.md
  docs/reference/validation.md
  docs/terms/checkpoint.md
  static/_redirects
Labels: devrel

#6282 [DOCS] Removing deprecated Custom Metrics doc
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_metrics.md
  sidebars.js
  static/_redirects
Labels: devrel

#6281 [DOCS] Re-writes "how to implement custom notifications" as "How to get Data Docs URLs for use in custom Validation Actions"
  docs/guides/validation/advanced/how_to_get_data_docs_urls_for_custom_validation_actions.md
  docs/guides/validation/advanced/how_to_implement_custom_notifications.md
  docs/guides/validation/index.md
  docs/reference/customize_your_deployment.md
  great_expectations/checkpoint/actions.py
  sidebars.js
  static/_redirects
Labels: devrel

#6298 [DOCS] Removes deprecated expectation notebook exploration doc
  docs/guides/expectations/index.md
  docs/guides/miscellaneous/how_to_quickly_explore_expectations_in_a_notebook.md
  sidebars.js
  static/_redirects
Labels: devrel

#6301 [RELEASE] 0.15.31
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team

#6291 [MAINTENANCE] Remove unneeded `BaseDataContext.get_batch_list`
  great_expectations/data_context/data_context/base_data_context.py
Labels: core-team

#6300 [DOCS] Removes a number of unused & deprecated docs
  docs/deployment_patterns/how_to_use_great_expectations_in_databricks.md
  docs/deployment_patterns/how_to_use_great_expectations_in_deepnote.md
  docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_a_file_system_or_blob_store.md
  docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_tables_in_sql.md
  docs/guides/connecting_to_your_data/how_to_choose_between_working_with_a_single_or_multiple_batches_of_data.md
  docs/guides/connecting_to_your_data/how_to_choose_which_dataconnector_to_use.md
  docs/guides/connecting_to_your_data/how_to_configure_a_configuredassetdataconnector.md
  docs/guides/connecting_to_your_data/how_to_configure_a_dataconnector_to_introspect_and_partition_a_file_system_or_blob_store.md
  docs/guides/connecting_to_your_data/how_to_configure_a_dataconnector_to_introspect_and_partition_tables_in_sql.md
  docs/guides/connecting_to_your_data/how_to_configure_a_runtimedataconnector.md
  docs/guides/connecting_to_your_data/how_to_configure_an_inferredassetdataconnector.md
  docs/guides/connecting_to_your_data/how_to_create_a_batch_of_data_from_an_in_memory_spark_or_pandas_dataframe.md
  docs/guides/connecting_to_your_data/how_to_get_one_or_more_batches_of_data_from_a_configured_datasource.md
  docs/guides/expectations/advanced/how_to_create_renderers_for_custom_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_table_expectations.md
  docs/guides/expectations/creating_custom_expectations/overview.md
  docs/guides/expectations/features_custom_expectations/how_to_add_data_visualization_renderers_for_an_expectation.md
  docs/guides/expectations/features_custom_expectations/how_to_add_sqlalchemy_support_for_an_expectation.md
  docs/guides/expectations/features_custom_expectations/how_to_add_statement_renderers_for_an_expectation.md
  docs/guides/expectations/how_to_create_and_edit_expectations_based_on_domain_knowledge_without_inspecting_data_directly.md
  docs/guides/expectations/index.md
  docs/guides/miscellaneous/migration_guide.md
  docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_a_filesystem.md
  docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.md
  docs/guides/validation/validate_data_overview.md
  docs/intro.md
  docs/reference/checkpoints_and_actions.md
  docs/reference/core_concepts.md
  docs/reference/data_context.md
  docs/reference/data_docs.md
  docs/reference/datasources.md
  docs/reference/dividing_data_assets_into_batches.md
  docs/reference/execution_engine.md
  docs/reference/expectations/conditional_expectations.md
  docs/reference/expectations/execution_engine.md
  docs/reference/expectations/expectation_suite_operations.md
  docs/reference/expectations/expectations.md
  docs/reference/metrics.md
  docs/reference/profilers.md
  docs/reference/supporting_resources.md
  docs/reference/validation.md
  docs/terms/checkpoint.md
  docs/terms/data_docs.md
  docs/terms/renderer.md
  docs/tutorials/getting_started/tutorial_connect_to_data.md
  sidebars.js
  static/_redirects
Labels: devrel

#6302 [DOCS] Prioritizes Onboarding Data Assistant in ToC
  sidebars.js
Labels: devrel

#6319 [MAINTENANCE] Clean up implicit `Optional` errors flagged by `mypy`
  great_expectations/checkpoint/actions.py
  great_expectations/checkpoint/types/checkpoint_result.py
  great_expectations/cli/toolkit.py
  great_expectations/cli/util.py
  great_expectations/cli/v012/toolkit.py
  great_expectations/cli/v012/util.py
  great_expectations/core/batch.py
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_suite.py
  great_expectations/data_context/config_validator/yaml_config_validator.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/types/base.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/datasource/data_connector/batch_filter.py
  great_expectations/datasource/data_connector/configured_asset_aws_glue_data_catalog_data_connector.py
  great_expectations/datasource/data_connector/file_path_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_aws_glue_data_catalog_data_connector.py
  great_expectations/datasource/data_connector/sorter/custom_list_sorter.py
  great_expectations/datasource/simple_sqlalchemy_datasource.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_most_common_value_to_be_in_set.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_to_exist.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/expectations/core/expect_column_values_to_be_null.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_not_be_null.py
  great_expectations/expectations/core/expect_table_column_count_to_be_between.py
  great_expectations/expectations/core/expect_table_column_count_to_equal.py
  great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py
  great_expectations/expectations/core/expect_table_columns_to_match_set.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_equal.py
  great_expectations/expectations/core/expect_table_row_count_to_equal_other_table.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/registry.py
  great_expectations/profile/json_schema_profiler.py
  great_expectations/self_check/util.py
  great_expectations/validation_operators/types/validation_operator_result.py
  great_expectations/validator/metric_configuration.py
  great_expectations/validator/validator.py
Labels: core-team

#6278 [MAINTENANCE] Add manual prod flags to core Expectations
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_value_z_scores_to_be_less_than.py
  great_expectations/expectations/core/expect_column_values_to_be_json_parseable.py
  great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py
  great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py
  great_expectations/expectations/core/expect_column_values_to_match_regex.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex_list.py
  great_expectations/expectations/core/expect_compound_columns_to_be_unique.py
Labels: devrel

#6318 Fallback to isnot method if is_not is not available (old sqlalchemy)
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_distinct_values.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_value_counts.py
Labels: devrel

#6274 Add ZEP postgres datasource.
  great_expectations/zep/__init__.py
  great_expectations/zep/demos.py
  great_expectations/zep/interfaces.py
  great_expectations/zep/postgres_datasource.py
  tests/zep/test_metadatasource.py
  tests/zep/test_postgres_datasource.py
Labels: core-team

#6305 [MAINTENANCE] Delete "metric_dependencies" from MetricConfiguration constructor arguments
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/util.py
  great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py
  great_expectations/expectations/metrics/column_aggregate_metric_provider.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_standard_deviation.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/compound_columns_unique.py
  great_expectations/expectations/metrics/table_metrics/table_column_count.py
  great_expectations/expectations/metrics/table_metrics/table_columns.py
  great_expectations/rule_based_profiler/domain_builder/categorical_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/map_metric_column_domain_builder.py
  great_expectations/rule_based_profiler/helpers/simple_semantic_type_filter.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/validator/metric_configuration.py
  tests/conftest.py
  tests/execution_engine/test_execution_engine.py
  tests/execution_engine/test_pandas_execution_engine.py
  tests/execution_engine/test_sparkdf_execution_engine.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/expectations/metrics/test_core.py
  tests/expectations/test_util.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_equal_three.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/parameter_builder/test_histogram_single_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_value_counts_single_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_value_set_multi_batch_parameter_builder.py
  tests/test_fixtures/rule_based_profiler/plugins/my_custom_semantic_type_column_domain_builder.py
  tests/validator/conftest.py
  tests/validator/test_metrics_calculator.py
  tests/validator/test_validation_graph.py
Labels: core-team

#6304 [MAINTENANCE] Clean up `DataContext`
  great_expectations/data_context/data_context/data_context.py
Labels: core-team

#6258 [MAINTENANCE] Deprecate `save_changes` flag on `Datasource` CRUD
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  tests/data_context/abstract_data_context/test_datasource_delete.py
  tests/data_context/test_data_context_datasources.py
Labels: core-team

#6328 [MAINTENANCE] Update range of allowable sqlalchemy versions
  reqs/requirements-dev-lite.txt
Labels: devrel

#6327 [BUGFIX] Patch broken `CloudNotificationAction` tests
  tests/conftest.py
Labels: core-team

#6325 [MAINTENANCE] Fixing checkpoint types
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/async_executor.py
  great_expectations/core/expectation_suite.py
  great_expectations/core/run_identifier.py
  great_expectations/core/util.py
  great_expectations/data_context/types/base.py
  pyproject.toml
Labels: core-team

#6218 [MAINTENANCE] Fix column_reflection_fallback for Trino and minor logging/testing improvements
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/util.py
  tests/integration/docusaurus/connecting_to_your_data/database/trino_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/trino_yaml_example.py
  tests/integration/test_script_runner.py
Labels: devrel

#6144 [DOCS] Add ZenML into integration table in Readme
  README.md
Labels: community

#6331 [BUGFIX] add create_temp_table flag to ExecutionEngineConfigSchema
  great_expectations/data_context/types/base.py
Labels: community

#6333 [MAINTENANCE] Change the number of expected Expectations in the 'quick check' stage of build_gallery pipeline
  azure-pipelines-expectation-gallery.yml
Labels: devrel

#6334 [BUGFIX] MapMetrics now return `partial_unexpected` values for `SUMMARY` format
  great_expectations/expectations/expectation.py
  tests/expectations/metrics/test_map_metric.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_in_type_list.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_increasing.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_regex.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_be_in_set.json
Labels: core-team

#6324 [DOCS] add `pypi` release badge
  README.md
Labels: documentation, core-team

#6222 [DOCS] DOC-308 update CLI command in docs when working with RBPs instead of Data Assistants
  docs/guides/expectations/how_to_create_and_edit_expectations_with_a_profiler.md
Labels: devrel

#6338 [RELEASE] 0.15.32
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team

#5766 [DOCS] DOC-366 updates to docs in support of branding updates
  docs/integrations/contributing_integration.md
  docs/terms/execution_engine.md
Labels: devrel

#6339 [BUGFIX] Fix issue with misaligned indentation in docs snippets
  scripts/remark-named-snippets/snippet.js
Labels: core-team

#6340 [MAINTENANCE] Add missing one-line docstrings and try to make the others consistent
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_most_common_value_to_be_in_set.py
  great_expectations/expectations/core/expect_column_pair_values_a_to_be_greater_than_b.py
  great_expectations/expectations/core/expect_column_pair_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_equal.py
  great_expectations/expectations/core/expect_column_value_z_scores_to_be_less_than.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_dateutil_parseable.py
  great_expectations/expectations/core/expect_column_values_to_be_decreasing.py
  great_expectations/expectations/core/expect_column_values_to_be_increasing.py
  great_expectations/expectations/core/expect_column_values_to_be_json_parseable.py
  great_expectations/expectations/core/expect_column_values_to_be_null.py
  great_expectations/expectations/core/expect_column_values_to_match_json_schema.py
  great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py
  great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py
  great_expectations/expectations/core/expect_column_values_to_match_regex.py
  great_expectations/expectations/core/expect_column_values_to_match_regex_list.py
  great_expectations/expectations/core/expect_column_values_to_match_strftime_format.py
  great_expectations/expectations/core/expect_column_values_to_not_be_null.py
  great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern.py
  great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern_list.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex_list.py
  great_expectations/expectations/core/expect_compound_columns_to_be_unique.py
  great_expectations/expectations/core/expect_multicolumn_sum_to_equal.py
Labels: devrel

#6321 [MAINTENANCE] Refactor variable aggregation/substitution logic into `ConfigurationProvider` hierarchy
  great_expectations/core/config_provider.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  scripts/check_docstring_coverage.py
  tests/data_context/test_data_context_config_variables.py
Labels: core-team

#6342 [MAINTENANCE] In ExecutionEngine: Make variable names and usage more descriptive of their purpose.
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/map_metric_provider.py
Labels: core-team

#6349 [MAINTENANCE] Move Cloud-specific enums to `cloud_constants.py`
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/config_provider.py
  great_expectations/data_context/cloud_constants.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/data_context/migrator/cloud_migrator.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/profiler_store.py
  great_expectations/data_context/store/validations_store.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/render/renderer/site_builder.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/validation_operators/validation_operators.py
  tests/actions/conftest.py
  tests/conftest.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/migrator/test_cloud_migrator.py
  tests/data_context/store/conftest.py
  tests/data_context/store/test_checkpoint_store.py
  tests/data_context/store/test_configuration_store.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
  tests/data_context/store/test_ge_cloud_store_backend.py
  tests/data_context/store/test_store_backends.py
Labels: core-team

#6348 [MAINTENANCE] Refactor out `termcolor` dependency
  docs_rtd/requirements.txt
  great_expectations/cli/pretty_printing.py
  great_expectations/cli/v012/util.py
  great_expectations/core/usage_statistics/package_dependencies.py
  requirements.txt
  tests/cli/test_datasource_pandas.py
  tests/cli/test_datasource_sqlite.py
  tests/cli/upgrade_helpers/test_upgrade_helper.py
  tests/cli/utils.py
  tests/cli/v012/test_datasource_pandas.py
  tests/cli/v012/test_datasource_sqlite.py
  tests/cli/v012/test_init_pandas.py
  tests/cli/v012/test_store.py
  tests/cli/v012/test_validation_operator.py
  tests/cli/v012/upgrade_helpers/test_upgrade_helper_pre_v013.py
  tests/integration/usage_statistics/usage_stats_event_examples.py
  tests/test_fixtures/upgrade_helper/test_basic_project_upgrade_expected_stdout.fixture
  tests/test_fixtures/upgrade_helper/test_basic_project_upgrade_expected_v012_stdout.fixture
  tests/test_fixtures/upgrade_helper/test_project_upgrade_with_exception_expected_stdout.fixture
  tests/test_fixtures/upgrade_helper/test_project_upgrade_with_exception_expected_v012_stdout.fixture
  tests/test_fixtures/upgrade_helper/test_project_upgrade_with_manual_steps_expected_stdout.fixture
  tests/test_fixtures/upgrade_helper/test_project_upgrade_with_manual_steps_expected_v012_stdout.fixture
  tests/test_fixtures/upgrade_helper/test_v2_to_v3_project_upgrade_expected_v012_stdout.fixture
  tests/test_fixtures/upgrade_helper/test_v2_to_v3_project_upgrade_with_manual_steps_checkpoints.fixture
  tests/test_fixtures/upgrade_helper/test_v2_to_v3_project_upgrade_with_manual_steps_checkpoints_datasources_validation_operators_expected_stdout.fixture
  tests/test_fixtures/upgrade_helper/test_v2_to_v3_project_upgrade_without_manual_steps_expected_stdout.fixture
Labels: core-team

#6351 [DOCS] Add `yarn snippet-check` command
  package.json
  scripts/remark-named-snippets/snippet.js
Labels: core-team

#6341 Zep PostgresDatasource returns a list of batches.
  great_expectations/zep/interfaces.py
  great_expectations/zep/postgres_datasource.py
  tests/zep/test_postgres_datasource.py
Labels: core-team

#5339 [MAINTENANCE] Refactor `usage_stats_opt_out` method in DataContext
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/util.py
  tests/core/usage_statistics/test_usage_statistics.py
  tests/data_context/test_data_context_config_ui.py
  tests/integration/usage_statistics/test_usage_stats_common_messages_are_sent_v3api.py
Labels: core-team

#6347 [MAINTENANCE] Fix computed metrics type hint in ExecutionEngine.resolve_metrics() method
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/expectations/registry.py
  great_expectations/rule_based_profiler/attributed_resolved_metrics.py
  great_expectations/rule_based_profiler/domain_builder/categorical_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/map_metric_column_domain_builder.py
  great_expectations/rule_based_profiler/estimators/exact_numeric_range_estimator.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/metric_computation_result.py
  great_expectations/rule_based_profiler/parameter_builder/histogram_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/mean_table_columns_set_match_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/validator/computed_metric.py
  great_expectations/validator/metrics_calculator.py
  great_expectations/validator/validation_graph.py
  great_expectations/validator/validator.py
  tests/execution_engine/test_execution_engine.py
  tests/execution_engine/test_pandas_execution_engine.py
  tests/execution_engine/test_sparkdf_execution_engine.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/expectations/metrics/test_core.py
  tests/validator/test_validation_graph.py
Labels: core-team

#5876 Subject: Support to include ID/PK in validation result for each row t…
  great_expectations/expectations/metrics/map_metric_provider.py
  tests/expectations/metrics/test_map_metric.py
Labels: community, devrel, feature

#6361 [MAINTENANCE] Pin `mypy` to `0.990`
  great_expectations/core/expectation_suite.py
  great_expectations/data_context/config_validator/yaml_config_validator.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/exceptions/exceptions.py
  great_expectations/render/renderer/inline_renderer.py
  great_expectations/util.py
  pyproject.toml
  reqs/requirements-dev-contrib.txt
  tasks.py
Labels: core-team

#6352 [MAINTENANCE] Misc cleanup of GX Cloud helpers
  great_expectations/checkpoint/actions.py
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/config_provider.py
  great_expectations/data_context/cloud_constants.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/data_context/migrator/cloud_migrator.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/profiler_store.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/store/validations_store.py
  great_expectations/data_context/types/base.py
  great_expectations/data_context/types/refs.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/exceptions/exceptions.py
  great_expectations/render/renderer/site_builder.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/util.py
  great_expectations/validation_operators/validation_operators.py
  tests/actions/conftest.py
  tests/conftest.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/migrator/test_cloud_migrator.py
  tests/data_context/store/conftest.py
  tests/data_context/store/test_checkpoint_store.py
  tests/data_context/store/test_configuration_store.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
  tests/data_context/store/test_ge_cloud_store_backend.py
  tests/data_context/test_data_context_datasources.py
  tests/data_context/test_data_context_ge_cloud_mode.py
  tests/data_context/test_data_context_variables.py
  tests/data_context/test_get_data_context.py
  tests/rule_based_profiler/test_rule_based_profiler.py
Labels: core-team

#6350 [MAINTENANCE] Update column_reflection_fallback to also use schema name for Trino
  great_expectations/expectations/metrics/util.py
Labels: devrel

#6368 [BUGFIX] Use `requirements.txt` file when installing linting/static check dependencies in CI
  azure-pipelines-dev.yml
  azure-pipelines.yml
  great_expectations/exceptions/exceptions.py
  great_expectations/util.py
  reqs/requirements-dev-contrib.txt
Labels: core-team

#6370 [MAINTENANCE] Bump version of `black` in contrib CLI
  contrib/cli/requirements.txt
Labels: core-team

#6320 [FEATURE] POC ZEP Config Loading
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/zep/config.py
  great_expectations/zep/context.py
  great_expectations/zep/demos.py
  great_expectations/zep/fakes.py
  great_expectations/zep/interfaces.py
  great_expectations/zep/logger.py
  great_expectations/zep/metadatasource.py
  great_expectations/zep/postgres_datasource.py
  great_expectations/zep/sources.py
  great_expectations/zep/type_lookup.py
  great_expectations/zep/util.py
  pyproject.toml
  reqs/requirements-dev-contrib.txt
  requirements.txt
  scripts/check_docstring_coverage.py
  tests/zep/config.yaml
  tests/zep/conftest.py
  tests/zep/test_config.py
  tests/zep/test_metadatasource.py
  tests/zep/test_postgres_datasource.py
  tests/zep/test_type_lookup.py
Labels: core-team

#6366 Removes comment in code that was causing confusion to some users.
  great_expectations/data_context/data_context/data_context.py
Labels: devrel

#6376 [BUGFIX] Patch nested snippet indentation issues within `remark-named-snippets` plugin
  docs/scripts/remark-named-snippets/index.js
  docs/scripts/remark-named-snippets/snippet.js
  docusaurus.config.js
  package.json
Labels: core-team

#6374 [MAINTENANCE] minor metrics typing
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/metric_provider.py
  great_expectations/expectations/metrics/query_metrics/query_table.py
  great_expectations/expectations/metrics/table_metric_provider.py
  great_expectations/expectations/metrics/table_metrics/table_column_count.py
  great_expectations/expectations/metrics/table_metrics/table_column_types.py
  pyproject.toml
Labels: core-team

#6375 [MAINTENANCE] Make `ConfigurationProvider` and `ConfigurationSubstitutor` private
  great_expectations/core/config_provider.py
  great_expectations/core/config_substitutor.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context_variables.py
  tests/core/test_config_substitutor.py
  tests/data_context/abstract_data_context/test_abstract_data_context_datasource_crud.py
  tests/data_context/test_data_context_config_variables.py
  tests/data_context/test_data_context_variables.py
Labels: core-team

#6377 [MAINTENANCE] Rename `GeCloudStoreBackend` to `GXCloudStoreBackend`
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/data_context/migrator/cloud_migrator.py
  great_expectations/data_context/store/__init__.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/ge_cloud_store_backend.py
  great_expectations/data_context/store/gx_cloud_store_backend.py
  great_expectations/data_context/store/html_site_store.py
  great_expectations/data_context/store/store.py
  tests/conftest.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
  tests/data_context/conftest.py
  tests/data_context/store/conftest.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_ge_cloud_store_backend.py
  tests/data_context/store/test_gx_cloud_store_backend.py
  tests/data_context/test_data_context_datasources.py
Labels: core-team

#6371 [MAINTENANCE] Cleanup Metrics and ExecutionEngine methods
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/__init__.py
  great_expectations/expectations/metrics/column_aggregate_metric_provider.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/metric_provider.py
  pyproject.toml
  tests/execution_engine/test_execution_engine.py
  tests/execution_engine/test_pandas_execution_engine.py
  tests/execution_engine/test_sparkdf_execution_engine.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/expectations/metrics/test_core.py
  tests/expectations/metrics/test_map_metric.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_max_to_be_between_custom.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_equal_three.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_table_columns_to_be_unique.py
  tests/rule_based_profiler/data_assistant/test_data_assistant_runner.py
Labels: core-team

#6358 F/great 1314/integrate zep in core
  great_expectations/core/batch.py
  great_expectations/core/batch_manager.py
  great_expectations/core/usage_statistics/anonymizers/batch_request_anonymizer.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/validator/validator.py
  great_expectations/zep/demos.py
  great_expectations/zep/fakes.py
  great_expectations/zep/interfaces.py
  great_expectations/zep/postgres_datasource.py
  great_expectations/zep/sources.py
  tests/zep/config.yaml
  tests/zep/conftest.py
  tests/zep/test_config.py
  tests/zep/test_metadatasource.py
  tests/zep/test_postgres_datasource.py
Labels: core-team

#6384 [MAINTENANCE] Loosen `pydantic` version requirement
  contrib/cli/requirements.txt
  reqs/requirements-dev-contrib.txt
  requirements.txt
Labels: core-team

#6386 [BUGFIX] Ensure `packaging_and_installation` CI tests against latest tag
  azure/dev-install-matrix.yml
Labels: core-team

#6387 [RELEASE] 0.15.33
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team

#6362 [DOCS] DOC-379 bring spark datasource configuration example scripts under test
  docs/guides/connecting_to_your_data/datasource_configuration/filesystem_components/_section_import_necessary_modules_and_initialize_your_data_context.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/spark_components/_part_assets_configured.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/spark_components/_part_assets_inferred.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/spark_components/_part_assets_runtime.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/spark_components/_part_glob_directive_details.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/spark_components/_section_add_a_dictionary_as_the_value_of_the_data_connectors_key.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/spark_components/_section_add_the_execution_engine_to_your_datasource_configuration.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/spark_components/_section_configure_batch_spec_passthrough.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/spark_components/_tab_data_connector_example_configurations_configured.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/spark_components/_tab_data_connector_example_configurations_inferred.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/spark_components/_tab_data_connector_example_configurations_runtime.mdx
  tests/integration/docusaurus/connecting_to_your_data/datasource_configuration/datasource_configuration_test_utilities.py
  tests/integration/docusaurus/connecting_to_your_data/datasource_configuration/full_datasource_configurations.py
  tests/integration/docusaurus/connecting_to_your_data/datasource_configuration/how_to_configure_a_datasource_universal_steps.py
  tests/integration/docusaurus/connecting_to_your_data/datasource_configuration/how_to_configure_a_pandas_datasource.py
  tests/integration/docusaurus/connecting_to_your_data/datasource_configuration/how_to_configure_a_spark_datasource.py
  tests/integration/test_script_runner.py
Labels: devrel

#6378 [MAINTENANCE] move `zep` -> `experimental` package
  great_expectations/core/batch.py
  great_expectations/core/batch_manager.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/experimental/__init__.py
  great_expectations/experimental/context.py
  great_expectations/experimental/datasources/__init__.py
  great_expectations/experimental/datasources/config.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/metadatasource.py
  great_expectations/experimental/datasources/postgres_datasource.py
  great_expectations/experimental/datasources/sources.py
  great_expectations/experimental/datasources/type_lookup.py
  great_expectations/experimental/logger.py
  great_expectations/validator/validator.py
  great_expectations/zep/__init__.py
  great_expectations/zep/demos.py
  great_expectations/zep/fakes.py
  great_expectations/zep/logger.py
  tests/experimental/datasources/__init__.py
  tests/experimental/datasources/config.yaml
  tests/experimental/datasources/conftest.py
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_metadatasource.py
  tests/experimental/datasources/test_postgres_datasource.py
  tests/experimental/datasources/test_type_lookup.py
Labels: core-team

#6388 [MAINTENANCE] Migrate additional methods from `BaseDataContext` to other parts of context hierarchy
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
Labels: core-team

#6391 [BUGFIX] Fixed missing comma in pydantic constraints
  requirements.txt
Labels: community

#6396 [BUGFIX] fix pydantic dev req file entries
  contrib/cli/requirements.txt
  reqs/requirements-dev-contrib.txt
Labels: core-team

#6389 [MAINTENANCE] Make "IDDict.to_id()" serialization more efficient.
  great_expectations/core/batch.py
  great_expectations/core/id_dict.py
  great_expectations/data_context/store/database_store_backend.py
  great_expectations/data_context/store/store.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/registry.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/domain.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_container.py
  great_expectations/util.py
  tests/core/test_batch_related_objects.py
Labels: core-team

#6394 [MAINTENANCE] Remove call to verify_library_dependent_modules for pybigquery
  great_expectations/cli/datasource.py
  great_expectations/cli/v012/datasource.py
Labels: devrel

#6398 [FEATURE] ZEP Config serialize as YAML
  great_expectations/experimental/datasources/config.py
  great_expectations/experimental/datasources/postgres_datasource.py
  tests/experimental/datasources/test_config.py
Labels: core-team

#6401 [MAINTENANCE] ZEP - move yaml methods to ExperimentalBaseModel
  great_expectations/experimental/__init__.py
  great_expectations/experimental/datasources/config.py
  great_expectations/experimental/datasources/experimental_base_model.py
  great_expectations/experimental/datasources/interfaces.py
  tests/experimental/datasources/test_config.py
Labels: core-team

#6395 [MAINTENANCE] Migrate additional CRUD methods from `BaseDataContext` to `AbstractDataContext`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/migrator/configuration_bundle.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/data_context/test_data_context_profilers.py
Labels: core-team

#6405 [BUGFIX] Patch key-generation issue with `DataContext.save_profiler()`
  great_expectations/data_context/data_context/base_data_context.py
Labels: core-team

#6403 [MAINTENANCE] Migrate remaining methods from `BaseDataContext`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
Labels: core-team

#6404 [MAINTENANCE] ZEP - `GxConfig` cleanup
  great_expectations/experimental/context.py
  great_expectations/experimental/datasources/config.py
  great_expectations/experimental/datasources/experimental_base_model.py
Labels: core-team

#6406 [MAINTENANCE] Cleanup For Better Code Elegance/Readability
  great_expectations/exceptions/exceptions.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/expectations/core/expect_column_values_to_be_null.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/core/expect_table_row_count_to_equal_other_table.py
  great_expectations/expectations/expectation.py
  great_expectations/util.py
  great_expectations/validator/metrics_calculator.py
  great_expectations/validator/validation_graph.py
  great_expectations/validator/validator.py
  tests/validator/test_validation_graph.py
Labels: core-team

#5994 [FEATURE] add new metric - query template values
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_to_be_unique_with_condition.py
  great_expectations/expectations/metrics/query_metrics/__init__.py
  great_expectations/expectations/metrics/query_metrics/query_template_values.py
Labels: community

#6410 [BUGFIX] updated capitalone setup.py file
  contrib/capitalone_dataprofiler_expectations/setup.py
Labels: community

#6412 [MAINTENANCE] Implement `RendererConfiguration`
  great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py
  great_expectations/render/renderer_configuration.py
Labels: core-team

#6418 [MAINTENANCE] Clean Up Type Hints and Minor Refactoring For Better Code Elegance/Readability
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py
  great_expectations/expectations/metrics/column_aggregate_metric_provider.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_most_common_value.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_partition.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_values_between_count.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_decreasing.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_increasing.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/metric_provider.py
  great_expectations/expectations/metrics/table_metrics/table_column_count.py
  great_expectations/expectations/metrics/table_metrics/table_column_types.py
  great_expectations/expectations/metrics/table_metrics/table_columns.py
  great_expectations/expectations/metrics/table_metrics/table_head.py
  great_expectations/expectations/metrics/table_metrics/table_row_count.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/validator/metrics_calculator.py
  great_expectations/validator/validation_graph.py
  great_expectations/validator/validator.py
Labels: core-team

#6421 [MAINTENANCE] Sorting batch IDs and typehints clean up
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
Labels: core-team

#6422 [MAINTENANCE] Small refactor
  great_expectations/validator/metrics_calculator.py
Labels: core-team

#6372 [FEATURE] add multiple column metric
  contrib/experimental/great_expectations_experimental/expectations/expect_query_to_have_no_duplicate_value_combinations.py
  great_expectations/expectations/metrics/query_metrics/__init__.py
  great_expectations/expectations/metrics/query_metrics/query_multiple_columns.py
Labels: community

#6407 [DOCS] add boto3 explanations on document
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_confirm_that_the_new_validation_results_store_has_been_added_by_running_great_expectations_store_list.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_update_your_configuration_file_to_include_a_new_store_for_expectations_on_s.mdx
Labels: community

#6164 [BUGFIX] issue-4295-fix-issue
  great_expectations/data_asset/data_asset.py
  tests/dataset/test_pandas_dataset.py
  tests/dataset/test_pandas_dataset_conditionals.py
Labels: community

#6442 Add metadata to experimental datasource Batch class
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/postgres_datasource.py
  tests/experimental/datasources/test_postgres_datasource.py
Labels: core-team

#6443 [MAINTENANCE] Update and Simplify Pandas tests for MapMetrics
  tests/expectations/metrics/test_map_metric.py
Labels: core-team

#6444 [MAINTENANCE] Clean Up Variable Names In Test Modules, Type Hints, and Minor Refactoring For Better Code Elegance/Readability
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/validator/metrics_calculator.py
  great_expectations/validator/validation_graph.py
  great_expectations/validator/validator.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/rule_based_profiler/parameter_builder/test_histogram_single_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_mean_table_columns_set_match_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_regex_pattern_string_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_simple_date_format_string_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_value_counts_single_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_value_set_multi_batch_parameter_builder.py
  tests/validator/test_validation_graph.py
Labels: core-team

#6425 [CONTRIB] Add number of unique values expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_to_have_n_distinct_values_with_condition.py
Labels: community

#6429 [CONTRIB] Feature/add two tables expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_values_to_exist_in_second_table_column.py
Labels: community

#6432 [CONTRIB] Add no days missing expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_to_have_no_days_missing.py
Labels: community

#6433 [CONTRIB] add expectation - check gaps in SCD tables
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_slowly_changing_table_to_have_no_gaps.py
Labels: community

#6373 [FEATURE] add multiple input metric
  contrib/experimental/great_expectations_experimental/expectations/expect_query_count_with_filter_to_meet_threshold.py
Labels: community

#6449 [BUGFIX] Fix for `mssql` tests that depend on `datetime` to `string` conversion
  tests/render/test_render_BulletListContentBlock.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_informed.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_informed_mssql.json
Labels: core-team

#6293 [DOCS] add configuration of anonymous_usage_statistics for documentati…
  docs/deployment_patterns/how_to_use_great_expectations_in_emr_serverless.md
  tests/integration/docusaurus/deployment_patterns/aws_emr_serverless_deployment_patterns_great_expectations.yaml
Labels: DevRel Triage, community, devrel

#6392 [BUGFIX] Metrics return value no longer returns None for `unexpected_index_list` - Sql and Spark
  great_expectations/expectations/expectation.py
  tests/expectations/metrics/test_map_metric.py
  tests/expectations/test_expectation_arguments.py
  tests/test_sets/metrics_test.db
Labels: core-team

#6454 [MAINTENANCE] Remove yaml user_flow_scripts
  tests/integration/test_script_runner.py
Labels: core-team

#6457 [MAINTENANCE] Bump ubuntu version in CI
  azure-pipelines-dev.yml
  azure-pipelines.yml
Labels: core-team

#6446 [CONTRIB] Multicolumns sum equal to single column
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_sum_values_to_be_equal_to_single_column.py
Labels: community

#6456 Add sorters to zep postgres datasource.
  great_expectations/experimental/datasources/postgres_datasource.py
  tests/experimental/datasources/test_postgres_datasource.py
Labels: core-team
