Repository great-expectations/great_expectations, pull requests merged in 2023-03, with the labels that each got.

#7254 [FEATURE] Develop PandasAzureBlobStorageDatasource (as part of New Datasources)
  great_expectations/experimental/datasources/__init__.py
  great_expectations/experimental/datasources/pandas_azure_blob_storage_datasource.py
  great_expectations/experimental/datasources/pandas_filesystem_datasource.py
  great_expectations/experimental/datasources/pandas_google_cloud_storage_datasource.py
  great_expectations/experimental/datasources/pandas_s3_datasource.py
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource.json
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource/CSVAsset.json
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource/ExcelAsset.json
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource/FeatherAsset.json
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource/HDFAsset.json
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource/HTMLAsset.json
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource/JSONAsset.json
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource/ORCAsset.json
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource/ParquetAsset.json
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource/PickleAsset.json
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource/SPSSAsset.json
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource/STATAAsset.json
  great_expectations/experimental/datasources/schemas/PandasAzureBlobStorageDatasource/XMLAsset.json
  great_expectations/experimental/datasources/spark_filesystem_datasource.py
  great_expectations/experimental/datasources/spark_s3_datasource.py
  tests/experimental/datasources/test_pandas_azure_blob_storage_datasource.py
  tests/experimental/datasources/test_pandas_google_cloud_storage_datasource.py
Labels: core-team, platform

#7224 [CONTRIB] expect_multicolumn_sum_values_to_be_equal_to_single_column
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_sum_values_to_be_between.py
Labels: community

#7259 [MAINTENANCE] Fix linting errors in `contrib/`
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_sum_values_to_be_between.py
Labels: core-team, platform

#7252 [CONTRIB][BUGFIX] Update custom multi-column expectation logic and default kwargs
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_values_not_to_be_all_null.py
Labels: community

#7255 [FEATURE] Develop SparkGoogleCloudStorageDatasource SparkAzureBlobStorageDatasource (as part of New Datasources)
  great_expectations/experimental/datasources/__init__.py
  great_expectations/experimental/datasources/pandas_azure_blob_storage_datasource.py
  great_expectations/experimental/datasources/pandas_google_cloud_storage_datasource.py
  great_expectations/experimental/datasources/pandas_s3_datasource.py
  great_expectations/experimental/datasources/schemas/SparkAzureBlobStorageDatasource.json
  great_expectations/experimental/datasources/schemas/SparkAzureBlobStorageDatasource/CSVAsset.json
  great_expectations/experimental/datasources/schemas/SparkGoogleCloudStorageDatasource.json
  great_expectations/experimental/datasources/schemas/SparkGoogleCloudStorageDatasource/CSVAsset.json
  great_expectations/experimental/datasources/spark_azure_blob_storage_datasource.py
  great_expectations/experimental/datasources/spark_google_cloud_storage_datasource.py
  great_expectations/experimental/datasources/spark_s3_datasource.py
  tests/experimental/datasources/test_spark_azure_blob_storage_datasource.py
  tests/experimental/datasources/test_spark_google_cloud_storage_datasource.py
Labels: core-team, platform

#7260 [MAINTENANCE] Keep repo root consistent
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines.yml
  scripts/check_repo_root_size.sh
Labels: core-team, dx

#7261 [BUGFIX] `params_with_json_schema` is undefined in `ExpectSelectColumnValuesToBeUniqueWithinRecord._prescriptive_renderer`
  great_expectations/expectations/core/expect_select_column_values_to_be_unique_within_record.py
Labels: core-team, platform

#7262 [MAINTENANCE] Threshold for public API report
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs-integration.yml
  ci/azure-pipelines.yml
  scripts/public_api_report.py
Labels: core-team, dx

#7242 [BUGFIX] Patch Cloud workflow for `add_or_update_datasource`
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/test_data_context_test_yaml_config.py
Labels: core-team, platform

#7264 [DOCS] Fix hyperlinks in docs
  docs/docusaurus/docs/changelog.md
  docs_rtd/changelog.rst
Labels: core-team, platform

#7267 [DOCS] Scan yaml examples for class names that should be part of the public API
  scripts/public_api_report.py
  tests/scripts/test_public_api_report.py
Labels: core-team, dx

#7266 [MAINTENANCE] Update the signature of Fluent datasource factory methods
  great_expectations/experimental/datasources/metadatasource.py
  great_expectations/experimental/datasources/signatures.py
  great_expectations/experimental/datasources/sources.py
  tests/experimental/datasources/test_metadatasource.py
Labels: core-team, platform

#7269 [BUGFIX] Stop modifying input batch request when getting a batch list.
  great_expectations/experimental/datasources/file_path_data_asset.py
  tests/experimental/datasources/test_spark_filesystem_datasource.py
Labels: core-team, platform

#7271 [MAINTENANCE] Move some scripts into ci folder
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs-integration.yml
  ci/azure-pipelines.yml
  ci/checks/check_for_docs_deps_changes.sh
  ci/checks/check_no_line_number_snippets.py
  ci/checks/check_repo_root_size.sh
  ci/checks/validate_docs_snippets.py
Labels: core-team, dx

#7258 [MAINTENANCE] `_PandasDataAsset` positional argument support
  great_expectations/experimental/datasources/pandas_datasource.py
  scripts/public_api_report.py
  tests/experimental/datasources/integration/conftest.py
  tests/experimental/datasources/test_pandas_datasource.py
Labels: core-team, platform

#7268 [MAINTENANCE] Refactor to utilize common DataConnector instantiation and Connection Test Error Message templates for New FilePath Datasources
  great_expectations/experimental/datasources/data_asset/data_connector/azure_blob_storage_data_connector.py
  great_expectations/experimental/datasources/data_asset/data_connector/filesystem_data_connector.py
  great_expectations/experimental/datasources/data_asset/data_connector/google_cloud_storage_data_connector.py
  great_expectations/experimental/datasources/data_asset/data_connector/s3_data_connector.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_azure_blob_storage_datasource.py
  great_expectations/experimental/datasources/pandas_filesystem_datasource.py
  great_expectations/experimental/datasources/pandas_google_cloud_storage_datasource.py
  great_expectations/experimental/datasources/pandas_s3_datasource.py
  great_expectations/experimental/datasources/spark_azure_blob_storage_datasource.py
  great_expectations/experimental/datasources/spark_filesystem_datasource.py
  great_expectations/experimental/datasources/spark_google_cloud_storage_datasource.py
  great_expectations/experimental/datasources/spark_s3_datasource.py
  tests/experimental/datasources/data_asset/data_connector/test_s3_data_connector.py
Labels: core-team, platform

#7272 [MAINTEANCE] Merge `PandasDatasource` read method signatures with associated `_PandasDataAsset`s
  great_expectations/experimental/datasources/pandas_datasource.py
Labels: core-team, platform

#7238 [CONTRIB] Feature/expect column values to match thai
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_thai.py
Labels: community

#7270 [MAINTENANCE] Use ruff linting on scripts folder
  .pre-commit-config.yaml
  pyproject.toml
  scripts/build_api_docs.py
  scripts/check_public_api_docstrings.py
Labels: core-team, dx

#7277 [BUGFIX] Single dynamic pandas model failures don't result in all models failing when used
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/pandas_file_path_datasource.py
Labels: core-team, platform

#7279 [DOCS] Fix reference to M1 Mac installation guide
  docs/docusaurus/docs/guides/setup/installation/components_local/_preface.mdx
Labels: core-team, platform

#7274 [MAINTENANCE] Add maybe imports
  great_expectations/experimental/datasources/sql_datasource.py
  great_expectations/util.py
  tests/test_not_imported.py
Labels: core-team, platform

#7282 [DOCS] Remove additional warnings from API docs build.
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
Labels: core-team, dx

#7281 [MAINTENANCE] Proper mocking of AbstractDataContext for testing
  great_expectations/checkpoint/checkpoint.py
  tests/checkpoint/test_checkpoint.py
Labels: core-team, platform

#7283 [MAINTENANCE] Warn if sqlalchemy version is >= 2.0.0
  great_expectations/data_context/store/database_store_backend.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/optional_imports.py
Labels: core-team, dx

#7273 [FEATURE] Editor support for Fluent Datasources dynamic `.add_<DS_TYPE>()` methods
  great_expectations/experimental/datasources/__init__.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/pandas_file_path_datasource.py
  great_expectations/experimental/datasources/sources.py
  great_expectations/experimental/datasources/sources.pyi
  tests/experimental/datasources/integration/conftest.py
  tests/experimental/datasources/test_pandas_datasource.py
  tests/experimental/datasources/test_pandas_filesystem_datasource.py
Labels: core-team, platform, zep

#7291 [BUGFIX] Fix typographical error in type used in "isinstance()" comparison in BatchManager (was generating "must be formal [...] Batch" warning erroneously)
  great_expectations/core/batch.py
  great_expectations/core/batch_manager.py
Labels: core-team, platform

#7288 [DOCS] Fix blog links in `parse_strings_as_datetimes` warnings
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_max.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_min.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_between.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_decreasing.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_in_set.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_increasing.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_not_in_set.py
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_greater.py
  great_expectations/warnings.py
  tests/test_deprecation.py
Labels: core-team, dx

#7293 [MAINTENANCE] Call the correct sqlalchemy method to eliminate deprecation warning
  great_expectations/data_context/store/query_store.py
  great_expectations/optional_imports.py
  tests/data_context/store/test_query_store.py
Labels: core-team, dx

#7278 [MAINTENANCE] Fluent Datasources - initial snippet tests
  great_expectations/datasource/fluent/pandas_filesystem_datasource.py
  great_expectations/datasource/fluent/schemas/PandasFilesystemDatasource.json
  great_expectations/datasource/fluent/sources.py
  scripts/public_api_report.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_one_or_more_files_using_pandas.py
  tests/integration/test_script_runner.py
Labels: core-team, platform, zep

#7290 [MAINTENANCE] add `ruff` `PTH` `use-pathlib` `# noqa` comments
  docs_rtd/conf.py
  great_expectations/_version.py
  great_expectations/cli/checkpoint.py
  great_expectations/cli/datasource.py
  great_expectations/cli/init.py
  great_expectations/cli/python_subprocess.py
  great_expectations/cli/suite.py
  great_expectations/cli/upgrade_helpers/upgrade_helper_v11.py
  great_expectations/cli/upgrade_helpers/upgrade_helper_v13.py
  great_expectations/cli/v012/checkpoint.py
  great_expectations/cli/v012/datasource.py
  great_expectations/cli/v012/init.py
  great_expectations/cli/v012/python_subprocess.py
  great_expectations/cli/v012/suite.py
  great_expectations/core/config_provider.py
  great_expectations/data_asset/file_data_asset.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/data_context/serializable_data_context.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/html_site_store.py
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/datasource/batch_kwargs_generator/glob_reader_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/query_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/s3_subdir_reader_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/subdir_reader_batch_kwargs_generator.py
  great_expectations/datasource/data_connector/util.py
  great_expectations/expectations/expectation.py
  great_expectations/render/renderer/page_renderer.py
  great_expectations/render/renderer/site_builder.py
  great_expectations/render/renderer/suite_edit_notebook_renderer.py
  great_expectations/self_check/util.py
  great_expectations/util.py
  scripts/docs_link_checker.py
  scripts/trace_docs_deps.py
  tasks.py
  tests/conftest.py
  tests/core/test_yaml_handler.py
  tests/core/usage_statistics/test_usage_statistics.py
  tests/profile/conftest.py
  tests/profile/test_basic_suite_builder_profiler.py
  tests/profile/test_profile.py
  tests/render/conftest.py
  tests/render/renderer/test_checkpoint_new_notebook_renderer.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/render/renderer/test_suite_scaffold_notebook_renderer.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/render/test_data_documentation_site_builder.py
  tests/render/test_default_markdown_view.py
  tests/render/test_render_BulletListContentBlock.py
  tests/test_dataset_implementations/test_dataset_implementations.py
  tests/test_definitions/test_expectations_v2_api.py
  tests/test_definitions/test_expectations_v3_api.py
  tests/test_ge_utils.py
  tests/test_great_expectations.py
  tests/test_utils.py
  tests/validator/test_validator.py
Labels: core-team, platform

#7296 [MAINTENANCE] Enable SparkDatasource add_asset() methods to accept "header" and "infer_schema" arguments; fix typos in docstrings.
  great_expectations/core/batch.py
  great_expectations/datasource/fluent/data_asset/data_connector/data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/file_path_data_connector.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/spark_google_cloud_storage_datasource.py
  tests/datasource/fluent/data_asset/data_connector/test_azure_blob_storage_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_filesystem_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_google_cloud_storage_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_s3_data_connector.py
  tests/datasource/fluent/test_pandas_filesystem_datasource.py
Labels: core-team, platform

#7299 [MAINTENANCE] Replace fluent data connector names with a constant
  great_expectations/datasource/fluent/constants.py
  great_expectations/datasource/fluent/data_asset/data_connector/file_path_data_connector.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/sql_datasource.py
Labels: core-team, platform

#7300 [MAINTENANCE] Apply ruff path rules for contrib
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_between_exclusive_threshold_range.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_between_inclusive_threshold_range.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_greater_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_greater_than_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_less_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_less_than_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_between_exclusive_threshold_range.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_between_inclusive_threshold_range.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_greater_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_greater_than_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_less_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_less_than_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/conftest.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/expectations/metrics/test_core.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/rule_based_profiler/data_assistant/test_data_profiler_structured_data_assistant.py
  contrib/cli/great_expectations_contrib/cli.py
  contrib/cli/great_expectations_contrib/commands.py
  contrib/cli/great_expectations_contrib/package.py
  contrib/experimental/great_expectations_experimental/expectations/__init__.py
  contrib/experimental/great_expectations_experimental/metrics/__init__.py
  contrib/experimental/great_expectations_experimental/tests/rule_based_profiler/data_assistant/test_growth_numeric_data_assistant.py
  contrib/experimental/great_expectations_experimental/tests/rule_based_profiler/data_assistant/test_statistics_data_assistant.py
  contrib/experimental/great_expectations_experimental/tests/test_utils.py
  contrib/experimental/setup.py
  contrib/ruff.toml
  contrib/time_series_expectations/assets/generate_test_time_series_data.py
Labels: core-team, dx

#7302 [BUGFIX] Correct a typographical error in specific path-forming template name for SparkDatasource-Microsoft Azure Blob Storage combination
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.py
Labels: core-team, platform

#7303 [MAINTENANCE] Rename column splitter to splitter.
  great_expectations/datasource/fluent/schemas/PostgresDatasource.json
  great_expectations/datasource/fluent/schemas/PostgresDatasource/QueryAsset.json
  great_expectations/datasource/fluent/schemas/PostgresDatasource/TableAsset.json
  great_expectations/datasource/fluent/schemas/SQLDatasource.json
  great_expectations/datasource/fluent/schemas/SQLDatasource/QueryAsset.json
  great_expectations/datasource/fluent/schemas/SQLDatasource/TableAsset.json
  great_expectations/datasource/fluent/schemas/SqliteDatasource.json
  great_expectations/datasource/fluent/schemas/SqliteDatasource/SqliteQueryAsset.json
  great_expectations/datasource/fluent/schemas/SqliteDatasource/SqliteTableAsset.json
  great_expectations/datasource/fluent/sql_datasource.py
  great_expectations/datasource/fluent/sqlite_datasource.py
  tests/datasource/fluent/great_expectations.yml
  tests/datasource/fluent/integration/test_integration_datasource.py
  tests/datasource/fluent/test_config.py
  tests/datasource/fluent/test_postgres_datasource.py
  tests/datasource/fluent/test_sqlite_datasource.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core-team, platform

#7244 [BUGFIX] Use timezone-aware datetimes in checkpoint run information by default.
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/run_identifier.py
  great_expectations/data_context/types/base.py
  great_expectations/render/renderer/microsoft_teams_renderer.py
  tests/render/test_microsoft_teams_renderer.py
Labels: core-team

#7307 [MAINTENANCE] Add build docs to block PR pipeline
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines.yml
  great_expectations/datasource/fluent/pandas_filesystem_datasource.py
Labels: core-team, dx

#7308 [MAINTENANCE] Linting for `tests/datasource`
  pyproject.toml
  tests/datasource/batch_kwarg_generator/test_query_generator.py
  tests/datasource/batch_kwarg_generator/test_s3_subdir_reader_generator.py
  tests/datasource/batch_kwarg_generator/test_subdir_reader_generator.py
  tests/datasource/conftest.py
  tests/datasource/data_connector/sorters/test_sorting.py
  tests/datasource/data_connector/test_configured_asset_filesystem_data_connector.py
  tests/datasource/data_connector/test_configured_asset_glue_catalog_data_connector.py
  tests/datasource/data_connector/test_configured_asset_s3_data_connector.py
  tests/datasource/data_connector/test_data_connector.py
  tests/datasource/data_connector/test_data_connector_query_filesystem.py
  tests/datasource/data_connector/test_data_connector_query_sql.py
  tests/datasource/data_connector/test_inferred_asset_azure_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_dbfs_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_filesystem_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_glue_catalog_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_s3_data_connector.py
  tests/datasource/data_connector/test_runtime_data_connector.py
  tests/datasource/data_connector/test_sql_data_connector.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/integration/integration_test_utils.py
  tests/datasource/fluent/test_metadatasource.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/datasource/fluent/test_postgres_datasource.py
  tests/datasource/test_batch_generators.py
  tests/datasource/test_batch_kwargs.py
  tests/datasource/test_datasource_config_ui.py
  tests/datasource/test_new_datasource.py
  tests/datasource/test_new_datasource_with_aws_glue_data_connector.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_pandas_execution_engine.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_sparkdf_execution_engine.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_sql_execution_engine.py
  tests/datasource/test_new_datasource_with_sql_data_connector.py
  tests/datasource/test_pandas_datasource.py
  tests/datasource/test_sparkdf_datasource.py
  tests/datasource/test_sqlalchemy_datasource.py
Labels: core-team, platform

#7310 [DOCS] Fix unsupported chars in API docs
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/pandas_filesystem_datasource.py
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/pandas_s3_datasource.py
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/spark_filesystem_datasource.py
  great_expectations/datasource/fluent/spark_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/spark_s3_datasource.py
Labels: core-team, dx

#7312 [MAINTENANCE] Elide Duplication of "name" Key from Fluent Datasource and DataAsset Configuration
  great_expectations/datasource/fluent/config.py
  tests/datasource/fluent/great_expectations.yml
  tests/datasource/fluent/test_config.py
Labels: core-team, platform

#7313 [BUGFIX] `row_conditions` now allow whitespace
  great_expectations/expectations/row_conditions.py
  tests/expectations/test_row_conditions.py
Labels: core-team, dx

#7304 Remove nonexistent pypi ref in README. Add WIP warning in README.
  contrib/time_series_expectations/README.md
Labels: core-team

#7306 [BUGFIX] Scope `PandasDatasource` reader method types and serialization (1 of 2)
  docs/sphinx_api_docs_source/public_api_report.py
  great_expectations/core/batch_spec.py
  great_expectations/core/util.py
  great_expectations/datasource/fluent/constants.py
  great_expectations/datasource/fluent/fluent_base_model.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/sources.py
  great_expectations/datasource/new_datasource.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/validator/validator.py
  tests/datasource/fluent/integration/conftest.py
  tests/datasource/fluent/integration/integration_test_utils.py
  tests/datasource/fluent/test_pandas_filesystem_datasource.py
Labels: core-team, platform

#7285 [BUGFIX] AssertError Duing Great Expectations Installation
  setup.py
Labels: community

#7317 [MAINTENANCE] Update allowed deprecation warning threshold in advance of `0.16.0`
  tests/test_deprecation.py
Labels: core-team, platform

#7320 [BUGFIX] Provide Error Checking for "expectation_suite_name" in Checkpoint Constructor and Run Methods
  great_expectations/checkpoint/checkpoint.py
  tests/checkpoint/test_checkpoint.py
Labels: core-team, platform

#7315 [MAINTENANCE] Fluent Datasource stubs for dynamic Pandas add_asset methods
  great_expectations/datasource/fluent/__init__.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.pyi
  great_expectations/datasource/fluent/pandas_file_path_datasource.pyi
  great_expectations/datasource/fluent/pandas_filesystem_datasource.pyi
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.pyi
  great_expectations/datasource/fluent/pandas_s3_datasource.pyi
  scripts/gen_stub.py
  tests/datasource/fluent/integration/conftest.py
  tests/datasource/fluent/test_pandas_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_pandas_filesystem_datasource.py
  tests/datasource/fluent/test_pandas_google_cloud_storage_datasource.py
  tests/datasource/fluent/test_pandas_s3_datasource.py
Labels: core-team, platform

#7322 [MAINTENANCE] Stub files for Fluent `PandasDatasource` and `py.typed`
  great_expectations/datasource/fluent/pandas_datasource.pyi
  great_expectations/py.typed
  scripts/gen_stub.py
  setup.py
  tests/datasource/fluent/test_pandas_datasource.py
Labels: core-team, platform

#7318 [BUGFIX] Scope `PandasDatasource` reader method types and serialization (2 of 2)
  great_expectations/datasource/fluent/dynamic_pandas.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/pandas_datasource.pyi
  great_expectations/datasource/fluent/schemas/PandasDatasource/CSVAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/ExcelAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/FeatherAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/HDFAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/HTMLAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/JSONAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/ORCAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/ParquetAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/PickleAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/SPSSAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/STATAAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/TableAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/XMLAsset.json
  great_expectations/datasource/fluent/sources.py
Labels: core-team, platform

#7321 [BUGFIX] raise error if no identifier provided to get checkpoint/expectation suite
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  tests/cli/conftest.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
Labels: community

#7326 [DOCS] Add instructions to cli for creating data assets
  great_expectations/cli/batch_request.py
  tests/cli/test_batch_request.py
Labels: core-team, dx

#7323 [BUGFIX] Fluent Datasources: Ensure that Datasource and DataAsset Model Serialization Does Not Include `"name"` Field
  docs/sphinx_api_docs_source/public_api_report.py
  great_expectations/datasource/fluent/config.py
  great_expectations/datasource/fluent/fluent_base_model.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.pyi
  great_expectations/datasource/fluent/pandas_filesystem_datasource.pyi
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.pyi
  great_expectations/datasource/fluent/pandas_s3_datasource.pyi
  tests/datasource/fluent/test_config.py
Labels: core-team, platform

#7329 [RELEASE] 0.16.0
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#7332 [MAINTENANCE] In Fluent Datasources: Configuration Serialization Methods Do Not Need to be Public
  docs/sphinx_api_docs_source/public_api_report.py
  great_expectations/datasource/fluent/config.py
  great_expectations/datasource/fluent/fluent_base_model.py
Labels: core-team, platform

#7314 [DOCS] Adding ADR
  docs/.adr-dir
  docs/adr/0001-record-architecture-decisions.md
  great_expectations/core/usage_statistics/package_dependencies.py
  reqs/requirements-dev-contrib.txt
Labels: core-team

#7328 Add crud methods to context.sources
  docs/sphinx_api_docs_source/public_api_report.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/datasource/fluent/metadatasource.py
  great_expectations/datasource/fluent/sources.py
  great_expectations/datasource/fluent/sources.pyi
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_metadatasource.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core-team, platform

#7331 [MAINTENANCE] Split out mysql and multi db docs integration tests into a separate job
  ci/azure-pipelines-docs-integration.yml
  tests/integration/backend_dependencies.py
  tests/integration/db/multiple_db/__init__.py
  tests/integration/db/multiple_db/integration_tests.py
  tests/integration/db/mysql/__init__.py
  tests/integration/db/mysql/integration_tests.py
  tests/integration/docusaurus/connecting_to_your_data/database/mysql_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/mysql_yaml_example.py
  tests/integration/integration_test_fixture.py
  tests/integration/test_script_runner.py
Labels: core-team, dx

#7340 [MAINTENANCE ] Include all `.pyi` files in package data
  setup.py
Labels: core-team, platform

#7342 [MAINTENANCE] Separate docs_integrations tests by backend
  ci/azure-pipelines-docs-integration.yml
  tests/integration/backend_dependencies.py
  tests/integration/db/multiple_db/integration_tests.py
  tests/integration/test_definitions/__init__.py
  tests/integration/test_definitions/multiple_db/__init__.py
  tests/integration/test_definitions/multiple_db/integration_tests.py
  tests/integration/test_definitions/mysql/__init__.py
  tests/integration/test_definitions/mysql/integration_tests.py
  tests/integration/test_definitions/postgresql/__init__.py
  tests/integration/test_definitions/postgresql/integration_tests.py
  tests/integration/test_script_runner.py
Labels: core-team, dx

#7336 [BUGFIX] Ensure Correct JSON and Dictionary Dump Output of Serialized Fluent Objects
  docs/sphinx_api_docs_source/public_api_report.py
  great_expectations/datasource/fluent/config.py
  tests/datasource/fluent/test_config.py
Labels: core-team, platform

#7333 [DOCS] Add Cloud onboarding tutorial
  docs/gx_cloud/tutorials/getting_started/getting_started_with_gx_cloud.md
Labels: core-team

#7341 [BUGFIX] Fluent Datasources - empty "assets" key on serialization
  great_expectations/datasource/fluent/constants.py
  great_expectations/datasource/fluent/fluent_base_model.py
  great_expectations/datasource/fluent/interfaces.py
  tests/datasource/fluent/test_config.py
  tests/datasource/fluent/test_metadatasource.py
Labels: core-team, platform

#7327 [BUGFIX] Use Path().glob Instead of Path(). Issue #7239
  setup.py
Labels: community

#7348 [DOCS] Fix onboarding cloud tutorial
  docs/docusaurus/docs/gx_cloud/tutorials/getting_started/getting_started_with_gx_cloud.md
Labels: community

#7347 [FEATURE] Fluent CRUD operation stubs
  great_expectations/datasource/fluent/sources.py
  great_expectations/datasource/fluent/sources.pyi
  scripts/gen_stub.py
Labels: core-team, platform

#7351 [MAINTENANCE] Update test around unneeded deprecation warning threshold
  tests/test_deprecation.py
Labels: core-team, platform

#7292 [DOCS] SQL Alchemy 2 Warnigns
  docs/docusaurus/docs/components/warnings/_sql_alchemy2.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/components/_connection_string_athena.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/components/_datasource_redshift_configuration.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/components/_redshift_dependencies.md
  docs/docusaurus/docs/guides/connecting_to_your_data/datasource_configuration/how_to_configure_a_sql_datasource.md
  docs/docusaurus/yarn.lock
  docs/yarn.lock
Labels: devrel

#7346 [DOCS] Add lakeFS as a data versioning tool
  docs/intro.md
Labels: community

#7349 [MAINTENANCE] ruff 0.0.255
  .pre-commit-config.yaml
  contrib/cli/requirements.txt
  great_expectations/core/util.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_sampler.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_splitter.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/row_conditions.py
  reqs/requirements-dev-contrib.txt
Labels: core-team, platform

#7350 [MAINTENANCE] add sqla deps to type-checking CI step
  great_expectations/core/config_substitutor.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/self_check/util.py
  requirements-types.txt
Labels: core-team, platform

#7356 [MAINTENANCE] Remove deprecated code around `generator_asset`
  great_expectations/cli/v012/toolkit.py
  great_expectations/datasource/batch_kwargs_generator/batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/glob_reader_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/manual_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/query_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/s3_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/s3_subdir_reader_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/subdir_reader_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/table_batch_kwargs_generator.py
  tests/test_deprecation.py
Labels: core-team, platform

#7363 [MAINTENANCE] Revert accidental changes pushed to `develop`
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  tests/data_context/store/test_configuration_store.py
Labels: core-team, platform

#7362 D/sql alchemy 2 warnings
  docs/docusaurus/docs/guides/connecting_to_your_data/database/mssql.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/mysql.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/postgres.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/snowflake.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/sqlite.md
Labels: devrel

#7364 [DOCS] Update Cloud Getting Started Guide
  docs/gx_cloud/tutorials/getting_started/getting_started_with_gx_cloud.md
Labels: core-team

#7352 [MAINTENANCE] Warnings are errors + Suppress warnings in preparation for supporting SQLAlchemy 2.x
  ci/azure-pipelines-dev.yml
  pyproject.toml
  tests/integration/usage_statistics/test_usage_stats_common_messages_are_sent_v3api.py
  tests/render/test_render.py
Labels: core-team, dx

#7360 [MAINTENANCE] Rename misc internal uses of `ge_cloud_id`
  great_expectations/checkpoint/actions.py
  great_expectations/checkpoint/checkpoint.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/gx_cloud_store_backend.py
  great_expectations/data_context/types/refs.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/render/renderer/site_builder.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  great_expectations/validation_operators/validation_operators.py
  tests/actions/conftest.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/store/test_checkpoint_store.py
  tests/data_context/store/test_configuration_store.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
  tests/data_context/test_base_data_context.py
Labels: core-team, platform

#7355 [FEATURE] Implement DataBricks (DBFS) DataConnector for Fluent Datasources needs
  great_expectations/core/util.py
  great_expectations/datasource/data_connector/file_path_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/__init__.py
  great_expectations/datasource/fluent/data_asset/data_connector/azure_blob_storage_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/dbfs_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/filesystem_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/google_cloud_storage_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/s3_data_connector.py
  tests/core/test_util.py
  tests/datasource/fluent/data_asset/data_connector/test_dbfs_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_filesystem_data_connector.py
Labels: core-team, platform

#7371 [BUGFIX] Patch misc errors in advance of v0.16.1 release
  tests/data_context/cloud_data_context/test_include_rendered_content.py
Labels: core-team, platform

#7367 [BUGFIX] `#ephemeral_data_asset` broken data docs links
  great_expectations/data_context/store/_store_backend.py
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/render/renderer/page_renderer.py
  great_expectations/render/renderer/site_builder.py
  tests/data_context/store/test_store_backends.py
Labels: core-team, platform

#7375 [MAINTENANCE] Add additional warning ignores to pyproject.toml
  pyproject.toml
Labels: core-team, platform

#7370 [MAINTENANCE] Enable `snowflake` V3 Expectations Tests
  ci/azure-pipelines-cloud-integration.yml
  great_expectations/self_check/util.py
  tests/test_definitions/column_aggregate_expectations/expect_column_max_to_be_between.json
  tests/test_definitions/column_aggregate_expectations/expect_column_mean_to_be_between.json
  tests/test_definitions/column_aggregate_expectations/expect_column_stdev_to_be_between.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between__evaluation_parameters.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_informed.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_naive.json
  tests/test_definitions/column_pair_map_expectations/expect_column_pair_values_to_be_equal.json
  tests/test_definitions/column_pair_map_expectations/expect_column_pair_values_to_be_in_set.json
  tests/test_definitions/test_expectations_v3_api.py
Labels: core-team, dx

#7382 [MAINTENANCE] Temporarily disable warnings as errors for v0.16.1 release
  pyproject.toml
Labels: core-team, platform

#7381 [BUGFIX] Add FluentBatchRequest early exit to convert_to_json_serializable
  great_expectations/core/util.py
  tests/datasource/fluent/integration/test_integration_datasource.py
Labels: core-team, platform

#7379 [MAINTENANCE] Make sure sqlalchemy 2.0 warnings are emitted when running pipelines
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines.yml
  pyproject.toml
Labels: core-team, dx

#7389 [MAINTENANCE] Make sure all existing warnings are ignored in full CI pipeline
  pyproject.toml
Labels: core-team, dx

#7391 [DOCS] Add back GX logo to README
  README.md
Labels: core-team, platform

#7393 [BUGFIX] Fix bug with case sensitive execution env
  great_expectations/core/usage_statistics/execution_environment.py
  great_expectations/core/usage_statistics/package_dependencies.py
  tests/core/usage_statistics/test_package_dependencies.py
Labels: core-team, dx

#7387 [FEATURE] Make SQL datasources add asset methods public.
  great_expectations/datasource/fluent/postgres_datasource.py
  great_expectations/datasource/fluent/schemas/PostgresDatasource.json
  great_expectations/datasource/fluent/schemas/SQLDatasource.json
  great_expectations/datasource/fluent/schemas/SqliteDatasource.json
  great_expectations/datasource/fluent/sql_datasource.py
  great_expectations/datasource/fluent/sqlite_datasource.py
Labels: core-team, platform

#7365 [MAINTENANCE] Add PR title checker GitHub Action
  .github/workflows/pr-title-checker.yml
Labels: core-team, platform

#7383 [MAINTENANCE] Re-enable warnings as errors
  pyproject.toml
Labels: core-team, platform

#7398 [BUGFIX] Fixing typographical errors and argument omissions
  great_expectations/datasource/fluent/spark_dbfs_datasource.py
  tests/datasource/fluent/test_spark_dbfs_datasource.py
Labels: core-team, platform

#7396 [MAINTENANCE] Test against minimum SQLAlchemy versions
  ci/azure-pipelines-sqlalchemy-compatibility.yml
  pyproject.toml
Labels: core-team, dx

#7402 [MAINTENANCE] : split up map_metric_provider.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/map_metric_provider/__init__.py
  great_expectations/expectations/metrics/map_metric_provider/column_condition_partial.py
  great_expectations/expectations/metrics/map_metric_provider/column_function_partial.py
  great_expectations/expectations/metrics/map_metric_provider/column_map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/map_metric_provider/column_map_metric_provider.py
  great_expectations/expectations/metrics/map_metric_provider/column_pair_condition_partial.py
  great_expectations/expectations/metrics/map_metric_provider/column_pair_function_partial.py
  great_expectations/expectations/metrics/map_metric_provider/column_pair_map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/map_metric_provider/column_pair_map_metric_provider.py
  great_expectations/expectations/metrics/map_metric_provider/is_sqlalchemy_metric_selectable.py
  great_expectations/expectations/metrics/map_metric_provider/map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/map_metric_provider/map_metric_provider.py
  great_expectations/expectations/metrics/map_metric_provider/multicolumn_condition_partial.py
  great_expectations/expectations/metrics/map_metric_provider/multicolumn_function_partial.py
  great_expectations/expectations/metrics/map_metric_provider/multicolumn_map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/map_metric_provider/multicolumn_map_metric_provider.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/compound_columns_unique.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/multicolumn_sum_equal.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/select_column_values_unique_within_record.py
  pyproject.toml
  tests/expectations/metrics/test_map_metric.py
Labels: core-team

#7403 [CONTRIB] Limit results for two expectations
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_to_be_unique_with_condition.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_to_have_n_distinct_values_with_condition.py
Labels: community

#7409 [DOCS] DOC-473 Adds guide "How to set up GX to work with SQL databases"
  docs/docusaurus/docs/guides/setup/optional_dependencies/sql_databases/how_to_setup_gx_to_work_with_sql_databases.md
Labels: devrel

#7377 updates to quickstart, to create working code
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_quickly_connect_to_a_single_file_with_pandas.md
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
Labels: core-team

#7384 [MAINTENANCE] Change for `connection.execute()` for SQLAlchemy 2 compatibility
  assets/partners/anthonydb/just_connect.py
  contrib/experimental/great_expectations_experimental/expectations/expect_table_checksum_to_equal_other_table.py
  contrib/experimental/great_expectations_experimental/tests/test_utils.py
  great_expectations/core/util.py
  great_expectations/data_context/store/database_store_backend.py
  great_expectations/data_context/store/query_store.py
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_sampler.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_splitter.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py
  great_expectations/expectations/row_conditions.py
  great_expectations/util.py
  pyproject.toml
  tests/cli/test_init_sqlite.py
  tests/conftest.py
  tests/data_context/store/test_database_store_backend.py
  tests/data_context/test_data_context_test_yaml_config.py
  tests/data_context/test_data_context_v013.py
  tests/dataset/test_sqlalchemydataset.py
  tests/datasource/fluent/integration/conftest.py
  tests/datasource/test_sqlalchemy_datasource.py
  tests/execution_engine/test_sqlalchemy_batch_data.py
  tests/expectations/test_null_filters.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant_happy_paths.py
  tests/test_utils.py
Labels: core-team, dx

#7413 [MAINTENANCE] Bump SQLAlchemy lower bound to 1.4.0
  reqs/requirements-dev-lite.txt
Labels: core-team, dx

#7366 [MAINTENANCE] Validate `ExpectationConfiguration` before adding to suite
  great_expectations/core/expectation_suite.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/registry.py
  tests/conftest.py
  tests/core/test_expectation_suite.py
  tests/core/test_expectation_suite_crud_methods.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/rule_based_profiler/test_user_workflow_fixtures.py
  tests/test_fixtures/rule_based_profiler/alice_user_workflow_verbose_profiler_config.yml
Labels: core-team, platform

#7415 [MAINTENANCE] Convert to python built in warning categories
  pyproject.toml
Labels: core-team, dx

#7407 [FEATURE] Fluent `SQLDatasource` `create_temp_table`
  great_expectations/datasource/fluent/schemas/PostgresDatasource.json
  great_expectations/datasource/fluent/schemas/SQLDatasource.json
  great_expectations/datasource/fluent/schemas/SqliteDatasource.json
  great_expectations/datasource/fluent/sql_datasource.py
  great_expectations/datasource/fluent/sqlite_datasource.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_postgres_datasource.py
  tests/datasource/fluent/test_sqlite_datasource.py
Labels: core-team, platform

#7421 [MAINTENANCE] Move NotImported to optional_imports.py and start using it.
  great_expectations/core/util.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/sql_datasource.py
  great_expectations/optional_imports.py
  great_expectations/util.py
  pyproject.toml
  tests/test_not_imported.py
Labels: core-team, platform

#7401 [FEATURE] F/great 1463/add updates with datasource obj
  great_expectations/datasource/fluent/sources.py
  great_expectations/datasource/fluent/sources.pyi
  tests/datasource/fluent/test_metadatasource.py
Labels: core-team, platform

#7417 [DOCS] Put data_context.md code examples under test
  docs/docusaurus/docs/terms/data_context.md
  docs/sphinx_api_docs_source/public_api_report.py
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/pandas_yaml_example.py
Labels: core-team, dx

#7426 [MAINTENANCE] Fix some failing tests when running pytest with no args locally
  tests/data_context/store/test_store_backends.py
  tests/test_great_expectations.py
Labels: core-team, dx

#7425 [FEATURE] Fluent SparkDataframeDatasource with DataframeDataAsset
  great_expectations/datasource/fluent/__init__.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/schemas/SparkDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDatasource/DataFrameAsset.json
  great_expectations/datasource/fluent/sources.pyi
  great_expectations/datasource/fluent/spark_datasource.py
  great_expectations/optional_imports.py
  great_expectations/self_check/util.py
  tests/conftest.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/datasource/fluent/test_spark_datasource.py
  tests/execution_engine/test_sparkdf_execution_engine.py
Labels: core-team, platform

#7390 [CONTRIB][MAINTENANCE] Custom query expectation and editing query.template_values metric
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_custom_query_to_return_num_rows.py
  great_expectations/expectations/metrics/query_metrics/query_template_values.py
Labels: community

#7437 [MAINTENANCE] Some fluent datasource methods should be private
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/pandas_dbfs_datasource.py
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/pandas_s3_datasource.py
  great_expectations/datasource/fluent/sources.py
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/spark_datasource.py
  great_expectations/datasource/fluent/spark_dbfs_datasource.py
  great_expectations/datasource/fluent/spark_filesystem_datasource.py
  great_expectations/datasource/fluent/spark_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/spark_s3_datasource.py
  great_expectations/datasource/fluent/sql_datasource.py
Labels: core-team, platform

#7445 [RELEASE] 0.16.2
  docs/docusaurus/docs/changelog.md
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#7446 [BUGFIX] Fix LegacyRow import.
  great_expectations/core/util.py
Labels: core-team, platform

#7444 [BUGFIX] Repair SparkSession initialization behavior to disallow restarting, unless explicitly instructed through configuration
  great_expectations/core/util.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  tests/datasource/test_new_datasource.py
  tests/integration/spark/test_spark_config.py
Labels: core-team, platform

#7443 [BUGFIX] Skip dialect specific tests if no flag passed or flag not available
  great_expectations/execution_engine/sqlalchemy_dialect.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
Labels: core-team, dx

#7448 [RELEASE] 0.16.3
  docs/docusaurus/docs/changelog.md
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#7416 [MAINTENANCE] Case whens argument change for SQLAlchemy 2.0 compatibility
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_in_set.py
  great_expectations/expectations/metrics/map_metric_provider/map_condition_auxilliary_methods.py
  pyproject.toml
Labels: core-team, dx

#7451 [DOCS] New ADR proposal for patch version support
  .gitignore
  docs/adr/0002-support-latest-point-release.md
Labels: core-team

#7452 [MAINTENANCE]`mypy` `1.1.1` update
  contrib/cli/requirements.txt
  reqs/requirements-dev-contrib.txt
Labels: core-team, platform

#7440 [MAINTENANCE] Remove v2 api CLI
  docs/docusaurus/docs/components/setup/data_context/_filesystem_data_context_initialize_with_cli.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_in_deepnote.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/docusaurus/docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_use_the_cli_to_begin_the_interactive_process_of_creating_expectations.mdx
  docs/docusaurus/docs/guides/miscellaneous/how_to_use_the_great_expectations_cli.md
  docs/docusaurus/docs/guides/miscellaneous/migration_guide.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/components_how_to_configure_a_new_data_context_with_the_cli/_initialize_data_context_with_the_cli.mdx
  docs/docusaurus/docs/tutorials/getting_started/tutorial_setup.md
  docs/sphinx_api_docs_source/public_api_report.py
  docs_rtd/guides/tutorials/getting_started_v3_api/create_your_first_expectations.rst
  docs_rtd/guides/tutorials/getting_started_v3_api/initialize_a_data_context.rst
  great_expectations/cli/cli.py
  great_expectations/cli/v012/__init__.py
  great_expectations/cli/v012/checkpoint.py
  great_expectations/cli/v012/checkpoint_script_template.py
  great_expectations/cli/v012/cli.py
  great_expectations/cli/v012/cli_logging.py
  great_expectations/cli/v012/cli_messages.py
  great_expectations/cli/v012/datasource.py
  great_expectations/cli/v012/docs.py
  great_expectations/cli/v012/init.py
  great_expectations/cli/v012/mark.py
  great_expectations/cli/v012/project.py
  great_expectations/cli/v012/python_subprocess.py
  great_expectations/cli/v012/store.py
  great_expectations/cli/v012/suite.py
  great_expectations/cli/v012/toolkit.py
  great_expectations/cli/v012/util.py
  great_expectations/cli/v012/validation_operator.py
  tests/cli/test_checkpoint.py
  tests/cli/test_cli.py
  tests/cli/test_datasource_athena.py
  tests/cli/test_datasource_new_pandas_paths.py
  tests/cli/test_datasource_pandas.py
  tests/cli/test_datasource_snowflake.py
  tests/cli/test_datasource_sqlite.py
  tests/cli/test_docs.py
  tests/cli/test_init.py
  tests/cli/test_init_missing_libraries.py
  tests/cli/test_init_pandas.py
  tests/cli/test_init_sqlite.py
  tests/cli/test_project.py
  tests/cli/test_store.py
  tests/cli/test_suite.py
  tests/cli/test_validation_operator.py
  tests/cli/upgrade_helpers/test_upgrade_helper.py
  tests/integration/fixtures/gcp_deployment/ge_checkpoint_bigquery.py
  tests/integration/fixtures/gcp_deployment/ge_checkpoint_gcs.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/test_fixtures/upgrade_helper/test_basic_project_upgrade_expected_stdout.fixture
  tests/test_fixtures/upgrade_helper/test_project_upgrade_with_exception_expected_stdout.fixture
  tests/test_fixtures/upgrade_helper/test_project_upgrade_with_manual_steps_expected_stdout.fixture
  tests/test_fixtures/upgrade_helper/test_v2_to_v3_project_upgrade_with_manual_steps_checkpoints.fixture
  tests/test_fixtures/upgrade_helper/test_v2_to_v3_project_upgrade_with_manual_steps_checkpoints_datasources_validation_operators_expected_stdout.fixture
  tests/test_fixtures/upgrade_helper/test_v2_to_v3_project_upgrade_without_manual_steps_expected_stdout.fixture
Labels: core-team, dx

#7456 [MAINTENANCE] Updating language per issue 3572
  docs_rtd/reference/spare_parts/profiling_reference.rst
  great_expectations/profile/basic_suite_builder_profiler.py
  great_expectations/render/view/templates/carousel_modal.j2
  tests/profile/test_basic_suite_builder_profiler.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
Labels: core-team

#7457 [DOCS] Remove outdated instructions for building documentation
  docs/docusaurus/docs/contributing/contributing_setup.md
Labels: core-team, dx

#7455 [DOCS] Updating the docs to gx_dev
  .gitignore
  ci/user-install-matrix.yml
  docs/docusaurus/docs/contributing/contributing_setup.md
Labels: core-team

#7439 [MAINTENANCE] Remove v2 api expectations tests
  ci/azure-pipelines-cloud-integration.yml
  tests/datasource/test_new_datasource.py
  tests/test_definitions/test_expectations_v2_api.py
Labels: core-team, dx

#7422 [MAINTENANCE] Move docs_link_checker.py and create new docs-specific pipeline
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs-integration.yml
  ci/azure-pipelines-docs.yml
  docs/checks/__init__.py
  docs/checks/docs_link_checker.py
  docs/docusaurus/docs/components/connect_to_data/link_lists/_connecting_to_sql_datasources_block_config.md
  docs/docusaurus/docs/components/connect_to_data/link_lists/_connecting_to_sql_datasources_fluently.md
  docs/docusaurus/docs/components/connect_to_data/next_steps/_after_create_and_configure_data_asset.md
  docs/docusaurus/docs/components/connect_to_data/next_steps/_after_create_in_memory_data_asset.md
  docs/docusaurus/docs/components/connect_to_data/next_steps/_after_create_non_sql_datasource.md
  docs/docusaurus/docs/components/connect_to_data/next_steps/_after_create_sql_data_asset.md
  docs/docusaurus/docs/components/connect_to_data/next_steps/_after_create_sql_datasource.md
  docs/docusaurus/docs/components/connect_to_data/next_steps/_after_create_validator.md
  docs/docusaurus/docs/components/connect_to_data/next_steps/_after_request_data_from_a_data_asset.md
  docs/docusaurus/docs/components/setup/dependencies/_postgresql_configure_credentials_in_config_variables_yml.md
  docs/docusaurus/docs/components/setup/dependencies/_sql_generic_configure_credentials.md
  docs/docusaurus/docs/components/setup/link_lists/_setup_and_install_for_cloud_data.md
  docs/docusaurus/docs/components/setup/link_lists/_setup_and_install_for_filesystem_data.md
  docs/docusaurus/docs/components/setup/link_lists/_setup_and_install_for_hosted_data.md
  docs/docusaurus/docs/components/setup/link_lists/_setup_and_install_for_sql_data.md
  docs/docusaurus/docs/components/setup/next_steps/_links_after_installing_gx.md
  docs/docusaurus/docs/components/setup/next_steps/_links_for_adding_azure_blob_storage_configurations_to_data_context.md
  docs/docusaurus/docs/components/setup/next_steps/_links_for_adding_postgresql_configurations_to_data_context.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/batch_requests/how_to_request_data_from_a_data_asset.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_azure_blob_storage_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_azure_blob_storage_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_gcs_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_gcs_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_s3_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_s3_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_file_based_data_asset.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_sql_based_data_asset.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_a_sql_table.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_postgresql_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data_using_a_query.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sqlite_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_connect_to_one_or_more_files_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/in_memory/how_to_connect_to_in_memory_data_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/how_to_choose_which_dataconnector_to_use.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/initializing_data_contexts/how_to_initialize_a_filesystem_data_context_in_python.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_instantiate_a_specific_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_quickly_instantiate_a_data_context.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/sql_databases/how_to_setup_gx_to_work_with_sql_databases.md
  docs/docusaurus/docs/gx_cloud/tutorials/getting_started/getting_started_with_gx_cloud.md
Labels: core-team, dx

#7378 [MAINTENANCE] select call style change for SQLAlchemy 2 compatibility
  contrib/experimental/great_expectations_experimental/expectations/expect_column_to_have_no_days_missing.py
  contrib/experimental/great_expectations_experimental/expectations/expect_day_count_to_be_close_to_equivalent_week_day_mean.py
  contrib/experimental/great_expectations_experimental/expectations/expect_yesterday_count_compared_to_avg_equivalent_days_of_week.py
  great_expectations/data_context/store/database_store_backend.py
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/datasource/sqlalchemy_datasource.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_sampler.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_splitter.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_distinct_values.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_value_counts.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_values_between_count.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_match_like_pattern_list.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_match_regex_list.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_not_match_like_pattern_list.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_not_match_regex_list.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_equal.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/map_metric_provider/column_map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/map_metric_provider/column_pair_map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/map_metric_provider/map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/map_metric_provider/multicolumn_map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/compound_columns_unique.py
  great_expectations/expectations/metrics/table_metrics/table_head.py
  great_expectations/expectations/metrics/util.py
  great_expectations/util.py
  pyproject.toml
  tests/data_context/store/test_database_store_backend.py
  tests/dataset/test_sqlalchemydataset.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/integration/db/taxi_data_utils.py
  tests/integration/db/test_sql_data_sampling.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_introspect_and_partition_your_data/sql_database/yaml_example_complete.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_max_to_be_between_custom.py
  tests/test_fixtures/custom_sqlalchemy_dataset.py
Labels: core-team, dx

#7460 [MAINTENANCE] Decruft map_metric_provider.py
  great_expectations/expectations/metrics/map_metric_provider/map_metric_provider.py
Labels: core-team

#7459 [MAINTENANCE] Add tests for `_register_metric_functions` in the `MetricProvider` class hierarchy.
  great_expectations/expectations/metrics/map_metric_provider.py
  tests/expectations/metrics/test_metric_providers.py
Labels: core-team

#7458 [BUGFIX] Ensure that MetricStore Records "data_asset_name" Properly
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_column_profiler_report.py
  great_expectations/checkpoint/actions.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/data_context/data_context/abstract_data_context.py
Labels: core-team, platform

#7465 [DOCS] Fixes typo in code snippet for "How to organize Batches in a file-based Data Asset" guide
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_file_based_data_asset.md
Labels: devrel

#7466 [DOCS] Postgresql drivername fix for SQLAlchemy compatibility. Closes #7464
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_to_postgresql.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_to_postgresql.md
  docs_rtd/guides/how_to_guides/configuring_data_contexts/how_to_use_a_yaml_file_or_environment_variables_to_populate_credentials.rst
  docs_rtd/guides/how_to_guides/configuring_metadata_stores/how_to_configure_a_validation_result_store_to_postgresql.rst
  docs_rtd/guides/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_to_postgresql.rst
  docs_rtd/reference/spare_parts/data_context_reference.rst
Labels: community

#7470 [DOCS] Corrects code snippets
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_connect_to_one_or_more_files_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_connect_to_one_or_more_files_using_spark.md
Labels: devrel

#7400 [MAINTENANCE] SqlAlchemy2 Compatibility - implicit autocommit
  great_expectations/data_context/store/database_store_backend.py
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/df_to_database_loader.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py
  great_expectations/self_check/util.py
  great_expectations/util.py
  pyproject.toml
  tests/conftest.py
  tests/data_context/store/test_database_store_backend.py
  tests/data_context/test_data_context_test_yaml_config.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_postgres_datasource.py
  tests/datasource/test_sqlalchemy_datasource.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
  tests/execution_engine/test_sqlalchemy_batch_data.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/profile/test_user_configurable_profiler_v3_batch_request.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant_happy_paths.py
  tests/sqlalchemy_test_doubles.py
  tests/test_utils.py
Labels: core-team, dx

#7467 [BUGFIX] Fix incorrect type hint and correct typographical errors in DomainBuilder docstrings and fill in missing docstrings
  great_expectations/rule_based_profiler/domain_builder/categorical_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/column_pair_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/multi_column_domain_builder.py
  great_expectations/rule_based_profiler/helpers/cardinality_checker.py
  pyproject.toml
Labels: core-team, platform

#7000 [FEATURE] Add package, contributors and metrics filter in Algolia script for expectation
  assets/scripts/AlgoliaScripts/upload_s3_expectation_to_algolia.js
Labels: community

#7471 [MAINTENANCE] Remove SQLAlchemyDataset/Datasource
  docs/sphinx_api_docs_source/public_api_report.py
  great_expectations/core/usage_statistics/anonymizers/datasource_anonymizer.py
  great_expectations/dataset/__init__.py
  great_expectations/dataset/sqlalchemy_dataset.py
  great_expectations/datasource/__init__.py
  great_expectations/datasource/sqlalchemy_datasource.py
  great_expectations/self_check/util.py
  great_expectations/validator/validator.py
  tests/cli/test_datasource_sqlite.py
  tests/cli/test_init_sqlite.py
  tests/conftest.py
  tests/data_asset/test_data_asset.py
  tests/data_context/conftest.py
  tests/data_context/fixtures/plugins/__init__.py
  tests/data_context/fixtures/plugins/my_custom_v2_api_datasource.py
  tests/data_context/test_configuration_storage.py
  tests/data_context/test_configuration_storage_pre_v013.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_config_variables.py
  tests/data_context/test_data_context_config_variables_pre_v013.py
  tests/data_context/test_pandas_datetime_suites_pre_v013.py
  tests/dataset/__init__.py
  tests/dataset/test_dataset.py
  tests/dataset/test_dataset_legacy.py
  tests/dataset/test_dataset_util_legacy.py
  tests/dataset/test_pandas_dataset.py
  tests/dataset/test_pandas_dataset_conditionals.py
  tests/dataset/test_sparkdfdataset.py
  tests/dataset/test_sqlalchemydataset.py
  tests/dataset/test_util.py
  tests/datasource/batch_kwarg_generator/test_query_generator.py
  tests/datasource/batch_kwarg_generator/test_table_generator.py
  tests/datasource/conftest.py
  tests/datasource/data_connector/test_sql_data_connector.py
  tests/datasource/test_datasource_anonymizer.py
  tests/datasource/test_sparkdf_datasource.py
  tests/datasource/test_sqlalchemy_datasource.py
  tests/profile/test_basic_suite_builder_profiler.py
  tests/profile/test_profile.py
  tests/test_autoinspect.py
  tests/test_dataset_implementations/__init__.py
  tests/test_dataset_implementations/test_dataset_implementations.json
  tests/test_dataset_implementations/test_dataset_implementations.py
  tests/test_fixtures/custom_sqlalchemy_dataset.py
  tests/test_ge_utils.py
Labels: core-team, dx

#7483 [DOCS] Add a note about installing version of pyspark that matches Spark version
  docs/docusaurus/docs/contributing/contributing_setup.md
Labels: core-team, dx

#7484 [DOCS] adding cloud language to quickstart
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
Labels: devrel

#7485 [DOCS] doc-409 Corrects links in databricks guide
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_in_databricks.md
Labels: devrel

#7478 [DOCS] Doc-472 Corrects numbering of steps in guide
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_amazon_s3.md
Labels: devrel

#7490 [MAINTENANCE] Deprecated API features detected warning for SQLAlchemy 2.0 compatibility
  pyproject.toml
Labels: core-team, dx

#7473 [BUGFIX] Reset Metrics Registry in order to keep state of Metrics Registry test cases Runs mutually consistent
  great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py
  tests/expectations/metrics/test_metric_providers.py
Labels: core-team, platform

#7454 [MAINTENANCE] type-checking implementation files
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines.yml
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/pandas_dbfs_datasource.py
  great_expectations/datasource/fluent/sources.py
  great_expectations/datasource/fluent/spark_dbfs_datasource.py
  tasks.py
Labels: core-team, platform

#7492 [MAINTENANCE] Small Refactor of ColumnDomainBuilder for code elegance and computational performance improvements
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_string_integers_increasing.py
  great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py
  great_expectations/validator/metric_configuration.py
Labels: core-team, platform

#7477 [DOCS] DOC-474 Updates URL for usage statistics page
  docs/docusaurus/docs/reference/supplemental_documentation.md
  docs/docusaurus/docs/reference/usage_statistics.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
Labels: devrel

#7489 [MAINTENANCE] Connection.connect warning for SQLAlchemy 2.0 compatibility
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py
  great_expectations/self_check/sqlalchemy_connection_manager.py
  great_expectations/self_check/util.py
  pyproject.toml
  tests/cli/test_checkpoint.py
  tests/profile/test_user_configurable_profiler_v3_batch_request.py
  tests/sqlalchemy_test_doubles.py
Labels: core-team, dx

#7506 [BUGFIX] Corrected typographical errors in two docstrings
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/rule_based_profiler/domain_builder/data_profiler_column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/multi_column_domain_builder.py
Labels: core-team, platform

#7503 [MAINTENANCE] Pass `PandasDatasource` `batch_metadata` as `kwargs` to remove possibility of `None` on `DataAsset` model
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_datasource.py
Labels: core-team, platform

#7504 [MAINTENANCE] Fix sqlalchemy warnings for pandas + sql fluent datasources
  great_expectations/compatibility/README.md
  great_expectations/compatibility/__init__.py
  great_expectations/compatibility/sqlalchemy_and_pandas.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/optional_imports.py
  great_expectations/self_check/util.py
  great_expectations/warnings.py
  tests/data_context/test_data_context_test_yaml_config.py
Labels: core-team, dx

#7495 [DOCS] Testing ADR
  docs/adr/0003-automated-testing.md
Labels: core-team

#7516 [BUGFIX] Typo in min versions install
  ci/constraints-test/py37-min-install.txt
Labels: core-team, dx

#7515 [MAINTENANCE] Revert PR 7490
  pyproject.toml
Labels: core-team, dx
