Repository great-expectations/great_expectations, pull requests merged in 2023-02, with the labels that each got.

#6844 [FEATURE] Experimental `Datasource` and `DataAsset` connection testing
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/metadatasource.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/postgres_datasource.py
  great_expectations/experimental/datasources/sources.py
  great_expectations/experimental/datasources/sql_datasource.py
  great_expectations/experimental/datasources/sqlite_datasource.py
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_metadatasource.py
  tests/experimental/datasources/test_postgres_datasource.py
  tests/experimental/datasources/test_sqlite_datasource.py
Labels: core-team, platform

#7012 [DOCS] DOC-420 updates to screenshots
  docs/images/data_docs_taxi_failed_validation01.png
  docs/images/data_docs_taxi_failed_validation02.png
  docs/images/datadocs.png
  docs/images/multiple_line_markdown.png
  docs/images/multiple_line_string.png
Labels: devrel

#7013 [MAINTENANCE] Make Pandas installation with Python 3.10 less restrictive
  requirements.txt
Labels: core-team, platform

#7021 [BUGFIX] Patch logic error in new `add_or_update` methods
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/data_context/test_data_context_state_management.py
Labels: core-team, platform

#6985 [DOCS] DOC-416 How to use GX with AWS using Redshift
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_congratulations_aws_redshift.md
  docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_redshift.md
  docs/guides/connecting_to_your_data/database/components/_datasource_redshift_configuration.md
  docs/guides/connecting_to_your_data/database/components/_datasource_redshift_test.md
  docs/guides/connecting_to_your_data/database/components/_redshift_credentials.md
  docs/guides/connecting_to_your_data/database/components/_redshift_dependencies.md
  docs/guides/connecting_to_your_data/database/redshift.md
  sidebars.js
Labels: devrel

#7022 [DOCS] Fix metric provider and reorganize sidebar
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
  great_expectations/expectations/metrics/metric_provider.py
Labels: core-team, dx

#7023 [MAINTENANCE] ZEP - postgres test typing
  pyproject.toml
  tests/experimental/datasources/test_postgres_datasource.py
Labels: core-team, platform

#7024 [DOCS] Typo - Update api_reference.md
  docs/reference/api_reference.md
Labels: core-team, dx

#7009 [BUGFIX ] ZEP - pandas serde fix
  great_expectations/experimental/datasources/constants.py
  great_expectations/experimental/datasources/dynamic_pandas.py
  great_expectations/experimental/datasources/experimental_base_model.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_datasource.py
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_pandas_datasource.py
Labels: core-team, platform

#7027 add preview image for twitter and other social preview images
  docusaurus.config.js
  static/img/gx-preview.png
Labels: devrel

#7015 [BUGFIX] Pandas ID/PK - bugfix for column name and update tests
  great_expectations/self_check/util.py
  tests/test_definitions/column_map_expectations/expect_column_value_lengths_to_be_between.json
  tests/test_definitions/column_map_expectations/expect_column_value_lengths_to_equal.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between__evaluation_parameters.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_informed.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_naive.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_decreasing.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_in_set.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_in_type_list.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_increasing.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_null.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_unique.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_json_schema.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_regex.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_regex_list.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_be_in_set.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_be_null.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_match_regex.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_match_regex_list.json
  tests/test_definitions/column_pair_map_expectations/expect_column_pair_values_a_to_be_greater_than_b.json
  tests/test_definitions/column_pair_map_expectations/expect_column_pair_values_to_be_in_set.json
  tests/test_definitions/multicolumn_map_expectations/expect_compound_columns_to_be_unique.json
  tests/test_definitions/multicolumn_map_expectations/expect_multicolumn_sum_to_equal.json
  tests/test_definitions/multicolumn_map_expectations/expect_select_column_values_to_be_unique_within_record.json
  tests/test_definitions/test_expectations_v2_api.py
  tests/test_definitions/test_expectations_v3_api.py
Labels: core-team, dx

#7018 [CONTRIB] Adding support for punctuation in column_value for the row_condition parser
  great_expectations/expectations/row_conditions.py
  tests/expectations/test_row_conditions.py
Labels: community

#7032 [DOCS] Nest sidebar by shortest import path
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
  src/css/custom.scss
Labels: core-team, dx

#7034 [MAINTENANCE] Update `update_` methods in `DataContext` to return persisted object
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/data_context/test_data_context_state_management.py
Labels: core-team, platform

#7037 [MAINTENANCE] ZEP - use parameter that exists on min pandas version
  tests/experimental/datasources/test_pandas_datasource.py
Labels: core-team, platform

#7038 [MAINTENANCE] xfail ZEP async spark tests for release
  tests/experimental/datasources/test_spark_datasource.py
Labels: core-team, platform, zep

#7025 [FEATURE] Place FilesystemDataAsset into separate module (its functionality is used by both PandasDatasource and SparkDatasource)
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/experimental/datasources/dynamic_pandas.py
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/spark_datasource.py
  tests/experimental/datasources/integration/conftest.py
  tests/experimental/datasources/test_pandas_datasource.py
  tests/experimental/datasources/test_spark_datasource.py
Labels: core-team, platform, zep

#7039 [RELEASE] 0.15.47
  .github/teams.yml
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#7031 [MAINTENANCE] Deprecate old `DataContext` CRUD methods
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/data_context/test_data_context_deprecation.py
Labels: core-team, platform

#7035 [MAINTENANCE] Simplify logic for `add_or_update`
  great_expectations/data_context/data_context/abstract_data_context.py
Labels: core-team, platform

#7028 [MAINTENANCE] ZEP - test type-checking
  pyproject.toml
  tests/experimental/datasources/conftest.py
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_pandas_datasource.py
Labels: core-team, platform, zep

#6988 [MAINTENANCE] ZEP put schemas under source control
  great_expectations/experimental/datasources/__init__.py
  great_expectations/experimental/datasources/dynamic_pandas.py
  great_expectations/experimental/datasources/schemas/CSVAsset.json
  great_expectations/experimental/datasources/schemas/CSVSparkAsset.json
  great_expectations/experimental/datasources/schemas/ExcelAsset.json
  great_expectations/experimental/datasources/schemas/JSONAsset.json
  great_expectations/experimental/datasources/schemas/PandasDatasource.json
  great_expectations/experimental/datasources/schemas/ParquetAsset.json
  great_expectations/experimental/datasources/schemas/PostgresDatasource.json
  great_expectations/experimental/datasources/schemas/SQLDatasource.json
  great_expectations/experimental/datasources/schemas/SparkDatasource.json
  great_expectations/experimental/datasources/schemas/TableAsset.json
  tasks.py
  tests/experimental/datasources/test_schemas.py
Labels: core-team, platform, zep

#7041 [BUGFIX] ID/PK - Rendering `ColumnPair` and `MultiColumn` Expectations in DataDocs
  great_expectations/exceptions/exceptions.py
  great_expectations/expectations/core/expect_multicolumn_sum_to_equal.py
  great_expectations/render/util.py
  tests/render/test_render_ValidationResultsTableContentBlockRenderer.py
  tests/render/test_util.py
Labels: core-team, dx

#7036 [MAINTENANCE] Add `id` as a param to any CRUD methods with `ge_cloud_id`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/migrator/configuration_bundle.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/data_context/migrator/conftest.py
  tests/data_context/store/test_checkpoint_store.py
  tests/data_context/test_data_context_deprecation.py
  tests/data_context/test_data_context_profilers.py
  tests/rule_based_profiler/test_rule_based_profiler.py
Labels: core-team, platform

#7045 [BUGFIX] `ColumnPairExpectation` tests need to consider 2 possible GroupBy results
  tests/render/test_util.py
Labels: core-team, dx

#7019 [FEATURE] Experimental `DataAsset` `test_connection`
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/schemas/PostgresDatasource.json
  great_expectations/experimental/datasources/schemas/SQLDatasource.json
  great_expectations/experimental/datasources/schemas/TableAsset.json
  great_expectations/experimental/datasources/spark_datasource.py
  great_expectations/experimental/datasources/sql_datasource.py
  great_expectations/experimental/datasources/sqlite_datasource.py
  tests/experimental/datasources/conftest.py
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_pandas_datasource.py
  tests/experimental/datasources/test_postgres_datasource.py
  tests/experimental/datasources/test_spark_datasource.py
Labels: core-team, platform, zep

#7047 [MAINTENANCE] Minor Cleanup
  great_expectations/datasource/data_connector/configured_asset_azure_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_filesystem_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_s3_data_connector.py
  great_expectations/datasource/data_connector/file_path_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_azure_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_s3_data_connector.py
  great_expectations/datasource/data_connector/util.py
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/interfaces.py
  tests/datasource/data_connector/test_configured_asset_s3_data_connector.py
  tests/datasource/data_connector/test_file_path_data_connector.py
Labels: core-team, platform

#6907 [MAINTENANCE] replace `isort` with `ruff` sorting rules
  .pre-commit-config.yaml
  azure-pipelines-contrib.yml
  azure-pipelines-dev.yml
  azure-pipelines.yml
  contrib/cli/great_expectations_contrib/commands.py
  contrib/cli/requirements.txt
  docs/contributing/style_guides/code_style.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_pair_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_multicolumn_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_query_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_table_expectations.md
  great_expectations/core/expectation_diagnostics/expectation_diagnostics.py
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/__init__.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/rule_based_profiler/expectation_configuration_builder/default_expectation_configuration_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/self_check/util.py
  pyproject.toml
  reqs/requirements-dev-contrib.txt
  tasks.py
  tests/expectations/test_generate_diagnostic_checklist.py
  tests/expectations/test_run_diagnostics.py
Labels: core-team, platform

#6962 [MAINTENANCE] Standardize `Checkpoint` CRUD
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  tests/data_context/store/test_checkpoint_store.py
  tests/data_context/test_data_context_state_management.py
Labels: core-team, platform

#7048 [MAINTENANCE] ruff `0.0.241`
  .pre-commit-config.yaml
  contrib/cli/requirements.txt
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/sources.py
  great_expectations/experimental/datasources/spark_datasource.py
  great_expectations/experimental/datasources/sql_datasource.py
  great_expectations/experimental/datasources/sqlite_datasource.py
  reqs/requirements-dev-contrib.txt
  tests/experimental/datasources/test_metadatasource.py
Labels: core-team, platform

#7050 [MAINTENANCE] finish linting `great_expectations`
  .pre-commit-config.yaml
  great_expectations/dataset/ruff.toml
  great_expectations/dataset/sparkdf_dataset.py
  great_expectations/dataset/sqlalchemy_dataset.py
  pyproject.toml
Labels: core-team, platform

#7055 [MAINTENANCE] fix - `FutureWarning: pandas.Float64Index is deprecated` when importing `great_expectations`
  great_expectations/experimental/datasources/dynamic_pandas.py
Labels: core-team, platform, zep

#7058 [DOCS] Add new `DataContext` CRUD to public API
  great_expectations/core/_docs_decorators.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/migrator/configuration_bundle.py
Labels: core-team, platform

#7051 [FEATURE] Experimental Splitter connection testing
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/postgres_datasource.py
  great_expectations/experimental/datasources/schemas/PostgresDatasource.json
  great_expectations/experimental/datasources/spark_datasource.py
  great_expectations/experimental/datasources/sql_datasource.py
  great_expectations/experimental/datasources/sqlite_datasource.py
  tests/experimental/datasources/conftest.py
  tests/experimental/datasources/test_postgres_datasource.py
Labels: core-team, platform, zep

#7001 [FEATURE] ID/PK `ColumnPairExpectations` and `MultiColumnMapExpectations` - Spark
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/self_check/util.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/conftest.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_informed.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_be_null.json
Labels: core-team, dx

#7053 [CONTRIB] Row condition parser sqlalchemy: adding support for != operator & adding support all operators for string
  great_expectations/expectations/row_conditions.py
  tests/expectations/test_row_conditions.py
Labels: community

#7056 [BUGFIX] zep - always serialize type field
  great_expectations/experimental/datasources/constants.py
  great_expectations/experimental/datasources/experimental_base_model.py
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/interfaces.py
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_pandas_datasource.py
  tests/experimental/datasources/test_postgres_datasource.py
Labels: core-team, platform, zep

#7059 [FEATURE] Add `expectation_suite` arg to `DataContext` `ExpectationSuite` CRUD
  great_expectations/core/expectation_suite.py
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/data_context/test_data_context_state_management.py
Labels: core-team, platform

#7046 [FEATURE] ID/PK ColumnPairExpectations and MultiColumnMapExpectations - SQL
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/self_check/util.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/conftest.py
  tests/expectations/metrics/column_map_metrics/test_unexpected_indices_and_query.py
  tests/expectations/metrics/test_map_metric.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between__evaluation_parameters.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_informed.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_informed_mssql.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_naive.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_like_pattern.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_like_pattern_list.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_match_like_pattern.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_match_like_pattern_list.json
  tests/test_sets/metrics_test.db
  tests/validator/test_validator.py
Labels: core-team, dx

#7068 [BUGFIX] ZEP - html asset generation on pandas `1.1`
  great_expectations/experimental/datasources/dynamic_pandas.py
  great_expectations/experimental/datasources/pandas_datasource.py
  tests/experimental/datasources/test_pandas_datasource.py
Labels: core-team, platform

#7062 [FEATURE] Introducing General-Purpose Wrapper for Regular Expressions Parsing and incorporating it in "_FilesystemDataAsset"
  great_expectations/experimental/datasources/data_asset/__init__.py
  great_expectations/experimental/datasources/data_asset/data_connector/__init__.py
  great_expectations/experimental/datasources/data_asset/data_connector/regex_parser.py
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/pandas_datasource.py
  tests/experimental/datasources/data_asset/data_connector/test_regex_parser.py
  tests/experimental/datasources/test_pandas_datasource.py
Labels: core-team, platform

#7073 [MAINTENANCE] Enable ruff `TCH` rules
  .git-blame-ignore-revs
  contrib/ruff.toml
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_sampler.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_splitter.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/row_conditions.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/validator/validator.py
  pyproject.toml
  tests/ruff.toml
Labels: core-team, platform

#7071 [MAINTENANCE] Cache dependency installation during build of `Dockerfile.tests`
  docker/Dockerfile.tests
Labels: core-team, platform

#7010 [MAINTENANCE] Fix most typing errors in `DataAssistantResult`
  great_expectations/cli/toolkit.py
  great_expectations/core/_docs_decorators.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/store.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/profile/json_schema_profiler.py
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  pyproject.toml
  tests/experimental/datasources/test_viral_snippets.py
Labels: core-team, platform

#7066 [FEATURE] Add `checkpoint` arg to `DataContext` `Checkpoint` CRUD
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  tests/data_context/test_data_context_state_management.py
Labels: core-team, platform

#7060 [FEATURE] Add `profiler` arg to `DataContext` `Profiler` CRUD
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/data_context/test_data_context_state_management.py
Labels: core-team, platform

#7075 Refactor Filesystem DataAsset into FilePath DataAsset and Filesystem DataAsset (later inherits former)
  great_expectations/experimental/datasources/file_path_data_asset.py
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/schemas/CSVAsset.json
  great_expectations/experimental/datasources/schemas/CSVSparkAsset.json
  great_expectations/experimental/datasources/schemas/ClipboardAsset.json
  great_expectations/experimental/datasources/schemas/ExcelAsset.json
  great_expectations/experimental/datasources/schemas/FeatherAsset.json
  great_expectations/experimental/datasources/schemas/GBQAsset.json
  great_expectations/experimental/datasources/schemas/HDFAsset.json
  great_expectations/experimental/datasources/schemas/HTMLAsset.json
  great_expectations/experimental/datasources/schemas/JSONAsset.json
  great_expectations/experimental/datasources/schemas/ORCAsset.json
  great_expectations/experimental/datasources/schemas/ParquetAsset.json
  great_expectations/experimental/datasources/schemas/PickleAsset.json
  great_expectations/experimental/datasources/schemas/SPSSAsset.json
  great_expectations/experimental/datasources/schemas/SQLQueryAsset.json
  great_expectations/experimental/datasources/schemas/SQLTableAsset.json
  great_expectations/experimental/datasources/schemas/STATAAsset.json
  great_expectations/experimental/datasources/schemas/XMLAsset.json
  requirements.txt
  tests/experimental/datasources/test_pandas_datasource.py
  tests/experimental/datasources/test_schemas.py
Labels: core-team, platform

#7083 [DOCS] DOC-461 remove unlinked link
  docs/guides/setup/configuring_data_docs/components_how_to_host_and_share_data_docs_on_amazon_s3/_additional_notes.mdx
Labels: devrel

#7081 [MAINTENANCE] Refactor `Store` and `StoreBackend` to leverage new CRUD methods
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/store/_store_backend.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/profiler_store.py
  great_expectations/data_context/store/store.py
  great_expectations/exceptions/exceptions.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/data_context/store/test_checkpoint_store.py
  tests/data_context/store/test_store.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context_state_management.py
  tests/rule_based_profiler/test_rule_based_profiler.py
Labels: core-team, platform

#7085 [DOCS] Adding algolia click events
  package.json
  src/theme/SearchBar/index.js
  src/theme/SearchPage/index.js
  yarn.lock
Labels: devrel

#7084 [BUGFIX] fix ZEP pandas min tests
  great_expectations/experimental/datasources/dynamic_pandas.py
  tasks.py
  tests/experimental/datasources/test_pandas_datasource.py
Labels: core-team, platform

#7033 [DOCS] Versioning for documentation
  docs/build_docs
  docs/guides/validation/validation_actions/how_to_trigger_email_as_a_validation_action.md
  docusaurus.config.js
  versions.json
Labels: core-team, dx

#7088 correct typo in data assistants portion of the getting started tutorial
  docs/tutorials/getting_started/tutorial_create_expectations.md
Labels: devrel

#7087 [MAINTENANCE] ID/PK - CompoundColumnsUnique is filtered only for SQL
  great_expectations/expectations/expectation.py
Labels: core-team, dx

#7089 [MAINTENANCE] Minor clean up to make `DataConnector` method names less confusing.
  great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py
  great_expectations/datasource/data_connector/data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_file_path_data_connector.py
  great_expectations/datasource/data_connector/runtime_data_connector.py
  tests/datasource/data_connector/test_configured_asset_azure_data_connector.py
  tests/datasource/data_connector/test_configured_asset_filesystem_data_connector.py
  tests/datasource/data_connector/test_configured_asset_gcs_data_connector.py
  tests/datasource/data_connector/test_configured_asset_s3_data_connector.py
  tests/datasource/data_connector/test_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_azure_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_dbfs_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_filesystem_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_gcs_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_s3_data_connector.py
  tests/datasource/data_connector/test_runtime_data_connector.py
Labels: core-team, platform

#7091 [BUGFIX] Skip all ZEP pandas datasource tests for min pandas
  great_expectations/experimental/datasources/dynamic_pandas.py
  tests/experimental/datasources/test_pandas_datasource.py
Labels: core-team, platform

#7092 [MAINTENANCE] Refactor DataConnector Path Format Utilities For Better Encapsulation
  great_expectations/datasource/data_connector/data_connector.py
  great_expectations/datasource/data_connector/file_path_data_connector.py
  great_expectations/datasource/data_connector/util.py
Labels: core-team, platform

#6902 [FEATURE] Add API action
  great_expectations/checkpoint/actions.py
  tests/actions/test_core_actions.py
Labels: community

#7097 [MAINTENANCE] Temporarily xfail ID/PK tests due to Pandas min version conflicts
  tests/render/test_util.py
Labels: core-team, platform

#7098 [MAINTENANCE] Remove Extra Character from ID/PK Example README
  examples/demos/primary_keys_in_validation_results/README.md
Labels: core-team, dx

#7099 [RELEASE] 0.15.48
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#7095 [MAINTENANCE] Rename experimental `get_batch_request` to `build_batch_request`
  great_expectations/experimental/datasources/file_path_data_asset.py
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/sql_datasource.py
  tests/experimental/datasources/integration/conftest.py
  tests/experimental/datasources/integration/test_integration_datasource.py
  tests/experimental/datasources/test_metadatasource.py
  tests/experimental/datasources/test_pandas_datasource.py
  tests/experimental/datasources/test_postgres_datasource.py
  tests/experimental/datasources/test_spark_datasource.py
  tests/experimental/datasources/test_viral_snippets.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant_happy_paths.py
Labels: core-team, platform

#7104 [FEATURE] Enable customization of candidate Regular Expression patterns when running OnboardingDataAssistant
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
Labels: core-team, platform

#7106 Fix incorrect label on "How to configure a SQL Datasource" docs page
  docs/guides/connecting_to_your_data/datasource_configuration/sql_components/_section_configure_your_data_assets.mdx
  docs/guides/connecting_to_your_data/datasource_configuration/sql_components/_section_data_connector_example_configurations.mdx
Labels: core-team

#7107 [BUGFIX] Rename experimental `get_batch_request` to `build_batch_request`
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant_happy_paths.py
Labels: core-team, platform

#7074 [FEATURE] Enable `gx.get_context()` to work without any inputs
  great_expectations/cli/project.py
  great_expectations/data_context/types/base.py
  great_expectations/util.py
  tests/data_context/test_data_context_data_docs_api.py
  tests/data_context/test_get_data_context.py
Labels: core-team, platform

#7109 [BUGFIX] Remove version from versions.json
  versions.json
Labels: core-team, dx

#7100 [FEATURE] Add polars `ColumnValuesValueLengthEquals` and `ColumnValuesValueLength` metrics
  great_expectations/execution_engine/polars_execution_engine.py
  great_expectations/expectations/metrics/column_map_metrics/column_value_lengths.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_non_null.py
  great_expectations/expectations/metrics/import_manager.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/self_check/util.py
  reqs/requirements-dev-polars.txt
  tests/test_definitions/test_expectations_v3_api.py
Labels: core-team, dx

#7111 [MAINTENANCE] Update dependency on pydantic
  requirements.txt
Labels: core-team, dx

#7113 [FEATURE] Update some polars map metric providers
  great_expectations/execution_engine/polars_execution_engine.py
  great_expectations/expectations/metrics/map_metric_provider.py
Labels: core-team, dx

#7078 [MAINTENANCE] Move experimental `base_directory` from `_FilesystemDataAsset` to `PandasDatasource` and `SparkDatasource`
  great_expectations/experimental/datasources/__init__.py
  great_expectations/experimental/datasources/dynamic_pandas.py
  great_expectations/experimental/datasources/file_path_data_asset.py
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/schemas/CSVAsset.json
  great_expectations/experimental/datasources/schemas/CSVSparkAsset.json
  great_expectations/experimental/datasources/schemas/ClipboardAsset.json
  great_expectations/experimental/datasources/schemas/ExcelAsset.json
  great_expectations/experimental/datasources/schemas/FeatherAsset.json
  great_expectations/experimental/datasources/schemas/GBQAsset.json
  great_expectations/experimental/datasources/schemas/HDFAsset.json
  great_expectations/experimental/datasources/schemas/HTMLAsset.json
  great_expectations/experimental/datasources/schemas/JSONAsset.json
  great_expectations/experimental/datasources/schemas/ORCAsset.json
  great_expectations/experimental/datasources/schemas/ParquetAsset.json
  great_expectations/experimental/datasources/schemas/PickleAsset.json
  great_expectations/experimental/datasources/schemas/SPSSAsset.json
  great_expectations/experimental/datasources/schemas/SQLQueryAsset.json
  great_expectations/experimental/datasources/schemas/SQLTableAsset.json
  great_expectations/experimental/datasources/schemas/STATAAsset.json
  great_expectations/experimental/datasources/schemas/XMLAsset.json
  great_expectations/experimental/datasources/sources.py
  great_expectations/experimental/datasources/spark_datasource.py
  great_expectations/experimental/datasources/sql_datasource.py
  great_expectations/experimental/datasources/sqlite_datasource.py
  tasks.py
  tests/experimental/datasources/integration/conftest.py
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_pandas_datasource.py
  tests/experimental/datasources/test_schemas.py
  tests/experimental/datasources/test_spark_datasource.py
Labels: core-team, platform

#7114 [FEATURE] Update polars map metric partial functions
  great_expectations/expectations/metrics/map_metric_provider.py
Labels: core-team, dx

#7115 [MAINTENANCE] Use secret to store algolia api key
  .github/workflows/algoliaIndexer.yml
Labels: core-team, dx

#7070 [FEATURE] Add `datasource` arg to `DataContext` `Datasource` CRUD
  great_expectations/core/usage_statistics/usage_statistics.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/exceptions/exceptions.py
  tests/core/usage_statistics/test_usage_statistics_data_context.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/test_data_context_datasources.py
  tests/data_context/test_data_context_state_management.py
  tests/data_context/test_loading_and_saving_of_data_context_configs.py
Labels: core-team, platform

#7079 [DOCS] Add CRUD API matrix to `AbstractDataContext` docstring
  great_expectations/data_context/data_context/abstract_data_context.py
Labels: core-team, platform

#7067 [DOCS] Build API docs using latest released version
  docs/build_docs
  great_expectations/core/expectation_suite.py
Labels: core-team, dx

#7123 [MAINTENANCE] ZEP - Realign pandas asset args for `Datasource` level `base_directory`
  great_expectations/experimental/datasources/dynamic_pandas.py
  great_expectations/experimental/datasources/file_path_data_asset.py
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/schemas/ClipboardAsset.json
  great_expectations/experimental/datasources/schemas/ExcelAsset.json
  great_expectations/experimental/datasources/schemas/FeatherAsset.json
  great_expectations/experimental/datasources/schemas/GBQAsset.json
  great_expectations/experimental/datasources/schemas/HDFAsset.json
  great_expectations/experimental/datasources/schemas/ORCAsset.json
  great_expectations/experimental/datasources/schemas/ParquetAsset.json
  great_expectations/experimental/datasources/schemas/SPSSAsset.json
  great_expectations/experimental/datasources/schemas/SQLQueryAsset.json
  great_expectations/experimental/datasources/schemas/SQLTableAsset.json
  tests/experimental/datasources/test_pandas_datasource.py
Labels: core-team, platform, zep

#7120 [CONTRIB] Add experimental expectation to check column values after split
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_after_split_to_be_in_set.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_after_split_to_be_unique.py
Labels: community

#7125 [DOCS] Add displayHTML method to view Data Docs
  docs/deployment_patterns/how_to_use_great_expectations_in_databricks.md
Labels: community

#7132 [BUGFIX] Properly Enable/Disable Spark Integration Tests Depending on pyspark Installation for New Datasources
  tests/experimental/datasources/integration/conftest.py
Labels: core-team, platform

#7131 [DOCS] Use named snippets part 1
  docs/deployment_patterns/how_to_use_great_expectations_in_aws_glue.md
  docs/deployment_patterns/how_to_use_great_expectations_in_databricks.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_create_tab_yaml.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_run.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_save_tab_yaml.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_test_tab_yaml.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_expectation_suite_add_expectations_with_validator.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_expectation_suite_save.md
  docs/scripts/remark-named-snippets/snippet.js
  tests/integration/docusaurus/deployment_patterns/aws_glue_deployment_patterns.py
  tests/integration/docusaurus/deployment_patterns/aws_glue_deployment_patterns_great_expectations.yaml
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_dataframe_python_configs.py
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_dataframe_yaml_configs.py
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_file_python_configs.py
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_file_yaml_configs.py
Labels: core-team, dx

#7054 [MAINTENANCE] format notebooks with `black`
  .pre-commit-config.yaml
  contrib/cli/requirements.txt
  examples/demos/primary_keys_in_validation_results/pandas/Demo-Pandas.ipynb
  examples/demos/primary_keys_in_validation_results/spark/Demo-Spark.ipynb
  examples/demos/primary_keys_in_validation_results/sqlite/Demo-Sql.ipynb
  examples/notebooks/Crop_Expectations_With_Reshape.ipynb
  examples/notebooks/Distributional_Expectations_Demo.ipynb
  examples/notebooks/Distributional_Expectations_Demo_Prep.ipynb
  examples/notebooks/explore_titanic_data.ipynb
  pyproject.toml
  reqs/requirements-dev-contrib.txt
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/postgresql/SetupTestDB.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/BasicExample_RBP_Instantiation_and_running.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running-OnboardingAssistant-Pandas.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running-OnboardingAssistant-Spark.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running-OnboardingAssistant-Sql.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_ConfiguredAssetFileSystemExample_Pandas.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_ConfiguredAssetFileSystemExample_Spark.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_ConfiguredAssetSQLExample_SQL.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_InferredAssetFileSystemExample_Pandas.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_InferredAssetFileSystemExample_Spark.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_InferredAssetSQLExample.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/SelfInitializingExpectations.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project/notebooks/pandas/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project/notebooks/spark/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project/notebooks/sql/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project_with_v30_configuration_and_no_checkpoints/notebooks/pandas/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project_with_v30_configuration_and_no_checkpoints/notebooks/spark/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project_with_v30_configuration_and_no_checkpoints/notebooks/sql/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project_with_v30_configuration_and_v20_checkpoints/notebooks/pandas/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project_with_v30_configuration_and_v20_checkpoints/notebooks/spark/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project_with_v30_configuration_and_v20_checkpoints/notebooks/sql/validation_playground.ipynb
  tests/test_sets/create_test_cases_for_sql_data_connector.ipynb
Labels: core-team, platform

#7136 [DOCS]: fix capitalization of Slack
  docs/intro.md
Labels: community

#7138 [MAINTENANCE] mypy `v1.0.0`
  contrib/cli/requirements.txt
  great_expectations/self_check/util.py
  great_expectations/util.py
  reqs/requirements-dev-contrib.txt
Labels: core-team, platform

#7141 [DOCS] Remove sitemap.xml
  docs/README.md
  docs/sitemap.xml
Labels: core-team, dx

#7142 [BUGFIX] Copy previous versions after checking out the the current commit
  docs/build_docs
Labels: core-team, dx

#7134 [MAINTENANCE] Output Consistent Data Format from "table.head" Metric for every ExecutionEngine
  great_expectations/core/batch.py
  great_expectations/core/batch_manager.py
  great_expectations/datasource/data_connector/data_connector.py
  great_expectations/expectations/metrics/table_metrics/table_head.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/validator/metrics_calculator.py
Labels: core-team, platform

#7137 [MAINTENANCE] ruff 0.0.246 update
  .pre-commit-config.yaml
  contrib/cli/requirements.txt
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/types/base.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/util.py
  great_expectations/expectations/row_conditions.py
  great_expectations/experimental/datasources/file_path_data_asset.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/sql_datasource.py
  great_expectations/validator/validator.py
  reqs/requirements-dev-contrib.txt
  tests/conftest.py
  tests/core/test_serialization.py
Labels: core-team, platform

#7139 [BUGFIX] `TupleAzureBlobStoreBackend` no longer gives warning when obfuscating connection string
  great_expectations/data_context/util.py
  tests/data_context/test_data_context_utils.py
Labels: core-team, dx

#7133 Refactor sql splitter to take selectable instead of str.
  great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_splitter.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  tests/datasource/test_simple_sqlalchemy_datasource.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
Labels: core-team, platform

#7130 [BUGFIX] Patch inconsistent ordering within GCP test asserts
  great_expectations/self_check/util.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between__evaluation_parameters.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_informed.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_naive.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_in_set.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_unique.json
  tests/test_definitions/test_expectations_v3_api.py
Labels: core-team, platform

#7116 [FEATURE] Update polars map metric providers (partial)
  great_expectations/expectations/metrics/column_aggregate_metric_provider.py
  great_expectations/expectations/metrics/map_metric_provider.py
Labels: core-team, dx

#7144 [MAINTENANCE] Update V3 DataConnector utilities to support New Datasources (ZEP)
  great_expectations/checkpoint/checkpoint.py
  great_expectations/datasource/data_connector/configured_asset_filesystem_data_connector.py
  great_expectations/datasource/data_connector/data_connector.py
  great_expectations/datasource/data_connector/file_path_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_filesystem_data_connector.py
  great_expectations/datasource/data_connector/util.py
  great_expectations/util.py
  great_expectations/validator/metrics_calculator.py
  great_expectations/validator/validator.py
Labels: core-team, platform

#7147 [BUGFIX] Parse pandas version correctly for development builds
  great_expectations/experimental/datasources/dynamic_pandas.py
Labels: community

#7149 [MAINTENANCE] Clean up pathlib.Path() usage in DataConnector utilities and restore tighter formatting in great_expectations/util.py
  great_expectations/datasource/data_connector/util.py
  great_expectations/util.py
Labels: core-team, platform

#7155 [BUGFIX] Patch broken rendered content Cloud tests
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/profiler_store.py
Labels: core-team, platform

#7154 [DOCS] doc-464 consolidating and standardizing snippets
  docs/components/_congrats.md
  docs/components/_data.jsx
  docs/components/versions/_gx_version_code_box.mdx
  docs/guides/setup/installation/components_local/_verify_ge_install_succeeded.mdx
  docs/tutorials/getting_started/tutorial_setup.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
Labels: devrel

#7152 [MAINTENANCE] Remove unused dockerfile
  docker/Dockerfile
  docker/build.py
  docker/requirements.txt
Labels: core-team, platform

#6086 [CONTRIB] added new Expectations - India_zip_code expectation and not_to_be_future_date expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_not_to_be_future_date.py
  contrib/great_expectations_zipcode_expectations/expect_column_values_to_be_valid_india_zip.py
Labels: community, devrel

#7159 Delete cli v012 tests.
  tests/cli/v012/__init__.py
  tests/cli/v012/tap.py
  tests/cli/v012/test_checkpoint.py
  tests/cli/v012/test_cli.py
  tests/cli/v012/test_datasource.py
  tests/cli/v012/test_datasource_pandas.py
  tests/cli/v012/test_datasource_snowflake.py
  tests/cli/v012/test_datasource_sqlite.py
  tests/cli/v012/test_docs.py
  tests/cli/v012/test_docs_pre_v013.py
  tests/cli/v012/test_init.py
  tests/cli/v012/test_init_missing_libraries.py
  tests/cli/v012/test_init_pandas.py
  tests/cli/v012/test_init_sqlite.py
  tests/cli/v012/test_project.py
  tests/cli/v012/test_store.py
  tests/cli/v012/test_suite.py
  tests/cli/v012/test_suite_pre_v013.py
  tests/cli/v012/test_toolkit.py
  tests/cli/v012/test_validation_operator.py
  tests/cli/v012/upgrade_helpers/test_upgrade_helper_pre_v013.py
  tests/cli/v012/utils.py
Labels: core-team, platform

#7096 [MAINTENANCE] ZEP - update asset factories method signatures from asset models
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/signatures.py
Labels: zep

#7163 [BUGFIX] pydantic>=1.10.4 - ImportError: cannot import name dataclass_transform
  requirements.txt
Labels: core-team, platform

#7164 [MAINTENANCE] Bump minimum version of `pytest`
  reqs/requirements-dev-lite.txt
Labels: core-team, platform

#7156 [MAINTENANCE] Clean up additional deprecation warnings from outdated CRUD API
  docs/guides/expectations/advanced/how_to_create_a_new_expectation_suite_by_profiling_from_a_jsonschema_file.md
  great_expectations/cli/toolkit.py
  great_expectations/cli/v012/toolkit.py
  great_expectations/core/usage_statistics/usage_statistics.py
  great_expectations/data_asset/data_asset.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/render/renderer/suite_scaffold_notebook_renderer.py
  great_expectations/render/v3/notebook_assets/suite_edit/footer.py.j2
  tests/actions/test_validation_operators.py
  tests/actions/test_validation_operators_in_data_context.py
  tests/checkpoint/conftest.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/cli/test_datasource_pandas.py
  tests/cli/test_suite.py
  tests/core/usage_statistics/test_usage_statistics_data_context.py
  tests/data_context/abstract_data_context/test_abstract_data_context_datasource_crud.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_base_data_context.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_state_management.py
  tests/experimental/datasources/integration/integration_test_utils.py
  tests/integration/docusaurus/expectations/advanced/user_configurable_profiler_cross_table_comparison.py
  tests/integration/docusaurus/expectations/advanced/user_configurable_profiler_cross_table_comparison_from_query.py
  tests/integration/docusaurus/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.py
  tests/integration/docusaurus/reference/core_concepts/result_format.py
  tests/integration/usage_statistics/test_usage_stats_common_messages_are_sent_v3api.py
  tests/performance/taxi_benchmark_util.py
  tests/profile/test_jsonschema_profiler.py
  tests/profile/test_user_configurable_profiler_v2_batch_kwargs.py
  tests/profile/test_user_configurable_profiler_v3_batch_request.py
  tests/render/renderer/test_checkpoint_new_notebook_renderer.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant_happy_paths.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running-OnboardingAssistant-Pandas.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running-OnboardingAssistant-Spark.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running-OnboardingAssistant-Sql.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/DataAssistants_Instantiation_And_Running.ipynb
  tests/test_fixtures/v3/notebook_assets/suite_edit/footer.py.j2
Labels: core-team, platform

#7166 [CONTRIB] Update the rendered text for min and max values to be clearer.
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
Labels: core-team

#7168 [RELEASE] 0.15.49
  docs/changelog.md
  docs/components/_data.jsx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#7151 [FEATURE] Update zep to use sqlalchemy_data_splitter.py
  great_expectations/experimental/datasources/schemas/PostgresDatasource.json
  great_expectations/experimental/datasources/schemas/QueryAsset.json
  great_expectations/experimental/datasources/schemas/SQLDatasource.json
  great_expectations/experimental/datasources/schemas/TableAsset.json
  great_expectations/experimental/datasources/sql_datasource.py
  great_expectations/experimental/datasources/sqlite_datasource.py
  tests/experimental/datasources/conftest.py
  tests/experimental/datasources/integration/conftest.py
  tests/experimental/datasources/integration/test_integration_datasource.py
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_postgres_datasource.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant_happy_paths.py
Labels: core-team, platform

#7121 [FEATURE] ZEP - Dynamically define `add_<ASSET_TYPE>_asset()` methods if needed
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/sources.py
  tests/experimental/datasources/test_pandas_datasource.py
Labels: core-team, platform, zep

#7143 [DOCS] Use named snippets part 2
  docs/deployment_patterns/how_to_use_great_expectations_in_emr_serverless.md
  docs/guides/connecting_to_your_data/cloud/s3/components_spark/_instantiate_your_projects_datacontext.md
  docs/tutorials/getting_started/tutorial_create_expectations.md
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/deployment_patterns/aws_emr_serverless_deployment_patterns.py
  tests/integration/docusaurus/deployment_patterns/aws_emr_serverless_deployment_patterns_great_expectations.yaml
  tests/integration/docusaurus/reference/core_concepts/checkpoints_and_actions.py
  tests/integration/docusaurus/tutorials/getting-started/getting_started.py
Labels: core-team, dx

#5861 [FEATURE] add expectation_column_values_to_be_continuous
  contrib/experimental/great_expectations_experimental/expectations/expect_column_distinct_values_to_be_continuous.py
Labels: community

#7169 [DOCS] Use named snippets part 3
  docs/guides/connecting_to_your_data/cloud/azure/pandas.md
  docs/guides/connecting_to_your_data/cloud/azure/spark.md
  docs/guides/connecting_to_your_data/cloud/gcs/pandas.md
  docs/guides/connecting_to_your_data/cloud/gcs/spark.md
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/pandas/configured_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/pandas/configured_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/pandas/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/spark/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/spark/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/pandas/configured_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/pandas/configured_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/spark/inferred_and_runtime_python_example.py
Labels: core-team, dx

#7167 [DOCS] doc-451 getting started initial conversion to quickstart
  docs/components/_data.jsx
  docs/components/_prerequisites.jsx
  docs/components/creating_expectations/individually/_tip_use_the_expectation_gallery.md
  docs/components/setting_up/installing_gx/_gx_installation_verify_success.md
  docs/components/setting_up/installing_gx/_tip_use_a_venv.md
  docs/components/versions/_gx_version_code_box.mdx
  docs/tutorials/quickstart/quickstart.md
  sidebars.js
Labels: devrel

#7158 [MAINTENANCE] Experimental `PandasDatasource`, single-batch `_PandasDataAsset`s, related schemas
  great_expectations/experimental/datasources/dynamic_pandas.py
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/schemas/PandasCSVAsset.json
  great_expectations/experimental/datasources/schemas/PandasClipboardAsset.json
  great_expectations/experimental/datasources/schemas/PandasDatasource.json
  great_expectations/experimental/datasources/schemas/PandasExcelAsset.json
  great_expectations/experimental/datasources/schemas/PandasFeatherAsset.json
  great_expectations/experimental/datasources/schemas/PandasFwfAsset.json
  great_expectations/experimental/datasources/schemas/PandasGBQAsset.json
  great_expectations/experimental/datasources/schemas/PandasHDFAsset.json
  great_expectations/experimental/datasources/schemas/PandasHTMLAsset.json
  great_expectations/experimental/datasources/schemas/PandasJSONAsset.json
  great_expectations/experimental/datasources/schemas/PandasORCAsset.json
  great_expectations/experimental/datasources/schemas/PandasParquetAsset.json
  great_expectations/experimental/datasources/schemas/PandasSPSSAsset.json
  great_expectations/experimental/datasources/schemas/PandasSQLQueryAsset.json
  great_expectations/experimental/datasources/schemas/PandasSQLTableAsset.json
  great_expectations/experimental/datasources/schemas/PandasSTATAAsset.json
  great_expectations/experimental/datasources/schemas/PandasSqlAsset.json
  great_expectations/experimental/datasources/schemas/PandasTableAsset.json
  great_expectations/experimental/datasources/schemas/PandasXMLAsset.json
  great_expectations/experimental/datasources/schemas/SqliteDatasource.json
  tasks.py
  tests/experimental/datasources/test_schemas.py
Labels: core-team, platform

#7170 [MAINTENANCE] Removing path for `--v2-api upgrade` and informative message
  great_expectations/cli/cli.py
  great_expectations/cli/v012/toolkit.py
  great_expectations/cli/v012/upgrade_helpers/__init__.py
  great_expectations/cli/v012/upgrade_helpers/base_upgrade_helper.py
  great_expectations/cli/v012/upgrade_helpers/upgrade_helper_v11.py
  great_expectations/cli/v012/upgrade_helpers/upgrade_helper_v13.py
  tests/integration/docusaurus/miscellaneous/migration_guide_pandas_v2_api.py
  tests/integration/docusaurus/miscellaneous/migration_guide_pandas_v3_api.py
  tests/integration/docusaurus/miscellaneous/migration_guide_spark_v2_api.py
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/pandas/v3/great_expectations/checkpoints/test_v3_checkpoint.yml
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/spark/v3/great_expectations/checkpoints/test_v3_checkpoint.yml
Labels: core-team, dx

#7177 [BUGFIX] Patch broken Cloud test blocking 0.15.49 release
  tests/data_context/cloud_data_context/test_include_rendered_content.py
Labels: core-team, platform

#7179 Update changelog when updated release 0.15.49
  docs/changelog.md
  docs_rtd/changelog.rst
Labels: core-team, platform

#7094 [FEATURE] Utilize DataConnector in service of new DataAsset implementations
  great_expectations/core/batch.py
  great_expectations/experimental/datasources/data_asset/data_connector/__init__.py
  great_expectations/experimental/datasources/data_asset/data_connector/data_connector.py
  great_expectations/experimental/datasources/data_asset/data_connector/file_path_data_connector.py
  great_expectations/experimental/datasources/data_asset/data_connector/filesystem_data_connector.py
  great_expectations/experimental/datasources/data_asset/data_connector/s3_data_connector.py
  great_expectations/experimental/datasources/file_path_data_asset.py
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/schemas/CSVAsset.json
  great_expectations/experimental/datasources/schemas/CSVSparkAsset.json
  great_expectations/experimental/datasources/schemas/ExcelAsset.json
  great_expectations/experimental/datasources/schemas/FeatherAsset.json
  great_expectations/experimental/datasources/schemas/HDFAsset.json
  great_expectations/experimental/datasources/schemas/HTMLAsset.json
  great_expectations/experimental/datasources/schemas/JSONAsset.json
  great_expectations/experimental/datasources/schemas/ORCAsset.json
  great_expectations/experimental/datasources/schemas/PandasFilesystemDatasource.json
  great_expectations/experimental/datasources/schemas/ParquetAsset.json
  great_expectations/experimental/datasources/schemas/PickleAsset.json
  great_expectations/experimental/datasources/schemas/SPSSAsset.json
  great_expectations/experimental/datasources/schemas/STATAAsset.json
  great_expectations/experimental/datasources/schemas/SparkDatasource.json
  great_expectations/experimental/datasources/schemas/XMLAsset.json
  great_expectations/experimental/datasources/spark_datasource.py
  great_expectations/util.py
  tests/experimental/datasources/data_asset/__init__.py
  tests/experimental/datasources/data_asset/data_connector/__init__.py
  tests/experimental/datasources/data_asset/data_connector/test_filesystem_data_connector.py
  tests/experimental/datasources/data_asset/data_connector/test_s3_data_connector.py
  tests/experimental/datasources/integration/__init__.py
  tests/experimental/datasources/test_pandas_datasource.py
  tests/experimental/datasources/test_spark_datasource.py
Labels: core-team, platform, zep

#7181 [DOCS] Use named snippets part 5
  docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.md
  docs/terms/_batches_and_batch_requests.mdx
  tests/integration/docusaurus/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.py
Labels: core-team, dx

#7174 [MAINTENANCE] Raise store config `ClassInstantiationError` from original `DataContextError`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/store/store.py
Labels: core-team, platform

#7178 [MAINTENANCE] New Datasources: Delineate "SparkFilesystemDatasource" (instead of "SparkDatasource") -- to be congruent with "PandasFilesystemDatasource"
  great_expectations/experimental/datasources/__init__.py
  great_expectations/experimental/datasources/data_asset/data_connector/filesystem_data_connector.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/schemas/SparkFilesystemDatasource.json
  great_expectations/experimental/datasources/spark_datasource.py
  tests/experimental/datasources/integration/conftest.py
  tests/experimental/datasources/test_spark_datasource.py
Labels: core-team, platform

#7190 [MAINTENANCE] Small Refactor to Enable PandasDatsource for multiple Storage Environments
  great_expectations/experimental/datasources/__init__.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/pandas_filesystem_datasource.py
  tasks.py
  tests/experimental/datasources/test_pandas_filesystem_datasource.py
Labels: core-team, platform

#7176 [DOCS] Use named snippets part 4
  docs/guides/connecting_to_your_data/cloud/s3/components_spark/_configure_your_datasource.md
  docs/guides/connecting_to_your_data/cloud/s3/components_spark/_save_the_datasource_configuration_to_your_datacontext.md
  docs/guides/connecting_to_your_data/cloud/s3/components_spark/_test_your_new_datasource.md
  docs/guides/connecting_to_your_data/database/components/_datasource_redshift_configuration.md
  docs/guides/connecting_to_your_data/database/components/_datasource_redshift_test.md
  docs/guides/connecting_to_your_data/database/mssql.md
  docs/guides/connecting_to_your_data/database/mysql.md
  docs/terms/checkpoint.md
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/mssql_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/mssql_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/mysql_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/mysql_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/redshift_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/redshift_yaml_example.py
  tests/integration/docusaurus/reference/core_concepts/checkpoints_and_actions.py
Labels: core-team, dx

#7183 [FEATURE] F/great 1393/add initial non datetime sql splitters
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/schemas/PostgresDatasource.json
  great_expectations/experimental/datasources/schemas/QueryAsset.json
  great_expectations/experimental/datasources/schemas/SQLDatasource.json
  great_expectations/experimental/datasources/schemas/SqliteDatasource.json
  great_expectations/experimental/datasources/schemas/TableAsset.json
  great_expectations/experimental/datasources/sql_datasource.py
  tests/experimental/datasources/conftest.py
  tests/experimental/datasources/great_expectations.yml
  tests/experimental/datasources/integration/test_integration_datasource.py
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_postgres_datasource.py
  tests/experimental/datasources/test_viral_snippets.py
Labels: core-team, platform

#7171 [DOCS] Use named snippets part 6
  docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/guides/connecting_to_your_data/filesystem/spark.md
  docs/guides/connecting_to_your_data/how_to_configure_a_configuredassetdataconnector.md
  docs/guides/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.md
  docs_pending/tutorial_create_expectations_onboarding_assistant.md
  tests/integration/docusaurus/connecting_to_your_data/filesystem/spark_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/spark_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_configure_a_configuredassetdataconnector.py
  tests/integration/docusaurus/tutorials/getting-started/getting_started.py
  tests/integration/fixtures/gcp_deployment/ge_checkpoint_bigquery.py
  tests/integration/fixtures/gcp_deployment/ge_checkpoint_gcs.py
Labels: core-team, dx

#7192 [DOCS] Use named snippets part 7
  docs/guides/expectations/advanced/how_to_create_a_new_expectation_suite_using_rule_based_profilers.md
  docs/guides/setup/configuring_data_contexts/how_to_configure_credentials.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_gcs.md
  docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_gcs.md
  tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py
  tests/integration/docusaurus/setup/configuring_data_contexts/how_to_configure_credentials.py
  tests/integration/docusaurus/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_gcs.py
  tests/integration/docusaurus/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_gcs.py
Labels: core-team, dx

#7173 [FEATURE] Experimental `PandasDatasource` with single-batch `_PandasDataAsset`s
  great_expectations/core/batch_spec.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/experimental/datasources/dynamic_pandas.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/pandas_filesystem_datasource.py
  great_expectations/experimental/datasources/schemas/PandasCSVAsset.json
  great_expectations/experimental/datasources/schemas/PandasDatasource.json
  great_expectations/experimental/datasources/schemas/PandasHTMLAsset.json
  great_expectations/experimental/datasources/schemas/PandasORCAsset.json
  great_expectations/experimental/datasources/schemas/PandasPickleAsset.json
  great_expectations/experimental/datasources/schemas/PandasSTATAAsset.json
  great_expectations/experimental/datasources/schemas/PandasTableAsset.json
  great_expectations/experimental/datasources/schemas/PandasXMLAsset.json
  great_expectations/experimental/datasources/schemas/XMLAsset.json
  tests/experimental/datasources/test_pandas_datasource.py
  tests/experimental/datasources/test_pandas_filesystem_datasource.py
Labels: core-team, platform

#7129 [FEATURE] Experimental filesystem `DataAsset`s `path` in batch request options and batch metadata
  great_expectations/core/util.py
  great_expectations/experimental/datasources/file_path_data_asset.py
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/pandas_filesystem_datasource.py
  great_expectations/experimental/datasources/spark_datasource.py
  great_expectations/experimental/datasources/sql_datasource.py
  tests/experimental/datasources/integration/conftest.py
  tests/experimental/datasources/integration/test_integration_datasource.py
  tests/experimental/datasources/test_pandas_filesystem_datasource.py
  tests/experimental/datasources/test_spark_datasource.py
Labels: core-team, platform

#7187 [BUGFIX]: Allow CLI to work with `RuntimeDataConnector`
  great_expectations/cli/toolkit.py
  tests/cli/test_toolkit.py
Labels: community

#7189 [BUGFIX] Patch GX Cloud `validator.save_expectation_suite()` workflow
  great_expectations/data_context/data_context/cloud_data_context.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
Labels: core-team, platform

#7195 [DOCS] Use named snippets part 9
  docs/guides/expectations/how_to_use_auto_initializing_expectations.md
  docs/guides/miscellaneous/how_to_template.md
  docs/guides/miscellaneous/how_to_write_a_how_to_guide.md
  docs/guides/miscellaneous/migration_guide.md
  scripts/validate_docs_snippets.py
  tests/integration/docusaurus/expectations/auto_initializing_expectations/auto_initializing_expect_column_mean_to_be_between.py
  tests/integration/docusaurus/expectations/auto_initializing_expectations/is_expectation_auto_initializing.py
  tests/integration/docusaurus/template/script_example.py
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/pandas/v2/great_expectations/checkpoints/test_v2_checkpoint.yml
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/pandas/v2/great_expectations/great_expectations.yml
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/pandas/v3/great_expectations/checkpoints/test_v3_checkpoint.yml
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/pandas/v3/great_expectations/great_expectations.yml
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/postgresql/v2/great_expectations/checkpoints/test_v2_checkpoint.yml
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/postgresql/v2/great_expectations/great_expectations.yml
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/postgresql/v3/great_expectations/checkpoints/test_v3_checkpoint.yml
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/postgresql/v3/great_expectations/great_expectations.yml
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/spark/v2/great_expectations/checkpoints/test_v2_checkpoint.yml
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/spark/v2/great_expectations/great_expectations.yml
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/spark/v3/great_expectations/checkpoints/test_v3_checkpoint.yml
  tests/test_fixtures/configuration_for_testing_v2_v3_migration/spark/v3/great_expectations/great_expectations.yml
Labels: core-team, dx

#7201 [DOCS] Use named snippets part 11
  docs/guides/connecting_to_your_data/cloud/s3/components_pandas/_configure_your_datasource.mdx
  docs/guides/connecting_to_your_data/cloud/s3/components_pandas/_instantiate_your_projects_datacontext.mdx
  docs/guides/connecting_to_your_data/cloud/s3/components_pandas/_save_the_datasource_configuration_to_your_datacontext.mdx
  docs/guides/connecting_to_your_data/cloud/s3/components_pandas/_test_your_new_datasource.mdx
  docs/guides/connecting_to_your_data/connect_to_data_overview.md
  docs/guides/connecting_to_your_data/filesystem/pandas.md
  docs/guides/connecting_to_your_data/how_to_configure_a_dataconnector_to_introspect_and_partition_a_file_system_or_blob_store.md
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/pandas/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/pandas/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/pandas_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/pandas_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_introspect_and_partition_your_data/files/yaml_example_gradual.py
Labels: core-team, dx

#7196 [FEATURE] Default `PandasDatasource`
  great_expectations/core/util.py
  great_expectations/experimental/datasources/sources.py
  tests/experimental/datasources/integration/conftest.py
  tests/experimental/datasources/integration/integration_test_utils.py
  tests/experimental/datasources/test_pandas_datasource.py
  tests/experimental/datasources/test_pandas_filesystem_datasource.py
Labels: core-team, platform

#7194 [DOCS] Use named snippets part 8
  docs/guides/connecting_to_your_data/filesystem/pandas.md
  docs/guides/connecting_to_your_data/how_to_configure_a_configuredassetdataconnector.md
  docs/guides/connecting_to_your_data/how_to_create_a_batch_of_data_from_an_in_memory_spark_or_pandas_dataframe.md
  docs/guides/connecting_to_your_data/in_memory/spark.md
  tests/integration/docusaurus/connecting_to_your_data/filesystem/pandas_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/pandas_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_create_a_batch_of_data_from_an_in_memory_pandas_dataframe.py
  tests/integration/docusaurus/connecting_to_your_data/in_memory/spark_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/in_memory/spark_yaml_example.py
Labels: core-team, dx

#7199 [DOCS] Use named snippets part 10
  docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_a_file_system_or_blob_store.md
  docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_tables_in_sql.md
  docs/guides/connecting_to_your_data/database/postgres.md
  docs/guides/connecting_to_your_data/database/redshift.md
  docs/guides/connecting_to_your_data/database/snowflake.md
  docs/guides/connecting_to_your_data/database/sqlite.md
  docs/guides/connecting_to_your_data/database/trino.md
  docs/guides/connecting_to_your_data/how_to_configure_a_runtimedataconnector.md
  docs/guides/connecting_to_your_data/how_to_configure_an_inferredassetdataconnector.md
  docs/guides/connecting_to_your_data/how_to_get_one_or_more_batches_of_data_from_a_configured_datasource.md
  tests/integration/docusaurus/connecting_to_your_data/database/postgres_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/redshift_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/snowflake_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/snowflake_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/sqlite_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/sqlite_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/trino_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_configure_a_runtimedataconnector.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_configure_an_inferredassetdataconnector.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_get_one_or_more_batches_of_data_from_a_configured_datasource.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_introspect_and_partition_your_data/files/yaml_example_complete.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_introspect_and_partition_your_data/sql_database/yaml_example_complete.py
Labels: core-team, dx

#7207 [MAINTENANCE] Replace `regex` with `batching_regex` for fluent filesystem-like datasources
  great_expectations/experimental/datasources/data_asset/data_connector/file_path_data_connector.py
  great_expectations/experimental/datasources/data_asset/data_connector/filesystem_data_connector.py
  great_expectations/experimental/datasources/data_asset/data_connector/s3_data_connector.py
  great_expectations/experimental/datasources/file_path_data_asset.py
  great_expectations/experimental/datasources/filesystem_data_asset.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_filesystem_datasource.py
  great_expectations/experimental/datasources/schemas/CSVAsset.json
  great_expectations/experimental/datasources/schemas/CSVSparkAsset.json
  great_expectations/experimental/datasources/schemas/ExcelAsset.json
  great_expectations/experimental/datasources/schemas/FeatherAsset.json
  great_expectations/experimental/datasources/schemas/HDFAsset.json
  great_expectations/experimental/datasources/schemas/HTMLAsset.json
  great_expectations/experimental/datasources/schemas/JSONAsset.json
  great_expectations/experimental/datasources/schemas/ORCAsset.json
  great_expectations/experimental/datasources/schemas/PandasFilesystemDatasource.json
  great_expectations/experimental/datasources/schemas/ParquetAsset.json
  great_expectations/experimental/datasources/schemas/PickleAsset.json
  great_expectations/experimental/datasources/schemas/SPSSAsset.json
  great_expectations/experimental/datasources/schemas/STATAAsset.json
  great_expectations/experimental/datasources/schemas/SparkFilesystemDatasource.json
  great_expectations/experimental/datasources/schemas/XMLAsset.json
  great_expectations/experimental/datasources/spark_datasource.py
  tests/experimental/datasources/data_asset/data_connector/test_filesystem_data_connector.py
  tests/experimental/datasources/data_asset/data_connector/test_s3_data_connector.py
  tests/experimental/datasources/integration/conftest.py
  tests/experimental/datasources/integration/test_integration_datasource.py
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_pandas_filesystem_datasource.py
  tests/experimental/datasources/test_spark_datasource.py
Labels: core-team, platform

#7211 [DOCS] Fix broken link in anonymous_usage_statistics.md
  docs/reference/anonymous_usage_statistics.md
Labels: community

#7212 [BUGFIX] Dynamic pandas asset model field substitution
  great_expectations/experimental/datasources/dynamic_pandas.py
Labels: core-team, platform

#7210 [DOCS] doc-471 Restructure the block-configuration ToC entries
  docs/tutorials/getting_started/tutorial_connect_to_data.md
  docs/tutorials/getting_started/tutorial_create_expectations.md
  docs/tutorials/getting_started/tutorial_overview.md
  docs/tutorials/getting_started/tutorial_review.md
  docs/tutorials/getting_started/tutorial_setup.md
  docs/tutorials/getting_started/tutorial_validate_data.md
  docs/tutorials/quickstart/quickstart.md
  sidebars.js
  static/_redirects
Labels: devrel

#7215 [MAINTENANCE] Misc `DataContext` state management & API cleanup
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/data_context/test_data_context_state_management.py
Labels: core-team, platform

#7214 [DOCS] Use named snippets part 12
  docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/guides/connecting_to_your_data/in_memory/pandas.md
  docs/scripts/remark-named-snippets/index.js
  tests/integration/docusaurus/connecting_to_your_data/in_memory/pandas_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/in_memory/pandas_yaml_example.py
  tests/integration/fixtures/gcp_deployment/great_expectations/great_expectations.yml
Labels: core-team, dx

#7218 [RELEASE] 0.15.50
  docs/changelog.md
  docs/components/_data.jsx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#7216 [MAINTENANCE] No line number snippets checker
  azure-pipelines-dev.yml
  azure-pipelines-docs-integration.yml
  azure-pipelines.yml
  docusaurus.config.js
  package.json
  scripts/check_no_line_number_snippets.py
Labels: core-team, dx

#7221 [DOCS] Versioning instructions and fix references for versioning
  docs/README.md
  docs/deployment_patterns/how_to_use_great_expectations_in_flyte.md
  docs/guides/expectations/advanced/how_to_create_expectations_that_span_multiple_batches_using_evaluation_parameters.md
  docs/intro.md
  docs/tutorials/getting_started/tutorial_validate_data.md
Labels: core-team, dx

#7217 [MAINTENANCE] Re-enable snippet checker
  docs/README.md
  scripts/validate_docs_snippets.py
Labels: core-team, dx

#7222 [DOCS] Fix links to images in welcome page
  docs/intro.md
  scripts/docs_link_checker.py
Labels: core-team, dx

#7223 [MAINTENANCE] Refactor New SparkDatasource in order to prepare for adding support for Cloud Files Storage environments
  great_expectations/experimental/datasources/__init__.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/pandas_filesystem_datasource.py
  great_expectations/experimental/datasources/schemas/SparkFilesystemDatasource.json
  great_expectations/experimental/datasources/schemas/SparkFilesystemDatasource/CSVSparkAsset.json
  great_expectations/experimental/datasources/spark_datasource.py
  great_expectations/experimental/datasources/spark_file_path_datasource.py
  great_expectations/experimental/datasources/spark_filesystem_datasource.py
  tests/experimental/datasources/test_pandas_s3_datasource.py
  tests/experimental/datasources/test_spark_filesystem_datasource.py
Labels: core-team, platform

#7220 [BUGFIX] `docs-integration` tests failing after CRUD updates
  great_expectations/core/usage_statistics/usage_statistics.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_configure_a_runtimedataconnector.py
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_dataframe_yaml_configs.py
  tests/integration/docusaurus/expectations/auto_initializing_expectations/auto_initializing_expect_column_mean_to_be_between.py
  tests/integration/docusaurus/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.py
  tests/integration/docusaurus/reference/core_concepts/checkpoints_and_actions.py
  tests/integration/test_script_runner.py
Labels: core-team, dx

#7186 [CONTRIB]-add athena credential support
  azure-pipelines-dev.yml
  great_expectations/cli/datasource.py
  reqs/requirements-dev-athena.txt
  tests/cli/test_datasource_athena.py
  tests/cli/test_datasource_new_helpers.py
  tests/cli/test_datasource_sqlite.py
Labels: community

#6588 [FEATURE] Improve Trino types support
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/metrics/util.py
Labels: community

#7230 [DOCS] Add API docs build to versioning instructions
  docs/docusaurus/README.md
Labels: core-team, dx
