Repository great-expectations/great_expectations, pull requests merged in 2023-08, with the labels that each got.

#8443 [MAINTENANCE] Run cloud e2e tests.
  .github/workflows/ci.yml
  tests/__init__.py
  tests/conftest.py
  tests/datasource/fluent/test_config.py
  tests/datasource/fluent/test_schemas.py
  tests/validator/test_validator.py
Labels: core

#8452 [MAINTENANCE] Start testing clickhouse in github actions.
  .github/workflows/ci.yml
  tasks.py
Labels: core

#8460 [MAINTENANCE] Github Actions - Spark tests
  .github/workflows/ci.yml
  assets/docker/spark/docker-compose.yml
  tasks.py
Labels: core

#8455 [MAINTENANCE] Pytest Github Action - Add more backends to Docs Snippet stage
  .github/workflows/ci.yml
  tasks.py
Labels: dx, core

#8458 [MAINTENANCE] Remove external_sqldialect marker as test coverage marker.
  .github/workflows/ci.yml
  pyproject.toml
  tasks.py
  tests/conftest.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
  tests/expectations/core/test_expect_column_values_to_be_in_type_list.py
  tests/expectations/core/test_expect_column_values_to_be_of_type.py
  tests/expectations/test_run_diagnostics.py
  tests/expectations/test_run_diagnostics_supporting_methods.py
  tests/expectations/test_util.py
  tests/performance/test_bigquery_benchmarks.py
  tests/profile/test_basic_suite_builder_profiler.py
Labels: core

#8437 [DOCS] Remove Expectation Implementations by Backend Topic
  docs/docusaurus/docs/reference/expectations/implemented_expectations.md
  docs/docusaurus/docs/terms/expectation.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
  tests/integration/docusaurus/deployment_patterns/aws_glue_deployment_patterns.py
Labels: devrel

#8417 [MAINTENANCE] Pytest Github Action - BigQuery and Postgres
  .github/workflows/ci.yml
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  tasks.py
  tests/scripts/test_public_api_report.py
  tests/test_utils.py
Labels: dx, core

#8465 [MAINTENANCE] Run `marker-tests` after `unit-tests` and `static-analysis`
  .github/workflows/ci.yml
  tasks.py
Labels: core

#8467 [MAINTENANCE] Run all_backend tests along with specific service tests.
  tasks.py
Labels: core

#8466 [MAINTENANCE] AWS Glue script using Context Manager to catch `FutureWarning`
  tests/integration/docusaurus/deployment_patterns/aws_glue_deployment_patterns.py
Labels: dx, core

#8462 [MAINTENANCE] Remove old required tests which have been replaced.
  .github/workflows/ci.yml
  tasks.py
Labels: core

#8463 [MAINTENANCE] Run all python versions on scheduled run
  .github/workflows/ci.yml
  .pre-commit-config.yaml
Labels: core

#8471 [MAINTENANCE] `min-versions` wait for `unit-tests`, `static-analysis`
  .github/workflows/ci.yml
Labels: core

#8473 [MAINTENANCE] Remove Azure Dev CI steps
  ci/azure-pipelines-dev.yml
Labels: core

#8472 [DOCS] Update the API Reference Landing Page
  docs/docusaurus/docs/reference/api_reference.md
Labels: devrel

#8475 [DOCS] Fix Grid Autosizing
  docs/docusaurus/docs/components/LinkCardGrid/styles.module.css
Labels: devrel

#8450 [MAINTENANCE] Update ListTableNamesAction to use GxAgentEnvVars
  great_expectations/agent/actions/list_table_names.py
  tests/agent/actions/test_list_table_names_action.py
Labels: maintenance, cloud, core

#8477 [MAINTENANCE] Add check that each test only has one required marker.
  tasks.py
  tests/checkpoint/test_checkpoint.py
  tests/cli/test_batch_request.py
  tests/cli/test_datasource_new_helpers.py
  tests/cli/test_toolkit.py
  tests/conftest.py
  tests/core/test_config_provider.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/datasource/test_data_context_datasource_non_sql_methods_sparkdf_execution_engine.py
  tests/data_context/migrator/test_cloud_migrator.py
  tests/data_context/migrator/test_configuration_bundle.py
  tests/data_context/store/test_checkpoint_store.py
  tests/data_context/store/test_data_context_store.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
  tests/data_context/store/test_expectations_store.py
  tests/data_context/store/test_ge_cloud_store_backend.py
  tests/data_context/store/test_profiler_store.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/store/test_validations_store.py
  tests/data_context/test_data_context_datasources.py
  tests/data_context/test_data_context_deprecation.py
  tests/data_context/test_data_context_ge_cloud_mode.py
  tests/data_context/test_data_context_utils.py
  tests/datasource/fluent/test_contexts.py
  tests/datasource/test_new_datasource.py
  tests/performance/test_bigquery_benchmarks.py
  tests/rule_based_profiler/parameter_builder/test_unexpected_count_statistics_multi_batch_parameter_builder.py
  tests/rule_based_profiler/test_rule_based_profiler.py
  tests/scripts/test_public_api_report.py
  tests/test_definitions/test_expectations_v3_api.py
  tests/test_markers.py
  tests/test_the_utils_in_test_utils.py
Labels: core

#8461 [MAINTENANCE] Add test case for run_name_template using env_var
  tests/data_context/test_data_context_data_docs_api.py
Labels: core

#8476 [MAINTENANCE] Delete `azure-pipelines-dev.yml`
  .github/workflows/ci.yml
  ci/azure-pipelines-dev.yml
Labels: core

#8464 [BUGFIX] PP-282: fixing update_datasource method bug
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/data_context/test_data_context_state_management.py
Labels: core

#8478 [MAINTENANCE] Test out releaser github action
  .github/workflows/release.yml
Labels: dx, core

#8480 [BUGFIX] Add `performance` marker to `pyproject.toml`
  pyproject.toml
Labels: dx, core

#8481 [MAINTENANCE] Add missing marker to pyproject.toml
  pyproject.toml
Labels: core

#8406 [DOCS] Update Use Great Expectations with Amazon Web Services using Athena
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docs/components/prerequisites/_python_version.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_aws_cli_verify_installation.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_create_and_run.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_create_tab_python.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_create_tab_yaml.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_create_tabs.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_run.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_save.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_data_docs_build_and_view.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_datasource_code_environment.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_datasource_sql_runtime_configuration.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_expectation_suite_add_expectations_with_validator.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_expectation_suite_batch_request_validator_prepare_or_reuse.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_python_where_to_get.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_athena.md
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/s3/components_pandas/_instantiate_your_projects_datacontext.mdx
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/s3/components_pandas/_save_the_datasource_configuration_to_your_datacontext.mdx
  docs/docusaurus/docs/guides/connecting_to_your_data/database/components/_connection_string_athena.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/components/_datasource_athena_test.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/components_how_to_host_and_share_data_docs_on_amazon_s3/_add_a_new_s3_site_to_the_data_docs_sites_section_of_your_great_expectationsyml.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_docs/components_how_to_host_and_share_data_docs_on_amazon_s3/_additional_notes.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_docs/components_how_to_host_and_share_data_docs_on_amazon_s3/_configure_your_bucket_policy_to_enable_appropriate_access.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_docs/components_how_to_host_and_share_data_docs_on_amazon_s3/_create_an_s3_bucket.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_docs/components_how_to_host_and_share_data_docs_on_amazon_s3/_test_that_your_configuration_is_correct_by_building_the_site.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components/_install_boto3_with_pip.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components/_verify_aws_credentials_are_configured_properly.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_confirm_that_the_new_expectations_store_has_been_added_by_running_great_expectations_store_list.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_copy_existing_expectation_json_files_to_the_s_bucket_this_step_is_optional.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_update_your_configuration_file_to_include_a_new_store_for_expectations_on_s.mdx
  docs/docusaurus/docs/guides/setup/installation/components_local/_check_python_version.mdx
  docs/docusaurus/docs/guides/setup/installation/components_local/_create_an_venv_with_pip.mdx
  docs/docusaurus/docs/guides/setup/installation/components_local/_ensure_latest_pip.mdx
  docs/docusaurus/docs/guides/setup/installation/components_local/_install_ge_with_pip.mdx
  docs/docusaurus/docs/guides/setup/installation/components_local/_verify_ge_install_succeeded.mdx
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  tests/integration/db/awsathena.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/pandas/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/athena_python_example.py
  tests/integration/docusaurus/deployment_patterns/aws_cloud_storage_pandas.py
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_dataframe_python_configs.py
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_dataframe_yaml_configs.py
Labels: devrel

#8485 [MAINTENANCE] Slack notifications if non-pr ci github action pipeline fails
  .github/workflows/ci.yml
Labels: core

#8486 [MAINTENANCE] Run additional matrix steps on any non-`pull_request` event
  .github/workflows/ci.yml
Labels: core

#8470 [DOCS] add `public_api` decorator to `TableAsset` and `QueryAsset`
  great_expectations/datasource/fluent/schemas/DatabricksSQLDatasource.json
  great_expectations/datasource/fluent/schemas/DatabricksSQLDatasource/QueryAsset.json
  great_expectations/datasource/fluent/schemas/DatabricksSQLDatasource/TableAsset.json
  great_expectations/datasource/fluent/schemas/PostgresDatasource.json
  great_expectations/datasource/fluent/schemas/PostgresDatasource/QueryAsset.json
  great_expectations/datasource/fluent/schemas/PostgresDatasource/TableAsset.json
  great_expectations/datasource/fluent/schemas/SQLDatasource.json
  great_expectations/datasource/fluent/schemas/SQLDatasource/QueryAsset.json
  great_expectations/datasource/fluent/schemas/SQLDatasource/TableAsset.json
  great_expectations/datasource/fluent/schemas/SnowflakeDatasource.json
  great_expectations/datasource/fluent/schemas/SnowflakeDatasource/QueryAsset.json
  great_expectations/datasource/fluent/schemas/SnowflakeDatasource/TableAsset.json
  great_expectations/datasource/fluent/schemas/SqliteDatasource.json
  great_expectations/datasource/fluent/schemas/SqliteDatasource/SqliteQueryAsset.json
  great_expectations/datasource/fluent/schemas/SqliteDatasource/SqliteTableAsset.json
  great_expectations/datasource/fluent/sql_datasource.py
Labels: documentation, docs, core

#8442 [BUGFIX] Fix Postgres, Trino quoted identifier issues
  great_expectations/datasource/fluent/sql_datasource.py
  tests/datasource/fluent/integration/test_sql_datasources.py
  tests/datasource/fluent/test_sql_datasources.py
Labels: core

#8484 [MAINTENANCE] GX-Release Process update to use GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/release.yml
  ci/azure-pipelines.yml
Labels: dx, core

#8491 [RELEASE] 0.17.8
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8495 [MAINTENANCE] Notify on build-n-publish failure.
  .github/workflows/ci.yml
Labels: core

#8497 [MAINTENANCE] Send slack notification on release
  .github/workflows/ci.yml
Labels: core

#8492 [DOCS] Update Code Example for Viewing a Full Checkpoint Configuration
  docs/docusaurus/docs/tutorials/getting_started/how_to_use_great_expectations_in_databricks.md
  docs/docusaurus/docs/tutorials/getting_started/how_to_use_great_expectations_with_sql.md
Labels: devrel

#8499 [MAINTENANCE] Removed unused github action.
  .github/workflows/test-sqlalchemy-latest.yml
Labels: core

#8506 [MAINTENANCE] Change default testing level from WARNING to INFO
  pyproject.toml
Labels: core

#8445 [DOCS] Add New Topic for Connecting to In-Memory Source Data Using Spark
  docs/docusaurus/docs/components/connect_to_data/link_lists/_connect_to_in_memory_data_fluently.md
  docs/docusaurus/docs/components/connect_to_data/link_lists/_connecting_to_data_fluently.md
  docs/docusaurus/docs/guides/connecting_to_your_data/connect_to_data_lp.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/in_memory/connect_in_memory_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/in_memory/how_to_connect_to_in_memory_data_using_pandas.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_in_memory_data_using_spark.py
  tests/integration/test_script_runner.py
Labels: devrel

#8496 [DOCS] Remove Unused Documentation Style Guide Topic
  .github/pull_request_template.md
  docs/docusaurus/docs/contributing/style_guides/docs_style.md
  docs/docusaurus/static/_redirects
Labels: devrel

#8513 [BUGFIX] PR title checker's code should handle apostrophes
  .github/workflows/pr-title-checker.yml
Labels: core

#8489 [DOCS] Update Links and Content in the Data Context Topic
  docs/docusaurus/docs/conceptual_guides/learn_lp.md
  docs/docusaurus/docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.md
  docs/docusaurus/docs/terms/data_context.md
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
  docs_rtd/reference/core_concepts/metrics.rst
Labels: devrel

#8514 [MAINTENANCE] Mob typing: update list of deprecated, never to be typed files.
  great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py
  great_expectations/datasource/data_connector/sorter/dictionary_sorter.py
  pyproject.toml
Labels: core

#8483 [DOCS] Update Connect to filesystem source data
  docs/docusaurus/docs/components/connect_to_data/link_lists/_connect_to_filesystem_data_fluently.md
  docs/docusaurus/docs/components/connect_to_data/link_lists/_connecting_to_data_fluently.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/connect_filesystem_source_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_connect_to_one_or_more_files_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_connect_to_one_or_more_files_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_quickly_connect_to_a_single_file_with_pandas.md
Labels: devrel

#8509 [MAINTENANCE] Better testing for FDS quoted identifier logic
  great_expectations/datasource/fluent/sql_datasource.py
  tests/datasource/fluent/integration/test_sql_datasources.py
Labels: core

#8515 [MAINTENANCE] Remove Click upper bound constraint.
  great_expectations/cli/cli.py
  great_expectations/cli/python_subprocess.py
  requirements.txt
  tests/test_packaging.py
Labels: core

#8522 [BUGFIX] Patch `add_or_update_expectation_suite` with Cloud-backed contexts
  great_expectations/data_context/data_context/cloud_data_context.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
Labels: core

#8468 [MAINTENANCE] Docs Pipeline Clean up
  .github/workflows/ci.yml
  ci/azure-pipelines-docs.yml
  ci/checks/validate_docs_snippets.py
Labels: dx, core

#8156 [DOCS] Add step to install azure-storage-blob when using azure storage blobs…
  README.md
  docs/docusaurus/docs/components/prerequisites/_abs_created_an_azure_blob_container.md
  docs/docusaurus/docs/components/setup/link_lists/_setup_configurations.md
  docs/docusaurus/docs/components/setup/next_steps/_links_for_adding_azure_blob_storage_configurations_to_data_context.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/docusaurus/docs/guides/setup/components_index/_data_docs.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/initializing_data_contexts/how_to_initialize_a_filesystem_data_context_in_python.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_instantiate_a_specific_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_quickly_instantiate_a_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/instantiate_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/host_and_share_data_docs.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_a_filesystem.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_amazon_s3.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_azure_blob_storage.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_update_your_configuration_file_to_include_a_new_store_for_validation_results_on_s.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_update_your_configuration_file_to_include_a_new_store_for_expectations_on_s.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/configure_expectation_stores.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/configure_result_stores.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_azure_blob_storage.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_gcs.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_azure_blob_storage.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_gcs.md
  docs/docusaurus/docs/reference/customize_your_deployment.md
  docs/docusaurus/docs/terms/data_docs_store.md
  docs/docusaurus/static/_redirects
  docs_rtd/feature_maturity_content.json
Labels: documentation, core

#7040 [DOCS] add python version badge to README
  README.md
Labels: cloud

#8525 [MAINTENANCE] Retire `docs-integration` tests that are already running in GitHub Actions
  .github/workflows/ci.yml
  ci/azure-pipelines-docs-integration.yml
  pyproject.toml
  tasks.py
Labels: dx, core

#8531 [MAINTENANCE] Remove Cross-Table comparison from Docs-Integration, which is already being run
  .github/workflows/ci.yml
  ci/azure-pipelines-docs-integration.yml
Labels: dx, core

#8533 [MAINTENANCE] Github Actions DocsChange Step with Checkout Stage added
  .github/workflows/ci.yml
Labels: dx, core

#8529 [RELEASE] 0.17.9
  .github/workflows/ci.yml
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#7014 [DOCS] Update URL to blog post for anonymous stats
  docs_rtd/reference/spare_parts/data_context_reference.rst
Labels: cloud

#8321 [DOCS] Updates Quickstart guide
  docs/docusaurus/docs/components/_prerequisites.jsx
  docs/docusaurus/docs/components/prerequisites/_if_you_still_need_to_setup_gx.md
  docs/docusaurus/docs/components/setup/link_lists/_setup_and_install_for_filesystem_data.md
  docs/docusaurus/docs/guides/setup/installation/components_local/_preface.mdx
  docs/docusaurus/docs/guides/setup/installation/hosted_environment.md
  docs/docusaurus/docs/guides/setup/installation/local.md
  docs/docusaurus/docs/team_templates/conceptual_template.md
  docs/docusaurus/docs/team_templates/how_to_template.md
  docs/docusaurus/docs/team_templates/reference_template.md
  docs/docusaurus/docs/team_templates/tutorial_template.md
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
  docs/docusaurus/static/_redirects
Labels: devrel

#8539 [DOCS] Relocate Compare Two Tables with the Onboarding Data Assistant
  docs/docusaurus/docs/guides/expectations/create_manage_expectations_lp.md
  docs/docusaurus/docs/guides/expectations/profilers_data_assistants_lp.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8523 [BUGFIX] DatabricksSQL TableAsset quoted identifiers
  .github/workflows/ci.yml
  assets/docker/databricks/docker-compose.yml
  great_expectations/compatibility/sqlalchemy.py
  great_expectations/datasource/fluent/databricks_sql_datasource.py
  great_expectations/datasource/fluent/schemas/DatabricksSQLDatasource/DatabricksTableAsset.json
  pyproject.toml
  tasks.py
  tests/conftest.py
  tests/datasource/fluent/integration/test_sql_datasources.py
  tests/datasource/fluent/test_databricks_sql_datasource.py
Labels: core

#8382 [CONTRIB] Updating Special Characters Expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_not_contain_special_characters.py
Labels: community

#8521 [DOCS] Update to exact_match parameter: expect_table_columns_to_match_set
  great_expectations/expectations/core/expect_table_columns_to_match_set.py
Labels: community

#8512 [BUGFIX] Fixed persist to be considered for spark fluent datasource
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDatasource.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource.json
  great_expectations/datasource/fluent/sources.pyi
  great_expectations/datasource/fluent/spark_datasource.py
  tests/datasource/fluent/test_spark_datasource.py
Labels: community

#8541 [MAINTENANCE] Fix marker key
  .github/workflows/ci.yml
  tasks.py
Labels: dx, core

#8542 [MAINTENANCE] Fix conditional in CI
  .github/workflows/ci.yml
Labels: dx, core

#8543 [MAINTENANCE] Ignore distutils warning
  pyproject.toml
Labels: dx, core

#8545 [MAINTENANCE] Fix docs-snippets ci job
  .github/workflows/ci.yml
Labels: dx, core

#8508 [MAINTENANCE] Update Docusaurus to `2.4.1`
  docs/docusaurus/package.json
  docs/docusaurus/yarn.lock
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  great_expectations/checkpoint/types/checkpoint_result.py
  great_expectations/core/expectation_suite.py
  great_expectations/datasource/data_connector/configured_asset_azure_data_connector.py
  great_expectations/expectations/expectation.py
  great_expectations/profile/user_configurable_profiler.py
Labels: dx, core

#8505 [MAINTENANCE] ruff `0.0.282`
  .pre-commit-config.yaml
  assets/scripts/build_gallery.py
  contrib/cli/requirements.txt
  great_expectations/checkpoint/util.py
  great_expectations/compatibility/sqlalchemy_compatibility_wrappers.py
  great_expectations/data_context/store/html_site_store.py
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/datasource/batch_kwargs_generator/glob_reader_batch_kwargs_generator.py
  great_expectations/expectations/expectation.py
  great_expectations/validation_operators/validation_operators.py
  pyproject.toml
  reqs/requirements-dev-contrib.txt
  scripts/build_api_docs.py
  tests/build_index_page.py
  tests/render/test_render_BulletListContentBlock.py
  tests/test_definitions/test_expectations_v3_api.py
  tests/test_deprecation.py
  tests/test_packaging.py
Labels: core

#8498 [BUGFIX] add_splitter_on_column_value
  great_expectations/datasource/fluent/sql_datasource.py
  tests/datasource/fluent/integration/test_integration_datasource.py
  tests/integration/db/taxi_data_utils.py
Labels: core

#8547 [MAINTENANCE] Update `docs snippets` stage in `ci.yml` for scheduled and triggered runs
  .github/workflows/ci.yml
Labels: dx, core

#8544 [BUGFIX] Fix persist is not being reflected for Spark Legacy Datasource
  great_expectations/data_context/types/base.py
  great_expectations/datasource/sparkdf_datasource.py
  tests/datasource/test_sparkdf_datasource.py
  tests/integration/spark/test_spark_config.py
Labels: community

#8526 [BUGFIX] Snowflake column identifiers
  .github/workflows/ci.yml
  great_expectations/expectations/metrics/util.py
  pyproject.toml
  tasks.py
  tests/conftest.py
  tests/datasource/fluent/integration/test_sql_datasources.py
Labels: core

#8555 [MAINTENANCE] Allow duplicate keys in checkpoint configuration with the same values
  great_expectations/checkpoint/util.py
Labels: core

#8557 [MAINTENANCE] airflow220-min-versions
  .github/workflows/ci.yml
Labels: core

#8520 [DOCS] Update Spark Code Examples in Connect to In-memory Source Data
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  tasks.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_in_memory_data_using_spark.py
Labels: devrel

#8532 [FEATURE] Make SQLDatasource.assets field a `tagged-union`
  great_expectations/datasource/fluent/schemas/DatabricksSQLDatasource.json
  great_expectations/datasource/fluent/schemas/PostgresDatasource.json
  great_expectations/datasource/fluent/schemas/SQLDatasource.json
  great_expectations/datasource/fluent/schemas/SnowflakeDatasource.json
  great_expectations/datasource/fluent/schemas/SqliteDatasource.json
  great_expectations/datasource/fluent/sql_datasource.py
  tests/datasource/fluent/test_config.py
Labels: core

#8559 [BUGFIX] Use a randomized schema name when running snowflake tests to support concurrency
  tests/datasource/fluent/integration/test_sql_datasources.py
Labels: bug, core

#8538 [DOCS] Update MetricProviders Conceptual Topic
  docs/docusaurus/docs/conceptual_guides/metricproviders.md
  docs/docusaurus/docs/terms/metric.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8567 [BUGFIX] Skip Snowflake FDS tests for User Forks
  tests/datasource/fluent/integration/test_sql_datasources.py
Labels: bug

#8553 [CONTRIB] expect_multicolumn_values_to_be_equal
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_values_to_be_equal.py
Labels: community

#8562 [CONTRIB] fix query template values metric
  great_expectations/expectations/metrics/query_metrics/query_template_values.py
Labels: community

#8558 [BUGFIX]Fix Agent error types
  great_expectations/agent/actions/data_assistants/utils.py
  tests/agent/actions/data_assistants/test_run_onboarding_data_assistant_action.py
Labels: core

#8568 [BUGFIX] Fix link update for versioned docs when there are multiple links on the same line
  docs/prepare_prior_versions.py
  tests/docs/test_prepare_prior_versions.py
Labels: dx, core

#8572 [BUGFIX] Raise errors when spark column names contain a period for unsupported metrics, fix some metrics
  great_expectations/expectations/metrics/table_metrics/table_column_types.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/helpers/simple_semantic_type_filter.py
  great_expectations/rule_based_profiler/parameter_builder/histogram_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/unexpected_count_statistics_multi_batch_parameter_builder.py
  tests/rule_based_profiler/data_assistant/test_column_value_missing_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
Labels: dx, core

#8576 [RELEASE] 0.17.10
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8577 [MAINTENANCE] Delete deprecated `partition_data`
  great_expectations/dataset/util.py
  tests/data_asset/test_data_asset_util.py
  tests/test_deprecation.py
Labels: core

#8578 [RELEASE] 0.17.11
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8574 [MAINTENANCE] Delete deprecated `get_batch`
  great_expectations/core/batch.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/validation_operators/validation_operators.py
  tests/actions/test_validation_operators.py
  tests/actions/test_validation_operators_in_data_context.py
  tests/data_asset/test_data_asset.py
  tests/data_context/datasource/test_data_context_datasource_sql_methods.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_test_yaml_config.py
  tests/data_context/test_data_context_v013.py
  tests/data_context/test_pandas_datetime_suites.py
  tests/datasource/test_pandas_datasource.py
  tests/datasource/test_sparkdf_datasource.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/pandas_yaml_example.py
  tests/integration/usage_statistics/instantiate_context_with_usage_statistics.py
  tests/profile/test_basic_suite_builder_profiler.py
  tests/profile/test_profile.py
  tests/render/test_data_documentation_site_builder.py
  tests/test_deprecation.py
Labels: core

#8573 [MAINTENANCE] Delete deprecated `add_batch_kwargs_generator`
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/profile/test_profile.py
Labels: core

#8501 [MAINTENANCE] Add typing stubs to `requirements-types.txt`
  great_expectations/data_context/store/metric_store.py
  great_expectations/data_context/store/query_store.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/store/validations_store.py
  great_expectations/types/base.py
  requirements-types.txt
  tasks.py
Labels: core

#8586 [MAINTENANCE] mypy 1.5
  contrib/cli/requirements.txt
  great_expectations/core/expectation_configuration.py
  pyproject.toml
  reqs/requirements-dev-contrib.txt
  tests/datasource/fluent/conftest.py
  tests/test_packaging.py
Labels: dx, core

#8487 [BUGFIX] Fix incorrect type of SqlAlchemyExecutionEngine constructor's arg
  great_expectations/datasource/fluent/sql_datasource.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  tests/datasource/fluent/test_postgres_datasource.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
Labels: community

#8564 [DOCS] Update Data Assistant and Edit an Expectation Suite Topics
  docs/docusaurus/docs/guides/expectations/create_manage_expectations_lp.md
  docs/docusaurus/docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_missingness_data_assistant.md
  docs/docusaurus/docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.md
  docs/docusaurus/docs/guides/expectations/how_to_edit_an_existing_expectationsuite.md
  tests/integration/docusaurus/expectations/how_to_edit_an_expectation_suite.py
Labels: devrel

#8596 [MAINTENANCE] Consistently use `datasources` property on context
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/data_context/abstract_data_context/test_abstract_data_context_datasource_crud.py
Labels: core

#8597 [BUGFIX] Fix faulty logic around writing to .gitignore in context root dir
  great_expectations/data_context/data_context/serializable_data_context.py
  tests/data_context/test_data_context.py
Labels: core

#8584 [MAINTENANCE] Deprecate `BaseDataContext` and `DataContext`
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/data_context.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/cli/upgrade_helpers/test_upgrade_helper.py
  tests/conftest.py
  tests/data_context/test_base_data_context.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_deprecation.py
Labels: core

#8599 [BUGFIX] Update Docs test after DataContext Deprecation
  tests/integration/docusaurus/reference/core_concepts/result_format.py
  tests/integration/fixtures/yellow_tripdata_pandas_fixture/multiple_batch_requests_one_validator_multiple_steps.py
  tests/integration/fixtures/yellow_tripdata_pandas_fixture/multiple_batch_requests_one_validator_one_step.py
  tests/integration/fixtures/yellow_tripdata_pandas_fixture/one_multi_batch_request_one_validator.py
  tests/integration/fixtures/yellow_tripdata_pandas_fixture/two_batch_requests_two_validators.py
Labels: dx, core

#8575 [MAINTENANCE] Update metrics data model to use generic value type
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  great_expectations/experimental/metric_repository/metrics.py
  tests/experimental/metric_repository/demo.py
Labels: dx, core

#8603 [MAINTENANCE] Update the CTA in the Data Docs footer
  great_expectations/render/view/templates/cloud-footer.j2
Labels: core

#8609 [MAINTENANCE] Clean-up: Renaming "self-initializing" to "auto-initializing"
  docs/docusaurus/docs/guides/expectations/how_to_use_auto_initializing_expectations.md
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  great_expectations/expectations/expectation.py
  tests/expectations/test_expectation_auto_initializing.py
  tests/integration/docusaurus/expectations/auto_initializing_expectations/is_expectation_auto_initializing.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_ConfiguredAssetFileSystemExample_Pandas.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_ConfiguredAssetFileSystemExample_Spark.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_ConfiguredAssetSQLExample_SQL.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_InferredAssetFileSystemExample_Pandas.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_InferredAssetFileSystemExample_Spark.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_InferredAssetSQLExample.ipynb
  tests/test_fixtures/rule_based_profiler/example_notebooks/SelfInitializingExpectations.ipynb
Labels: core

#8388 [MAINTENANCE] Adding support for project_root_dir to get_context
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_instantiate_a_specific_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/instantiate_data_context.md
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context/serializable_data_context.py
  great_expectations/util.py
  tests/conftest.py
  tests/data_context/test_data_context_config_errors.py
  tests/data_context/test_data_context_deprecation.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_instantiate_a_specific_filesystem_data_context.py
Labels: core

#8612 [MAINTENANCE] Simplify CI YAML conditional for 0.17.12 release
  .github/workflows/ci.yml
Labels: core

#8613 [BUGFIX] Fix DraftDatasourceConfigAction connection string substitution
  great_expectations/agent/actions/draft_datasource_config_action.py
Labels: core

#8593 [MAINTENANCE] Add mode param to get_context
  great_expectations/util.py
  tests/data_context/test_get_data_context.py
Labels: core

#8615 [RELEASE] 0.17.12
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8606 [FEATURE] Scripts for Identify Failed Rows (ID/PK) Doc
  tests/integration/docusaurus/expectations/advanced/failed_rows_pandas.py
  tests/integration/docusaurus/expectations/advanced/failed_rows_spark.py
  tests/integration/docusaurus/expectations/advanced/failed_rows_sql.py
  tests/integration/fixtures/failed_rows/great_expectations/.gitignore
  tests/integration/fixtures/failed_rows/great_expectations/checkpoints/my_checkpoint.yml
  tests/integration/fixtures/failed_rows/great_expectations/expectations/.ge_store_backend_id
  tests/integration/fixtures/failed_rows/great_expectations/expectations/visitors_exp.json
  tests/integration/fixtures/failed_rows/great_expectations/great_expectations.yml
  tests/integration/fixtures/failed_rows/great_expectations/plugins/custom_data_docs/styles/data_docs_custom_styles.css
  tests/integration/test_script_runner.py
  tests/test_sets/visits/README.md
  tests/test_sets/visits/visits.csv
  tests/test_sets/visits/visits.db
Labels: dx, core

#8610 [FEATURE] Ensure FDS asset gets updated with new cloud id on add
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/serializable_data_context.py
  great_expectations/datasource/fluent/interfaces.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
  tests/datasource/fluent/test_contexts.py
Labels: core

#8549 [MAINTENANCE] Update Docusaurus to `2.4.1` and ensure Algolia search works
  docs/docusaurus/package.json
  docs/docusaurus/src/theme/SearchBar/index.js
  docs/docusaurus/yarn.lock
Labels: dx, core

#8621 [MAINTENANCE] add py311 min versions tests
  .github/workflows/ci.yml
  ci/constraints-test/py310-min-install.txt
  ci/constraints-test/py311-min-install.txt
Labels: core

#8623 [MAINTENANCE] Move `get_context` out of utils
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  great_expectations/__init__.py
  great_expectations/cli/checkpoint_script_template.py
  great_expectations/cli/datasource.py
  great_expectations/cli/toolkit.py
  great_expectations/data_context/__init__.py
  great_expectations/data_context/data_context/__init__.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/data_context/context_factory.py
  great_expectations/util.py
  tests/actions/conftest.py
  tests/actions/test_validation_operators.py
  tests/actions/test_validation_operators_in_data_context.py
  tests/checkpoint/conftest.py
  tests/cli/test_checkpoint.py
  tests/cli/test_datasource_new_pandas_paths.py
  tests/cli/test_datasource_pandas.py
  tests/cli/test_datasource_sqlite.py
  tests/cli/test_docs.py
  tests/cli/test_init.py
  tests/cli/test_suite.py
  tests/cli/test_toolkit.py
  tests/conftest.py
  tests/core/usage_statistics/test_payload_builder.py
  tests/core/usage_statistics/test_usage_statistics.py
  tests/core/usage_statistics/test_usage_statistics_handler_methods.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_concurrency_config.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_config_ui.py
  tests/data_context/test_data_context_config_variables.py
  tests/data_context/test_data_context_data_docs_api.py
  tests/data_context/test_data_context_datasources.py
  tests/data_context/test_data_context_ge_cloud_mode.py
  tests/data_context/test_data_context_in_code_config.py
  tests/data_context/test_data_context_on_teams.py
  tests/data_context/test_data_context_v013.py
  tests/datasource/fluent/test_metadatasource.py
  tests/execution_engine/test_sparkdf_execution_engine.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/spark/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/spark/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/spark_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/in_memory/spark_python_example.py
  tests/integration/docusaurus/deployment_patterns/aws_emr_serverless_deployment_patterns.py
  tests/integration/docusaurus/deployment_patterns/aws_glue_deployment_patterns.py
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_dataframe_yaml_configs.py
  tests/integration/usage_statistics/instantiate_context_with_usage_statistics.py
  tests/integration/usage_statistics/test_usage_stats_common_messages_are_sent_v3api.py
  tests/performance/taxi_benchmark_util.py
  tests/render/renderer/test_checkpoint_new_notebook_renderer.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/render/test_data_documentation_site_builder.py
  tests/validator/test_validator.py
Labels: core

#8614 [BUGFIX] Fix bug in Query template values metric when it gets int values
  great_expectations/expectations/metrics/query_metrics/query_template_values.py
  tests/expectations/metrics/query_metrics/test_query_metrics.py
Labels: dx, core

#8581 [DOCS] Remove Unused Topics and Update YAML Examples
  docs/docusaurus/docs/components/connect_to_data/link_lists/_connecting_to_data_fluently.md
  docs/docusaurus/docs/components/connect_to_data/link_lists/_connecting_to_sql_datasources_fluently.md
  docs/docusaurus/docs/components/connect_to_data/link_lists/_work_with_fluent_data_assets.md
  docs/docusaurus/docs/components/connect_to_data/next_steps/_after_create_sql_datasource.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/connect_sql_source_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_a_sql_table.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_postgresql_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data_using_a_query.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sqlite_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/sql_data_assets.md
  docs/docusaurus/docs/guides/expectations/advanced/how_to_compare_two_tables_with_the_onboarding_data_assistant.md
Labels: devrel

#8624 [MAINTENANCE] Remove reference to CLI in generated GX YAML
  great_expectations/data_context/templates.py
  tests/data_context/test_templates.py
Labels: core

#8629 [MAINTENANCE] Fix Azure CI packaging step
  ci/dev-install-matrix.yml
Labels: core

#8634 [BUGFIX] Ensure that `oss_id` updates conf file rather than overwriting
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/data_context/test_data_context.py
Labels: core

#8635 [DOCS] Update Connect to SQL database source data
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/connect_sql_source_data.md
Labels: devrel

#8565 [DOCS] Remove Instances of SimpleCheckpoint
  tests/integration/docusaurus/reference/core_concepts/checkpoints_and_actions.py
Labels: devrel

#8641 [MAINTENANCE] Ignore `pandas` warning emitted through `altair` codepath
  pyproject.toml
Labels: core

#8620 [DOCS] add `@public_api` to `PandasDatasource` methods and assets
  great_expectations/datasource/fluent/pandas_datasource.pyi
Labels: docs, core

#8643 [MAINTENANCE] Delete `ExpectationExplorer`
  great_expectations/data_asset/data_asset.py
  great_expectations/jupyter_ux/expectation_explorer.py
  great_expectations/validator/validator.py
Labels: core

#8608 [MAINTENANCE] Kill datasource cache in non-Cloud envs
  great_expectations/core/datasource_dict.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/migrator/configuration_bundle.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/datasource/fluent/sources.py
  great_expectations/self_check/util.py
  great_expectations/util.py
  tests/checkpoint/cloud_config.py
  tests/checkpoint/test_checkpoint.py
  tests/cli/test_checkpoint.py
  tests/cli/test_suite.py
  tests/conftest.py
  tests/core/test_datasource_dict.py
  tests/data_context/abstract_data_context/test_abstract_data_context_datasource_crud.py
  tests/data_context/abstract_data_context/test_datasource_delete.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/test_data_context_datasources.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_contexts.py
  tests/test_definitions/test_expectations_v3_api.py
Labels: core

#8600 [BUGFIX] Query Compatibility With Trino
  contrib/experimental/great_expectations_experimental/expectations/expect_column_to_have_no_months_missing.py
Labels: community

#8563 [MAINTENANCE] databricks_sql integration tests
  .github/workflows/ci.yml
  pyproject.toml
  tests/datasource/fluent/integration/test_sql_datasources.py
Labels: core

#8645 [MAINTENANCE] Fix or ignore warnings appearing in python 3.11
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  great_expectations/util.py
  pyproject.toml
Labels: core

#8644 [MAINTENANCE] Remove deprecated sqlalchemy-databricks connector
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/datasource/fluent/databricks_sql_datasource.py
  reqs/requirements-dev-databricks.txt
  tests/datasource/fluent/test_databricks_sql_datasource.py
Labels: core

#8633 [MAINTENANCE] metrics typing
  great_expectations/expectations/metrics/column_aggregate_metrics/column_partition.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_value_counts.py
  great_expectations/expectations/metrics/map_metric_provider/column_condition_partial.py
  great_expectations/expectations/metrics/map_metric_provider/column_function_partial.py
  great_expectations/expectations/metrics/map_metric_provider/column_pair_condition_partial.py
  great_expectations/expectations/metrics/map_metric_provider/column_pair_function_partial.py
  great_expectations/expectations/metrics/map_metric_provider/multicolumn_condition_partial.py
  great_expectations/expectations/metrics/map_metric_provider/multicolumn_function_partial.py
  great_expectations/expectations/metrics/map_metric_provider/multicolumn_map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/metric_provider.py
  great_expectations/util.py
  pyproject.toml
Labels: dx, core

#8640 [MAINTENANCE] Delete misc batch kwarg generators
  great_expectations/datasource/batch_kwargs_generator/__init__.py
  great_expectations/datasource/batch_kwargs_generator/batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/databricks_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/glob_reader_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/manual_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/query_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/s3_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/subdir_reader_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/table_batch_kwargs_generator.py
  great_expectations/datasource/sparkdf_datasource.py
  great_expectations/exceptions/exceptions.py
  tests/data_context/fixtures/contexts/incomplete_uncommitted/great_expectations/great_expectations.yml
  tests/datasource/batch_kwarg_generator/test_batch_kwargs_generator.py
  tests/datasource/batch_kwarg_generator/test_glob_reader_generator.py
  tests/datasource/batch_kwarg_generator/test_manual_generator.py
  tests/datasource/batch_kwarg_generator/test_s3_generator.py
  tests/datasource/test_batch_generators.py
  tests/datasource/test_pandas_datasource.py
Labels: core

#8651 [BUGFIX] Always run docs-snippets action on release tag.
  .github/workflows/ci.yml
Labels: core

#8554 [DOCS] Add New Topic for Identifying Failed Table Rows
  docs/docusaurus/docs/guides/connecting_to_your_data/components/prerequisites.jsx
  docs/docusaurus/docs/guides/expectations/advanced/identify_failed_rows_expectations.md
  docs/docusaurus/docs/guides/expectations/create_manage_expectations_lp.md
  docs/docusaurus/docs/guides/images/failed_rows_data_docs_pandas.png
  docs/docusaurus/docs/guides/images/failed_rows_data_docs_spark.png
  docs/docusaurus/docs/guides/images/failed_rows_data_docs_sql.png
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_confirm_that_the_validations_results_store_has_been_correctly_configured.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/configure_result_stores.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_gcs.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_on_a_filesystem.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_to_postgresql.md
  docs/docusaurus/docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_additional_resources.mdx
  docs/docusaurus/docs/guides/validation/how_to_validate_data_by_running_a_checkpoint.md
  docs/docusaurus/docs/guides/validation/validate_data_overview.md
  docs/docusaurus/docs/guides/validation/validation_actions/how_to_collect_openlineage_metadata_using_a_validation_action.md
  docs/docusaurus/docs/guides/validation/validation_actions/how_to_trigger_email_as_a_validation_action.md
  docs/docusaurus/docs/guides/validation/validation_actions/how_to_trigger_opsgenie_notifications_as_a_validation_action.md
  docs/docusaurus/docs/guides/validation/validation_actions/how_to_trigger_slack_notifications_as_a_validation_action.md
  docs/docusaurus/docs/terms/checkpoint.md
  docs/docusaurus/docs/tutorials/getting_started/how_to_use_great_expectations_in_databricks.md
  docs/docusaurus/docs/tutorials/getting_started/how_to_use_great_expectations_with_sql.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
  tests/integration/docusaurus/expectations/advanced/failed_rows_pandas.py
  tests/integration/docusaurus/expectations/advanced/failed_rows_spark.py
  tests/integration/docusaurus/expectations/advanced/failed_rows_sql.py
  tests/integration/docusaurus/validation/checkpoints/how_to_validate_data_by_running_a_checkpoint.py
  tests/test_sets/visits/README.md
Labels: devrel

#8653 [RELEASE] 0.17.13
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8655 [BUGFIX] Use correct syntax for creating temporary views for DatabricksSQL datasources
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/execution_engine/sqlalchemy_dialect.py
  tests/datasource/fluent/integration/test_sql_datasources.py
Labels: core

#8652 [MAINTENANCE] typing - `expect_column` - `to_exist` and `to_not_be_null`
  great_expectations/expectations/core/expect_column_to_exist.py
  great_expectations/expectations/core/expect_column_values_to_not_be_null.py
  great_expectations/expectations/expectation.py
  pyproject.toml
Labels: core
