Repository great-expectations/great_expectations, pull requests merged in 2023-07, with the labels that each got.

#8227 [MAINTENANCE] Remove a line ignoring warnings about iteritems
  pyproject.toml
Labels: core

#8233 [MAINTENANCE] Correcting typographical error in test method naming.
  tests/rule_based_profiler/parameter_builder/test_mean_unexpected_map_metric_multi_batch_parameter_builder.py
Labels: dx, core

#8237 [MAINTENANCE] Reference environment consistency - installed version
  examples/reference_environments/README.md
  examples/reference_environments/abs/jupyter.Dockerfile
  examples/reference_environments/bigquery/jupyter.Dockerfile
  examples/reference_environments/gcs/jupyter.Dockerfile
  examples/reference_environments/postgres/jupyter.Dockerfile
  examples/reference_environments/s3/jupyter.Dockerfile
  examples/reference_environments/snowflake/jupyter.Dockerfile
Labels: dx, core

#8239 [MAINTENANCE] Reference environment consistency - unpin python version
  examples/reference_environments/abs/jupyter.Dockerfile
  examples/reference_environments/bigquery/jupyter.Dockerfile
  examples/reference_environments/gcs/jupyter.Dockerfile
  examples/reference_environments/postgres/jupyter.Dockerfile
  examples/reference_environments/s3/jupyter.Dockerfile
  examples/reference_environments/snowflake/jupyter.Dockerfile
Labels: dx, core

#8240 [MAINTENANCE] Use data docs container for cloud blob stores
  examples/reference_environments/abs/README.md
  examples/reference_environments/abs/abs_example.ipynb
  examples/reference_environments/abs/abs_example_abs_stores.ipynb
  examples/reference_environments/abs/compose.yaml
  examples/reference_environments/abs/data_docs.Dockerfile
  examples/reference_environments/bigquery/bigquery_example.ipynb
  examples/reference_environments/gcs/README.md
  examples/reference_environments/gcs/compose.yaml
  examples/reference_environments/gcs/data_docs.Dockerfile
  examples/reference_environments/gcs/gcs_public_nyc_tlc_bucket_example.ipynb
  examples/reference_environments/gcs/gcs_public_nyc_tlc_bucket_gcs_stores_example.ipynb
  examples/reference_environments/postgres/postgres_example.ipynb
  examples/reference_environments/postgres/postgres_example_postgres_stores.ipynb
  examples/reference_environments/s3/README.md
  examples/reference_environments/s3/compose.yaml
  examples/reference_environments/s3/data_docs.Dockerfile
  examples/reference_environments/s3/s3_public_nyc_tlc_bucket_example.ipynb
  examples/reference_environments/s3/s3_public_nyc_tlc_bucket_s3_stores_example.ipynb
  examples/reference_environments/snowflake/snowflake_example.ipynb
Labels: dx, core

#8242 [MAINTENANCE] Reference Environments: Match the new quickstart
  examples/reference_environments/abs/abs_example.ipynb
  examples/reference_environments/abs/abs_example_abs_stores.ipynb
  examples/reference_environments/gcs/gcs_public_nyc_tlc_bucket_example.ipynb
  examples/reference_environments/gcs/gcs_public_nyc_tlc_bucket_gcs_stores_example.ipynb
  examples/reference_environments/postgres/postgres_example.ipynb
  examples/reference_environments/postgres/postgres_example_postgres_stores.ipynb
  examples/reference_environments/s3/s3_public_nyc_tlc_bucket_example.ipynb
  examples/reference_environments/s3/s3_public_nyc_tlc_bucket_s3_stores_example.ipynb
Labels: dx, core

#8238 [BUGFIX] Ensure DataAssistantResult.plot_expectations_and_metrics does not raise exceptions when no Metrics or Expectations are available to plot
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
Labels: dx, core

#8230 [MAINTENANCE] Reference Environment - AWS Credentials Clean up
  great_expectations/cli/example.py
Labels: dx, core

#8222 [FEATURE] Reference Environment - AWS RDS
  examples/reference_environments/aws_postgres/README.md
  examples/reference_environments/aws_postgres/aws_postgres_example.ipynb
  examples/reference_environments/aws_postgres/aws_postgres_example_aws_stores.ipynb
  examples/reference_environments/aws_postgres/compose.yaml
  examples/reference_environments/aws_postgres/data_docs.Dockerfile
  examples/reference_environments/aws_postgres/jupyter.Dockerfile
  examples/reference_environments/postgres/compose.yaml
  great_expectations/cli/example.py
Labels: dx, core

#8244 [MAINTENANCE] Filter altair/jsonschema Deprecation warning
  great_expectations/rule_based_profiler/altair/encodings.py
Labels: core

#8246 [MAINTENANCE] Filter `jsonschema.RefResolver`, `ErrorTree` warnings in tests
  pyproject.toml
Labels: core

#8247 [MAINTENANCE] Temporarily upper bound Click due to `mypy` typing issues
  requirements.txt
  tests/test_packaging.py
Labels: core

#8251 [MAINTENANCE] Update `test_deprecation.py` in advance of 0.17.3 release
  tests/test_deprecation.py
Labels: core

#8204 [MAINTENANCE] enable typechecking in validator.py
  great_expectations/core/batch.py
  great_expectations/core/batch_manager.py
  great_expectations/data_asset/util.py
  great_expectations/datasource/data_connector/data_connector.py
  great_expectations/datasource/data_connector/runtime_data_connector.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/validator/validator.py
  pyproject.toml
  tests/datasource/fluent/integration/integration_test_utils.py
Labels: core

#8225 [MAINTENANCE] Refactor validations in Checkpoint to use `CheckpointValidationConfig`
  great_expectations/checkpoint/checkpoint.py
  great_expectations/checkpoint/configurator.py
  great_expectations/checkpoint/util.py
  great_expectations/core/configuration.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/types/base.py
  tests/checkpoint/test_checkpoint.py
  tests/checkpoint/test_checkpoint_config.py
  tests/data_context/conftest.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_state_management.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core

#8254 [MAINTENANCE] Protect `develop` with `no-commit-to-branch` pre-commit hook
  .pre-commit-config.yaml
Labels: dx, core

#8252 [MAINTENANCE] Change Pydantic models to utilize `by_alias=True`
  great_expectations/datasource/fluent/config.py
  great_expectations/datasource/fluent/fluent_base_model.py
Labels: core

#8256 [RELEASE] 0.17.3
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8183 [MAINTENANCE] Support individual connection args for Snowflake FDS
  great_expectations/compatibility/snowflake.py
  great_expectations/datasource/fluent/schemas/SnowflakeDatasource.json
  great_expectations/datasource/fluent/snowflake_datasource.py
  great_expectations/datasource/fluent/sources.pyi
  tests/datasource/fluent/great_expectations.yml
  tests/datasource/fluent/test_snowflake_datasource.py
Labels: core

#8189 [MAINTENANCE] Replace dynamic datasource deletion with single `delete` method
  great_expectations/datasource/fluent/sources.py
  tests/datasource/fluent/test_contexts.py
  tests/datasource/fluent/test_metadatasource.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core

#8248 [MAINTENANCE] Disable usage statistics when in Cloud-backed environments
  great_expectations/data_context/data_context/cloud_data_context.py
  tests/core/usage_statistics/test_usage_statistics_data_context.py
Labels: core

#8261 [RELEASE] 0.17.4
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8257 [FEATURE] Airflow reference environment
  examples/reference_environments/airflow_2_6_2/.gitignore
  examples/reference_environments/airflow_2_6_2/Dockerfile
  examples/reference_environments/airflow_2_6_2/README.md
  examples/reference_environments/airflow_2_6_2/compose.yaml
  examples/reference_environments/airflow_2_6_2/config/README.md
  examples/reference_environments/airflow_2_6_2/dags/dag.py
  examples/reference_environments/airflow_2_6_2/logs/README.md
  examples/reference_environments/airflow_2_6_2/plugins/README.md
  examples/reference_environments/airflow_2_6_2/setup_airflow.sh
  great_expectations/cli/example.py
Labels: dx, core

#8265 [MAINTENANCE] Remove duplicate custom checks in PR pipeline
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs.yml
Labels: core

#8269 [MAINTENANCE] Use updated search api key
  docs/docusaurus/docusaurus.config.js
  docs/docusaurus/src/theme/SearchBar/index.js
Labels: core

#8262 [MAINTENANCE] DataAssistantDispatcher should not reach into DataAssistant
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_dispatcher.py
Labels: core

#8272 [MAINTENANCE] GH action static analysis and unittest setup
  .github/workflows/ci.yml
  tasks.py
Labels: core

#8264 [MAINTENANCE] remove algolia index action
  .github/workflows/algoliaIndexer.yml
Labels: core

#8268 [FEATURE] Missingness DataAssistant initial implementation
  great_expectations/rule_based_profiler/data_assistant/__init__.py
  great_expectations/rule_based_profiler/data_assistant/column_value_missing_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_dispatcher.py
  great_expectations/rule_based_profiler/data_assistant_result/__init__.py
  great_expectations/rule_based_profiler/data_assistant_result/column_value_missing_data_assistant_result.py
  great_expectations/rule_based_profiler/parameter_builder/__init__.py
  great_expectations/rule_based_profiler/parameter_builder/unexpected_count_statistics_multi_batch_parameter_builder.py
  pyproject.toml
  tests/rule_based_profiler/data_assistant/test_column_value_missing_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/parameter_builder/test_unexpected_count_statistics_multi_batch_parameter_builder.py
Labels: dx, core

#8043 [MAINTENANCE] Improvement to contributor documentation
  .gitignore
  CONTRIBUTING_CODE.md
  CONTRIBUTING_WORKFLOWS.md
  IDE_SETUP_TIPS.md
  ci/checks/check_repo_root_size.sh
  contrib/README.md
  docker/README.md
  docs/checks/docs_link_checker.py
  docs/docusaurus/docs/guides/validation/validation_actions/how_to_trigger_email_as_a_validation_action.md
  docs/docusaurus/docs/intro.md
  scripts/build_glossary_page.py
Labels: community

#8280 [MAINTENANCE] Implement unit tests for BatchFilter.parse_batch_slice logic
  tests/datasource/data_connector/test_batch_filter.py
Labels: dx, core

#8281 [MAINTENANCE] Run GH Action CI job every 3 hours
  .github/workflows/ci.yml
Labels: core

#8282 [MAINTENANCE] Ensure all tests in tests/checkpoint are marked
  pyproject.toml
  tests/checkpoint/test_checkpoint.py
  tests/checkpoint/test_checkpoint_config.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/checkpoint/test_checkpoint_run_anonymizer.py
  tests/checkpoint/test_checkpoint_with_fluent_datasources.py
  tests/checkpoint/test_simple_checkpoint.py
  tests/checkpoint/test_simple_checkpoint_with_fluent_datasources.py
Labels: core

#8275 [MAINTENANCE] Pytest Mark - `Validator` and utils
  pyproject.toml
  tests/rule_based_profiler/config/test_base.py
  tests/rule_based_profiler/test_profiler_run_anonymizer.py
  tests/scripts/test_public_api_report.py
  tests/scripts/test_trace_docs_deps.py
  tests/test_deprecation.py
  tests/test_not_imported.py
  tests/test_the_utils_in_self_check_utils.py
  tests/test_the_utils_in_test_utils.py
  tests/validator/test_metrics_calculator.py
  tests/validator/test_validation_graph.py
Labels: dx, core

#8286 [MAINTENANCE] Add marker cli to all cli tests.
  pyproject.toml
  tests/cli/test_batch_request.py
  tests/cli/test_checkpoint.py
  tests/cli/test_cli.py
  tests/cli/test_datasource.py
  tests/cli/test_datasource_athena.py
  tests/cli/test_datasource_new_helpers.py
  tests/cli/test_datasource_new_pandas_paths.py
  tests/cli/test_datasource_pandas.py
  tests/cli/test_datasource_snowflake.py
  tests/cli/test_datasource_sqlite.py
  tests/cli/test_docs.py
  tests/cli/test_init.py
  tests/cli/test_init_missing_libraries.py
  tests/cli/test_init_pandas.py
  tests/cli/test_init_sqlite.py
  tests/cli/test_project.py
  tests/cli/test_sanitize_yaml_and_save_datasource.py
  tests/cli/test_store.py
  tests/cli/test_suite.py
  tests/cli/test_toolkit.py
  tests/cli/test_validation_operator.py
  tests/cli/upgrade_helpers/test_upgrade_helper.py
Labels: core

#8283 [MAINTENANCE] Reduce maximum allowed unittest duration
  .github/workflows/ci.yml
  tasks.py
  tests/datasource/fluent/test_pandas_filesystem_datasource.py
Labels: core

#8285 [MAINTENANCE] Add tests for Batch slicing for SparkFilePathDatasource
  great_expectations/datasource/fluent/file_path_data_asset.py
  great_expectations/datasource/fluent/interfaces.py
  tests/datasource/data_connector/test_batch_filter.py
  tests/datasource/fluent/test_pandas_filesystem_datasource.py
  tests/datasource/fluent/test_spark_filesystem_datasource.py
Labels: dx, core

#8288 [MAINTENANCE] Pytest Mark - `RuleBasedProfiler` and others
  pyproject.toml
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant_happy_paths.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/domain_builder/test_cardinality_checker.py
  tests/rule_based_profiler/domain_builder/test_categorical_column_domain_builder.py
  tests/rule_based_profiler/domain_builder/test_domain.py
  tests/rule_based_profiler/domain_builder/test_domain_builder.py
  tests/rule_based_profiler/domain_builder/test_map_metric_column_domain_builder.py
  tests/rule_based_profiler/expectation_configuration_builder/test_default_expectation_configuration_builder.py
  tests/rule_based_profiler/parameter_builder/test_histogram_single_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_mean_table_columns_set_match_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_mean_unexpected_map_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_numeric_metric_range_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_parameter_computations.py
  tests/rule_based_profiler/parameter_builder/test_parameter_container.py
  tests/rule_based_profiler/parameter_builder/test_simple_date_format_string_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_unexpected_count_statistics_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_value_counts_single_batch_parameter_builder.py
  tests/test_great_expectations.py
Labels: dx, core

#8290 [MAINTENANCE] Pin jsonschema
  requirements.txt
  tests/test_packaging.py
Labels: dx, core

#8287 [MAINTENANCE] Remove two slow DataAssistant integration tests
  tests/rule_based_profiler/data_assistant/test_column_value_missing_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
Labels: dx, core

#8173 [DOCS] Replaces outdated integration guides with redirects to versioned documentation
  docs/docusaurus/docs/components/prerequisites/_python_version.md
  docs/docusaurus/docs/deployment_patterns/aws_lp.md
  docs/docusaurus/docs/deployment_patterns/how_to_instantiate_a_data_context_hosted_environments.md
  docs/docusaurus/docs/deployment_patterns/how_to_instantiate_a_data_context_on_an_emr_spark_cluster.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_in_aws_glue.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_in_deepnote.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_in_emr_serverless.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_in_flyte.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_meltano.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_prefect.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_ydata_synthetic.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_athena.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_cloud_storage_and_pandas.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_redshift.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_s3_and_spark.md
  docs/docusaurus/docs/guides/validation/advanced/how_to_validate_data_without_a_checkpoint.md
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.md
  docs/docusaurus/docs/guides/validation/index.md
  docs/docusaurus/docs/integrations/integration_datahub.md
  docs/docusaurus/docs/integrations/integration_zenml.md
  docs/docusaurus/docs/reference/customize_your_deployment.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
  tests/integration/docusaurus/deployment_patterns/aws_emr_serverless_deployment_patterns.py
  tests/integration/docusaurus/deployment_patterns/aws_emr_serverless_deployment_patterns_great_expectations.yaml
  tests/integration/docusaurus/deployment_patterns/aws_glue_deployment_patterns.py
  tests/integration/docusaurus/deployment_patterns/aws_glue_deployment_patterns_great_expectations.yaml
Labels: devrel

#8284 [MAINTENANCE] Add data docs container to airflow env
  examples/reference_environments/airflow_2_6_2/Dockerfile
  examples/reference_environments/airflow_2_6_2/README.md
  examples/reference_environments/airflow_2_6_2/compose.yaml
  examples/reference_environments/airflow_2_6_2/dags/dag.py
  examples/reference_environments/airflow_2_6_2/data_docs.Dockerfile
  examples/reference_environments/aws_postgres/data_docs.Dockerfile
Labels: dx, core

#8292 [MAINTENANCE] xfail Cloud E2E test
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
Labels: core

#8298 [MAINTENANCE] Remove --verbose pytest default
  .github/workflows/ci.yml
  tasks.py
Labels: core

#8296 [MAINTENANCE] Update marker on slow test from unit to filesystem.
  tests/checkpoint/test_checkpoint_result_format.py
Labels: core

#8279 [MAINTENANCE] Typing Improvements - render/util
  great_expectations/render/util.py
  pyproject.toml
  tests/checkpoint/test_checkpoint_result_format.py
Labels: dx, core

#8299 [MAINTENANCE] Add pytest marks to tests/actions
  pyproject.toml
  tests/actions/test_core_actions.py
  tests/actions/test_sns_action.py
  tests/actions/test_store_metric_action.py
  tests/actions/test_validation_operators.py
  tests/actions/test_validation_operators_in_data_context.py
Labels: core

#8295 [MAINTENANCE] Mark tests in tests/core/usage_statistics
  pyproject.toml
  tests/core/usage_statistics/test_anonymizer.py
  tests/core/usage_statistics/test_events.py
  tests/core/usage_statistics/test_execution_environment.py
  tests/core/usage_statistics/test_package_dependencies.py
  tests/core/usage_statistics/test_payload_builder.py
  tests/core/usage_statistics/test_schema_validation.py
  tests/core/usage_statistics/test_usage_statistics.py
  tests/core/usage_statistics/test_usage_statistics_data_context.py
  tests/core/usage_statistics/test_usage_statistics_handler_methods.py
  tests/core/usage_statistics/test_usage_stats_schema.py
  tests/core/usage_statistics/test_util.py
Labels: core

#8300 [MAINTENANCE] Mark tests in /tests/data_asset
  tests/data_asset/test_data_asset.py
  tests/data_asset/test_data_asset_citations.py
  tests/data_asset/test_data_asset_internals.py
  tests/data_asset/test_data_asset_util.py
  tests/data_asset/test_datetime_evaluation_parameter.py
  tests/data_asset/test_expectation_decorators.py
  tests/data_asset/test_filedata_asset.py
  tests/data_asset/test_filedata_asset_expectations.py
  tests/data_asset/test_parameter_substitution.py
Labels: core

#8278 [FEATURE] single batch missingness data assistant
  great_expectations/rule_based_profiler/data_assistant/column_value_missing_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_dispatcher.py
  great_expectations/rule_based_profiler/parameter_builder/unexpected_count_statistics_multi_batch_parameter_builder.py
  tests/rule_based_profiler/data_assistant/test_column_value_missing_data_assistant.py
  tests/rule_based_profiler/parameter_builder/test_unexpected_count_statistics_multi_batch_parameter_builder.py
Labels: core

#8297 [MAINTENANCE] Add markers to tests/core
  tests/core/test_config_substitutor.py
  tests/core/test_convert_to_json_serializable.py
  tests/core/test_evaluation_parameters.py
  tests/core/test_expectation_suite_crud_methods.py
  tests/core/test_expectation_validation.py
  tests/core/test_serialization.py
  tests/core/test_yaml_handler.py
Labels: core

#8293 [MAINTENANCE] Apply pytest markers to root dir `tests/data_context` tests
  tests/data_context/test_base_data_context.py
  tests/data_context/test_concurrency_config.py
  tests/data_context/test_configuration_storage.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_config_errors.py
  tests/data_context/test_data_context_config_ui.py
  tests/data_context/test_data_context_config_variables.py
  tests/data_context/test_data_context_data_docs_api.py
  tests/data_context/test_data_context_datasources.py
  tests/data_context/test_data_context_in_code_config.py
  tests/data_context/test_data_context_on_teams.py
  tests/data_context/test_data_context_profilers.py
  tests/data_context/test_data_context_resource_identifiers.py
  tests/data_context/test_data_context_store_configs.py
  tests/data_context/test_data_context_test_yaml_config.py
  tests/data_context/test_data_context_test_yaml_config_usage_stats.py
  tests/data_context/test_data_context_utils.py
  tests/data_context/test_data_context_variables.py
  tests/data_context/test_get_data_context.py
  tests/data_context/test_loading_and_saving_of_data_context_configs.py
  tests/data_context/test_pandas_datetime_suites.py
  tests/data_context/test_templates.py
Labels: dx, core

#8306 [MAINTENANCE] Increase timeout for flaky tests
  tests/datasource/fluent/test_pandas_filesystem_datasource.py
Labels: dx, core

#8305 [MAINTENANCE] Remove `trace_docs_deps` script in CI
  ci/azure-pipelines-docs-integration.yml
  ci/checks/check_for_docs_deps_changes.sh
  scripts/trace_docs_deps.py
  tests/scripts/test_trace_docs_deps.py
Labels: core

#8310 [RELEASE] 0.17.5
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: dx, core

#8277 [MAINTENANCE] GH Actions pytest marker test matrix
  .github/workflows/ci.yml
Labels: core

#8301 [MAINTENANCE] Pytest Mark - Render folder
  tests/cli/test_suite.py
  tests/render/renderer/content_block/test_expectation_string_renderer.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/render/test_EmailRenderer.py
  tests/render/test_OpsgenieRenderer.py
  tests/render/test_SlackRenderer.py
  tests/render/test_column_section_renderer.py
  tests/render/test_data_documentation_site_builder.py
  tests/render/test_default_jinja_view.py
  tests/render/test_default_markdown_view.py
  tests/render/test_inline_renderer.py
  tests/render/test_microsoft_teams_renderer.py
  tests/render/test_page_renderer.py
  tests/render/test_render.py
  tests/render/test_render_BulletListContentBlock.py
  tests/render/test_render_ExceptionListContentBlockRenderer.py
  tests/render/test_render_ValidationResultsTableContentBlockRenderer.py
  tests/render/test_renderer.py
  tests/render/test_styled_string_template.py
  tests/render/test_util.py
  tests/render/util.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
Labels: dx, core

#8315 [MAINTENANCE] Fix docs pipeline check changes
  ci/azure-pipelines-docs.yml
Labels: dx, core

#8316 [MAINTENANCE] Add test markers to tests/datasource/fluent/XXX/X.py
  pyproject.toml
  tests/datasource/fluent/data_asset/data_connector/test_azure_blob_storage_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_dbfs_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_filesystem_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_google_cloud_storage_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_s3_data_connector.py
  tests/datasource/fluent/integration/conftest.py
  tests/datasource/fluent/integration/test_integration_datasource.py
  tests/datasource/fluent/integration/test_migration.py
  tests/datasource/fluent/test_config.py
Labels: core

#8318 [MAINTENANCE] Pytest Mark - Profiling
  tests/performance/test_bigquery_benchmarks.py
  tests/profile/test_basic_suite_builder_profiler.py
  tests/profile/test_jsonschema_profiler.py
  tests/profile/test_profile.py
  tests/profile/test_user_configurable_profiler_v2_batch_kwargs.py
  tests/profile/test_user_configurable_profiler_v3_batch_request.py
Labels: dx, core

#8311 [MAINTENANCE] `invoke deps` task
  .github/workflows/ci.yml
  tasks.py
Labels: dx, core

#8312 [MAINTENANCE] Fix requirements and CONTRIBUTING_CODE doc
  .github/workflows/test-sqlalchemy-latest.yml
  CONTRIBUTING_CODE.md
  ci/azure-pipelines-cloud-integration.yml
  ci/azure-pipelines-docs-integration.yml
  ci/azure-pipelines.yml
  ci/checks/check_repo_root_size.sh
  ci/dev-install-matrix.yml
  constraints-dev-sqlalchemy-pandas-v1.txt
  constraints-dev.txt
  docs/expectation_gallery/azure-pipelines-expectation-gallery.yml
  examples/reference_environments/airflow_2_6_2/Dockerfile
  examples/reference_environments/bigquery/jupyter.Dockerfile
  examples/reference_environments/gcs/jupyter.Dockerfile
  examples/reference_environments/snowflake/jupyter.Dockerfile
  reqs/README.md
  reqs/requirements-dev-bigquery.txt
  reqs/requirements-dev-sqlalchemy-less-than-2.txt
  reqs/requirements-dev-sqlalchemy.txt
  reqs/requirements-dev-sqlalchemy1.txt
  reqs/requirements-dev-tools.txt
  requirements-dev.txt
  requirements-types.txt
  setup.py
  tests/test_packaging.py
Labels: dx, core

#8323 [MAINTENANCE] gitignore for GCP credentials
  examples/reference_environments/.gitignore
Labels: dx, core

#8317 [MAINTENANCE] Pytest Mark - DataContext Part 2
  pyproject.toml
  tests/data_context/abstract_data_context/test_datasource_delete.py
  tests/data_context/abstract_data_context/test_list_datasources.py
  tests/data_context/cloud_data_context/test_data_docs_api.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/datasource/test_data_context_datasource_non_sql_methods_pandas_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_non_sql_methods_sparkdf_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_pandas_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_sparkdf_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_sqlalchemy_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_sql_methods.py
  tests/data_context/migrator/test_cloud_migrator.py
  tests/data_context/migrator/test_file_migrator.py
  tests/data_context/store/test_checkpoint_store.py
  tests/data_context/store/test_configuration_store.py
  tests/data_context/store/test_database_store_backend.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_evaluation_parameter_store.py
  tests/data_context/store/test_evaluation_parameter_store_pre_v013.py
  tests/data_context/store/test_expectations_store.py
  tests/data_context/store/test_ge_cloud_store_backend.py
  tests/data_context/store/test_gx_cloud_store_backend.py
  tests/data_context/store/test_html_site_store.py
  tests/data_context/store/test_profiler_store.py
  tests/data_context/store/test_query_store.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/store/test_store_dynamic_loading.py
  tests/data_context/store/test_validations_store.py
Labels: dx, core

#8324 [MAINTENANCE] Pytest Mark - ExecutionEngine
  tests/execution_engine/split_and_sample/test_pandas_execution_engine_sampling.py
  tests/execution_engine/split_and_sample/test_pandas_execution_engine_splitting.py
  tests/execution_engine/split_and_sample/test_sparkdf_execution_engine_sampling.py
  tests/execution_engine/split_and_sample/test_sparkdf_execution_engine_splitting.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
  tests/execution_engine/test_execution_engine.py
  tests/execution_engine/test_pandas_execution_engine.py
  tests/execution_engine/test_sparkdf_execution_engine.py
  tests/execution_engine/test_sqlalchemy_batch_data.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
Labels: dx, core

#8319 [MAINTENANCE] Pytest Mark - Integration and Expectations
  tests/expectations/core/test_expect_column_max_to_be_between.py
  tests/expectations/core/test_expect_column_mean_to_be_positive.py
  tests/expectations/core/test_expect_column_value_z_scores_to_be_less_than.py
  tests/expectations/core/test_expect_column_values_to_be_decreasing.py
  tests/expectations/core/test_expect_column_values_to_be_in_set.py
  tests/expectations/core/test_expect_column_values_to_be_in_type_list.py
  tests/expectations/core/test_expect_column_values_to_be_increasing.py
  tests/expectations/core/test_expect_column_values_to_be_of_type.py
  tests/expectations/core/test_expect_column_values_to_match_regex_parameterized.py
  tests/expectations/core/test_expect_queried_column_value_frequency_to_meet_threshold.py
  tests/expectations/core/test_expect_queried_table_row_count_to_be.py
  tests/expectations/core/test_expect_table_row_count_to_be_between.py
  tests/expectations/test_dataclass_serializable_dot_dict_pattern.py
  tests/expectations/test_expectation_arguments.py
  tests/expectations/test_expectation_atomic_renderers.py
  tests/expectations/test_expectation_diagnostics.py
  tests/expectations/test_expectation_self_initializing.py
  tests/expectations/test_expectation_test_data_cases.py
  tests/expectations/test_format_map_output.py
  tests/expectations/test_generate_diagnostic_checklist.py
  tests/expectations/test_null_filters.py
  tests/expectations/test_registry.py
  tests/expectations/test_row_conditions.py
  tests/expectations/test_run_diagnostics.py
  tests/expectations/test_run_diagnostics_supporting_methods.py
  tests/expectations/test_util.py
  tests/integration/profiling/rule_based_profiler/test_profiler_basic_workflows.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/integration/profiling/rule_based_profiler/test_rule_based_profiler.py
  tests/integration/spark/test_spark_config.py
  tests/integration/usage_statistics/test_all_events_are_in_schema.py
  tests/integration/usage_statistics/test_integration_usage_statistics.py
  tests/integration/usage_statistics/test_usage_statistics_messages.py
  tests/integration/usage_statistics/test_usage_stats_common_messages_are_sent_v3api.py
Labels: dx, core

#8342 [MAINTENANCE] Disable Airflow provider tests in CI due to external test failures
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines.yml
Labels: core

#8341 [MAINTENANCE] Bump minimum version of `numpy==1.21.6` for Python 3.9
  ci/constraints-test/py39-min-install.txt
  requirements.txt
Labels: dx, core

#8314 [CONTRIB] Create custom expectation for Chi Square Test
  contrib/experimental/great_expectations_experimental/expectations/expect_column_chisquare_test_pvalue_to_be_greater_than.py
Labels: core

#8045 [DOCS] Adds a consolidated overview of using GX as a conceptual guide
  docs/docusaurus/docs/components/_python_version.mdx
  docs/docusaurus/docs/conceptual_guides/gx_overview.md
  docs/docusaurus/docs/conceptual_guides/images_overview/checkpoint_flowchart.png
  docs/docusaurus/docs/conceptual_guides/images_overview/data_context_flowchart.png
  docs/docusaurus/docs/conceptual_guides/images_overview/datasource_flowchart.png
  docs/docusaurus/sidebars.js
Labels: devrel

#8337 [FEATURE] Register MissingnessDataAssistant
  great_expectations/rule_based_profiler/data_assistant/column_value_missing_data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
Labels: core

#8338 [MAINTENANCE] Pytest Mark - DataConnector
  pyproject.toml
  tests/data_context/store/test_evaluation_parameter_store.py
  tests/data_context/store/test_store_backends.py
  tests/datasource/data_connector/sorters/test_sorters.py
  tests/datasource/data_connector/sorters/test_sorting.py
  tests/datasource/data_connector/test_configured_asset_azure_data_connector.py
  tests/datasource/data_connector/test_configured_asset_dbfs_data_connector.py
  tests/datasource/data_connector/test_configured_asset_filesystem_data_connector.py
  tests/datasource/data_connector/test_configured_asset_gcs_data_connector.py
  tests/datasource/data_connector/test_configured_asset_glue_catalog_data_connector.py
  tests/datasource/data_connector/test_configured_asset_s3_data_connector.py
  tests/datasource/data_connector/test_data_connector.py
  tests/datasource/data_connector/test_data_connector_query_filesystem.py
  tests/datasource/data_connector/test_data_connector_query_sql.py
  tests/datasource/data_connector/test_data_connector_util.py
  tests/datasource/data_connector/test_file_path_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_azure_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_dbfs_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_filesystem_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_gcs_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_glue_catalog_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_s3_data_connector.py
  tests/datasource/data_connector/test_runtime_data_connector.py
  tests/datasource/data_connector/test_sql_data_connector.py
  tests/execution_engine/split_and_sample/test_pandas_execution_engine_splitting.py
  tests/execution_engine/test_pandas_execution_engine.py
Labels: dx, core

#8302 [MAINTENANCE] Replace many repetitive slow integration tests for ParameterBuilder components with a few fast unit tests
  great_expectations/core/util.py
  great_expectations/rule_based_profiler/data_assistant/column_value_missing_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_column_value_missing_data_assistant.py
  tests/rule_based_profiler/parameter_builder/conftest.py
  tests/rule_based_profiler/parameter_builder/test_mean_unexpected_map_metric_multi_batch_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_unexpected_count_statistics_multi_batch_parameter_builder.py
  tests/rule_based_profiler/test_rule_based_profiler.py
Labels: dx, core

#8347 [MAINTENANCE] Finish marking fluent datasource tests.
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_contexts.py
  tests/datasource/fluent/test_metadatasource.py
  tests/datasource/fluent/test_pandas_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/datasource/fluent/test_pandas_dbfs_datasource.py
  tests/datasource/fluent/test_pandas_google_cloud_storage_datasource.py
  tests/datasource/fluent/test_pandas_s3_datasource.py
  tests/datasource/fluent/test_postgres_datasource.py
  tests/datasource/fluent/test_schemas.py
  tests/datasource/fluent/test_spark_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_spark_datasource.py
  tests/datasource/fluent/test_spark_dbfs_datasource.py
  tests/datasource/fluent/test_spark_filesystem_datasource.py
  tests/datasource/fluent/test_spark_google_cloud_storage_datasource.py
  tests/datasource/fluent/test_spark_s3_datasource.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core

#8327 [BUGFIX] Ensure that Fluent Datasources support database table names in lowercase for Oracle, DB2, and Snowflake
  great_expectations/datasource/fluent/sql_datasource.py
  tests/datasource/fluent/test_postgres_datasource.py
  tests/datasource/fluent/test_sql_datasources.py
  tests/sqlalchemy_test_doubles.py
Labels: dx, core

#8348 [MAINTENANCE] Add test markers to datasource/batch_kwarg_generator tests.
  tests/datasource/batch_kwarg_generator/test_batch_kwargs_generator.py
  tests/datasource/batch_kwarg_generator/test_glob_reader_generator.py
  tests/datasource/batch_kwarg_generator/test_manual_generator.py
  tests/datasource/batch_kwarg_generator/test_s3_generator.py
  tests/datasource/batch_kwarg_generator/test_subdir_reader_generator.py
Labels: core

#8309 [DOCS] Updated the Execution Engine terms page
  docs/docusaurus/docs/terms/execution_engine.md
Labels: core

#8354 [MAINTENANCE] Update mark on long running test.
  tests/checkpoint/test_checkpoint.py
Labels: core

#8355 Revert "[MAINTENANCE] Update mark on long running test."
  tests/checkpoint/test_checkpoint.py
Labels: core

#8356 [MAINTENANCE] Re-mark slow tests.
  tests/checkpoint/test_checkpoint.py
  tests/profile/test_user_configurable_profiler_v2_batch_kwargs.py
Labels: core

#8339 [MAINTENANCE] Update standard node package
  docs/docusaurus/package.json
  docs/docusaurus/yarn.lock
Labels: core

#8358 [MAINTENANCE] Making tests for column names insensitivity for Oracle, DB2, and Snowflake easier to read
  tests/expectations/metrics/test_metrics_util.py
Labels: dx, core

#8340 [DOCS] Add docs around Snowflake FDS
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/connect_sql_source_data.md
Labels: core

#8363 [MAINTENANCE] Add detect-private-key pre-commit hook
  .pre-commit-config.yaml
Labels: dx, core

#8359 [MAINTENANCE] Pytest Mark - Top-level `test/`
  tests/test_deprecation.py
  tests/test_great_expectations.py
  tests/test_packaging.py
Labels: dx, core

#8360 [MAINTENANCE] Unpin upper bound on Click dependency
  requirements.txt
  tests/test_packaging.py
Labels: core

#8349 [DOCS] Update link in Data Asset Glossary Topic
  docs/docusaurus/docs/terms/data_asset.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8367 [MAINTENANCE] Revert Click pin removal
  requirements.txt
  tests/test_packaging.py
Labels: core

#8353 [MAINTENANCE] Fix non-AssertErrors for Expectations during build-gallery process
  CONTRIBUTING_EXPECTATIONS.md
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_column_values_confidence_for_data_label_to_be_greater_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_column_values_confidence_for_data_label_to_be_less_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_column_values_to_be_equal_to_or_greater_than_profile_min.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_column_values_to_be_equal_to_or_less_than_profile_max.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_column_values_to_be_probabilistically_greater_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_between_exclusive_threshold_range.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_between_inclusive_threshold_range.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_greater_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_greater_than_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_less_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_less_than_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_between_exclusive_threshold_range.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_between_inclusive_threshold_range.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_greater_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_greater_than_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_less_than_or_equal_to_threshold.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_percent_diff_less_than_threshold.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_chisquare_simple_test_p_value_to_be_greater_than.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_distinct_values_to_be_continuous.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_after_split_to_be_in_set.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_not_to_be_future_date.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_edtf_parseable.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_thai.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_xml_schema.py
  contrib/experimental/great_expectations_experimental/expectations/expect_day_sum_to_be_close_to_equivalent_week_day_mean.py
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_sum_values_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_pair_values_to_be_both_filled_or_null.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_pair_values_to_have_diff.py
  contrib/experimental/great_expectations_experimental/expectations/expect_query_count_with_filter_to_meet_threshold.py
  contrib/experimental/great_expectations_experimental/expectations/expect_query_to_have_no_duplicate_value_combinations.py
  contrib/great_expectations_geospatial_expectations/great_expectations_geospatial_expectations/expectations/expect_column_minimum_bounding_radius_to_be_between.py
  contrib/great_expectations_geospatial_expectations/great_expectations_geospatial_expectations/expectations/expect_column_pair_values_lat_lng_matches_geohash.py
  contrib/great_expectations_geospatial_expectations/great_expectations_geospatial_expectations/expectations/expect_column_values_to_have_elevation.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_bic_belong_to_country.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_be_valid_doge_address.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_be_xml_parseable.py
  contrib/time_series_expectations/time_series_expectations/expectations/expect_batch_row_count_to_match_prophet_date_model.py
  contrib/time_series_expectations/time_series_expectations/expectations/expect_column_max_to_match_prophet_date_model.py
  contrib/time_series_expectations/time_series_expectations/expectations/expect_column_pair_values_to_match_prophet_date_model.py
  docs/docusaurus/docs/contributing/contributing_maturity.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_batch_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_pair_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_multicolumn_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/overview.md
  great_expectations/core/expectation_diagnostics/expectation_diagnostics.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  tests/expectations/test_generate_diagnostic_checklist.py
  tests/expectations/test_run_diagnostics.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_be_in_solfege_scale_set.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_only_contain_vowels.py
Labels: dx, core

#8357 [DOCS] Remove Outdated SQLAlchemy 2.0 Admonitions
  docs/docusaurus/docs/guides/setup/installation/install_gx.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/cloud/connect_gx_source_data_system.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/sql_databases/how_to_setup_gx_to_work_with_sql_databases.md
Labels: devrel

#8307 [CONTRIB] Contributed `expect_column_to_have_no_months_missing`
  contrib/experimental/great_expectations_experimental/expectations/expect_column_to_have_no_months_missing.py
Labels: community

#8350 [DOCS] Update Links to Get started with Great Expectations and Databricks
  README.md
  docs/docusaurus/docs/guides/setup/installation/hosted_environment.md
  docs/docusaurus/docs/guides/setup/installation/install_gx.md
  docs/docusaurus/static/_redirects
  tests/docs/test_prepare_prior_versions.py
Labels: devrel

#8365 [MAINTENANCE] Mark datasource top level tests
  tests/datasource/test_batch_generators.py
  tests/datasource/test_batch_kwargs.py
  tests/datasource/test_datasource.py
  tests/datasource/test_datasource_anonymizer.py
  tests/datasource/test_datasource_config_ui.py
  tests/datasource/test_datasource_serialization.py
  tests/datasource/test_new_datasource.py
  tests/datasource/test_new_datasource_with_aws_glue_data_connector.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_pandas_execution_engine.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_sparkdf_execution_engine.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_sql_execution_engine.py
  tests/datasource/test_new_datasource_with_sql_data_connector.py
  tests/datasource/test_pandas_datasource.py
  tests/datasource/test_sparkdf_datasource.py
  tests/datasource/test_util.py
Labels: core

#8369 [BUGFIX] Handle ValueError in agent action
  great_expectations/agent/actions/run_onboarding_data_assistant.py
Labels: core

#8361 [BUGFIX] Ensure that SQLAlchemy is installed for SQL Datasource and TableAsset Fluent Datasource Module
  great_expectations/datasource/fluent/sql_datasource.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
Labels: dx, core

#8370 [BUGFIX] DataAssistantResult should not error on get_expectation_suite without name
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  tests/rule_based_profiler/data_assistant/test_data_assistant_result.py
Labels: core

#8371 [BUGFIX] Exclude appropriate SnowflakeDatasource fields when creating an execution engine
  .github/workflows/ci.yml
  ci/azure-pipelines-dev.yml
  great_expectations/datasource/fluent/snowflake_datasource.py
  tests/datasource/fluent/test_snowflake_datasource.py
Labels: core

#8175 [DOCS] Add MetricProviders Conceptual Content
  docs/docusaurus/docs/conceptual_guides/learn_lp.md
  docs/docusaurus/docs/conceptual_guides/metricproviders.md
  docs/docusaurus/docs/glossary.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8172 [DOCS] Add Information for Adding Custom Parameters to Custom Expectations
  docs/docusaurus/docs/guides/expectations/add_features_custom_expectations_lp.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/add_custom_parameters.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/img/parameter_icon.svg
Labels: devrel

#8332 [DOCS] Remove index.md Files and Add Redirects
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_create_and_run.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_data_docs_build_and_view.md
  docs/docusaurus/docs/deployment_patterns/index.md
  docs/docusaurus/docs/guides/connecting_to_your_data/connect_to_data_overview.md
  docs/docusaurus/docs/guides/connecting_to_your_data/index.md
  docs/docusaurus/docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.md
  docs/docusaurus/docs/guides/expectations/how_to_use_auto_initializing_expectations.md
  docs/docusaurus/docs/guides/expectations/index.md
  docs/docusaurus/docs/guides/setup/index.md
  docs/docusaurus/docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_steps_for_checkpoints_.mdx
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config.md
  docs/docusaurus/docs/guides/validation/index.md
  docs/docusaurus/docs/guides/validation/validate_data_overview.md
  docs/docusaurus/docs/guides/validation/validation_actions/how_to_update_data_docs_as_a_validation_action.md
  docs/docusaurus/docs/team_templates/how_to_template.md
  docs/docusaurus/docs/team_templates/tutorial_template.md
  docs/docusaurus/docs/terms/action.md
  docs/docusaurus/docs/terms/batch.md
  docs/docusaurus/docs/terms/checkpoint.md
  docs/docusaurus/docs/terms/custom_expectation.md
  docs/docusaurus/docs/terms/data_asset.md
  docs/docusaurus/docs/terms/data_context.md
  docs/docusaurus/docs/terms/data_docs.md
  docs/docusaurus/docs/terms/datasource.md
  docs/docusaurus/docs/terms/execution_engine.md
  docs/docusaurus/docs/terms/expectation.md
  docs/docusaurus/docs/terms/expectation_store.md
  docs/docusaurus/docs/terms/validation_result_store.md
  docs/docusaurus/docs/terms/validator.md
  docs/docusaurus/static/_redirects
  tests/docs/test_prepare_prior_versions.py
Labels: devrel

#8344 [CONTRIB] Add KS test custom expectation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_kolmogoro_smirnov_test_p_value_to_be_greater_than.py
Labels: core

#8364 [FEATURE] Automatically pick single_batch or auto for Missingness Data Assistant
  great_expectations/rule_based_profiler/data_assistant/column_value_missing_data_assistant.py
  great_expectations/rule_based_profiler/parameter_builder/unexpected_count_statistics_multi_batch_parameter_builder.py
  tests/rule_based_profiler/data_assistant/test_column_value_missing_data_assistant.py
Labels: core

#8331 [DOCS] Update Compare Two Tables with the Onboarding Data Assistant
  ci/azure-pipelines-docs-integration.yml
  docs/docusaurus/docs/guides/expectations/advanced/how_to_compare_two_tables_with_the_onboarding_data_assistant.md
  tests/integration/docusaurus/expectations/advanced/data_assistant_cross_table_comparison.py
  tests/integration/test_definitions/multiple_backend/integration_tests.py
Labels: devrel

#8378 [MAINTENANCE] Do not run CI on draft pull requests, enable running manually
  .github/workflows/ci.yml
Labels: dx, core

#8380 [RELEASE] 0.17.6
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: dx, core

#8376 [MAINTENANCE] Update help text for build_gallery and add guides to docs/expectation_gallery
  assets/scripts/build_gallery.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/conftest.py
  contrib/experimental/great_expectations_experimental/tests/conftest.py
  docs/expectation_gallery/0-expectation-diagnostics-and-testing.md
  docs/expectation_gallery/1-the-build_gallery.py-script.md
  docs/expectation_gallery/2-managing-the-expectation-gallery-site.md
  docs/expectation_gallery/3-expectation-docstring-formatting.md
  docs/expectation_gallery/README.md
  tests/conftest.py
Labels: dx, core

#8334 [DOCS] Fix Mac M1 Great Expectations Installation link
  docs/docusaurus/docs/guides/setup/installation/components_local/_preface.mdx
Labels: community

#8381 [MAINTENANCE] Revert linting changes to format_docstring_to_markdown func
  assets/scripts/build_gallery.py
Labels: dx, core

#8385 [DOCS] Update Airflow integration page to link to Astronomer GX doc
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_airflow.md
Labels: devrel

#8386 [DOCS] Update Prefect integration page to link to Prefect GX docs
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_prefect.md
Labels: devrel

#8291 [DOCS] Add test python file and doc for validating multiple batches on doc
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_validate_multiple_batches_within_single_checkpoint.md
  docs/docusaurus/sidebars.js
  tests/integration/docusaurus/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config.py
  tests/integration/docusaurus/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.py
  tests/integration/docusaurus/validation/checkpoints/how_to_validate_data_by_running_a_checkpoint.py
  tests/integration/docusaurus/validation/checkpoints/how_to_validate_multiple_batches_within_single_checkpoint.py
  tests/integration/test_script_runner.py
Labels: core

#8390 [MAINTENANCE] Run type check and unit tests on draft PRs
  .github/workflows/ci.yml
Labels: dx, core

#8384 [DOCS] Update Snowflake FDS docs to clarify account identification methods
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/connect_sql_source_data.md
Labels: core

#8336 [FEATURE] Generalize Agent support for Data Assistants
  docs/sphinx_api_docs_source/public_api_excludes.py
  great_expectations/agent/actions/__init__.py
  great_expectations/agent/actions/data_assistants/__init__.py
  great_expectations/agent/actions/data_assistants/run_missingness_data_assistant.py
  great_expectations/agent/actions/data_assistants/run_onboarding_data_assistant.py
  great_expectations/agent/actions/data_assistants/utils.py
  great_expectations/agent/actions/run_onboarding_data_assistant.py
  great_expectations/agent/event_handler.py
  great_expectations/agent/models.py
  tests/agent/actions/data_assistants/__init__.py
  tests/agent/actions/data_assistants/test_run_missingness_data_assistant_action_utils.py
  tests/agent/actions/data_assistants/test_run_onboarding_data_assistant_action.py
  tests/agent/test_event_handler.py
Labels: core

#8366 [MAINTENANCE] Clean up misc pins in requirements
  great_expectations/core/usage_statistics/execution_environment.py
  great_expectations/core/usage_statistics/package_dependencies.py
  requirements.txt
  tests/core/usage_statistics/test_execution_environment.py
  tests/test_packaging.py
Labels: core

#8397 [MAINTENANCE] Pytest Mark - Rendering and UserConfigurable Profiler
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/jupyter_ux/test_jupyter_ux.py
  tests/profile/test_basic_suite_builder_profiler.py
  tests/profile/test_user_configurable_profiler_v2_batch_kwargs.py
  tests/profile/test_user_configurable_profiler_v3_batch_request.py
  tests/render/renderer/test_checkpoint_new_notebook_renderer.py
  tests/render/renderer/test_datasource_new_notebook_renderer.py
  tests/render/renderer/test_other_section_renderer.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/render/test_column_section_renderer.py
  tests/render/test_renderer.py
  tests/rule_based_profiler/data_assistant/test_data_assistant_result.py
  tests/rule_based_profiler/parameter_builder/test_parameter_builder.py
  tests/rule_based_profiler/parameter_builder/test_value_counts_single_batch_parameter_builder.py
  tests/scripts/test_public_api_report.py
  tests/validator/test_metrics_calculator.py
Labels: dx, core

#8383 [DOCS] Add documentation around Databricks SQL Datasource
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/connect_sql_source_data.md
Labels: core

#8396 [MAINTENANCE] Add missing markers to tests/datasource and test_markers.py
  tests/data_context/test_data_context_utils.py
  tests/data_context/test_data_context_v013.py
  tests/data_context/test_data_context_variables.py
  tests/data_context/test_loading_and_saving_of_data_context_configs.py
  tests/test_markers.py
Labels: core

#8335 [MAINTENANCE] Experimental column descriptive metrics repository
  docs/sphinx_api_docs_source/public_api_excludes.py
  great_expectations/agent/actions/__init__.py
  great_expectations/agent/actions/run_column_descriptive_metrics_action.py
  great_expectations/agent/event_handler.py
  great_expectations/agent/models.py
  great_expectations/experimental/__init__.py
  great_expectations/experimental/metric_repository/__init__.py
  great_expectations/experimental/metric_repository/batch_inspector.py
  great_expectations/experimental/metric_repository/cloud_data_store.py
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  great_expectations/experimental/metric_repository/data_store.py
  great_expectations/experimental/metric_repository/metric_repository.py
  great_expectations/experimental/metric_repository/metric_retriever.py
  great_expectations/experimental/metric_repository/metrics.py
  great_expectations/validator/metrics_calculator.py
  great_expectations/validator/validation_graph.py
  great_expectations/validator/validator.py
  tests/experimental/__init__.py
  tests/experimental/metric_repository/__init__.py
  tests/experimental/metric_repository/demo.py
Labels: dx, core

#8399 [MAINTENANCE] Mark remaining datasource tests.
  tests/datasource/batch_kwarg_generator/test_glob_reader_generator.py
  tests/datasource/data_connector/test_data_connector.py
  tests/datasource/data_connector/test_runtime_data_connector.py
  tests/datasource/data_connector/test_sql_data_connector.py
Labels: core

#8400 [MAINTENANCE] Pytest Mark - Metrics Folder
  tests/expectations/metrics/test_core.py
  tests/expectations/metrics/test_map_metric.py
  tests/expectations/metrics/test_metric_providers.py
  tests/expectations/metrics/test_table_column_types.py
Labels: dx, core

#8401 [MAINTENANCE] Add marks to missing expectations tests.
  tests/expectations/core/test_expect_column_values_to_be_in_set.py
  tests/expectations/core/test_expect_table_row_count_to_be_between.py
  tests/expectations/test_util.py
Labels: core

#8374 [BUGFIX] fixing minor bug in sqlalchemy_execution_engine.py
  great_expectations/compatibility/sqlalchemy.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
Labels: community

#8402 [MAINTENANCE]Add ci test for test marker coverage
  .github/workflows/ci.yml
  tasks.py
Labels: core

#8226 [MAINTENANCE] mypy 1.4.1
  contrib/cli/requirements.txt
  great_expectations/util.py
  reqs/requirements-dev-contrib.txt
  tests/datasource/fluent/test_spark_filesystem_datasource.py
  tests/test_packaging.py
Labels: core

#8403 [MAINTENANCE] snowflake regex
  great_expectations/expectations/metrics/util.py
  great_expectations/self_check/util.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_regex.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_match_regex_list.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_match_regex.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_not_match_regex_list.json
Labels: dx, core

#8405 [DOCS] Update docs on expectation docstrings
  contrib/experimental/great_expectations_experimental/expectations/expect_table_checksum_to_equal_other_table.py
  contrib/great_expectations_ethical_ai_expectations/great_expectations_ethical_ai_expectations/expectations/expect_table_binary_label_model_bias.py
  docs/docusaurus/docs/contributing/style_guides/code_style.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_batch_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_pair_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_multicolumn_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_query_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
  docs/expectation_gallery/1-the-build_gallery.py-script.md
  docs/expectation_gallery/3-expectation-docstring-formatting.md
  docs/expectation_gallery/README.md
  docs/expectation_gallery/azure-pipelines-expectation-gallery.yml
  great_expectations/expectations/core/expect_column_to_exist.py
  great_expectations/expectations/core/expect_table_column_count_to_be_between.py
  great_expectations/expectations/core/expect_table_column_count_to_equal.py
  great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py
  great_expectations/expectations/core/expect_table_columns_to_match_set.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_equal.py
  great_expectations/expectations/core/expect_table_row_count_to_equal_other_table.py
  tests/expectations/core/test_expect_column_mean_to_be_positive.py
Labels: dx, core

#8411 [MAINTENANCE] Resolve misc typing issues in metrics code
  great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_most_common_value.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  great_expectations/expectations/metrics/map_metric_provider/column_condition_partial.py
  great_expectations/expectations/metrics/map_metric_provider/column_map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/map_metric_provider/column_pair_condition_partial.py
  great_expectations/expectations/metrics/map_metric_provider/column_pair_function_partial.py
  great_expectations/expectations/metrics/map_metric_provider/map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/map_metric_provider/map_metric_provider.py
  great_expectations/expectations/metrics/map_metric_provider/multicolumn_condition_partial.py
  great_expectations/expectations/metrics/map_metric_provider/multicolumn_function_partial.py
  great_expectations/expectations/metrics/util.py
  pyproject.toml
Labels: core

#8412 [MAINTENANCE] conditional `snowflake-connector-python` version bump
  reqs/requirements-dev-snowflake.txt
Labels: core

#8234 [MAINTENANCE] Refactor `Table.head()` for `sqlalchemy`
  great_expectations/compatibility/sqlalchemy_and_pandas.py
  great_expectations/expectations/metrics/table_metrics/table_head.py
  great_expectations/self_check/util.py
  tests/expectations/metrics/table_metrics/test_table_head.py
Labels: dx, core

#8413 [MAINTENANCE] List required markers when verify marker test fails.
  tests/conftest.py
Labels: core

#8419 [DOCS] corrects default value for result_format in documentation
  docs/docusaurus/docs/reference/expectations/result_format.md
Labels: devrel

#8391 [DOCS] Remove Custom Expectations Overview Topic
  CONTRIBUTING_EXPECTATIONS.md
  CONTRIBUTING_PACKAGES.md
  docs/docusaurus/docs/components/setup/link_lists/_data_context_initialize_instatiate_save.md
  docs/docusaurus/docs/components/setup/next_steps/_links_after_installing_gx.md
  docs/docusaurus/docs/components/stores/_stores_overwrite_at_runtime.md
  docs/docusaurus/docs/conceptual_guides/expectation_classes.md
  docs/docusaurus/docs/contributing/components/prerequisites.jsx
  docs/docusaurus/docs/contributing/contributing_maturity.md
  docs/docusaurus/docs/deployment_patterns/how_to_instantiate_a_data_context_hosted_environments.md
  docs/docusaurus/docs/deployment_patterns/how_to_instantiate_a_data_context_on_an_emr_spark_cluster.md
  docs/docusaurus/docs/guides/connecting_to_your_data/components/spark_data_context_note.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_add_support_for_the_auto_initializing_framework_to_a_custom_expectation.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_batch_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_pair_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_multicolumn_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_parameterized_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_query_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/overview.md
  docs/docusaurus/docs/guides/expectations/custom_expectations_lp.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_example_cases_for_an_expectation.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_input_validation_for_an_expectation.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_spark_support_for_an_expectation.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_sqlalchemy_support_for_an_expectation.md
  docs/docusaurus/docs/guides/setup/components_index/_data_contexts.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/how_to_configure_credentials.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/how_to_convert_an_ephemeral_data_context_to_a_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/initializing_data_contexts/how_to_initialize_a_filesystem_data_context_in_python.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_explicitly_instantiate_an_ephemeral_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_instantiate_a_specific_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_quickly_instantiate_a_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/instantiate_data_context.md
  docs/docusaurus/docs/integrations/components/prerequisites.jsx
  docs/docusaurus/docs/reference/customize_your_deployment.md
  docs/docusaurus/docs/terms/execution_engine.md
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
  docs/docusaurus/docs_pending/tutorial_create_expectations_onboarding_assistant.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
  great_expectations/expectations/metrics/metric_provider.py
Labels: devrel

#8414 [DOCS] Update contributing code readme with required markers information.
  CONTRIBUTING_CODE.md
Labels: core

#8425 [MAINTENANCE] Bump version of `autoupdate` GH action
  .github/workflows/autoupdate.yml
Labels: core

#8416 [DOCS] Fix markdown link in install_gx.md
  docs/docusaurus/docs/guides/setup/installation/install_gx.md
Labels: community

#8418 [CONTRIB] Pyspark Implementation for expect_column_values_to_be_valid_currency_code
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_be_valid_currency_code.py
Labels: community

#8428 [MAINTENANCE] Bump Ubuntu version in `autoupdate` GH action
  .github/workflows/autoupdate.yml
Labels: core

#8313 [MAINTENANCE] Update error message around `context.add_checkpoint` when neither name nor checkpoint are provided
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/test_data_context_state_management.py
Labels: core

#8408 [MAINTENANCE] move Azure docs and public API steps to Github Actions
  .github/workflows/ci.yml
  ci/azure-pipelines.yml
Labels: core

#8420 [MAINTENANCE] Use constants for GX directory and YAML references
  tests/actions/test_validation_operators.py
  tests/checkpoint/conftest.py
  tests/cli/conftest.py
  tests/cli/test_checkpoint.py
  tests/cli/test_init.py
  tests/cli/test_init_missing_libraries.py
  tests/cli/test_init_pandas.py
  tests/cli/test_init_sqlite.py
  tests/cli/test_project.py
  tests/cli/test_suite.py
  tests/cli/test_toolkit.py
  tests/cli/upgrade_helpers/test_upgrade_helper.py
  tests/conftest.py
  tests/core/usage_statistics/test_usage_statistics.py
  tests/data_asset/test_data_asset.py
  tests/data_context/conftest.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/test_configuration_storage.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_config_variables.py
  tests/data_context/test_data_context_store_configs.py
  tests/data_context/test_data_context_variables.py
  tests/data_context/test_get_data_context.py
  tests/datasource/fluent/test_postgres_datasource.py
  tests/datasource/test_pandas_datasource.py
  tests/datasource/test_sparkdf_datasource.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_explicitly_instantiate_an_ephemeral_data_context.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_initialize_a_filesystem_data_context_in_python.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_instantiate_a_specific_filesystem_data_context.py
  tests/integration/docusaurus/deployment_patterns/aws_cloud_storage_pandas.py
  tests/integration/docusaurus/deployment_patterns/aws_cloud_storage_spark.py
  tests/integration/docusaurus/deployment_patterns/aws_redshift_deployment_patterns.py
  tests/integration/docusaurus/deployment_patterns/gcp_deployment_patterns_file_bigquery.py
  tests/integration/docusaurus/deployment_patterns/gcp_deployment_patterns_file_gcs.py
  tests/integration/docusaurus/expectations/how_to_create_and_edit_expectations_with_a_profiler.py
  tests/integration/docusaurus/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_gcs.py
  tests/integration/docusaurus/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_gcs.py
  tests/integration/test_script_runner.py
  tests/profile/conftest.py
  tests/render/conftest.py
  tests/render/renderer/test_checkpoint_new_notebook_renderer.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
  tests/render/test_data_documentation_site_builder.py
  tests/validator/test_validator.py
Labels: core

#8393 [FEATURE] Allow a rule to fail within DataAssistant and still run other rules
  great_expectations/rule_based_profiler/rule_based_profiler.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
Labels: core

#8431 [BUGFIX] `ensure_json_serializable` accounts for `pydantic.BaseModel`
  great_expectations/core/util.py
Labels: core

#8426 [BUGFIX] `Table.head()` follow-up for Python versions
  great_expectations/compatibility/sqlalchemy_and_pandas.py
Labels: dx, core

#8424 [MAINTENANCE] Clean up Databricks SQL FDS impl and docs
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/connect_sql_source_data.md
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/datasource/fluent/databricks_sql_datasource.py
  great_expectations/datasource/fluent/schemas/DatabricksSQLDatasource.json
  reqs/requirements-dev-databricks.txt
  setup.py
  tests/datasource/fluent/great_expectations.yml
  tests/datasource/fluent/test_databricks_sql_datasource.py
Labels: core

#8421 [DOCS] Docs TOC Reorg
  docs/docusaurus/docs/conceptual_guides/learn_lp.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8430 [DOCS] Fix snippet reference in how_to_use_great_expectations_with_sql.md
  docs/docusaurus/docs/tutorials/getting_started/how_to_use_great_expectations_with_sql.md
Labels: community

#8177 [FEATURE] Add Agent action to list table names in SQL Datasources
  docs/sphinx_api_docs_source/public_api_excludes.py
  great_expectations/agent/actions/__init__.py
  great_expectations/agent/actions/list_table_names.py
  great_expectations/agent/event_handler.py
  great_expectations/agent/models.py
  tests/agent/actions/test_list_table_names_action.py
Labels: feature, core

#8439 [BUGFIX] Cleanup aws_postgres reference environment
  examples/reference_environments/aws_postgres/data_docs.Dockerfile
Labels: dx, core

#8440 [BUGFIX] Use consistent name between compose and cli command
  examples/reference_environments/aws_postgres/compose.yaml
Labels: dx, core
