Repository great-expectations/great_expectations, pull requests merged in 2023-11, with the labels that each got.

#8905 [DOCS] Update Section Title
  docs/docusaurus/docs/cloud/expectations/manage_expectations.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8907 [FEATURE] Expect column specified percentile value to be above a given value.
  contrib/experimental/great_expectations_experimental/expectations/expect_column_percentile_value_to_be_above.py
Labels: community

#8913 [MAINTENANCE] Better error msg for refrence environments
  great_expectations/cli/example.py
Labels: dx, core

#8896 [MAINTENANCE] remove deprecated usage of pydantic Extra
  great_expectations/experimental/metric_repository/cloud_data_store.py
  great_expectations/experimental/metric_repository/metrics.py
Labels: core

#8889 [MAINTENANCE] E2E Test - Spark Filesystem with Cloud
  tests/integration/cloud/end_to_end/test_spark_filesystem_datasource.py
Labels: dx, core

#8849 [DOCS] Create a New Get Support Topic
  docs/docusaurus/docs/cloud/about_gx.md
  docs/docusaurus/docs/cloud/gx_cloud_lp.md
  docs/docusaurus/docs/get_support.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8891 [CONTRIB][FEATURE]-add-threshold-parameter
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_datetime_difference_in_months.py
Labels: community

#8914 [FEATURE] Warn users if more specific SQL Datasource is available.
  great_expectations/datasource/fluent/__init__.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/sources.pyi
  great_expectations/datasource/fluent/sql_datasource.py
  tests/conftest.py
  tests/datasource/fluent/test_sql_datasources.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
Labels: core

#8902 [MAINTENANCE] Update ruff + black + mypy
  .pre-commit-config.yaml
  contrib/cli/requirements.txt
  great_expectations/checkpoint/actions.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py
  great_expectations/jupyter_ux/__init__.py
  reqs/requirements-dev-contrib.txt
  tests/test_packaging.py
Labels: core

#8924 [MAINTENANCE] Deal with `GxDatasourceWarning` warnings in docs-snippet tests
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_a_sql_table.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_sql_data_using_a_query.py
  tests/integration/docusaurus/deployment_patterns/postgres_deployment_patterns.py
  tests/integration/docusaurus/expectations/advanced/data_assistant_cross_table_comparison.py
  tests/integration/docusaurus/expectations/advanced/how_to_dynamically_load_evaluation_parameters_from_a_database.py
  tests/integration/docusaurus/setup/configuring_data_contexts/how_to_configure_credentials.py
Labels: core

#8921 [MAINTENANCE] Add JennyTee as core contributor
  .github/teams.yml
Labels: core

#8926 [RELEASE] 0.18.1
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8918 [DOCS] Update Connect to SQL Database Data Assets
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/connect_sql_source_data.md
Labels: devrel

#8904 [DOCS] DSB-353: Add GX Cloud Architecture and Deployment Patterns page
  docs/docusaurus/docs/cloud/about_gx.md
  docs/docusaurus/docs/cloud/architecture_deployment_images/deployment_local_gx_oss_client.png
  docs/docusaurus/docs/cloud/architecture_deployment_images/deployment_orchestrator.png
  docs/docusaurus/docs/cloud/architecture_deployment_images/deployment_web_ui_only_snowflake.png
  docs/docusaurus/docs/cloud/architecture_deployment_images/gx_cloud_architecture_and_deployment_diagrams.drawio
  docs/docusaurus/docs/cloud/architecture_deployment_images/gx_cloud_architecture_components.png
  docs/docusaurus/docs/cloud/gx_cloud_lp.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8923 [DOCS] Update descs for custom expectations
  docs/docusaurus/docs/guides/expectations/custom_expectations_lp.md
Labels: community

#8906 [MAINTENANCE] Helpful Message for Expectations that require Metrics that are not available
  great_expectations/expectations/expectation.py
  tests/expectations/test_expectation.py
Labels: dx, core

#8884 [MAINTENANCE] `PandasFilesystemDatasource` E2E tests
  tests/integration/cloud/end_to_end/test_pandas_filesystem_datasource.py
Labels: core

#8940 [MAINTENANCE] Remove Cloud integration tests with duplicated logic
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/test_base_data_context.py
  tests/datasource/fluent/test_pandas_datasource.py
Labels: core

#8811 [DOCS] Update syntax highlighting in main README
  README.md
Labels: core

#8939 [DOCS] Minor Updates to GX Cloud Documentation
  docs/docusaurus/docs/cloud/checkpoints/manage_checkpoints.md
  docs/docusaurus/docs/cloud/data_assets/manage_data_assets.md
Labels: devrel

#8941 [MAINTENANCE] Fix error in boolean logic for local assume command
  tasks.py
Labels: core

#8876 [MAINTENANCE] Add local verify step for pact tests
  tasks.py
  tests/integration/cloud/rest_contracts/conftest.py
  tests/integration/cloud/rest_contracts/test_data_context_configuration.py
  tests/integration/cloud/rest_contracts/test_expectation_suites.py
Labels: core

#8948 [DOCS] add `FabricPowerBIDatasource` api docs
  great_expectations/datasource/fluent/schemas/FabricPowerBIDatasource.json
  great_expectations/datasource/fluent/schemas/FabricPowerBIDatasource/PowerBIDax.json
  great_expectations/datasource/fluent/schemas/FabricPowerBIDatasource/PowerBIMeasure.json
  great_expectations/datasource/fluent/schemas/FabricPowerBIDatasource/PowerBITable.json
  great_expectations/experimental/datasource/fabric.py
Labels: core

#8949 [DOCS] Document Add Data Asset to Existing Data Source Functionality
  docs/docusaurus/docs/cloud/data_assets/manage_data_assets.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8898 [DOCS] Create OSS Troubleshooting Topic
  docs/docusaurus/docs/troubleshooting.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8952 [DOCS] Minor Updates to Create a Data Asset
  docs/docusaurus/docs/cloud/data_assets/manage_data_assets.md
Labels: devrel

#8953 [RELEASE] 0.18.2
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8959 [DOCS] List the Available GX Cloud Expectations in Manage Expectations
  docs/docusaurus/docs/cloud/data_assets/manage_data_assets.md
  docs/docusaurus/docs/cloud/expectations/manage_expectations.md
Labels: devrel

#8956 [MAINTENANCE] Add delete Data Source and Data Asset methods to end-to-end tests
  tests/integration/cloud/end_to_end/conftest.py
  tests/integration/cloud/end_to_end/test_pandas_datasource.py
  tests/integration/cloud/end_to_end/test_pandas_filesystem_datasource.py
  tests/integration/cloud/end_to_end/test_snowflake_datasource.py
  tests/integration/cloud/end_to_end/test_spark_datasource.py
  tests/integration/cloud/end_to_end/test_spark_filesystem_datasource.py
Labels: core

#8951 [DOCS] DSB-484 Improve Quickstart diagram links
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
Labels: devrel

#8962 [MAINTENANCE] dry up validation status calc
  great_expectations/data_asset/data_asset.py
  great_expectations/validator/validation_statistics.py
  great_expectations/validator/validator.py
  tests/test_great_expectations.py
  tests/validator/test_validation_statistics.py
Labels: core

#8935 [MAINTENANCE] Update type hints so our decorators play well with classes
  great_expectations/core/_docs_decorators.py
Labels: core

#8942 [CONTRIB] add sqlalchemy execution engine compatability to expect_column_values…
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_not_to_be_future_date.py
Labels: community

#8938 [CONTRIB] add sqlalchemy support for expect_multicolumn_values_not_to_be_all_null
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_values_not_to_be_all_null.py
Labels: community

#8922 [FEATURE] Update SnowflakeDatasource connection details
  great_expectations/datasource/fluent/schemas/SnowflakeDatasource.json
  great_expectations/datasource/fluent/snowflake_datasource.py
  great_expectations/datasource/fluent/sources.pyi
  tests/datasource/fluent/test_snowflake_datasource.py
Labels: core

#8931 [DOCS] Update Add Validation Data or Expectation Suites to a Checkpoint
  ci/checks/check_integration_test_gets_run.py
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_add_validations_data_or_suites_to_a_checkpoint.md
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/integration/docusaurus/validation/checkpoints/how_to_add_validations_data_or_suites_to_a_checkpoint.py
  tests/integration/test_script_runner.py
Labels: devrel

#8969 [RELEASE] 0.18.3
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: dx, core

#8950 [MAINTENANCE] Fix error in mercury api container causing cloud-tests job to fail
  .github/workflows/ci.yml
  assets/docker/mercury/docker-compose.yml
Labels: core

#8946 [CONTRIB] `expect_multicolumn_datetime_difference_is_less_than_two_months`
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_datetime_difference_to_be_less_than_two_months.py
Labels: community

#8964 [BUGFIX] Fixed compound_columns_to_be_unique bug caused by the reuse of temporary tables in MySQL #6286
  great_expectations/expectations/metrics/multicolumn_map_metrics/compound_columns_unique.py
  tests/test_definitions/multicolumn_map_expectations/expect_compound_columns_to_be_unique.json
Labels: community

#8961 [MAINTENANCE] Make config mandatory in Expectation constructor
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_suite.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/registry.py
  great_expectations/validator/validator.py
  tests/expectations/fixtures/expect_column_values_to_equal_three.py
  tests/expectations/test_generate_diagnostic_checklist.py
  tests/expectations/test_run_diagnostics.py
  tests/expectations/test_run_diagnostics_supporting_methods.py
  tests/validator/test_validation_graph.py
Labels: core

#8967 [FEATURE] validator 1.0
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  great_expectations/core/batch_config.py
  great_expectations/validator/v1_validator.py
  pyproject.toml
  tests/conftest.py
  tests/core/test_batch_config.py
  tests/validator/test_v1_validator.py
Labels: core

#8976 [DOCS] Return Support Section to GX Cloud Docs
  docs/docusaurus/docs/cloud/about_gx.md
Labels: devrel

#8980 [BUGFIX] Patch breaking docs tests as a result of Expectation constructor changes
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_max_to_be_between_custom.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_be_in_solfege_scale_set.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_only_contain_vowels.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_multicolumn_values_to_be_multiples_of_three.py
Labels: core

#8982 [MAINTENANCE] Add context to `BatchConfig`, and fetch assets by name
  great_expectations/core/batch_config.py
  tests/conftest.py
  tests/core/test_batch_config.py
  tests/validator/test_v1_validator.py
Labels: core

#8965 [MAINTENANCE] Have `Expectation` inherit from `pydantic.BaseModel`
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_suite.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_not_be_null.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/registry.py
  great_expectations/validator/validator.py
  tests/expectations/metrics/test_map_metric.py
  tests/expectations/test_expectation.py
  tests/expectations/test_generate_diagnostic_checklist.py
  tests/expectations/test_run_diagnostics.py
  tests/expectations/test_run_diagnostics_supporting_methods.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_max_to_be_between_custom.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_be_in_solfege_scale_set.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_only_contain_vowels.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_multicolumn_values_to_be_multiples_of_three.py
  tests/validator/test_v1_validator.py
  tests/validator/test_validation_graph.py
  tests/validator/test_validator.py
Labels: core

#8973 [MAINTENANCE] Refactor ExpectationSuite.expectations
  great_expectations/core/expectation_suite.py
  great_expectations/data_asset/data_asset.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/dataset/pandas_dataset.py
  great_expectations/jupyter_ux/__init__.py
  great_expectations/profile/base.py
  great_expectations/profile/user_configurable_profiler.py
  great_expectations/render/renderer/page_renderer.py
  great_expectations/render/renderer/suite_edit_notebook_renderer.py
  great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py
  great_expectations/validator/v1_validator.py
  great_expectations/validator/validator.py
  tests/cli/test_suite.py
  tests/core/test_expectation_suite.py
  tests/core/test_expectation_suite_crud_methods.py
  tests/data_asset/test_data_asset_internals.py
  tests/data_asset/test_expectation_decorators.py
  tests/data_asset/test_filedata_asset.py
  tests/data_asset/test_parameter_substitution.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_state_management.py
  tests/integration/docusaurus/expectations/how_to_create_and_edit_an_expectationsuite_domain_knowledge.py
  tests/integration/docusaurus/expectations/how_to_edit_an_expectation_suite.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/profile/conftest.py
  tests/profile/test_profile.py
  tests/profile/test_user_configurable_profiler_v2_batch_kwargs.py
  tests/profile/test_user_configurable_profiler_v3_batch_request.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/render/test_column_section_renderer.py
  tests/render/test_render.py
  tests/rule_based_profiler/data_assistant/test_volume_data_assistant.py
  tests/rule_based_profiler/test_user_workflow_fixtures.py
  tests/test_fixtures/expectation_suites/parameterized_expectation_suite_fixture.json
Labels: core

#8958 [MAINTENANCE] Refactor Cloud end-to-end tests for ease of maintenance
  tests/integration/cloud/end_to_end/conftest.py
  tests/integration/cloud/end_to_end/test_pandas_datasource.py
  tests/integration/cloud/end_to_end/test_pandas_filesystem_datasource.py
  tests/integration/cloud/end_to_end/test_snowflake_datasource.py
  tests/integration/cloud/end_to_end/test_spark_datasource.py
  tests/integration/cloud/end_to_end/test_spark_filesystem_datasource.py
Labels: core

#8985 [MAINTENANCE] Start adding shared fields to Expectation model
  great_expectations/expectations/expectation.py
  great_expectations/validator/validator.py
  tests/expectations/core/test_expect_column_max_to_be_between.py
  tests/expectations/core/test_expect_column_values_to_be_decreasing.py
  tests/expectations/core/test_expect_column_values_to_be_increasing.py
  tests/expectations/metrics/test_map_metric.py
  tests/expectations/test_expectation.py
  tests/expectations/test_expectation_arguments.py
  tests/expectations/test_generate_diagnostic_checklist.py
  tests/expectations/test_run_diagnostics.py
  tests/expectations/test_run_diagnostics_supporting_methods.py
  tests/test_definitions/multicolumn_map_expectations/expect_compound_columns_to_be_unique.json
  tests/test_definitions/multicolumn_map_expectations/expect_multicolumn_sum_to_equal.json
  tests/test_definitions/multicolumn_map_expectations/expect_select_column_values_to_be_unique_within_record.json
  tests/validator/test_validator.py
Labels: core

#8983 [MAINTENANCE] Add name to batch config
  great_expectations/core/batch_config.py
  tests/core/test_batch_config.py
  tests/validator/test_v1_validator.py
Labels: core

#8977 [MAINTENANCE] Add wrapper for posthog analytics as well as an initial event
  great_expectations/analytics/__init__.py
  great_expectations/analytics/actions.py
  great_expectations/analytics/base_event.py
  great_expectations/analytics/client.py
  great_expectations/analytics/config.py
  great_expectations/analytics/events.py
  great_expectations/compatibility/pydantic.py
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/data_context/data_context/abstract_data_context.py
  requirements.txt
  tests/test_packaging.py
Labels: core
