Repository great-expectations/great_expectations, pull requests merged in 2023-04, with the labels that each got.

#7537 [MAINTENANCE]: Clean up ununsed imports
  examples/expectations/regex_based_column_map_expectation_template.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_only_contain_vowels.py
  tests/integration/docusaurus/expectations/examples/regex_based_column_map_expectation_template.py
Labels: core-team

#7539 [BUGFIX] Fix issue running quickstart
  great_expectations/compatibility/sqlalchemy_and_pandas.py
  great_expectations/df_to_database_loader.py
  great_expectations/util.py
Labels: core-team, dx

#7536 [MAINTENANCE] Fix Type-Checking steps
  ci/azure-pipelines-dev.yml
  great_expectations/compatibility/sqlalchemy_and_pandas.py
  great_expectations/self_check/util.py
  tests/datasource/fluent/test_config.py
Labels: core-team, platform

#7541 [MAINTENANCE] Disable UserConfigurableProfiler tests relying on deprecated V2 functionality
  great_expectations/expectations/metrics/metric_provider.py
  tests/profile/test_basic_suite_builder_profiler.py
Labels: core-team, platform

#7538 [MAINTENANCE]: replace ColumnMetricProvider with ColumnAggregateMetricProvider
  contrib/experimental/great_expectations_experimental/expectations/expect_column_discrete_entropy_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_distribution_to_match_benfords_law.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_kurtosis_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_skew_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_normally_distributed.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_wasserstein_distance_to_be_less_than.py
Labels: core-team

#7544 [MAINTENANCE] Exclude files from deprecation warning check
  tests/test_deprecation.py
Labels: core-team, dx

#7542 [DOCS] Quickstart code under test
  ci/azure-pipelines-dev.yml
  docs/sphinx_api_docs_source/public_api_report.py
  tests/integration/docusaurus/tutorials/quickstart/__init__.py
  tests/integration/docusaurus/tutorials/quickstart/quickstart.py
  tests/integration/test_script_runner.py
Labels: core-team, dx

#7442 [BUGFIX] Fluent Datasource load from config fixes for remaining Pandas Datasources
  docs/docusaurus/docs/components/connect_to_data/cloud/_abs_fluent_data_asset_config_keys.mdx
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_azure_blob_storage_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_gcs_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_s3_using_pandas.md
  docs/sphinx_api_docs_source/public_api_report.py
  great_expectations/datasource/fluent/data_asset/data_connector/azure_blob_storage_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/google_cloud_storage_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/s3_data_connector.py
  great_expectations/datasource/fluent/file_path_data_asset.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.pyi
  great_expectations/datasource/fluent/pandas_dbfs_datasource.py
  great_expectations/datasource/fluent/pandas_dbfs_datasource.pyi
  great_expectations/datasource/fluent/pandas_filesystem_datasource.pyi
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.pyi
  great_expectations/datasource/fluent/pandas_s3_datasource.py
  great_expectations/datasource/fluent/pandas_s3_datasource.pyi
  great_expectations/datasource/fluent/sources.py
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/spark_dbfs_datasource.py
  great_expectations/datasource/fluent/spark_filesystem_datasource.py
  great_expectations/datasource/fluent/spark_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/spark_s3_datasource.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/great_expectations.yml
  tests/datasource/fluent/integration/test_integration_datasource.py
  tests/datasource/fluent/test_config.py
  tests/datasource/fluent/test_pandas_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_pandas_s3_datasource.py
  tests/datasource/fluent/test_spark_s3_datasource.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core-team, platform

#7549 [DOCS] Update GX version in `_data.jsx` component
  docs/docusaurus/docs/components/_data.jsx
Labels: core-team, platform

#7533 [DOCS] Fixes broken code block and incorrectly numbered steps in "How to organize Batches in a SQL-based Data Asset"
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_sql_based_data_asset.md
Labels: devrel

#7557 [DOCS] Update nav to match gx.io site
  docs/docusaurus/docusaurus.config.js
Labels: devrel

#7559 [DOCS] Corrects step numbers in "How to organize Batches in a file-based Data Asset"
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_file_based_data_asset.md
Labels: devrel

#7566 [DOCS] Delete SLACK_GUIDELINES.md
  CODE_OF_CONDUCT.md
  SLACK_GUIDELINES.md
  ci/checks/check_repo_root_size.sh
  docs/docusaurus/docs/intro.md
Labels: devrel

#7553 [BUGFIX] Address `pandas==2.0.0` test failures
  great_expectations/compatibility/pandas_compatibility.py
  great_expectations/datasource/fluent/pandas_s3_datasource.pyi
  great_expectations/self_check/util.py
  tests/cli/test_suite.py
  tests/expectations/metrics/test_core.py
  tests/expectations/test_expectation_atomic_renderers.py
Labels: core-team, dx

#7563 [DOCS] Update syntax highlighting of code blocks in GX Cloud Getting Started guide
  docs/docusaurus/docs/gx_cloud/tutorials/getting_started/getting_started_with_gx_cloud.md
Labels: core-team, platform

#7343 [MAINTENANCE] Test Pandas 2.0 prerelease in CI/CD
  ci/azure-pipelines.yml
  ci/constraints-test/pandas2-min-install.txt
Labels: core-team, platform

#7564 [MAINTENANCE] Add noqa directives for existing sqlalchemy imports
  great_expectations/cli/batch_request.py
  great_expectations/cli/checkpoint.py
  great_expectations/cli/datasource.py
  great_expectations/cli/init.py
  great_expectations/cli/suite.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/store/database_store_backend.py
  great_expectations/data_context/store/query_store.py
  great_expectations/data_context/util.py
  great_expectations/dataset/dataset.py
  great_expectations/dataset/util.py
  great_expectations/datasource/batch_kwargs_generator/query_batch_kwargs_generator.py
  great_expectations/datasource/batch_kwargs_generator/table_batch_kwargs_generator.py
  great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py
  great_expectations/datasource/fluent/pandas_datasource.pyi
  great_expectations/datasource/fluent/sql_datasource.py
  great_expectations/datasource/simple_sqlalchemy_datasource.py
  great_expectations/df_to_database_loader.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_splitter.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/execution_engine/util.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_be_json_parseable.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/core/expect_column_values_to_be_unique.py
  great_expectations/expectations/core/expect_column_values_to_match_json_schema.py
  great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_in_set.py
  great_expectations/expectations/metrics/import_manager.py
  great_expectations/expectations/metrics/table_metrics/table_column_types.py
  great_expectations/expectations/metrics/util.py
  great_expectations/expectations/row_conditions.py
  great_expectations/profile/basic_dataset_profiler.py
  great_expectations/rule_based_profiler/attributed_resolved_metrics.py
  great_expectations/self_check/sqlalchemy_connection_manager.py
  great_expectations/self_check/util.py
  great_expectations/util.py
Labels: core-team, dx

#7554 [DOCS] Fix code snippets for earlier versions
  docs/build_docs
  docs/docusaurus/docusaurus.config.js
  docs/docusaurus/package.json
  docs/docusaurus/scripts/remark-named-snippets/index.js
  docs/docusaurus/scripts/remark-named-snippets/snippet.js
  docs/docusaurus/yarn.lock
  docs/prepare_prior_versions.py
  docs/yarn.lock
Labels: core-team, dx

#7562 [MAINTENANCE] Add ruff rule for sqlalchemy imports
  .git-blame-ignore-revs
  contrib/ruff.toml
  pyproject.toml
  tests/ruff.toml
Labels: core-team, dx

#7532 [MAINTENANCE] adding a footer to data docs with a link to the cloud page
  great_expectations/render/view/static/styles/data_docs_default_styles.css
  great_expectations/render/view/templates/cloud-footer.j2
  great_expectations/render/view/templates/index_page.j2
  great_expectations/render/view/templates/page.j2
Labels: devrel

#7568 [DOCS] Fix typo in docs
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
Labels: core-team

#7569 [DOCS] Moar typo fix
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
Labels: core-team

#7513 [FEATURE] Fluent `DataAsset` `batch_metadata` config variables
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/datasource/fluent/file_path_data_asset.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/pandas_datasource.pyi
  great_expectations/datasource/fluent/spark_datasource.py
  great_expectations/datasource/fluent/sql_datasource.py
  tests/datasource/fluent/integration/conftest.py
  tests/datasource/fluent/test_config.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/datasource/fluent/test_pandas_dbfs_datasource.py
  tests/datasource/fluent/test_pandas_filesystem_datasource.py
  tests/datasource/fluent/test_pandas_s3_datasource.py
  tests/datasource/fluent/test_postgres_datasource.py
  tests/datasource/fluent/test_spark_datasource.py
  tests/datasource/fluent/test_spark_filesystem_datasource.py
  tests/datasource/fluent/test_sqlite_datasource.py
Labels: core-team, platform

#7558 [MAINTENANCE] Harden tests for `CloudDataContext` always `include_rendered_content`
  tests/data_context/cloud_data_context/test_include_rendered_content.py
  tests/data_context/test_get_data_context.py
Labels: core-team, platform

#7534 [FEATURE] Add batch metadata to spark add_*_asset methods
  great_expectations/datasource/fluent/file_path_data_asset.py
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/spark_datasource.py
  great_expectations/datasource/fluent/spark_dbfs_datasource.py
  great_expectations/datasource/fluent/spark_dbfs_datasource.pyi
  great_expectations/datasource/fluent/spark_filesystem_datasource.py
  great_expectations/datasource/fluent/spark_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/spark_s3_datasource.py
  tests/datasource/fluent/test_spark_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_spark_datasource.py
  tests/datasource/fluent/test_spark_dbfs_datasource.py
  tests/datasource/fluent/test_spark_filesystem_datasource.py
  tests/datasource/fluent/test_spark_google_cloud_storage_datasource.py
  tests/datasource/fluent/test_spark_s3_datasource.py
Labels: core-team, platform

#7561 [MAINTENANCE] Simplify `GXCloudStoreBackend._has_key` check
  great_expectations/data_context/store/gx_cloud_store_backend.py
  great_expectations/exceptions/exceptions.py
Labels: core-team, platform

#7571 [MAINTENANCE] Temporarily Pin `pandas<2.0.0` for compatibility
  great_expectations/self_check/util.py
  requirements.txt
  tests/cli/test_suite.py
  tests/expectations/test_expectation_atomic_renderers.py
  tests/test_definitions/test_expectations_v3_api.py
Labels: core-team, dx

#7529 [MAINTENANCE] SqlAlchemy 2.0 Compatibility - branched connection + `bind` argument now required
  great_expectations/compatibility/sqlalchemy_compatibility_wrappers.py
  great_expectations/datasource/fluent/pandas_s3_datasource.pyi
  great_expectations/datasource/fluent/spark_dbfs_datasource.pyi
  great_expectations/expectations/metrics/table_metrics/table_head.py
  great_expectations/self_check/util.py
  pyproject.toml
  tests/conftest.py
  tests/data_context/test_data_context_test_yaml_config.py
  tests/datasource/fluent/integration/conftest.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
  tests/execution_engine/test_sqlalchemy_batch_data.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/expectations/metrics/test_core.py
  tests/expectations/test_null_filters.py
  tests/profile/test_user_configurable_profiler_v3_batch_request.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant_happy_paths.py
  tests/test_deprecation.py
  tests/test_utils.py
Labels: core-team, dx

#7552 [BUGFIX] Render prescriptive `ExpectationConfiguration`s with evaluation parameters inline
  great_expectations/render/renderer_configuration.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/validator/test_validator.py
Labels: core-team, platform

#7578 [DOCS] Fix integral typo
  docs/docusaurus/docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_a_file_system_or_blob_store.md
  docs/docusaurus/docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_tables_in_sql.md
  docs/docusaurus/docs/guides/connecting_to_your_data/datasource_configuration/sql_components/_table_splitting_methods.mdx
Labels: core-team

#7567 [DOCS] Prepare earlier versions using develop
  docs/build_docs
Labels: core-team, dx

#7577 [MAINTENANCE] Add missing docstrings to fluent `sql_datasource` splitter methods.
  great_expectations/datasource/fluent/sql_datasource.py
Labels: core-team

#7579 [DOCS] Use orange in docs logs
  docs/build_docs
Labels: core-team, dx

#7517 [DOCS] Add GX Cloud Onboarding Script
  assets/scripts/gx_cloud/experimental/onboarding_script.py
Labels: cloud

#7575 [BUGFIX] Release Pipeline Fix
  ci/azure-pipelines.yml
  tests/data_context/cloud_data_context/test_include_rendered_content.py
Labels: core-team, dx

#7582 [RELEASE] 0.16.6
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#7581 [DOCS] Use current minor version number in drop down instead of "Current"
  docs/docusaurus/docusaurus.config.js
Labels: core-team, dx

#7585 [DOCS] Adds deprecation policy to changelog page
  docs/docusaurus/docs/changelog.md
Labels: devrel

#7576 [CONTRIB] add check to calculate difference between 2 dates in month
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_datetime_difference_in_months.py
Labels: community

#7588 [MAINTENANCE] Capitalize "If" in rendering of conditional Expectations
  great_expectations/render/renderer_configuration.py
  tests/validator/test_validator.py
Labels: core-team, platform

#7583 [DOCS] Use the actual version after release
  docs/docusaurus/docusaurus.config.js
Labels: core-team, dx

#7587 [MAINTENANCE] Remove pip pins in CI and in contributing_setup.md
  ci/azure-pipelines-cloud-integration.yml
  ci/azure-pipelines-contrib.yml
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-os-integration.yml
  ci/dev-install-matrix.yml
  ci/user-install-matrix.yml
  docs/docusaurus/docs/contributing/contributing_setup.md
  docs/expectation_gallery/azure-pipelines-expectation-gallery.yml
  docs/expectation_gallery/azure-pipelines-manual-staging-json-to-prod.yml
Labels: core-team, dx

#7584 [MAINTENANCE] Remove ignore of warning deprecated api features detected sqlalchemy 2
  pyproject.toml
Labels: core-team, dx

#7589 [MAINTENANCE] Fix sqlalchemy 2.0 incompatible warnings
  tests/cli/test_checkpoint.py
  tests/conftest.py
Labels: core-team, dx

#7580 [DOCS] Update some docs_rtd requirements so the venv can be created successfully
  docs_rtd/requirements.txt
Labels: core-team, dx

#7594 [DOCS] Updates how the GX Cloud Beta is referenced in the Quickstart guide.
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
Labels: devrel

#7591 [MAINTENANCE] Increase minimum scipy version package to 1.6.0 to take advantage of available capabilities.
  requirements.txt
Labels: core-team, platform

#7600 [DOCS] Corrects typo in code block within in-memory Pandas guide
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/in_memory/how_to_connect_to_in_memory_data_using_pandas.md
Labels: devrel

#7598 [MAINTENANCE] Remove s3fs dependency and upper bound for boto3
  constraints-dev.txt
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/datasource/batch_kwargs_generator/__init__.py
  great_expectations/datasource/batch_kwargs_generator/s3_subdir_reader_batch_kwargs_generator.py
  reqs/requirements-dev-lite.txt
  tests/datasource/batch_kwarg_generator/test_s3_subdir_reader_generator.py
Labels: core-team, dx

#7602 [MAINTENANCE] Move Fluent Datasources Sorters into `TYPE_CHECKING` block
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.pyi
  great_expectations/datasource/fluent/spark_filesystem_datasource.pyi
  great_expectations/datasource/fluent/spark_google_cloud_storage_datasource.pyi
  great_expectations/datasource/fluent/spark_s3_datasource.pyi
Labels: core-team, dx

#7604 [MAINTENANCE] Polish and ratchet requirements pins and upper bounds
  tests/test_packaging.py
Labels: core-team, dx

#7592 [CONTRIB] Expect Column Values to be Valid UUID - Added SqlAlchemyExecutionEngine support
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_be_valid_uuid.py
Labels: community

#7547 [FEATURE] Added AssumeRole Feature
  great_expectations/data_context/store/tuple_store_backend.py
Labels: community

#7597 [DOCS] Correct expectation documentation for expect_column_max_to_be_between
  great_expectations/expectations/core/expect_column_max_to_be_between.py
Labels: core-team

#7609 [MAINTENANCE] Deprecate ColumnExpectation in favor of ColumnAggregateExpectation
  contrib/experimental/great_expectations_experimental/expectations/expect_column_discrete_entropy_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_distinct_values_to_be_continuous.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_distribution_to_match_benfords_law.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_kurtosis_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_skew_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_sum_to_be.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_to_have_no_days_missing.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_in_set_spark_optimized.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_normally_distributed.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_string_integers_increasing.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_wasserstein_distance_to_be_less_than.py
  contrib/experimental/great_expectations_experimental/expectations/expect_day_count_to_be_close_to_equivalent_week_day_mean.py
  contrib/experimental/great_expectations_experimental/expectations/expect_yesterday_count_compared_to_avg_equivalent_days_of_week.py
  contrib/great_expectations_geospatial_expectations/great_expectations_geospatial_expectations/expectations/expect_column_average_lat_lon_pairwise_distance_to_be_less_than.py
  contrib/great_expectations_geospatial_expectations/great_expectations_geospatial_expectations/expectations/expect_column_average_to_be_within_range_of_given_point.py
  contrib/great_expectations_geospatial_expectations/great_expectations_geospatial_expectations/expectations/expect_column_minimum_bounding_radius_to_be_between.py
  contrib/great_expectations_geospatial_expectations/great_expectations_geospatial_expectations/expectations/expect_column_values_geometry_not_to_overlap.py
  contrib/great_expectations_geospatial_expectations/great_expectations_geospatial_expectations/expectations/expect_column_values_geometry_to_overlap.py
  contrib/time_series_expectations/README.md
  contrib/time_series_expectations/docs/README.md
  contrib/time_series_expectations/docs/working-notes.md
  contrib/time_series_expectations/time_series_expectations/expectations/column_aggregate_time_series_expectation.py
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_add_support_for_the_auto_initializing_framework_to_a_custom_expectation.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
  examples/expectations/column_aggregate_expectation_template.py
  great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_most_common_value_to_be_in_set.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/expectation.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_max_to_be_between_custom.py
  tests/integration/docusaurus/expectations/examples/column_aggregate_expectation_template.py
  tests/integration/docusaurus/expectations/examples/table_expectation_template.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/BasicExample_RBP_Instantiation_and_running.ipynb
Labels: core-team

#7610 [MAINTENANCE] Deprecate TableExpectation in favor of BatchExpectation
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/profile_numeric_columns_diff_expectation.py
  contrib/experimental/great_expectations_experimental/expectations/expect_table_checksum_to_equal_other_table.py
  contrib/great_expectations_ethical_ai_expectations/great_expectations_ethical_ai_expectations/expectations/expect_table_binary_label_model_bias.py
  contrib/great_expectations_ethical_ai_expectations/great_expectations_ethical_ai_expectations/expectations/expect_table_linear_feature_importances_to_be.py
  contrib/time_series_expectations/README.md
  contrib/time_series_expectations/docs/README.md
  contrib/time_series_expectations/docs/working-notes.md
  contrib/time_series_expectations/time_series_expectations/expectations/expect_batch_row_count_to_match_prophet_date_model.py
  docs/docusaurus/docs/contributing/style_guides/code_style.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_batch_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/overview.md
  docs/docusaurus/docs/guides/expectations/index.md
  docs/docusaurus/sidebars.js
  examples/expectations/batch_expectation_template.py
  great_expectations/expectations/core/expect_column_bootstrapped_ks_test_p_value_to_be_greater_than.py
  great_expectations/expectations/core/expect_column_chisquare_test_p_value_to_be_greater_than.py
  great_expectations/expectations/core/expect_column_pair_cramers_phi_value_to_be_less_than.py
  great_expectations/expectations/core/expect_column_parameterized_distribution_ks_test_p_value_to_be_greater_than.py
  great_expectations/expectations/core/expect_column_to_exist.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/core/expect_table_column_count_to_be_between.py
  great_expectations/expectations/core/expect_table_column_count_to_equal.py
  great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py
  great_expectations/expectations/core/expect_table_columns_to_match_set.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_equal.py
  great_expectations/expectations/core/expect_table_row_count_to_equal_other_table.py
  great_expectations/expectations/expectation.py
  tests/data_context/test_data_context.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_batch_columns_to_be_unique.py
  tests/integration/docusaurus/expectations/examples/batch_expectation_template.py
Labels: core-team

#7613 [MAINTENANCE] Explicitly test relevant modules in Sqlalchemy compatibility pipeline
  ci/azure-pipelines-sqlalchemy-compatibility.yml
  pyproject.toml
  tests/data_context/store/test_database_store_backend.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
  tests/execution_engine/test_sqlalchemy_batch_data.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/test_definitions/test_expectations_v3_api.py
Labels: core-team, dx

#7615 [DOCS] Add scripts under test for "How to create and edit Expectations with instant feedback from a sample Batch of data"
  great_expectations/datasource/fluent/file_path_data_asset.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/schemas/PandasDatasource.json
  great_expectations/datasource/fluent/spark_datasource.py
  great_expectations/datasource/fluent/sql_datasource.py
  tests/integration/docusaurus/validation/validator/how_to_create_and_edit_expectations_with_instant_feedback_block_config.py
  tests/integration/docusaurus/validation/validator/how_to_create_and_edit_expectations_with_instant_feedback_fluent.py
  tests/integration/test_script_runner.py
Labels: core-team, platform

#7573 [MAINTENANCE] Fluent Datasources: Eliminate redundant Datasource name and DataAsset name from dictionary and JSON configuration
  docs/sphinx_api_docs_source/public_api_report.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context/serializable_data_context.py
  great_expectations/data_context/data_context_variables.py
  great_expectations/data_context/types/base.py
  great_expectations/datasource/fluent/config.py
  great_expectations/datasource/fluent/constants.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/pandas_datasource.pyi
  great_expectations/datasource/fluent/pandas_file_path_datasource.py
  great_expectations/datasource/fluent/pandas_file_path_datasource.pyi
  great_expectations/datasource/fluent/pandas_filesystem_datasource.py
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/pandas_s3_datasource.py
  great_expectations/datasource/fluent/schemas/Datasource.json
  great_expectations/datasource/fluent/schemas/PandasAzureBlobStorageDatasource.json
  great_expectations/datasource/fluent/schemas/PandasDBFSDatasource.json
  great_expectations/datasource/fluent/schemas/PandasDatasource.json
  great_expectations/datasource/fluent/schemas/PandasFilesystemDatasource.json
  great_expectations/datasource/fluent/schemas/PandasGoogleCloudStorageDatasource.json
  great_expectations/datasource/fluent/schemas/PandasS3Datasource.json
  great_expectations/datasource/fluent/schemas/PostgresDatasource.json
  great_expectations/datasource/fluent/schemas/SQLDatasource.json
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDatasource.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource.json
  great_expectations/datasource/fluent/schemas/SqliteDatasource.json
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/spark_datasource.py
  great_expectations/datasource/fluent/spark_file_path_datasource.py
  great_expectations/datasource/fluent/spark_filesystem_datasource.py
  great_expectations/datasource/fluent/spark_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/spark_s3_datasource.py
  great_expectations/datasource/fluent/sql_datasource.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/integration/conftest.py
  tests/datasource/fluent/test_config.py
  tests/datasource/fluent/test_metadatasource.py
  tests/datasource/fluent/test_pandas_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/datasource/fluent/test_pandas_dbfs_datasource.py
  tests/datasource/fluent/test_pandas_filesystem_datasource.py
  tests/datasource/fluent/test_pandas_google_cloud_storage_datasource.py
  tests/datasource/fluent/test_pandas_s3_datasource.py
  tests/datasource/fluent/test_postgres_datasource.py
  tests/datasource/fluent/test_spark_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_spark_datasource.py
  tests/datasource/fluent/test_spark_dbfs_datasource.py
  tests/datasource/fluent/test_spark_filesystem_datasource.py
  tests/datasource/fluent/test_spark_google_cloud_storage_datasource.py
  tests/datasource/fluent/test_spark_s3_datasource.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core-team, platform

#7619 [BUGFIX] Remove spark from bic Expectations since it never worked for them
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_bic_belong_to_country.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_be_valid_bic.py
Labels: core-team, dx

#7622 [RELEASE] 0.16.7
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#7623 [MAINTENANCE] Update `teams.yml`
  .github/teams.yml
Labels: core

#7627 [DOCS] Update overview.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/overview.md
Labels: core

#7626 [BUGFIX] MapCondition Memory Inefficiencies in Spark
  great_expectations/expectations/metrics/map_metric_provider/map_condition_auxilliary_methods.py
  tests/checkpoint/test_checkpoint_result_format.py
Labels: dx, core

#7624 [DOCS] Updates the "Interactive Mode" guide for creating Expectations
  docs/docusaurus/docs/components/setup/link_lists/_data_context_initialize_quick_or_filesystem.mdx
  docs/docusaurus/docs/guides/connecting_to_your_data/how_to_get_one_or_more_batches_of_data_from_a_configured_datasource.md
  docs/docusaurus/docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_preface.mdx
  docs/docusaurus/docs/guides/expectations/how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data.md
  tests/integration/docusaurus/validation/validator/how_to_create_and_edit_expectations_with_instant_feedback_fluent.py
Labels: devrel

#7636 [DOCS] Updates the language in the banner linking the legacy site to the current docs.
  docs_rtd/_templates/layout.html
Labels: devrel

#7639 [MAINTENANCE] Remove stray cloud test marker.
  tests/checkpoint/test_checkpoint.py
Labels: core

#7632 [DOCS] Improve expect_column_values_to_be_of_type docstring
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
Labels: core

#7643 [DOCS] Corrects a typo found in the navigation section of the legacy docs
  docs_rtd/_templates/layout.html
Labels: devrel

#7645 [MAINTENANCE] Upgrade mypy to 1.2.0
  reqs/requirements-dev-contrib.txt
  tests/test_packaging.py
Labels: dx, core

#7647 [MAINTENANCE] Static type checking with python 3.8 followup
  ci/azure-pipelines-dev.yml
  great_expectations/compatibility/numpy.py
Labels: dx, core

#7654 [MAINTENANCE] numpy.typing only available after v1.20
  great_expectations/compatibility/numpy.py
Labels: dx, core

#7650 [MAINTENANCE] Uncap `altair` version, and bump minimum version to `4.2.1`. Also uncap `urllib3` version, and bump minimum version to `1.26`
  requirements.txt
  tests/conftest.py
  tests/test_packaging.py
Labels: dx, core

#7621 [DOCS] Standardize language around GX Cloud access tokens
  docs/docusaurus/docs/gx_cloud/tutorials/getting_started/getting_started_with_gx_cloud.md
Labels: core-team, platform

#7634 [DOCS] Added IAM user and IAM assume role doc
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_confirm_that_the_new_validation_results_store_has_been_added_by_running_great_expectations_store_list.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_update_your_configuration_file_to_include_a_new_store_for_expectations_on_s.mdx
Labels: community

#7658 [BUGFIX] Fix capitalone_dataprofiler_expectations imports
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/__init__.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/__init__.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_column_profiler_report.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_profile_diff.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_profile_numeric_columns.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_profile_percent_diff.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_profile_report.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_table_column_infos.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_table_column_list.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/rule_based_profiler/data_assistant/data_profiler_structured_data_assistant.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/expectations/metrics/test_core.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/rule_based_profiler/data_assistant/test_data_profiler_structured_data_assistant.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/rule_based_profiler/domain_builder/test_data_profiler_column_domain_builder.py
Labels: dx, core

#7570 [FEATURE] add Fluent Datasources to `CloudDataContext`
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/util.py
  reqs/requirements-dev-lite.txt
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_contexts.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core-team, platform

#7661 [BUGFIX] Correct GX configuration structure that incorporates both V3 and Fluent Datasources
  tests/datasource/fluent/test_config.py
Labels: dx, core

#7616 [DOCS] update to location of cloud callout in the OSS Quickstart
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
Labels: devrel

#7666 [RELEASE] 0.16.8
  .github/teams.yml
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#7665 [MAINTENANCE] Correcting minor typographical errors and type hints issues in Checkpoint and Test Checkpoint Modules
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/types/base.py
  tests/checkpoint/test_checkpoint.py
  tests/checkpoint/test_simple_checkpoint.py
Labels: dx, core

#7674 [MAINTENANCE] Only attempt docs-integration pipeline when manually triggered
  ci/azure-pipelines-docs-integration.yml
Labels: dx, core

#7673 [DOCS] Add fluent datasources and yaml configuration warning message
  docs/docusaurus/docs/components/warnings/_in_progress.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_in_aws_glue.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_in_databricks.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_in_deepnote.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_in_emr_serverless.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_meltano.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_prefect.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_ydata_synthetic.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_athena.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_cloud_storage_and_pandas.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_redshift.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_s3_and_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/connect_to_data_overview.md
  docs/docusaurus/docs/guides/expectations/advanced/how_to_compare_two_tables_with_the_user_configurable_profiler.md
  docs/docusaurus/docs/guides/expectations/advanced/how_to_create_a_new_expectation_suite_by_profiling_from_a_jsonschema_file.md
  docs/docusaurus/docs/guides/expectations/advanced/how_to_create_a_new_expectation_suite_using_rule_based_profilers.md
  docs/docusaurus/docs/guides/expectations/advanced/how_to_create_expectations_that_span_multiple_batches_using_evaluation_parameters.md
  docs/docusaurus/docs/guides/expectations/advanced/how_to_dynamically_load_evaluation_parameters_from_a_database.md
  docs/docusaurus/docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.md
  docs/docusaurus/docs/guides/expectations/how_to_create_and_edit_expectations_with_a_profiler.md
  docs/docusaurus/docs/guides/expectations/how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data.md
  docs/docusaurus/docs/guides/expectations/how_to_use_auto_initializing_expectations.md
  docs/docusaurus/docs/guides/miscellaneous/how_to_configure_notebooks_generated_by_suite_edit.md
  docs/docusaurus/docs/guides/validation/advanced/how_to_validate_data_with_an_in_memory_checkpoint.md
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_add_validations_data_or_suites_to_a_checkpoint.md
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config.md
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_create_a_new_checkpoint.md
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.md
  docs/docusaurus/docs/guides/validation/how_to_validate_data_by_running_a_checkpoint.md
  docs/docusaurus/docs/terms/batch_request.md
  docs/docusaurus/docs/terms/checkpoint.md
  docs/docusaurus/docs/terms/datasource.md
Labels: devrel

#7670 [MAINTENANCE] Clean up Checkpoint test method names and usage of batch_request_dict fixture
  tests/checkpoint/test_checkpoint.py
Labels: dx, core

#7676 [BUGFIX] Render Correct Fonts in Data Assistant Plot graphs
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
Labels: core

#7677 [MAINTENANCE] Correct typo in Checkpoint test method fixture
  tests/cli/test_checkpoint.py
  tests/conftest.py
  tests/render/renderer/test_checkpoint_new_notebook_renderer.py
Labels: dx, core

#7671 [DOCS] D/ /fluent connect to data overview
  docs/docusaurus/docs/guides/connecting_to_your_data/connect_to_data_overview.md
  tests/integration/docusaurus/connecting_to_your_data/connect_to_your_data_overview.py
  tests/integration/test_script_runner.py
Labels: core

#7681 [DOCS] Update fluent In Progress Cautionary Note
  docs/docusaurus/docs/components/warnings/_in_progress.md
Labels: devrel

#7683 [BUGFIX] Register core Expectations JIT in Validator workflows
  great_expectations/expectations/registry.py
  great_expectations/render/renderer/content_block/validation_results_table_content_block.py
  great_expectations/validator/validator.py
Labels: core

#7646 [MAINTENANCE] Enable remaining `CloudDataContext` `ExpectationSuite` CRUD
  docs/docusaurus/docs/gx_cloud/tutorials/getting_started/getting_started_with_gx_cloud.md
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
Labels: core

#7644 [DOCS] Remove version reference
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_create_a_new_checkpoint.md
Labels: core

#7686 [DOCS] Removing in-progress from docs confirmed as up-to-date
  docs/docusaurus/docs/guides/expectations/how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data.md
  docs/docusaurus/docs/guides/expectations/how_to_use_auto_initializing_expectations.md
Labels: core

#7692 [DOCS] Updated Datasource terms page
  docs/docusaurus/docs/terms/datasource.md
Labels: core

#7667 [MAINTENANCE] list_datasources should return FDS configs as well
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/types/base.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_data_context_datasources.py
  tests/data_context/test_data_context_v013.py
Labels: core

#7694 [DOCS] Removing json schema profiler documentation
  docs/docusaurus/docs/guides/expectations/advanced/how_to_create_a_new_expectation_suite_by_profiling_from_a_jsonschema_file.md
  docs/docusaurus/docs/guides/expectations/index.md
  docs/docusaurus/docs/terms/profiler.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
Labels: core

#7689 [DOCS] Removing CLI-based suite edit workflow
  docs/docusaurus/docs/guides/expectations/index.md
  docs/docusaurus/docs/guides/miscellaneous/how_to_configure_notebooks_generated_by_suite_edit.md
  docs/docusaurus/docs/reference/customize_your_deployment.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
Labels: core

#7695 [DOCS] Updated onboarding data assistant docs test script to Fluent-style
  ci/azure-pipelines-dev.yml
  docs/docusaurus/docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.md
  docs/sphinx_api_docs_source/public_api_report.py
  tests/integration/docusaurus/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.py
  tests/integration/test_script_runner.py
Labels: core

#7668 [DOCS] Update for fluent datasources: Expectations that span multiple batches evaluation params
  docs/docusaurus/docs/guides/expectations/advanced/how_to_create_expectations_that_span_multiple_batches_using_evaluation_parameters.md
  docs/sphinx_api_docs_source/public_api_report.py
  tests/integration/docusaurus/expectations/advanced/how_to_create_expectations_that_span_multiple_batches_using_evaluation_parameters.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7699 [DOCS] Quick docstring update for list_datasources
  great_expectations/data_context/data_context/abstract_data_context.py
Labels: core

#7700 [DOCS] Retiring the CLI
  docs/checks/docs_link_checker.py
  docs/docusaurus/docs/terms/cli.md
Labels: core

#7697 [FEATURE] Implementing Fluent Datasources Support for Checkpoint
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/batch.py
  great_expectations/core/usage_statistics/anonymizers/types/base.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/datasource/fluent/config.py
  great_expectations/datasource/fluent/file_path_data_asset.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/sources.py
  tests/checkpoint/conftest.py
  tests/checkpoint/test_checkpoint_with_fluent_datasources.py
  tests/conftest.py
  tests/datasource/fluent/integration/integration_test_utils.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/datasource/fluent/test_pandas_filesystem_datasource.py
  tests/test_fixtures/great_expectations_no_block_no_fluent_datasources.yml
  tests/test_fixtures/great_expectations_no_block_no_fluent_datasources_stats_enabled.yml
Labels: dx, core

#7698 [DOCS] Updating the Rule-Based Profiler doc to Fluent
  docs/docusaurus/docs/guides/expectations/advanced/how_to_create_a_new_expectation_suite_using_rule_based_profilers.md
  tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py
  tests/integration/docusaurus/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.py
  tests/integration/test_script_runner.py
Labels: core

#7715 [MAINTENACE] Adding black to invoke lint
  tasks.py
Labels: core

#7711 [BUGFIX] Replace renamed fixture
  tests/data_context/cloud_data_context/test_datasource_crud.py
Labels: core

#7716 [DOCS] Update Batch Request glossary entry.
  docs/docusaurus/docs/terms/batch_request.md
  tests/integration/docusaurus/connecting_to_your_data/connect_to_your_data_overview.py
  tests/integration/docusaurus/reference/glossary/batch_request.py
  tests/integration/test_script_runner.py
Labels: core

#7702 [DOCS] Removed guide for no YML, redirect to EphemeralDataContext
  docs/docusaurus/docs/components/setup/link_lists/_data_context_initialize_instatiate_save.md
  docs/docusaurus/docs/components/setup/next_steps/_links_after_installing_gx.md
  docs/docusaurus/docs/components/stores/_stores_overwrite_at_runtime.md
  docs/docusaurus/docs/deployment_patterns/how_to_instantiate_a_data_context_hosted_environments.md
  docs/docusaurus/docs/deployment_patterns/how_to_instantiate_a_data_context_on_an_emr_spark_cluster.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_in_databricks.md
  docs/docusaurus/docs/guides/connecting_to_your_data/components/spark_data_context_note.md
  docs/docusaurus/docs/guides/connecting_to_your_data/how_to_create_a_batch_of_data_from_an_in_memory_spark_or_pandas_dataframe.md
  docs/docusaurus/docs/guides/setup/components_index/_data_contexts.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/how_to_configure_credentials.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/how_to_convert_an_ephemeral_data_context_to_a_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/how_to_instantiate_a_data_context_without_a_yml_file.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/initializing_data_contexts/how_to_initialize_a_filesystem_data_context_in_python.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_explicitly_instantiate_an_ephemeral_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_instantiate_a_specific_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_quickly_instantiate_a_data_context.md
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.md
  docs/docusaurus/docs/reference/customize_your_deployment.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
  docs/prepare_prior_versions.py
Labels: core

#7724 [MAINTENANCE] Use same version of mypy in contrib tool
  contrib/cli/requirements.txt
Labels: dx, core

#7717 [DOCS] Update for fluent datasources: Dynamically load evaluation params from a database
  ci/azure-pipelines-dev.yml
  docs/docusaurus/docs/guides/expectations/advanced/how_to_dynamically_load_evaluation_parameters_from_a_database.md
  tests/integration/docusaurus/expectations/advanced/how_to_dynamically_load_evaluation_parameters_from_a_database.py
  tests/integration/fixtures/query_store/great_expectations/expectations/.ge_store_backend_id
  tests/integration/fixtures/query_store/great_expectations/great_expectations.yml
  tests/integration/fixtures/query_store/great_expectations/uncommitted/config_variables.yml
  tests/integration/test_definitions/postgresql/integration_tests.py
Labels: dx, core

#7725 [MAINTENANCE] Update a Fluent Datasource related fixture name to better reflect its capabilities
  tests/checkpoint/conftest.py
  tests/checkpoint/test_checkpoint_with_fluent_datasources.py
  tests/conftest.py
Labels: dx, core

#7705 [FEATURE] FDS persist `DataAsset` to YAML file immediately on creation
  docs/sphinx_api_docs_source/public_api_report.py
  great_expectations/datasource/fluent/config.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/sources.py
  tests/datasource/fluent/test_contexts.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/datasource/fluent/test_pandas_dbfs_datasource.py
  tests/datasource/fluent/test_pandas_filesystem_datasource.py
Labels: core

#7684 [BUGFIX] Add missing pyspark reference
  great_expectations/dataset/sparkdf_dataset.py
Labels: community

#7726 [DOCS] Update batch glossary docs.
  docs/docusaurus/docs/terms/_batches_and_batch_requests.mdx
  docs/docusaurus/docs/terms/batch.md
  docs/docusaurus/docs/terms/batch_request.md
Labels: core

#7729 [DOCS] Update for fluent datasources: Create a new Checkpoint
  docs/docusaurus/docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_a_edit_the_configuration.mdx
  docs/docusaurus/docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_b_test_your_config_using_contexttest_yaml_config.mdx
  docs/docusaurus/docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_c_store_your_checkpoint_config.mdx
  docs/docusaurus/docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_d_optional_check_your_stored_checkpoint_config.mdx
  docs/docusaurus/docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_e_optional_test_run_the_new_checkpoint_and_open_data_docs.mdx
  docs/docusaurus/docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_use_the_cli_to_open_a_jupyter_notebook_for_creating_a_new_checkpoint.mdx
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_create_a_new_checkpoint.md
  docs/sphinx_api_docs_source/public_api_report.py
  tests/integration/docusaurus/validation/checkpoints/how_to_create_a_new_checkpoint.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7723 [MAINTENANCE] fix get available data assets names for fds
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/data_context/test_data_context_datasources.py
Labels: maintenance, core

#7736 [DOCS] Temporarily revert `update_expectation_suite` call in GX Cloud quickstart
  docs/docusaurus/docs/gx_cloud/tutorials/getting_started/getting_started_with_gx_cloud.md
Labels: core

#7738 [MAINTENANCE] Update expectation logic and add docstring to build_gallery
  assets/scripts/build_gallery.py
  great_expectations/expectations/expectation.py
Labels: dx, core

#7703 [DOCS] Light update to How to add validations data or suites to a Checkpoint
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_add_validations_data_or_suites_to_a_checkpoint.md
Labels: core

#7730 [DOCS] Better output from `invoke public-api` report
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs.yml
  docs/sphinx_api_docs_source/include_exclude_definition.py
  docs/sphinx_api_docs_source/public_api_excludes.py
  docs/sphinx_api_docs_source/public_api_includes.py
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  docs/sphinx_api_docs_source/public_api_report.py
  tasks.py
  tests/scripts/test_public_api_report.py
Labels: dx, core

#7739 [DOCS] Removed unneeded calls to update datasource in docs.
  tests/integration/docusaurus/expectations/how_to_create_and_edit_expectations_with_a_profiler.py
  tests/integration/docusaurus/reference/glossary/batch_request.py
Labels: core

#7572 [MAINTENANCE] Add split/join logic to build_gallery process
  assets/scripts/build_gallery.py
  assets/scripts/download_json_from_s3.sh
  docs/expectation_gallery/azure-pipelines-expectation-gallery.yml
  great_expectations/expectations/expectation.py
Labels: core-team, dx

#7718 [DOCS] FDS Deployment Pattern - AWS S3 Pandas
  ci/azure-pipelines-dev.yml
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_create.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_create_tabs.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_run.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_save.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_save_tab_python.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_save_tab_yaml.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_expectation_suite_add_expectations_with_validator.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_expectation_suite_save.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_cloud_storage_and_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/s3/components_pandas/_add_csv_asset_to_pandas_s3_datasource.mdx
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/s3/components_pandas/_configure_your_datasource.mdx
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/s3/components_pandas/_test_your_new_datasource.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/components_how_to_configure_a_new_data_context_with_the_cli/_initialize_data_context_with_get_context.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/components_how_to_configure_a_new_data_context_with_the_cli/_initialize_data_context_with_the_cli.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_docs/components_how_to_host_and_share_data_docs_on_amazon_s3/_add_a_new_s3_site_to_the_data_docs_sites_section_of_your_great_expectationsyml.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_docs/components_how_to_host_and_share_data_docs_on_amazon_s3/_test_that_your_configuration_is_correct_by_building_the_site.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_identify_your_data_context_validation_results_store.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_update_your_configuration_file_to_include_a_new_store_for_validation_results_on_s.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_identify_your_data_context_expectations_store.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_update_your_configuration_file_to_include_a_new_store_for_expectations_on_s.mdx
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  tests/integration/docusaurus/deployment_patterns/aws_cloud_storage_pandas.py
  tests/integration/test_definitions/s3/integration_tests.py
Labels: dx, core

#7746 [MAINTENANCE] Use invoke public-api in main CI pipeline
  ci/azure-pipelines.yml
Labels: dx, core

#7682 [FEATURE] Cloud support FDS deletes
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/datasource/fluent/sources.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_contexts.py
Labels: core

#7749 [MAINTENANCE] Add remaining `public_api` decorators for core fluent datasources
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/pandas_s3_datasource.py
  great_expectations/datasource/fluent/spark_datasource.py
Labels: core

#7751 [MAINTENANCE] FDS update schemas - fixes CI
  great_expectations/datasource/fluent/schemas/PandasAzureBlobStorageDatasource.json
  great_expectations/datasource/fluent/schemas/PandasGoogleCloudStorageDatasource.json
  great_expectations/datasource/fluent/schemas/PandasS3Datasource.json
  great_expectations/datasource/fluent/schemas/SparkDatasource.json
Labels: core

#7752 [DOCS] Update pypyi page urls
  setup.py
Labels: core

#7748 [FEATURE] Persist Cloud DataAssets on creation
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context/serializable_data_context.py
  great_expectations/datasource/fluent/interfaces.py
  tests/datasource/fluent/test_contexts.py
  tests/datasource/fluent/test_metadatasource.py
Labels: core

#7755 [MAINTENANCE] FDS Deployment Guide - Pandas S3 fix reference
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_cloud_storage_and_pandas.md
Labels: dx, core

#7740 [FEATURE] Add tests for `Checkpoint` utilizing Pandas and Spark style Fluent Datasources.
  great_expectations/__init__.py
  great_expectations/checkpoint/util.py
  tests/checkpoint/conftest.py
  tests/checkpoint/test_checkpoint.py
  tests/checkpoint/test_checkpoint_with_fluent_datasources.py
  tests/conftest.py
Labels: dx, core

#7756 [RELEASE] 0.16.9
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#7669 [DOCS] Remove, relocate, consolidate, and edit Contributing content
  CONTRIBUTING.md
  CONTRIBUTING_CODE.md
  CONTRIBUTING_EXPECTATIONS.md
  CONTRIBUTING_PACKAGES.md
  README.md
  ci/checks/check_repo_root_size.sh
  docs/README.md
  docs/docusaurus/docs/contributing/contributing_checklist.md
  docs/docusaurus/docs/contributing/contributing_github.md
  docs/docusaurus/docs/contributing/contributing_maturity.md
  docs/docusaurus/docs/contributing/contributing_overview.md
  docs/docusaurus/docs/contributing/contributing_package.md
  docs/docusaurus/docs/contributing/contributing_setup.md
  docs/docusaurus/docs/contributing/contributing_test.md
  docs/docusaurus/docs/contributing/index.md
  docs/docusaurus/docs/contributing/style_guides/docs_style.md
  docs/docusaurus/docs/deployment_patterns/integrations_and_howtos_overview.md
  docs/docusaurus/docs/guides/expectations/contributing/how_to_contribute_a_custom_expectation_to_great_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_batch_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_pair_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_multicolumn_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_query_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/overview.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_example_cases_for_an_expectation.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_input_validation_for_an_expectation.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_spark_support_for_an_expectation.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_sqlalchemy_support_for_an_expectation.md
  docs/docusaurus/docs/guides/miscellaneous/how_to_write_a_how_to_guide.md
  docs/docusaurus/docs/integrations/contributing_integration.md
  docs/docusaurus/docs/integrations/index.md
  docs/docusaurus/docs/reference/reference_overview.md
  docs/docusaurus/docs/templates/how_to_template.md
  docs/docusaurus/docs/templates/integration_template.md
  docs/docusaurus/docs/terms/custom_expectation.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
Labels: devrel

#7763 [MAINTENANCE] IPython Python 3.8 upper bound
  requirements.txt
Labels: core

#7764 [DOCS] Temporarily pin ipython for python 3.8 before building api docs
  docs/build_docs
Labels: dx, core

#7761 [MAINTENANCE] breakup mypy ci steps
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines.yml
Labels: core

#7706 [FEATURE] Fluent `BatchRequest` slicing
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/batch.py
  great_expectations/core/util.py
  great_expectations/datasource/data_connector/batch_filter.py
  great_expectations/datasource/fluent/data_asset/data_connector/file_path_data_connector.py
  great_expectations/datasource/fluent/file_path_data_asset.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/pandas_datasource.pyi
  great_expectations/datasource/fluent/spark_datasource.py
  great_expectations/datasource/fluent/sql_datasource.py
  great_expectations/types/__init__.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/datasource/fluent/data_asset/data_connector/test_azure_blob_storage_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_filesystem_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_google_cloud_storage_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_s3_data_connector.py
  tests/datasource/fluent/integration/test_integration_datasource.py
  tests/datasource/fluent/test_config.py
  tests/datasource/fluent/test_pandas_filesystem_datasource.py
  tests/datasource/fluent/test_postgres_datasource.py
Labels: core

#7760 [DOCS] Update Links in Configure Topics
  docs/README.md
  docs/docusaurus/docs/contributing/contributing_overview.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_batch_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_pair_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_multicolumn_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_query_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/overview.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_example_cases_for_an_expectation.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_input_validation_for_an_expectation.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_spark_support_for_an_expectation.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_sqlalchemy_support_for_an_expectation.md
  docs/docusaurus/docs/terms/custom_expectation.md
  docs/docusaurus/static/_redirects
Labels: devrel

#7768 [DOCS] Link Updates
  CONTRIBUTING_CODE.md
  CONTRIBUTING_EXPECTATIONS.md
  CONTRIBUTING_PACKAGES.md
  README.md
Labels: devrel

#7771 [BUGFIX] Patch Expectation registry issue introduced in 0.16.9
  great_expectations/__init__.py
  great_expectations/validator/validator.py
Labels: core

#7772 [MAINTENANCE] fix async type-check step
  ci/azure-pipelines.yml
Labels: core

#7773 [MAINTENANCE] Bump Python version in `static_type_check` stage of async CI
  ci/azure-pipelines.yml
Labels: core

#7774 [RELEASE] 0.16.10
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#7753 [MAINTENANCE] Add check to `CloudDataContext` to ensure using latest PyPI version
  great_expectations/data_context/_version_checker.py
  great_expectations/data_context/data_context/cloud_data_context.py
  tests/data_context/cloud_data_context/test_version_checker.py
Labels: core

#7741 [DOCS] FDS Deployment Pattern - Google Cloud: BigQuery and GCS
  ci/azure-pipelines-dev.yml
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  tests/integration/docusaurus/deployment_patterns/gcp_deployment_patterns_file_bigquery.py
  tests/integration/docusaurus/deployment_patterns/gcp_deployment_patterns_file_gcs.py
  tests/integration/test_definitions/bigquery/integration_tests.py
  tests/integration/test_definitions/gcs/integration_tests.py
Labels: dx, core

#7759 [FEATURE] Add tests for `Checkpoint` utilizing SQLAlchemy style Fluent Datasources.
  great_expectations/checkpoint/checkpoint.py
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/checkpoint/conftest.py
  tests/checkpoint/test_checkpoint_with_fluent_datasources.py
  tests/conftest.py
Labels: dx, core
