Repository great-expectations/great_expectations, pull requests merged in 2023-05, with the labels that each got.

#7783 [BUGFIX] Patch faulty version checker logic
  great_expectations/data_context/_version_checker.py
Labels: core

#7785 [MAINTENANCE] Cache the latest great_expectations version
  great_expectations/data_context/_version_checker.py
  tests/conftest.py
  tests/data_context/cloud_data_context/test_version_checker.py
Labels: core

#7784 [DOCS] Remove temporary pin for ipython
  docs/build_docs
  requirements.txt
Labels: dx, core

#7776 [MAINTENANCE] Enable `flake8-bugbear` rules
  contrib/time_series_expectations/tests/expectations/test_expectations.py
  great_expectations/core/expectation_diagnostics/expectation_test_data_cases.py
  great_expectations/core/expectation_suite.py
  great_expectations/data_asset/file_data_asset.py
  great_expectations/data_context/store/_store_backend.py
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/datasource/fluent/dynamic_pandas.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/execution_engine/split_and_sample/data_sampler.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
  great_expectations/jupyter_ux/__init__.py
  great_expectations/jupyter_ux/expectation_explorer.py
  great_expectations/profile/base.py
  great_expectations/render/renderer/slack_renderer.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/self_check/util.py
  great_expectations/util.py
  great_expectations/validation_operators/validation_operators.py
  pyproject.toml
  tests/datasource/fluent/integration/integration_test_utils.py
  tests/performance/taxi_benchmark_util.py
  tests/render/test_data_documentation_site_builder.py
  tests/ruff.toml
  tests/test_not_imported.py
  tests/test_utils.py
  tests/validator/test_validator.py
Labels: core

#7769 [MAINTENANCE] Cleanup of Fluent `BatchRequest` type and immutability constraints
  docs/sphinx_api_docs_source/public_api_excludes.py
  great_expectations/core/batch.py
  great_expectations/datasource/data_connector/batch_filter.py
  great_expectations/datasource/fluent/__init__.py
  great_expectations/datasource/fluent/batch_request.py
  great_expectations/datasource/fluent/batch_request.pyi
  great_expectations/datasource/fluent/data_asset/data_connector/data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/file_path_data_connector.py
  great_expectations/datasource/fluent/file_path_data_asset.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/schemas/BatchRequest.json
  great_expectations/datasource/fluent/spark_datasource.py
  great_expectations/datasource/fluent/sql_datasource.py
  tasks.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/checkpoint/test_checkpoint_with_fluent_datasources.py
  tests/datasource/fluent/data_asset/data_connector/test_azure_blob_storage_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_filesystem_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_google_cloud_storage_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_s3_data_connector.py
  tests/datasource/fluent/integration/conftest.py
  tests/datasource/fluent/integration/integration_test_utils.py
  tests/datasource/fluent/integration/test_integration_datasource.py
  tests/datasource/fluent/test_batch_request.py
  tests/datasource/fluent/test_config.py
  tests/datasource/fluent/test_metadatasource.py
  tests/datasource/fluent/test_postgres_datasource.py
  tests/datasource/fluent/test_schemas.py
Labels: core

#7765 [DOCS] Add CLI Admonition
  docs/docusaurus/docs/components/warnings/_cli_removal.md
  docs/docusaurus/docs/deployment_patterns/how_to_instantiate_a_data_context_hosted_environments.md
  docs/docusaurus/docs/deployment_patterns/how_to_instantiate_a_data_context_on_an_emr_spark_cluster.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_airflow.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_meltano.md
  docs/docusaurus/docs/glossary.md
  docs/docusaurus/docs/guides/expectations/create_expectations_overview.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_use_custom_expectations.md
  docs/docusaurus/docs/guides/expectations/how_to_create_and_edit_expectations_based_on_domain_knowledge_without_inspecting_data_directly.md
  docs/docusaurus/docs/guides/miscellaneous/how_to_use_the_great_expectations_cli.md
  docs/docusaurus/docs/guides/miscellaneous/how_to_use_the_project_check_config_command.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/components_how_to_configure_a_new_data_context_with_the_cli/_preface.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/how_to_configure_credentials.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_a_filesystem.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_amazon_s3.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_azure_blob_storage.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_metricsstore.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_amazon_s3.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_azure_blob_storage.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_gcs.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_on_a_filesystem.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_to_postgresql.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_amazon_s3.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_azure_blob_storage.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_gcs.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_on_a_filesystem.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_to_postgresql.md
  docs/docusaurus/docs/guides/setup/installation/local.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/cloud/how_to_set_up_gx_to_work_with_data_in_abs.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/cloud/how_to_set_up_gx_to_work_with_data_on_aws_s3.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/cloud/how_to_set_up_gx_to_work_with_data_on_gcs.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/sql_databases/how_to_setup_gx_to_work_with_sql_databases.md
  docs/docusaurus/docs/guides/setup/setup_overview.md
  docs/docusaurus/docs/guides/validation/advanced/how_to_deploy_a_scheduled_checkpoint_with_cron.md
  docs/docusaurus/docs/guides/validation/how_to_validate_data_by_running_a_checkpoint.md
  docs/docusaurus/docs/guides/validation/validate_data_overview.md
  docs/docusaurus/docs/guides/validation/validation_actions/how_to_collect_openlineage_metadata_using_a_validation_action.md
  docs/docusaurus/docs/guides/validation/validation_actions/how_to_update_data_docs_as_a_validation_action.md
  docs/docusaurus/docs/integrations/integration_datahub.md
  docs/docusaurus/docs/reference/expectations/conditional_expectations.md
  docs/docusaurus/docs/templates/how_to_template.md
  docs/docusaurus/docs/terms/checkpoint.md
  docs/docusaurus/docs/terms/cli.md
  docs/docusaurus/docs/terms/data_assistant.md
  docs/docusaurus/docs/terms/data_docs.md
  docs/docusaurus/docs/terms/expectation_suite.md
  docs/docusaurus/docs/terms/store.md
Labels: devrel

#7754 [FEATURE] Spark parquet reader support for fluent datasources
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource/ParquetAsset.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource/ParquetAsset.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource/ParquetAsset.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource/ParquetAsset.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource/ParquetAsset.json
  great_expectations/datasource/fluent/spark_dbfs_datasource.py
  great_expectations/datasource/fluent/spark_file_path_datasource.py
  great_expectations/datasource/fluent/spark_filesystem_datasource.py
  great_expectations/datasource/fluent/spark_filesystem_datasource.pyi
  tests/datasource/fluent/test_spark_filesystem_datasource.py
Labels: dx, core

#7788 [DOCS] Link Update
  docs/docusaurus/docs/components/setup/link_lists/_setup_configurations.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_azure_blob_storage_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_azure_blob_storage_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_gcs_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_gcs_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_s3_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_s3_using_spark.md
Labels: devrel

#7778 [FEATURE] Add tests for `SimpleCheckpoint` utilizing Fluent Datasources with Pandas, Spark, and SQLAlchemy test cases.
  great_expectations/datasource/fluent/__init__.py
  great_expectations/datasource/fluent/interfaces.py
  tests/checkpoint/conftest.py
  tests/checkpoint/test_checkpoint.py
  tests/checkpoint/test_checkpoint_with_fluent_datasources.py
  tests/checkpoint/test_simple_checkpoint.py
  tests/checkpoint/test_simple_checkpoint_with_fluent_datasources.py
  tests/conftest.py
Labels: dx, core

#7793 [MAINTENANCE] Update pip instal extras and use AWS_ env vars
  ci/azure-pipelines-dev.yml
Labels: dx, core

#7747 [DOCS] Remove Redundant Introduction Headings
  CONTRIBUTING_EXPECTATIONS.md
  CONTRIBUTING_PACKAGES.md
  README.md
  docs/docusaurus/docs/components/_templates/_template_basic_install_and_setup.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/batch_requests/how_to_request_data_from_a_data_asset.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_azure_blob_storage_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_azure_blob_storage_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_gcs_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_gcs_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_s3_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_s3_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_file_based_data_asset.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_sql_based_data_asset.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_a_sql_table.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_postgresql_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data_using_a_query.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sqlite_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_connect_to_one_or_more_files_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_connect_to_one_or_more_files_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_quickly_connect_to_a_single_file_with_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/in_memory/how_to_connect_to_in_memory_data_using_pandas.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/how_to_convert_an_ephemeral_data_context_to_a_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/initializing_data_contexts/how_to_initialize_a_filesystem_data_context_in_python.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_explicitly_instantiate_an_ephemeral_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_instantiate_a_specific_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_quickly_instantiate_a_data_context.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/cloud/how_to_set_up_gx_to_work_with_data_in_abs.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/cloud/how_to_set_up_gx_to_work_with_data_on_aws_s3.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/cloud/how_to_set_up_gx_to_work_with_data_on_gcs.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/sql_databases/how_to_setup_gx_to_work_with_sql_databases.md
  docs/docusaurus/docs/gx_cloud/tutorials/getting_started/getting_started_with_gx_cloud.md
  docs/docusaurus/docs/integrations/integration_datahub.md
  docs/docusaurus/docs/integrations/integration_zenml.md
  docs/docusaurus/docs/templates/integration_template.md
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
  docs/docusaurus/docs_pending/guides/setup/optional_dependencies/how_to_setup_gx_to_work_with_postgresql.md
  docs/docusaurus/docs_pending/how_to_set_up_gx_to_work_with_athena.md
Labels: devrel

#7795 [BUGFIX] Correct import errors in Azure Blob Storage tests and make Azure Glob Storage and Google Cloud Storage tests more elegant.
  tests/core/test_config_substitutor.py
  tests/datasource/data_connector/test_configured_asset_azure_data_connector.py
  tests/datasource/data_connector/test_configured_asset_gcs_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_azure_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_gcs_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_azure_blob_storage_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_google_cloud_storage_data_connector.py
  tests/datasource/fluent/test_pandas_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_pandas_google_cloud_storage_datasource.py
  tests/datasource/fluent/test_spark_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_spark_google_cloud_storage_datasource.py
  tests/execution_engine/test_pandas_execution_engine.py
Labels: dx, core

#7777 [FEATURE] Spark read directory of files as a single batch for CSV
  great_expectations/datasource/fluent/data_asset/data_connector/dbfs_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/file_path_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/filesystem_data_connector.py
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource/DirectoryCSVAsset.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource/DirectoryCSVAsset.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource/DirectoryCSVAsset.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource/DirectoryCSVAsset.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource/DirectoryCSVAsset.json
  great_expectations/datasource/fluent/spark_dbfs_datasource.py
  great_expectations/datasource/fluent/spark_file_path_datasource.py
  great_expectations/datasource/fluent/spark_filesystem_datasource.py
  great_expectations/datasource/fluent/spark_filesystem_datasource.pyi
  tests/datasource/fluent/test_spark_filesystem_datasource.py
Labels: dx, core

#7803 [BUGFIX] Add `pytest` decorator to fixture
  tests/datasource/data_connector/test_configured_asset_azure_data_connector.py
Labels: core

#7767 [MAINTENANCE] Lint `test/data_context`
  pyproject.toml
  tests/data_context/abstract_data_context/test_abstract_data_context_datasource_crud.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_version_checker.py
  tests/data_context/conftest.py
  tests/data_context/datasource/test_data_context_datasource_non_sql_methods_pandas_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_non_sql_methods_sparkdf_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_pandas_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_sparkdf_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_sqlalchemy_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_sql_methods.py
  tests/data_context/migrator/conftest.py
  tests/data_context/migrator/test_cloud_migrator.py
  tests/data_context/store/test_gx_cloud_store_backend.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/store/test_validations_store.py
  tests/data_context/test_configuration_storage.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_config_errors.py
  tests/data_context/test_data_context_config_ui.py
  tests/data_context/test_data_context_config_variables.py
  tests/data_context/test_data_context_data_docs_api.py
  tests/data_context/test_data_context_ge_cloud_mode.py
  tests/data_context/test_data_context_state_management.py
  tests/data_context/test_data_context_store_configs.py
  tests/data_context/test_data_context_test_yaml_config.py
  tests/data_context/test_data_context_test_yaml_config_usage_stats.py
  tests/data_context/test_data_context_v013.py
  tests/data_context/test_pandas_datetime_suites.py
Labels: core

#7789 [MAINTENANCE] FDS Documentation Update - S3 Pandas reference fixes
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_add_csv_asset_to_pandas_s3_datasource.mdx
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_add_expectation_suite_and_validator_for_fluent_datasource.mdx
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_configure_your_datasource.mdx
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_expectation_suite_add_expectations_with_validator.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_initialize_data_context_with_create.mdx
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_test_your_new_datasource.mdx
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_cloud_storage_and_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/s3/components_pandas/_configure_your_datasource.mdx
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/s3/components_pandas/_test_your_new_datasource.mdx
Labels: dx, core

#7806 [MAINTENANCE] Update all pytest calls in CI to show reason skipped
  ci/azure-pipelines-cloud-integration.yml
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs-integration.yml
  ci/azure-pipelines-os-integration.yml
  ci/azure-pipelines-sqlalchemy-compatibility.yml
  ci/azure-pipelines.yml
  ci/dev-install-matrix.yml
Labels: dx, core

#7775 [DOCS] FDS Deployment Pattern - AWS: Spark and S3
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_batch_request.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_cloud_storage_and_pandas.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_s3_and_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/s3/components_spark/_add_csv_asset_to_spark_s3_datasource.md
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/s3/components_spark/_configure_your_datasource.md
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/s3/components_spark/_test_your_new_datasource.md
  tests/integration/docusaurus/deployment_patterns/aws_cloud_storage_spark.py
  tests/integration/test_definitions/s3/integration_tests.py
Labels: core

#7807 [MAINTENANCE] Dont run runme_script_runner_tests stage on forks
  ci/azure-pipelines-dev.yml
Labels: dx, core

#7798 [BUGFIX] Repair handling of regular expressions partitioning for cloud file storage environments utilizing prefix directive.
  great_expectations/datasource/data_connector/configured_asset_s3_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_s3_data_connector.py
  great_expectations/datasource/data_connector/util.py
  great_expectations/datasource/fluent/data_asset/data_connector/azure_blob_storage_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/google_cloud_storage_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/s3_data_connector.py
  tests/datasource/data_connector/test_configured_asset_azure_data_connector.py
  tests/datasource/data_connector/test_configured_asset_s3_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_azure_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_azure_blob_storage_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_google_cloud_storage_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_s3_data_connector.py
  tests/datasource/fluent/test_pandas_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_spark_azure_blob_storage_datasource.py
  tests/integration/docusaurus/deployment_patterns/gcp_deployment_patterns_file_gcs.py
Labels: dx, core

#7804 [MAINTENANCE] Lint `tests/checkpoint` & `tests/execution_engine`
  pyproject.toml
  tests/checkpoint/conftest.py
  tests/checkpoint/test_checkpoint.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/checkpoint/test_checkpoint_with_fluent_datasources.py
  tests/checkpoint/test_simple_checkpoint.py
  tests/checkpoint/test_simple_checkpoint_with_fluent_datasources.py
  tests/conftest.py
  tests/core/usage_statistics/test_usage_statistics.py
  tests/execution_engine/conftest.py
  tests/execution_engine/split_and_sample/test_pandas_execution_engine_splitting.py
  tests/execution_engine/split_and_sample/test_sparkdf_execution_engine_sampling.py
  tests/execution_engine/split_and_sample/test_sparkdf_execution_engine_splitting.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
  tests/execution_engine/test_execution_engine.py
  tests/execution_engine/test_pandas_execution_engine.py
  tests/execution_engine/test_sparkdf_execution_engine.py
  tests/execution_engine/test_sqlalchemy_batch_data.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
Labels: core

#7735 [MAINTENANCE] docs-integration re-start
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs-integration.yml
  pyproject.toml
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_one_or_more_files_using_pandas.py
  tests/integration/test_definitions/abs/integration_tests.py
  tests/integration/test_definitions/gcs/integration_tests.py
  tests/integration/test_definitions/multiple_backend/integration_tests.py
  tests/integration/test_definitions/postgresql/integration_tests.py
  tests/integration/test_definitions/spark/integration_tests.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7812 [MAINTENANCE] Remove runme fixtures/stages and enable docs-integration to run automatically
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs-integration.yml
  tests/integration/test_definitions/bigquery/integration_tests.py
  tests/integration/test_definitions/gcs/integration_tests.py
  tests/integration/test_definitions/multiple_backend/integration_tests.py
  tests/integration/test_definitions/postgresql/integration_tests.py
  tests/integration/test_definitions/s3/integration_tests.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7810 [FEATURE] Enable passing "spark_config" through to "SparkDFExecutionEngine" constructor as arguments to "add_spark*()" Fluent Datasources methods.
  great_expectations/core/util.py
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDatasource.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource.json
  great_expectations/datasource/fluent/sources.pyi
  great_expectations/datasource/fluent/spark_datasource.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/self_check/util.py
  tests/conftest.py
  tests/datasource/fluent/test_spark_datasource.py
  tests/datasource/test_new_datasource.py
  tests/integration/spark/test_spark_config.py
Labels: dx, core

#7817 [BUGFIX] AWS Docs reference clash
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_cloud_storage_and_pandas.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_s3_and_spark.md
Labels: dx, core

#7813 [BUGFIX] Cloud - Fix FDS Asset has no attribute `_data_connector`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core

#7820 [MAINTENANCE] Fix linting error.
  great_expectations/self_check/util.py
Labels: core

#7823 [MAINTENANCE] Fix pin count.
  tests/test_packaging.py
Labels: core

#7824 [RELEASE] 0.16.11
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#7818 [BUGFIX] Azure Package Presence/Absence Tests Strengthening
  great_expectations/datasource/fluent/sources.pyi
  tests/core/test_config_substitutor.py
  tests/datasource/data_connector/test_configured_asset_azure_data_connector.py
  tests/datasource/data_connector/test_inferred_asset_azure_data_connector.py
  tests/datasource/fluent/data_asset/data_connector/test_azure_blob_storage_data_connector.py
  tests/datasource/fluent/test_pandas_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_spark_azure_blob_storage_datasource.py
  tests/execution_engine/test_pandas_execution_engine.py
Labels: dx, core

#7826 [MAINTENANCE] FDS - Datasources can rebuild their own asset data_connectors
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/datasource/fluent/interfaces.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core

#7819 [MAINTENANCE] Enable Spark-S3 Integration tests on Azure CI/CD
  ci/azure-pipelines-docs-integration.yml
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_spark_s3_dependencies.md
  tests/integration/backend_dependencies.py
  tests/integration/docusaurus/deployment_patterns/aws_cloud_storage_spark.py
  tests/integration/test_definitions/aws_glue/integration_tests.py
  tests/integration/test_definitions/s3/integration_tests.py
Labels: dx, core

#7825 [MAINTENANCE] Clean up: Remove duplicated fixture and utilize deeper filtering mechanism for configuration assertions.
  tests/checkpoint/test_checkpoint.py
Labels: dx, core

#7831 [DOCS] Update docs for how_to_initialize_a_filesystem_data_context_in_python
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/initializing_data_contexts/how_to_initialize_a_filesystem_data_context_in_python.md
Labels: core

#7830 [BUGFIX] Handle "persist" directive in "SparkDFExecutionEngine" properly.
  great_expectations/execution_engine/sparkdf_execution_engine.py
Labels: dx, core

#7828 [MAINTENANCE] Enable S3/Spark Connecting To Your Data tests
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/inferred_and_runtime_yaml_example.py
  tests/integration/test_definitions/s3/integration_tests.py
Labels: dx, core

#7809 [FEATURE] Plumbing of validation_result_url from cloud response
  great_expectations/checkpoint/actions.py
  great_expectations/checkpoint/checkpoint.py
  great_expectations/data_context/store/gx_cloud_store_backend.py
  great_expectations/data_context/types/refs.py
  great_expectations/validation_operators/validation_operators.py
  tests/checkpoint/cloud_config.py
  tests/checkpoint/test_checkpoint.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
Labels: core

#7808 [BUGFIX] Adding support for Fluent Batch Requests to context.get_validator
  great_expectations/core/batch.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/datasource/data_connector/runtime_data_connector.py
  great_expectations/datasource/fluent/batch_request.py
  tests/core/test_batch.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_pandas_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_sparkdf_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_sqlalchemy_execution_engine.py
  tests/data_context/test_data_context_test_yaml_config.py
  tests/data_context/test_data_context_test_yaml_config_usage_stats.py
  tests/data_context/test_data_context_v013.py
  tests/data_context/test_get_data_context.py
  tests/datasource/test_new_datasource.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_pandas_execution_engine.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_sparkdf_execution_engine.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_sql_execution_engine.py
  tests/execution_engine/test_pandas_execution_engine.py
Labels: core

#7722 [DOCS] Updating Checkpoint terms page
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_create_a_new_checkpoint.md
  docs/docusaurus/docs/guides/validation/how_to_validate_data_by_running_a_checkpoint.md
  docs/docusaurus/docs/terms/checkpoint.md
  tests/integration/docusaurus/reference/core_concepts/checkpoints_and_actions.py
  tests/integration/docusaurus/validation/checkpoints/how_to_validate_data_by_running_a_checkpoint.py
  tests/integration/fixtures/yellow_trip_data_fluent_pandas/great_expectations/great_expectations.yml
  tests/integration/test_script_runner.py
Labels: core

#7835 [DOCS] Update how to create a checkpoint with Test YAML config
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config.md
  tests/integration/docusaurus/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config.py
  tests/integration/fixtures/yellow_trip_data_fluent_pandas/great_expectations.yml
  tests/integration/test_script_runner.py
Labels: core

#7710 [MAINTENANCE] New PR template
  .github/pull_request_template.md
Labels: dx, core

#7836 [DOCS] Removing datasource centric test_yaml_config doc
  docs/docusaurus/docs/components/setup/link_lists/_setup_configurations.md
  docs/docusaurus/docs/guides/connecting_to_your_data/datasource_configuration/components/_section_test_your_configuration_with_test_yaml_config.mdx
  docs/docusaurus/docs/guides/connecting_to_your_data/how_to_choose_which_dataconnector_to_use.md
  docs/docusaurus/docs/guides/connecting_to_your_data/how_to_configure_a_configuredassetdataconnector.md
  docs/docusaurus/docs/guides/connecting_to_your_data/how_to_configure_a_runtimedataconnector.md
  docs/docusaurus/docs/guides/connecting_to_your_data/how_to_configure_an_inferredassetdataconnector.md
  docs/docusaurus/docs/guides/setup/components_index/_data_contexts.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/how_to_configure_datacontext_components_using_test_yaml_config.md
  docs/docusaurus/docs/terms/data_context.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
Labels: core

#7829 [MAINTENANCE] ruff `.0.262 -> .0.265`
  .pre-commit-config.yaml
  contrib/cli/requirements.txt
  great_expectations/datasource/fluent/sources.pyi
  great_expectations/execution_engine/pandas_execution_engine.py
  reqs/requirements-dev-contrib.txt
  tests/data_context/test_data_context_test_yaml_config.py
  tests/data_context/test_data_context_test_yaml_config_usage_stats.py
  tests/test_packaging.py
Labels: core

#7701 [DOCS] Creating a Checkpoint from an In-Memory Dataframe
  docs/docusaurus/docs/guides/validation/advanced/how_to_validate_data_with_an_in_memory_checkpoint.md
  docs/docusaurus/docs/guides/validation/advanced/how_to_validate_data_without_a_checkpoint.md
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.md
  docs/docusaurus/docs/reference/customize_your_deployment.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/spark_datasource.py
  tests/cli/test_suite.py
  tests/integration/docusaurus/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.py
  tests/integration/docusaurus/validation/checkpoints/how_to_validate_data_with_a_python_configured_in_memory_checkpoint.py
  tests/integration/docusaurus/validation/checkpoints/how_to_validate_data_with_a_yaml_configured_in_memory_checkpoint.py
  tests/integration/test_script_runner.py
Labels: core

#7796 [MAINTENANCE] Boto import pattern established
  great_expectations/compatibility/aws.py
  great_expectations/execution_engine/pandas_execution_engine.py
  tests/datasource/fluent/test_pandas_s3_datasource.py
  tests/execution_engine/conftest.py
  tests/execution_engine/test_pandas_execution_engine.py
Labels: dx, core

#7843 [BUGFIX] FDS - Deletes not immediately reflected in `great_expectations.yml`
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/datasource/fluent/config.py
  great_expectations/datasource/fluent/sources.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core

#7846 [MAINTENANCE] Prevent TCH001 warnings for pydantic model annotations
  great_expectations/datasource/fluent/config.py
  great_expectations/datasource/fluent/dynamic_pandas.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/sources.pyi
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.pyi
  great_expectations/datasource/fluent/spark_google_cloud_storage_datasource.pyi
  great_expectations/datasource/fluent/spark_s3_datasource.pyi
  pyproject.toml
Labels: core

#7845 [BUGFIX] `batching_regex` tags are now correctly rendered in docs
  docs/docusaurus/scripts/remark-named-snippets/snippet.js
Labels: dx, core

#7838 [MAINTENANCE] Clean up version checker message formatting
  great_expectations/data_context/_version_checker.py
Labels: core

#7797 [MAINTENANCE] Return empty set instead of None
  great_expectations/datasource/fluent/directory_data_asset.py
  great_expectations/datasource/fluent/dynamic_pandas.py
  great_expectations/datasource/fluent/file_path_data_asset.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/spark_datasource.py
  great_expectations/datasource/fluent/spark_file_path_datasource.py
Labels: dx, core

#7858 [MAINTENANCE] Improve misconfigured sampler error message
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_sampler.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_sampling.py
Labels: core

#7857 [BUGFIX] Fix link checker and add to mypy type checking
  docs/checks/docs_link_checker.py
  pyproject.toml
Labels: dx, core

#7782 [BUGFIX] expect_day_count_to_be_close_to_equivalent_week_day_mean
  contrib/experimental/great_expectations_experimental/expectations/expect_day_count_to_be_close_to_equivalent_week_day_mean.py
  contrib/experimental/great_expectations_experimental/expectations/expect_yesterday_count_compared_to_avg_equivalent_days_of_week.py
  great_expectations/expectations/registry.py
Labels: community

#7860 [MAINTENANCE] Fixing path formatting for DataConnector of Fluent SparkAzureBlobStorageDatasource and correction of the `SQLAlchemy` compatibility usage in `TableHead` metric
  great_expectations/compatibility/sqlalchemy.py
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.py
  great_expectations/expectations/metrics/table_metrics/table_head.py
Labels: dx, core

#7727 [DOCS] Review and Revise Great Expectations Quickstart
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
Labels: devrel

#7863 [BUGFIX] Docs-Tests: `Connection.connect()` was causing Snowflake and BigQuery Tests to Fail
  tests/test_utils.py
Labels: dx, core

#7864 [MAINTENANCE] S3 Spark Integration Guide - Rendering Fix
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_spark_s3_dependencies.md
Labels: dx, core

#7866 [RELEASE] 0.16.12
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#7870 [DOCS] removes remaining Block-config Datasource guides
  docs/docusaurus/docs/components/_prerequisites.jsx
  docs/docusaurus/docs/components/connect_to_data/link_lists/_connect_to_filesystem_data_fluently.md
  docs/docusaurus/docs/components/connect_to_data/link_lists/_connect_to_in_memory_data_fluently.md
  docs/docusaurus/docs/components/connect_to_data/link_lists/_connecting_to_sql_datasources_block_config.md
  docs/docusaurus/docs/components/connect_to_data/link_lists/_connecting_to_sql_datasources_fluently.md
  docs/docusaurus/docs/components/connect_to_data/link_lists/_work_with_fluent_data_assets.md
  docs/docusaurus/docs/guides/connecting_to_your_data/datasource_configuration/how_to_configure_a_pandas_datasource.md
  docs/docusaurus/docs/guides/connecting_to_your_data/datasource_configuration/how_to_configure_a_spark_datasource.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_file_based_data_asset.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_sql_based_data_asset.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_a_sql_table.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data_using_a_query.md
  docs/docusaurus/docs/guides/connecting_to_your_data/in_memory/pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/in_memory/spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/index.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/initializing_data_contexts/how_to_initialize_a_filesystem_data_context_in_python.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_instantiate_a_specific_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_quickly_instantiate_a_data_context.md
  docs/docusaurus/docs/terms/data_assistant.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
Labels: devrel

#7852 [MAINTENANCE] FDS Documentation - Creating ExpectationSuite with Domain Knowledge
  docs/docusaurus/docs/guides/expectations/how_to_create_and_edit_expectations_based_on_domain_knowledge_without_inspecting_data_directly.md
  tests/integration/docusaurus/expectations/how_to_create_and_edit_an_expectationsuite_domain_knowledge.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7873 [FEATURE] Spark directory asset types
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource/DirectoryJSONAsset.json
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource/DirectoryORCAsset.json
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource/DirectoryParquetAsset.json
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource/DirectoryTextAsset.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource/DirectoryJSONAsset.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource/DirectoryORCAsset.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource/DirectoryParquetAsset.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource/DirectoryTextAsset.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource/DirectoryJSONAsset.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource/DirectoryORCAsset.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource/DirectoryParquetAsset.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource/DirectoryTextAsset.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource/DirectoryJSONAsset.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource/DirectoryORCAsset.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource/DirectoryParquetAsset.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource/DirectoryTextAsset.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource/DirectoryJSONAsset.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource/DirectoryORCAsset.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource/DirectoryParquetAsset.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource/DirectoryTextAsset.json
  great_expectations/datasource/fluent/spark_file_path_datasource.py
  great_expectations/datasource/fluent/spark_filesystem_datasource.pyi
  tests/datasource/fluent/test_spark_filesystem_datasource.py
Labels: dx, core

#7872 [FEATURE] Add Spark DeltaAsset type
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource/DeltaAsset.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource/DeltaAsset.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource/DeltaAsset.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource/DeltaAsset.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource/DeltaAsset.json
  great_expectations/datasource/fluent/spark_file_path_datasource.py
  great_expectations/datasource/fluent/spark_filesystem_datasource.pyi
  tests/datasource/fluent/test_spark_filesystem_datasource.py
Labels: dx, core

#7878 [MAINTENANCE] Refactor directory data asset
  great_expectations/datasource/fluent/directory_data_asset.py
  great_expectations/datasource/fluent/file_path_data_asset.py
  great_expectations/datasource/fluent/spark_file_path_datasource.py
  great_expectations/datasource/fluent/spark_filesystem_datasource.py
Labels: dx, core

#7879 [BUGFIX] Fix inability to extend SimpleCheckpoint -- and several additional enhancements and clean up
  great_expectations/checkpoint/checkpoint.py
  great_expectations/core/batch.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/datasource/fluent/sources.pyi
  tests/checkpoint/test_checkpoint.py
  tests/conftest.py
  tests/data_context/fixtures/plugins/extended_checkpoint.py
Labels: dx, core

#7874 [DOCS] More doc updates to remove the CLI
  docs/docusaurus/docs/guides/expectations/create_expectations_overview.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_use_custom_expectations.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_update_store_reference.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_confirm_list.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_azure_blob_storage.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_gcs.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_on_a_filesystem.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_to_postgresql.md
Labels: core

#7884 [DOCS] Add Links to Tutorial Templates in the README
  docs/docusaurus/docs/team_templates/README.md
Labels: devrel

#7871 [DOCS] removes block-config docs for source data systems in the cloud
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/azure/pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/azure/spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/gcs/pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/gcs/spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/s3/pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/cloud/s3/spark.md
  docs/docusaurus/docs/reference/customize_your_deployment.md
Labels: devrel

#7876 [DOCS] Continuing CLI Update
  docs/docusaurus/docs/guides/setup/setup_overview.md
  docs/docusaurus/docs/terms/expectation_suite.md
  docs/docusaurus/docs/terms/store.md
  tests/integration/docusaurus/setup/setup_overview.py
  tests/integration/test_script_runner.py
Labels: core

#7886 [DOCS] Removes the SQL block config guides.
  docs/docusaurus/docs/components/_prerequisites.jsx
  docs/docusaurus/docs/deployment_patterns/how_to_instantiate_a_data_context_hosted_environments.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_airflow.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_athena.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_redshift.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/athena.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/bigquery.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/mssql.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/mysql.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/postgres.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/redshift.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/snowflake.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/sqlite.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/trino.md
  docs/docusaurus/docs/guides/connecting_to_your_data/datasource_configuration/how_to_configure_a_sql_datasource.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_sql_based_data_asset.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_a_sql_table.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data_using_a_query.md
  docs/docusaurus/docs/guides/miscellaneous/migration_guide.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/initializing_data_contexts/how_to_initialize_a_filesystem_data_context_in_python.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_instantiate_a_specific_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_quickly_instantiate_a_data_context.md
  docs/docusaurus/docs/reference/customize_your_deployment.md
  docs/docusaurus/docs/terms/data_assistant.md
  docs/docusaurus/versions.json
Labels: devrel

#7893 [DOCS] Remove jq dependency for building docs
  docs/build_docs
Labels: dx, core

#7894 [DOCS] Less verbose logging during docs build
  docs/docusaurus/package.json
  docs/docusaurus/scripts/remark-named-snippets/snippet.js
  docs/prepare_prior_versions.py
Labels: dx, core

#7881 [BUGFIX] Delete ExpectationSuite by name in GX Cloud
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/gx_cloud_store_backend.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/store/test_gx_cloud_store_backend.py
Labels: bug, cloud, core

#7896 [DOCS] Corrections to Document "How to request data from a Data Asset" with proper FDS implementation and integration test.
  docs/docusaurus/README.md
  docs/docusaurus/docs/components/setup/datasource/data_asset/_get_existing_data_asset_from_existing_datasource.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/batch_requests/how_to_request_data_from_a_data_asset.md
  tests/integration/docusaurus/__init__.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/get_existing_data_asset_from_existing_datasource_pandas_filesystem_example.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7877 [FEATURE] Add DirectoryDeltaAsset
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkAzureBlobStorageDatasource/DirectoryDeltaAsset.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDBFSDatasource/DirectoryDeltaAsset.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource.json
  great_expectations/datasource/fluent/schemas/SparkFilesystemDatasource/DirectoryDeltaAsset.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource.json
  great_expectations/datasource/fluent/schemas/SparkGoogleCloudStorageDatasource/DirectoryDeltaAsset.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource.json
  great_expectations/datasource/fluent/schemas/SparkS3Datasource/DirectoryDeltaAsset.json
  great_expectations/datasource/fluent/spark_file_path_datasource.py
  great_expectations/datasource/fluent/spark_filesystem_datasource.pyi
  tests/datasource/fluent/test_spark_filesystem_datasource.py
Labels: dx, core

#6914 [MAINTENANCE] partial `checkpoint` type checking
  great_expectations/checkpoint/checkpoint.py
  great_expectations/checkpoint/configurator.py
  great_expectations/checkpoint/util.py
  great_expectations/core/batch.py
  great_expectations/core/config_peer.py
  great_expectations/data_context/data_context/abstract_data_context.py
  pyproject.toml
Labels: dx

#7899 [MAINTENANCE] type-checking `checkpoint/actions.py`
  great_expectations/checkpoint/actions.py
  pyproject.toml
Labels: dx, core

#7862 [BUGFIX] optional dataframe on datasources
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/schemas/PandasDatasource/DataFrameAsset.json
  great_expectations/datasource/fluent/schemas/SparkDatasource.json
  great_expectations/datasource/fluent/schemas/SparkDatasource/DataFrameAsset.json
  great_expectations/datasource/fluent/spark_datasource.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/integration/test_integration_datasource.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/datasource/fluent/test_spark_datasource.py
Labels: core

#7902 [MAINTENANCE] Trigger docs_integration on develop
  ci/azure-pipelines-docs-integration.yml
Labels: dx, core

#7901 [MAINTENANCE] Finish type-checking `checkpoint`
  great_expectations/checkpoint/actions.py
  great_expectations/checkpoint/types/checkpoint_result.py
  great_expectations/cli/checkpoint.py
  pyproject.toml
Labels: dx, core

#7907 [FEATURE] Implementing Python code snippets under test for "https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_file_based_data_asset"
  docs/docusaurus/docs/components/connect_to_data/filesystem/_tip_filesystem_data_asset_if_batching_regex_matches_multiple_files.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_file_based_data_asset.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/get_existing_data_asset_from_existing_datasource_pandas_filesystem_example.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/organize_batches_in_pandas_filesystem_datasource.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7910 [MAINTENANCE] Update How to set up GX to work with data in Azure Blob Storage
  docs/docusaurus/docs/guides/setup/optional_dependencies/cloud/how_to_set_up_gx_to_work_with_data_in_abs.md
Labels: dx, core

#7908 [BUGFIX] Fix Cloud FDS `add_or_update_*` methods
  great_expectations/core/http.py
  great_expectations/data_context/store/gx_cloud_store_backend.py
  great_expectations/datasource/fluent/sources.py
  tests/datasource/fluent/test_contexts.py
Labels: core

#7868 [DOCS] FDS Deployment Pattern Redshift
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_add_table_and_query_assets.mdx
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_configure_your_redshift_datasource.mdx
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/components/_test_your_new_redshift_datasource.mdx
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_redshift.md
  docs/docusaurus/docs/guides/connecting_to_your_data/database/components/_redshift_credentials.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_identify_your_data_context_expectations_store.mdx
  tests/integration/docusaurus/deployment_patterns/aws_redshift_deployment_patterns.py
  tests/integration/test_definitions/redshift/integration_tests.py
Labels: dx, core

#7914 [BUGFIX] fix `PandasAzureBlobStorageDatasource` config substitution
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/datasource/fluent/config_str.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.pyi
  great_expectations/datasource/fluent/schemas/PandasAzureBlobStorageDatasource.json
  great_expectations/datasource/fluent/sources.py
  tests/datasource/fluent/test_pandas_azure_blob_storage_datasource.py
Labels: core

#7892 [DOCS] Document and simplify local docs build
  docs/build_docs
  docs/build_docs_locally.sh
  docs/docusaurus/README.md
  docs/docusaurus/versions.json
  docs/logging.sh
  docs/prepare_prior_versions.py
  docs/prepare_to_build_docs.sh
  docs/sphinx_api_docs_source/README.md
  tasks.py
Labels: dx, core

#7909 [FEATURE] Implementing Python code snippets under test for "https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_sql_based_data_asset"
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_sql_based_data_asset.md
  docs/prepare_prior_versions.py
  great_expectations/datasource/fluent/file_path_data_asset.py
  great_expectations/datasource/fluent/sql_datasource.py
  great_expectations/datasource/fluent/sqlite_datasource.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/organize_batches_in_sqlite_datasource.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7918 [MAINTENANCE] Removing engine-specific tests that assert generic behavior
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_pandas_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_sparkdf_execution_engine.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_sqlalchemy_execution_engine.py
Labels: core

#7924 [MAINTENANCE] Add `docs/*.py` to `GXChanged` for linting
  ci/azure-pipelines-dev.yml
Labels: dx, core

#7859 [DOCS] How to Edit Existing `ExpectationSuite`
  docs/docusaurus/docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.md
  docs/docusaurus/docs/guides/expectations/how_to_edit_an_existing_expectationsuite.md
  docs/docusaurus/sidebars.js
  great_expectations/core/expectation_suite.py
  great_expectations/validator/validator.py
  tests/integration/docusaurus/expectations/how_to_edit_an_expectation_suite.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7922 [FEATURE] Implementing Python code snippets under test for "https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_connect_to_one_or_more_files_using_pandas"
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_connect_to_one_or_more_files_using_pandas.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_one_or_more_files_using_pandas.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/organize_batches_in_pandas_filesystem_datasource.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7917 [BUGFIX] Fix remaining FDS config substitution issues
  great_expectations/datasource/fluent/config.py
  great_expectations/datasource/fluent/config_str.py
  great_expectations/datasource/fluent/fluent_base_model.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/pandas_s3_datasource.py
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/spark_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/spark_s3_datasource.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/great_expectations.yml
  tests/datasource/fluent/test_config.py
  tests/datasource/fluent/test_config_str.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core

#7842 [FEATURE]: DataProfilerStructuredDataAssistant Float Rule
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/rule_based_profiler/data_assistant/data_profiler_structured_data_assistant.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/rule_based_profiler/data_assistant/test_data_profiler_structured_data_assistant.py
Labels: community

#7904 [DOCS] CLI Clean-up
  docs/docusaurus/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_a_filesystem.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_amazon_s3.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_azure_blob_storage.md
  docs/docusaurus/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.md
  docs/docusaurus/docs/guides/setup/installation/local.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/cloud/how_to_set_up_gx_to_work_with_data_on_aws_s3.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/cloud/how_to_set_up_gx_to_work_with_data_on_gcs.md
  docs/docusaurus/docs/guides/validation/advanced/how_to_deploy_a_scheduled_checkpoint_with_cron.md
  docs/docusaurus/docs/guides/validation/validation_actions/how_to_collect_openlineage_metadata_using_a_validation_action.md
  docs/docusaurus/docs/guides/validation/validation_actions/how_to_update_data_docs_as_a_validation_action.md
  docs/docusaurus/docs/integrations/integration_datahub.md
  tests/integration/common_workflows/simple_build_data_docs.py
  tests/integration/docusaurus/reference/glossary/checkpoints.py
  tests/integration/docusaurus/reference/glossary/data_docs.py
  tests/integration/docusaurus/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.py
  tests/integration/fixtures/yellow_trip_data_fluent_pandas/great_expectations.yml
  tests/integration/fixtures/yellow_trip_data_fluent_pandas/great_expectations/great_expectations.yml
  tests/integration/test_script_runner.py
Labels: core

#7925 [MAINTENANCE] Fixes Glue tests on vanilla pytest
  tests/datasource/conftest.py
Labels: core

#7920 [FEATURE] DataProfilerColumnDomainBuilder
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_table_column_list.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/rule_based_profiler/data_assistant/data_profiler_structured_data_assistant.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/rule_based_profiler/domain_builder/data_profiler_column_domain_builder.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/conftest.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/rule_based_profiler/data_assistant/test_data_profiler_structured_data_assistant.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/tests/rule_based_profiler/domain_builder/test_data_profiler_column_domain_builder.py
Labels: community

#7926 [FEATURE] Add "batch.columns()" convenience method to Fluent DataAsset implementation.
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/validator/metrics_calculator.py
Labels: dx, core

#7933 [RELEASE] 0.16.13
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#7934 [MAINTENANCE] Update `teams.yml`
  .github/teams.yml
Labels: core

#7936 [BUGFIX] Correcting instructions for Contributor Package installation
  CONTRIBUTING_PACKAGES.md
Labels: dx, core

#7938 [FEATURE] Implementing Python code snippets under test for "https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_quickly_connect_to_a_single_file_with_pandas"
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/filesystem/how_to_quickly_connect_to_a_single_file_with_pandas.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_quickly_connect_to_a_single_file_with_pandas.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7937 [MAINTENANCE] Remove the -rs flag from the ci pytest invocations.
  ci/azure-pipelines-cloud-integration.yml
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs-integration.yml
  ci/azure-pipelines-os-integration.yml
  ci/azure-pipelines-sqlalchemy-compatibility.yml
  ci/azure-pipelines.yml
  ci/dev-install-matrix.yml
Labels: core

#7895 [MAINTENANCE] Update `GXCloudIdentifier` to return nullable attrs instead of empty strings
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/gx_cloud_store_backend.py
  great_expectations/data_context/types/resource_identifiers.py
  tests/data_context/store/test_ge_cloud_store_backend.py
  tests/data_context/store/test_gx_cloud_store_backend.py
Labels: core

#7929 [MAINTENANCE] Better error message when calling "Fluent" methods from wrong Datasource type
  great_expectations/datasource/fluent/sources.py
  great_expectations/datasource/fluent/sources.pyi
  great_expectations/datasource/new_datasource.py
  tests/datasource/test_new_datasource.py
Labels: dx, core

#7935 [BUGFIX] Technical tags in Versioned Docs reference correct version
  docs/prepare_prior_versions.py
  tests/docs/__init__.py
  tests/docs/test_prepare_prior_versions.py
  tests/scripts/test_public_api_report.py
Labels: dx, core

#7916 [MAINTENANCE] bump python minimum version to 3.8
  CONTRIBUTING_CODE.md
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-sqlalchemy-compatibility.yml
  ci/azure-pipelines.yml
  ci/dev-install-matrix.yml
  ci/user-install-matrix.yml
  docker/README.md
  docs/docusaurus/docs/guides/setup/setup_overview.md
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
  great_expectations/cli/batch_request.py
  great_expectations/compatibility/google.py
  great_expectations/compatibility/sqlalchemy_bigquery.py
  great_expectations/core/async_executor.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/metrics/util.py
  great_expectations/self_check/util.py
  setup.cfg
  setup.py
  tests/datasource/test_new_datasource_with_sql_data_connector.py
  tests/performance/test_bigquery_benchmarks.py
  tests/test_definitions/test_expectations_v3_api.py
Labels: dx, core

#7943 [FEATURE] Implementing Python code snippets under test for "https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_s3_using_spark"
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_s3_using_spark.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_data_on_s3_using_spark.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_quickly_connect_to_a_single_file_with_pandas.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7942 [BUGFIX] Return qualified name when calling `TableAsset.as_selectable()`
  great_expectations/datasource/fluent/sql_datasource.py
Labels: community

#7952 [BUGFIX] Cloud - fix `add_or_update_*()` when using `name` as keyword arg
  great_expectations/data_context/store/gx_cloud_store_backend.py
  great_expectations/datasource/fluent/sources.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_contexts.py
Labels: core

#7947 [FEATURE] Implementing Python code snippets under test for "https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sqlite_data"
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sqlite_data.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_sqlite_data.py
  tests/integration/test_script_runner.py
Labels: core

#7953 [MAINTENANCE] ignore black formatting and ruff auto-fix revisions
  .git-blame-ignore-revs
Labels: core

#7958 [MAINTENANCE] Fix docs deploy
  docs/prepare_to_build_docs.sh
Labels: dx, core

#7964 [FEATURE] Implementing Python code snippets under test for "https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_gcs_using_spark"
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_gcs_using_spark.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_data_on_gcs_using_spark.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7950 [BUGFIX] Change GXSqlDialect.AWSATHENA to awsathena
  great_expectations/execution_engine/sqlalchemy_dialect.py
Labels: community

#7970 [BUGFIX] Setting maximum on `typing-extension` package version
  requirements.txt
  tests/test_packaging.py
Labels: dx, core

#7940 [FEATURE] add ssm parameter support for config secrets
  great_expectations/core/config_substitutor.py
  tests/core/test_config_substitutor.py
Labels: community

#7961 [DOCS] Fix issues with technical tags links in earlier versions
  docs/prepare_prior_versions.py
  tests/docs/test_prepare_prior_versions.py
Labels: dx, core

#7977 [DOCS] Temporarily pin typing-extensions for API docs
  docs/prepare_to_build_docs.sh
Labels: dx, core

#7967 [FEATURE] Implementing Python code snippets under test for "https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_azure_blob_storage_using_spark"
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_azure_blob_storage_using_spark.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_data_on_azure_blob_storage_using_spark.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7955 [DOCS] Add optional Slack step to Cloud Quickstart
  docs/docusaurus/docs/gx_cloud/tutorials/getting_started/getting_started_with_gx_cloud.md
Labels: core-team, core

#7978 [MAINTENANCE] Refactor documentation integration tests into their proper categories according to their respective backend.
  tests/integration/test_definitions/abs/integration_tests.py
  tests/integration/test_definitions/gcs/integration_tests.py
  tests/integration/test_definitions/multiple_backend/integration_tests.py
  tests/integration/test_definitions/s3/integration_tests.py
  tests/integration/test_definitions/spark/integration_tests.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7981 [DOCS] Versioning: Convert technical tag imports starting with /docs/ to relative paths
  docs/prepare_prior_versions.py
  tests/docs/test_prepare_prior_versions.py
Labels: dx, core

#7984 [FEATURE] Implementing Python code snippets under test for "https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_instantiate_a_specific_filesystem_data_context"
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_instantiate_a_specific_filesystem_data_context.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_instantiate_a_specific_filesystem_data_context.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7339 [BUGFIX] Resolve Issue 7335
  great_expectations/data_context/store/tuple_store_backend.py
Labels: community

#7985 [FEATURE] Implementing Python code snippets under test for "https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/initializing_data_contexts/how_to_initialize_a_filesystem_data_context_in_python"
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/initializing_data_contexts/how_to_initialize_a_filesystem_data_context_in_python.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_initialize_a_filesystem_data_context_in_python.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7956 [FEATURE] Put how_to_connect_to_sql_data fluent docs under test
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_sql_data.py
  tests/integration/test_script_runner.py
Labels: core

#7980 [MAINTENANCE] Update Cloud Tests for release this week + Revert pin on `typing-extension`
  docs/prepare_to_build_docs.sh
  requirements.txt
  tests/checkpoint/cloud_config.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
  tests/datasource/fluent/conftest.py
  tests/test_packaging.py
  tests/validator/test_validator.py
Labels: core

#7989 [BUGFIX] Cloud - Fix `context.sources.update_*()` `POST` instead of `PUT` calls
  great_expectations/datasource/fluent/sources.py
  tests/datasource/fluent/test_contexts.py
Labels: core

#7986 [FEATURE] Implementing Python code snippets under test for "https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/initializing_data_contexts/how_to_initialize_a_filesystem_data_context_in_python" and "https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_convert_an_ephemeral_data_context_to_a_filesystem_data_context".
  docs/docusaurus/docs/components/setup/data_context/_admonition_convert_to_file_context.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/how_to_convert_an_ephemeral_data_context_to_a_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_explicitly_instantiate_an_ephemeral_data_context.md
  docs/docusaurus/docs/terms/metric.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_explicitly_instantiate_an_ephemeral_data_context.py
  tests/integration/test_script_runner.py
Labels: dx, core

#7930 [DOCS] Removes Data Connector references
  docs/docusaurus/docs/glossary.md
  docs/docusaurus/docs/guides/connecting_to_your_data/how_to_choose_between_working_with_a_single_or_multiple_batches_of_data.md
  docs/docusaurus/docs/integrations/integration_zenml.md
  docs/docusaurus/docs/terms/data_asset.md
  docs/docusaurus/docs/terms/data_connector.md
  docs/docusaurus/docs/terms/datasource.md
  docs/docusaurus/docs/terms/plugin.md
  docs/docusaurus/sidebars.js
Labels: devrel

#7919 [MAINTENANCE] Use `Session` for all `api.greatexpectations.io` calls
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/exceptions/exceptions.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_contexts.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core

#7987 [FEATURE] put fluent doc "How to connect to sql data using a query" under test
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data_using_a_query.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_sql_data_using_a_query.py
  tests/integration/test_script_runner.py
Labels: core

#7973 [DOCS] add in-memory add expectation suite
  tests/integration/docusaurus/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.py
Labels: community

#7996 [FEATURE] Checker for correct Python code snippets in documentation.
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs.yml
  ci/azure-pipelines.yml
  ci/checks/check_no_line_number_snippets.py
  ci/checks/check_only_name_tag_snippets.py
Labels: dx, core

#7995 [BUGFIX] `meta_notes` rendered inline can fail schema validation for a valid configuration
  great_expectations/render/renderer_configuration.py
  tests/render/test_inline_renderer.py
Labels: core

#7998 [MAINTENANCE] Revert "[FEATURE] Checker for correct Python code snippets in documentation."
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs.yml
  ci/azure-pipelines.yml
  ci/checks/check_no_line_number_snippets.py
  ci/checks/check_only_name_tag_snippets.py
Labels: dx, core

#7975 [DOCS] Removes CLI documentation from current docs version
  docs/docusaurus/docs/components/_prerequisites.jsx
  docs/docusaurus/docs/components/setup/link_lists/_data_context_initialize_instatiate_save.md
  docs/docusaurus/docs/components/setup/link_lists/_data_context_initialize_quick_or_filesystem.mdx
  docs/docusaurus/docs/components/setup/next_steps/_links_after_installing_gx.md
  docs/docusaurus/docs/contributing/style_guides/cli_and_notebooks_style.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_athena.md
  docs/docusaurus/docs/guides/miscellaneous/how_to_use_the_great_expectations_cli.md
  docs/docusaurus/docs/guides/miscellaneous/how_to_use_the_project_check_config_command.md
  docs/docusaurus/docs/guides/setup/components_index/_data_contexts.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/components_how_to_configure_a_new_data_context_with_the_cli/_data_context_next_steps.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/components_how_to_configure_a_new_data_context_with_the_cli/_initialize_data_context_with_the_cli.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/components_how_to_configure_a_new_data_context_with_the_cli/_preface.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/components_how_to_configure_a_new_data_context_with_the_cli/_verify_data_context_initialization.mdx
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/how_to_configure_a_new_data_context_with_the_cli.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/initializing_data_contexts/how_to_initialize_a_filesystem_data_context_in_python.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_instantiate_a_specific_filesystem_data_context.md
  docs/docusaurus/docs/guides/setup/optional_dependencies/sql_databases/how_to_setup_gx_to_work_with_sql_databases.md
  docs/docusaurus/docs/reference/reference_overview.md
  docs/docusaurus/docs/reference/supplemental_documentation.md
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
  docs/prepare_prior_versions.py
  tests/docs/test_prepare_prior_versions.py
Labels: devrel

#8002 [FEATURE] NotImplementedErrors for all FDS methods when accessed from BDS
  great_expectations/datasource/new_datasource.py
  tests/datasource/test_new_datasource.py
Labels: core

#8005 [MAINTENANCE] Fix async Cloud tests
  tests/data_context/test_data_context_ge_cloud_mode.py
Labels: core

#8008 [BUGFIX] `xfail` two cloud tests that are blocking release 0.16.14
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
Labels: dx, core

#8011 [MAINTENANCE] Update `teams.yml`
  .github/teams.yml
Labels: core

#8010 [RELEASE] 0.16.14
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: dx, core

#8000 [FEATURE] Checker for correct Python code snippets in documentation.
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs.yml
  ci/azure-pipelines.yml
  ci/checks/check_no_line_number_snippets.py
  ci/checks/check_only_name_tag_snippets.py
Labels: dx, core

#7837 [FEATURE] Add scaffolding for gx-agent
  docs/sphinx_api_docs_source/public_api_excludes.py
  great_expectations/agent/__init__.py
  great_expectations/agent/agent.py
  great_expectations/agent/event_handler.py
  great_expectations/agent/message_service/__init__.py
  great_expectations/agent/message_service/asyncio_rabbit_mq_client.py
  great_expectations/agent/message_service/subscriber.py
  great_expectations/agent/models.py
  great_expectations/agent/run.py
  great_expectations/core/usage_statistics/package_dependencies.py
  reqs/requirements-dev-cloud.txt
  reqs/requirements-dev-test.txt
  requirements-types.txt
  setup.py
  tests/agent/__init__.py
  tests/agent/message_service/__init__.py
  tests/agent/message_service/amqp_errors.py
  tests/agent/message_service/test_rabbit_mq_client.py
  tests/agent/message_service/test_subscriber.py
  tests/agent/test_agent.py
  tests/agent/test_event_handler.py
  tests/agent/test_run.py
  tests/test_packaging.py
Labels: core

#7992 [MAINTENANCE] Add sensible default values to Checkpoint APIs
  great_expectations/checkpoint/checkpoint.py
  great_expectations/checkpoint/configurator.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/types/base.py
  tests/checkpoint/conftest.py
  tests/checkpoint/test_checkpoint.py
  tests/checkpoint/test_checkpoint_with_fluent_datasources.py
  tests/checkpoint/test_simple_checkpoint.py
  tests/cli/test_checkpoint.py
  tests/core/test_serialization.py
  tests/data_context/fixtures/plugins/extended_checkpoint.py
  tests/data_context/migrator/conftest.py
  tests/data_context/store/test_checkpoint_store.py
  tests/data_context/store/test_gx_cloud_store_backend.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_state_management.py
  tests/test_fixtures/upgrade_helper/UpgradeHelperV13_upgrade_with_manual_steps_checkpoints_datasources_validation_operators_log.json
  tests/test_fixtures/upgrade_helper/UpgradeHelperV13_upgrade_with_manual_steps_checkpoints_log.json
  tests/test_fixtures/upgrade_helper/test_v2_to_v3_project_upgrade_with_manual_steps_checkpoints.fixture
  tests/test_fixtures/upgrade_helper/test_v2_to_v3_project_upgrade_with_manual_steps_checkpoints_datasources_validation_operators_expected_stdout.fixture
Labels: core

#8014 [MAINTENANCE] Removing xfails that we're added to get release out.
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/store/test_datasource_store_cloud_backend.py
Labels: core

#8016 [MAINTENANCE] Remove reference to Superconductive from CITATION.cff
  CITATION.cff
Labels: devrel

#7983 [MAINTENANCE] Deleting References to UserConfigurableProfiler Documentation
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/docusaurus/docs/guides/expectations/advanced/how_to_create_a_new_expectation_suite_using_rule_based_profilers.md
  docs/docusaurus/docs/guides/expectations/components_how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data/_optional_profile_your_data_to_generate_expectations_then_edit_them_in_interactive_mode.mdx
  docs/docusaurus/docs/guides/expectations/create_expectations_overview.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_add_support_for_the_auto_initializing_framework_to_a_custom_expectation.md
  docs/docusaurus/docs/guides/expectations/how_to_create_and_edit_expectations_with_a_profiler.md
  docs/docusaurus/docs/guides/expectations/index.md
  docs/docusaurus/docs/terms/batch.md
  docs/docusaurus/docs/terms/batch_request.md
  docs/docusaurus/docs/terms/data_assistant.md
  docs/docusaurus/docs/terms/data_context.md
  docs/docusaurus/docs/terms/expectation_suite.md
  docs/docusaurus/docs/terms/metric.md
  docs/docusaurus/docs/terms/profiler.md
  docs/docusaurus/docs/terms/validator.md
  docs/docusaurus/sidebars.js
  great_expectations/checkpoint/checkpoint.py
  great_expectations/data_context/types/base.py
  great_expectations/expectations/registry.py
  tests/checkpoint/test_simple_checkpoint.py
  tests/checkpoint/test_simple_checkpoint_with_fluent_datasources.py
  tests/cli/test_checkpoint.py
  tests/data_context/test_data_context.py
  tests/datasource/fluent/integration/test_integration_datasource.py
Labels: dx, core

#8012 [MAINTENANCE] mypy 1.3 + azure deps in type-checking step
  contrib/cli/requirements.txt
  great_expectations/compatibility/azure.py
  great_expectations/core/config_substitutor.py
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.py
  great_expectations/execution_engine/pandas_execution_engine.py
  pyproject.toml
  reqs/requirements-dev-contrib.txt
  requirements-types.txt
  tests/datasource/fluent/data_asset/data_connector/test_azure_blob_storage_data_connector.py
  tests/datasource/fluent/test_pandas_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_spark_azure_blob_storage_datasource.py
  tests/test_packaging.py
Labels: dx, core

#7991 [DOCS] Add Windows Support Admonition
  docs/docusaurus/docs/guides/setup/installation/hosted_environment.md
  docs/docusaurus/docs/guides/setup/installation/local.md
  docs/docusaurus/docs/guides/setup/setup_overview.md
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
Labels: devrel

#8020 [FEATURE] Cloud - generate unique asset names for `pandas_default` assets
  great_expectations/datasource/fluent/constants.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/sources.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_contexts.py
Labels: core
