Repository great-expectations/great_expectations, pull requests merged in 2023-09, with the labels that each got.

#8648 [MAINTENANCE] Column Descriptive Metrics: Synchronize domain models
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  great_expectations/experimental/metric_repository/metrics.py
  tests/experimental/metric_repository/demo.py
Labels: dx, core

#8650 [MAINTENANCE] Column Descriptive Metrics: Add test for MetricRepository
  great_expectations/agent/actions/run_column_descriptive_metrics_action.py
  great_expectations/experimental/metric_repository/metric_repository.py
  tests/experimental/metric_repository/test_metric_repository.py
Labels: dx, core

#8642 [DOCS] Update Request Data from a Data Asset
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/batch_requests/how_to_request_data_from_a_data_asset.md
  docs/docusaurus/docs/guides/expectations/how_to_edit_an_existing_expectationsuite.md
  great_expectations/expectations/metrics/table_metric_provider.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_a_sql_table.py
Labels: devrel

#8659 [BUGFIX] Missing CloudDataContext when loading from config
  great_expectations/core/datasource_dict.py
Labels: core

#8658 [BUGFIX] Raise warning if data_connector cannot be built on config load
  great_expectations/datasource/fluent/interfaces.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_contexts.py
Labels: core

#8656 [MAINTENANCE] Implement cloud data store
  great_expectations/agent/actions/run_column_descriptive_metrics_action.py
  great_expectations/experimental/metric_repository/batch_inspector.py
  great_expectations/experimental/metric_repository/cloud_data_store.py
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  great_expectations/experimental/metric_repository/data_store.py
  great_expectations/experimental/metric_repository/metrics.py
  tests/experimental/metric_repository/test_cloud_data_store.py
Labels: dx, core

#8660 [RELEASE] 0.17.14
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8654 [MAINTENANCE] Update team members
  .github/teams.yml
Labels: core

#8661 [MAINTENANCE] Update GitPython
  docs_rtd/requirements.txt
Labels: core

#8617 [CONTRIB] fixing null eq safe for SQLAlchemy and rendering
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_values_to_be_equal.py
Labels: community

#8665 [DOCS] Add redirects for module API docs
  docs/docusaurus/static/_redirects
Labels: dx, core

#8667 [MAINTENANCE] Column Descriptive Metrics: Return id from Data Store
  great_expectations/agent/actions/run_column_descriptive_metrics_action.py
  great_expectations/experimental/metric_repository/cloud_data_store.py
  great_expectations/experimental/metric_repository/data_store.py
  great_expectations/experimental/metric_repository/metric_repository.py
  tests/experimental/metric_repository/test_cloud_data_store.py
Labels: dx, core

#8668 [MAINTENANCE] Column Descriptive Metrics: ColumnDescriptiveMetricsAction tests
  tests/agent/actions/test_run_column_descriptive_metrics_action.py
Labels: dx, core

#8669 [MAINTENANCE] Column Descriptive Metrics: Add tests and cleanup
  great_expectations/agent/actions/run_column_descriptive_metrics_action.py
  great_expectations/experimental/metric_repository/batch_inspector.py
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  great_expectations/experimental/metric_repository/metric_retriever.py
  tests/experimental/metric_repository/demo.py
  tests/experimental/metric_repository/test_batch_inspector.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever_integration.py
  tests/experimental/metric_repository/test_metrics.py
Labels: dx, core

#8677 [MAINTENANCE] Column Descriptive Metrics: Fix cloud data store - use pydantic
  great_expectations/experimental/metric_repository/cloud_data_store.py
  tests/experimental/metric_repository/test_cloud_data_store.py
Labels: dx, core

#8678 [MAINTENANCE] Run doc-checks on every PR.
  .github/workflows/ci.yml
Labels: core

#8680 [MAINTENANCE] Column Descriptive Metrics: Additional metrics mean median
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever_integration.py
Labels: dx, core

#8681 [RELEASE] 0.17.15
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8685 [MAINTENANCE] only build-docs on doc-changes
  .github/workflows/ci.yml
Labels: core

#8683 [MAINTENANCE] Azure Blob Stores `TupleStoreBackend` now supports `credential` string
  examples/reference_environments/abs/abs_example_abs_stores.ipynb
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/self_check/util.py
  tests/data_context/store/test_store_backends.py
Labels: dx, core

#8689 Update workflow with merge_group
  .github/workflows/ci.yml
Labels: core

#8691 Merge queue pr 2
  tests/checkpoint/test_checkpoint_with_fluent_datasources.py
Labels: core

#8687 [MAINTENANCE] Column Descriptive Metrics: Add column types metric
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever_integration.py
Labels: dx, core

#8690 Merge queue pr 1
  tests/checkpoint/test_checkpoint_with_fluent_datasources.py
Labels: core

#8695 Merge queue PR 4
  tasks.py
Labels: core

#8692 [MAINTENANCE] Column Descriptive Metrics: Add Null Count
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever_integration.py
Labels: dx, core

#8673 [MAINTENANCE] Comprehensive SQL column identifier tests
  great_expectations/execution_engine/sqlalchemy_dialect.py
  pyproject.toml
  tasks.py
  tests/datasource/fluent/integration/test_sql_datasources.py
Labels: core

#8696 [DOCS] Relocate Use Great Expectations with Google Cloud Platform and BigQuery
  README.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/connect_sql_source_data.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
  tests/integration/fixtures/gcp_deployment/README.md
Labels: devrel

#8682 [BUGFIX] Missing DataFrame for in-memory Data Assets using GX Cloud
  docs/sphinx_api_docs_source/public_api_excludes.py
  great_expectations/core/datasource_dict.py
  great_expectations/datasource/fluent/interfaces.py
  tests/datasource/fluent/test_metadatasource.py
  tests/datasource/fluent/test_pandas_datasource.py
Labels: core

#8698 [BUGFIX] Fix FDS auto-complete for Conda installs
  MANIFEST.in
Labels: core

#8699 [BUGFIX] Assets with persisted data don't get added to in-memory cache
  great_expectations/core/datasource_dict.py
  great_expectations/datasource/fluent/constants.py
  tests/datasource/fluent/test_pandas_datasource.py
Labels: core

#8560 [FEATURE] update data assistant run to take in validator
  docs/docusaurus/docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_missingness_data_assistant.md
  examples/notebooks/missingness_data_assistant.ipynb
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/parameter_builder/metric_multi_batch_parameter_builder.py
  tests/integration/docusaurus/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_missingness_data_assistant.py
  tests/rule_based_profiler/data_assistant/test_data_assistant_runner.py
Labels: core

#8534 [BUGFIX] Use one inspector for the same engine/execution_engine
  great_expectations/cli/batch_request.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/table_metrics/table_column_types.py
  great_expectations/expectations/metrics/util.py
  great_expectations/util.py
  tests/expectations/metrics/test_table_column_types.py
Labels: core

#8507 [MAINTENANCE] Add test case for trino datatypes in onboarding assitant
  great_expectations/expectations/metrics/util.py
  great_expectations/rule_based_profiler/helpers/simple_semantic_type_filter.py
  tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
  tests/rule_based_profiler/test_simple_sematic_filter.py
Labels: core

#8702 [MAINTENANCE] Add `get_all` method to Store and StoreBackend APIs
  great_expectations/data_context/store/_store_backend.py
  great_expectations/data_context/store/database_store_backend.py
  great_expectations/data_context/store/gx_cloud_store_backend.py
  great_expectations/data_context/store/in_memory_store_backend.py
  great_expectations/data_context/store/inline_store_backend.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/store/tuple_store_backend.py
  tests/data_context/store/test_gx_cloud_store_backend.py
Labels: core

#8707 [BUGFIX] add try except to redshift regexp resolver
  great_expectations/expectations/metrics/util.py
Labels: community

#8601 [FEATURE] Add `DataAssetStore`
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/__init__.py
  great_expectations/data_context/store/data_asset_store.py
  great_expectations/data_context/types/base.py
  great_expectations/datasource/fluent/interfaces.py
  tests/datasource/fluent/_fake_cloud_api.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/great_expectations.yml
  tests/datasource/fluent/test_contexts.py
Labels: core

#8423 [MAINTENANCE] Change default context root to `gx/` over `great_expectations/`
  great_expectations/data_context/data_context/serializable_data_context.py
  great_expectations/exceptions/exceptions.py
  tests/cli/test_cli.py
  tests/cli/test_docs.py
  tests/cli/test_init.py
  tests/cli/test_project.py
  tests/cli/upgrade_helpers/test_upgrade_helper.py
  tests/conftest.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_data_docs_api.py
  tests/data_context/test_data_context_store_configs.py
  tests/data_context/test_get_data_context.py
  tests/validator/test_validator.py
Labels: core

#8720 [BUGFIX] Patch `docs_integration` tests failures resulting from context root dir rename
  tests/integration/docusaurus/deployment_patterns/aws_cloud_storage_pandas.py
  tests/integration/docusaurus/deployment_patterns/aws_cloud_storage_spark.py
  tests/integration/docusaurus/deployment_patterns/aws_redshift_deployment_patterns.py
  tests/integration/docusaurus/deployment_patterns/gcp_deployment_patterns_file_bigquery.py
  tests/integration/docusaurus/expectations/advanced/failed_rows_pandas.py
  tests/integration/docusaurus/expectations/advanced/failed_rows_spark.py
  tests/integration/docusaurus/expectations/advanced/failed_rows_sql.py
Labels: core

#8714 [MAINTENANCE] Parameterize severity in PagerdutyAction
  great_expectations/checkpoint/actions.py
Labels: community

#8712 [MAINTENANCE] Column Descriptive Metrics: Make the retriever more resilient to metric failures
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever_integration.py
Labels: dx, core

#8719 [BUGFIX] Snowflake column name case sensitivity
  great_expectations/expectations/metrics/util.py
  tests/datasource/fluent/integration/test_sql_datasources.py
  tests/expectations/metrics/test_metrics_util.py
Labels: core

#8700 [DOCS] Clarify How to Use Custom Expectations Without a Filesystem
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_use_custom_expectations.md
Labels: devrel

#8674 [DOCS] Update Result Format Topic
  docs/docusaurus/docs/reference/expectations/result_format.md
Labels: devrel

#8728 [BUGFIX] Resolve issue around listing keys with empty state in `GXCloudStoreBackend`
  great_expectations/data_context/store/gx_cloud_store_backend.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/store/test_gx_cloud_store_backend.py
Labels: core

#8732 [RELEASE] 0.17.17
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8713 [MAINTENANCE] Additional examples of `row_condition` for Spark and SQL
  docs/docusaurus/docs/reference/expectations/conditional_expectations.md
  great_expectations/expectations/metrics/map_metric_provider/column_map_condition_auxilliary_methods.py
  tests/expectations/metrics/column_map_metrics/test_column_map_condition_auxillary_methods.py
Labels: dx, core

#8726 [MAINTENANCE] ruff `.0.290`
  .pre-commit-config.yaml
  ci/checks/check_integration_test_gets_run.py
  ci/checks/check_name_tag_snippets_referenced.py
  ci/checks/check_no_line_number_snippets.py
  ci/checks/check_only_name_tag_snippets.py
  ci/checks/validate_docs_snippets.py
  contrib/cli/requirements.txt
  contrib/experimental/great_expectations_experimental/expectations/expect_foreign_keys_in_column_a_to_exist_in_column_b.py
  great_expectations/cli/example.py
  great_expectations/core/expectation_diagnostics/expectation_test_data_cases.py
  great_expectations/data_context/data_context/serializable_data_context.py
  great_expectations/dataset/sparkdf_dataset.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
  great_expectations/self_check/util.py
  reqs/requirements-dev-contrib.txt
  tests/data_context/test_data_context_v013.py
  tests/expectations/test_dataclass_serializable_dot_dict_pattern.py
  tests/render/test_render_BulletListContentBlock.py
  tests/test_packaging.py
  tests/validator/test_validator.py
Labels: core

#8741 [BUGFIX] Patch faulty `GXCloudStoreBackend.has_key` logic
  great_expectations/data_context/store/gx_cloud_store_backend.py
  tests/data_context/store/test_gx_cloud_store_backend.py
Labels: core

#8742 [RELEASE] 0.17.18
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8721 [DOCS] Update README.md to include newsletter and a typo fix.
  README.md
Labels: devrel

#8744 [MAINTENANCE] Improve test coverage around `GXCloudStoreBackend.gx_cloud_response_json_to_object_dict`
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/data_asset_store.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/gx_cloud_store_backend.py
  great_expectations/data_context/store/json_site_store.py
  great_expectations/data_context/store/profiler_store.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/store/validations_store.py
  tests/data_context/store/test_checkpoint_store.py
  tests/data_context/store/test_data_asset_store.py
  tests/data_context/store/test_datasource_store.py
  tests/data_context/store/test_expectations_store.py
  tests/data_context/store/test_gx_cloud_store_backend.py
  tests/data_context/store/test_json_site_store.py
  tests/data_context/store/test_profiler_store.py
  tests/data_context/store/test_store.py
  tests/data_context/store/test_validations_store.py
Labels: core

#8745 [BUGFIX] Ensure renderers use parent class renderers instead of using non-implemented override methods
  great_expectations/expectations/core/expect_column_bootstrapped_ks_test_p_value_to_be_greater_than.py
  great_expectations/expectations/core/expect_column_chisquare_test_p_value_to_be_greater_than.py
  great_expectations/expectations/core/expect_column_parameterized_distribution_ks_test_p_value_to_be_greater_than.py
  great_expectations/expectations/core/expect_multicolumn_sum_to_equal.py
Labels: dx, core

#8746 [BUGFIX] Column Descriptive Metrics: Support numpy metrics
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/experimental/metric_repository/cloud_data_store.py
  reqs/requirements-dev-cloud.txt
  tests/experimental/metric_repository/test_cloud_data_store.py
Labels: dx, core

#8605 [FEATURE] Microsoft FabricPowerBIDatasource
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  great_expectations/core/batch_spec.py
  great_expectations/datasource/fluent/__init__.py
  great_expectations/datasource/fluent/schemas/FabricPowerBIDatasource.json
  great_expectations/datasource/fluent/schemas/FabricPowerBIDatasource/PowerBIDax.json
  great_expectations/datasource/fluent/schemas/FabricPowerBIDatasource/PowerBIMeasure.json
  great_expectations/datasource/fluent/schemas/FabricPowerBIDatasource/PowerBITable.json
  great_expectations/datasource/fluent/sources.pyi
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/experimental/datasource/__init__.py
  great_expectations/experimental/datasource/fabric.py
  tests/datasource/fluent/great_expectations.yml
  tests/datasource/fluent/test_fabric.py
Labels: core

#8711 [MAINTENANCE] Improve `DatasourceDict` performance
  great_expectations/core/datasource_dict.py
  great_expectations/data_context/store/datasource_store.py
  great_expectations/data_context/store/in_memory_store_backend.py
  great_expectations/data_context/store/store.py
  tests/conftest.py
  tests/core/test_datasource_dict.py
  tests/data_context/store/test_datasource_store.py
Labels: core

#8753 [RELEASE] 0.17.19
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8754 [MAINTENANCE] Column Descriptive Metrics: Add metric exceptions
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  great_expectations/validator/metrics_calculator.py
  great_expectations/validator/validator.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever.py
Labels: dx, core

#8749 [DOCS] Updated link for Prefect integration
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_prefect.md
Labels: core

#8748 [DOCS] Fixed broken links in footer to match marketing page
  docs/docusaurus/docusaurus.config.js
Labels: core

#8704 [DOCS] Remove examples of YAML configuration for Checkpoints in docs
  tests/integration/docusaurus/reference/core_concepts/checkpoints_and_actions.py
  tests/integration/docusaurus/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_gcs.py
Labels: core

#8730 [CONTRIB] Set merge_queue in CI pipeline and turn off auto-update
  .github/workflows/autoupdate.yml
  .github/workflows/ci.yml
Labels: core

#8739 [FEATURE] DataDocs Renderer for `ExpectMulticolumnSumToEqual` and `LikePattern` Expectations
  great_expectations/expectations/core/expect_column_pair_values_a_to_be_greater_than_b.py
  great_expectations/expectations/core/expect_column_pair_values_to_be_equal.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_equal.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_dateutil_parseable.py
  great_expectations/expectations/core/expect_column_values_to_be_decreasing.py
  great_expectations/expectations/core/expect_column_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/expectations/core/expect_column_values_to_be_increasing.py
  great_expectations/expectations/core/expect_column_values_to_be_json_parseable.py
  great_expectations/expectations/core/expect_column_values_to_be_null.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/core/expect_column_values_to_be_unique.py
  great_expectations/expectations/core/expect_column_values_to_match_json_schema.py
  great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py
  great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py
  great_expectations/expectations/core/expect_column_values_to_match_regex.py
  great_expectations/expectations/core/expect_column_values_to_match_regex_list.py
  great_expectations/expectations/core/expect_column_values_to_match_strftime_format.py
  great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_not_be_null.py
  great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern.py
  great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern_list.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex_list.py
  great_expectations/expectations/core/expect_compound_columns_to_be_unique.py
  great_expectations/expectations/core/expect_multicolumn_sum_to_equal.py
  great_expectations/expectations/core/expect_multicolumn_values_to_be_unique.py
  great_expectations/expectations/core/expect_select_column_values_to_be_unique_within_record.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/regex_based_column_map_expectation.py
  great_expectations/expectations/set_based_column_map_expectation.py
  great_expectations/render/util.py
  tests/expectations/fixtures/expect_column_values_to_equal_three.py
  tests/render/test_render_BulletListContentBlock.py
Labels: dx, core

#8758 [BUGFIX] Column Descriptive Metrics: Single connection
  docs/sphinx_api_docs_source/public_api_excludes.py
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever.py
Labels: dx, core

#8763 [MAINTENANCE] Update CODEOWNERS js rule to include front end community of practice
  CODEOWNERS
Labels: core

#8765 [MAINTENANCE] Fix CI - DictDot typing issue
  great_expectations/types/base.py
  requirements-types.txt
Labels: core

#8767 [MAINTENANCE] Stop using `extras` to install test dependencies
  .github/workflows/ci.yml
Labels: core

#8637 [DOCS] Remove YAML Configuration Option from Manage Checkpoints and Other Documentation
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/docusaurus/docs/guides/validation/checkpoints/checkpoint_lp.md
  docs/docusaurus/docs/guides/validation/checkpoints/components_how_to_create_a_new_checkpoint/_additional_resources.mdx
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_add_validations_data_or_suites_to_a_checkpoint.md
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config.md
  docs/docusaurus/docs/guides/validation/checkpoints/how_to_create_a_new_checkpoint.md
  docs/docusaurus/sidebars.js
  great_expectations/data_context/config_validator/yaml_config_validator.py
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/integration/docusaurus/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config.py
  tests/integration/test_script_runner.py
Labels: devrel

#8766 [MAINTENANCE] Skip full marker test on `merge_group`
  .github/workflows/ci.yml
Labels: core

#8768 [CONTRIB] Update notify_on_failure to not run on merge_group events
  .github/workflows/ci.yml
Labels: core

#8743 [CONTRIB] Adding simple tests for CloudDataStore add_expectation_suite
  tests/datasource/fluent/_fake_cloud_api.py
  tests/experimental/metric_repository/test_cloud_data_store.py
Labels: core

#8761 [CONTRIB] Adding tests for S3 Validation and Expectation Store prefix
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_confirm_that_the_new_validation_results_store_has_been_added_by_running_great_expectations_store_list.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_update_store_reference.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_update_your_configuration_file_to_include_a_new_store_for_validation_results_on_s.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_confirm_that_the_new_expectations_store_has_been_added_by_running_great_expectations_store_list.mdx
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_update_your_configuration_file_to_include_a_new_store_for_expectations_on_s.mdx
  docs_rtd/guides/how_to_guides/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_s3.rst
  docs_rtd/guides/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_in_amazon_s3.rst
  docs_rtd/reference/spare_parts/data_context_reference.rst
  tests/datasource/fluent/data_asset/data_connector/test_s3_data_connector.py
  tests/integration/docusaurus/deployment_patterns/aws_cloud_storage_pandas.py
  tests/integration/docusaurus/deployment_patterns/aws_cloud_storage_spark.py
  tests/integration/docusaurus/deployment_patterns/aws_redshift_deployment_patterns.py
Labels: core

#8693 [FEATURE] Allow optional expectation_suite_name to be passed to RunDataAssistantEvent
  great_expectations/agent/actions/data_assistants/run_missingness_data_assistant.py
  great_expectations/agent/actions/data_assistants/run_onboarding_data_assistant.py
  great_expectations/agent/actions/data_assistants/utils.py
  great_expectations/agent/agent.py
  great_expectations/agent/models.py
  tests/agent/actions/data_assistants/test_run_missingness_data_assistant_action_utils.py
  tests/agent/actions/data_assistants/test_run_onboarding_data_assistant_action.py
Labels: core

#8756 [DOCS] Create Snowflake Quickstart for GX Cloud
  docs/docusaurus/docs/cloud/quickstarts/snowflake_quickstart.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8764 [MAINTENANCE] Update Fabric MeasureAsset.groupby_columns signature
  great_expectations/datasource/fluent/schemas/FabricPowerBIDatasource.json
  great_expectations/datasource/fluent/schemas/FabricPowerBIDatasource/PowerBIMeasure.json
  great_expectations/experimental/datasource/fabric.py
  tests/datasource/fluent/great_expectations.yml
  tests/datasource/fluent/test_fabric.py
Labels: core

#8762 [MAINTENANCE] Add `great_expectations_cloud` as a dependency
  docs/sphinx_api_docs_source/public_api_excludes.py
  great_expectations/agent/__init__.py
  great_expectations/agent/actions/__init__.py
  great_expectations/agent/actions/agent_action.py
  great_expectations/agent/actions/data_assistants/__init__.py
  great_expectations/agent/actions/data_assistants/run_missingness_data_assistant.py
  great_expectations/agent/actions/data_assistants/run_onboarding_data_assistant.py
  great_expectations/agent/actions/data_assistants/utils.py
  great_expectations/agent/actions/draft_datasource_config_action.py
  great_expectations/agent/actions/list_table_names.py
  great_expectations/agent/actions/run_checkpoint.py
  great_expectations/agent/actions/run_column_descriptive_metrics_action.py
  great_expectations/agent/agent.py
  great_expectations/agent/config.py
  great_expectations/agent/event_handler.py
  great_expectations/agent/message_service/__init__.py
  great_expectations/agent/message_service/asyncio_rabbit_mq_client.py
  great_expectations/agent/message_service/subscriber.py
  great_expectations/agent/models.py
  great_expectations/agent/run.py
  great_expectations/core/usage_statistics/package_dependencies.py
  pyproject.toml
  reqs/README.md
  reqs/requirements-dev-cloud.txt
  reqs/requirements-dev-test.txt
  setup.py
  tests/agent/__init__.py
  tests/agent/actions/__init__.py
  tests/agent/actions/checkpoints/__init__.py
  tests/agent/actions/checkpoints/test_run_checkpoint_action.py
  tests/agent/actions/data_assistants/__init__.py
  tests/agent/actions/data_assistants/test_run_missingness_data_assistant_action_utils.py
  tests/agent/actions/data_assistants/test_run_onboarding_data_assistant_action.py
  tests/agent/actions/test_draft_datasource_config.py
  tests/agent/actions/test_list_table_names_action.py
  tests/agent/actions/test_run_column_descriptive_metrics_action.py
  tests/agent/message_service/__init__.py
  tests/agent/message_service/amqp_errors.py
  tests/agent/message_service/test_rabbit_mq_client.py
  tests/agent/message_service/test_subscriber.py
  tests/agent/test_agent.py
  tests/agent/test_event_handler.py
  tests/agent/test_run.py
  tests/experimental/metric_repository/test_cloud_data_store.py
  tests/test_packaging.py
Labels: core

#8771 [RELEASE] 0.17.20
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: dx, core

#8760 [DOCS] Create GX Cloud Agent Installation Topic
  docs/docusaurus/docs/cloud/set_up_gx_cloud.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8772 [DOCS] Update Section Link in GX Cloud TOC
  docs/docusaurus/sidebars.js
Labels: devrel

#8774 [MAINTENANCE] Bump Cloud dependency to `0.0.3.dev3`
  reqs/requirements-dev-cloud.txt
Labels: core

#8757 [MAINTENANCE] SQL column identifier testing - ensure expectations fail when expected
  tests/datasource/fluent/integration/test_sql_datasources.py
Labels: core

#8778 [MAINTENANCE] Fix merge group worker usage
  .github/workflows/ci.yml
Labels: core
