Repository great-expectations/great_expectations, pull requests merged in 2023-10, with the labels that each got.

#8777 [MAINTENANCE] Use checkoutV3
  .github/workflows/ci.yml
  .github/workflows/test-pep273-compatibility.yml
Labels: core

#8776 [DOCS] Update Cloud Snowflake install instructions
  docs/docusaurus/docs/cloud/set_up_gx_cloud.md
Labels: core

#8786 [MAINTENANCE] Removing gallery parameter parse_strings_as_datetimes
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_alphabetical.py
  great_expectations/dataset/dataset.py
  great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_decreasing.py
  great_expectations/expectations/core/expect_column_values_to_be_increasing.py
Labels: core

#8775 [DOCS] Add GX Cloud Content
  docs/docusaurus/docs/cloud/checkpoints/manage_checkpoints.md
  docs/docusaurus/docs/cloud/data_assets/manage_data_assets.md
  docs/docusaurus/docs/cloud/expectations/manage_expectations.md
  docs/docusaurus/docs/cloud/gx_cloud_lp.md
  docs/docusaurus/docs/cloud/quickstarts/quickstart_lp.md
  docs/docusaurus/docs/cloud/quickstarts/snowflake_quickstart.md
  docs/docusaurus/docs/cloud/set_up_gx_cloud.md
  docs/docusaurus/docs/cloud/users/manage_users.md
  docs/docusaurus/docs/cloud/validations/manage_validations.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/img/small_gx_logo.png
  docs/docusaurus/static/img/snowflake_icon.png
  docs/docusaurus/static/img/validation_timeline.png
  docs/docusaurus/static/img/view_validation_timeline_detail.png
Labels: devrel

#8794 [DOCS] Update Link on Landing Page
  docs/docusaurus/docs/cloud/gx_cloud_lp.md
Labels: devrel

#8800 [DOCS] Minor Update to Code Syntax in Quickstart
  docs/docusaurus/docs/cloud/quickstarts/snowflake_quickstart.md
Labels: devrel

#8791 [MAINTENANCE] Prevent block-style datasource creation with Cloud-backed contexts
  great_expectations/data_context/data_context/cloud_data_context.py
  tests/conftest.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/conftest.py
  tests/data_context/test_data_context_datasources.py
Labels: core

#8792 [MAINTENANCE] Raise error if constructing FDS with individual args through base context API
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
Labels: core

#8801 [DOCS] Consistent pip install instructions
  docs/docusaurus/docs/cloud/quickstarts/snowflake_quickstart.md
  docs/docusaurus/docs/cloud/set_up_gx_cloud.md
  reqs/requirements-dev-cloud.txt
Labels: core

#8770 [MAINTENANCE] Remove SimpleCheckpoint from public API docs
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  great_expectations/checkpoint/checkpoint.py
Labels: core

#8793 [DOCS] Add Mermaid plugin to Docusaurus
  docs/docusaurus/docusaurus.config.js
  docs/docusaurus/package.json
  docs/docusaurus/yarn.lock
Labels: devrel

#8788 [MAINTENANCE] disallow-untyped-decorators
  great_expectations/cli/mark.py
  great_expectations/core/_docs_decorators.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/migrator/configuration_bundle.py
  great_expectations/dataset/dataset.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/pandas_datasource.pyi
  great_expectations/datasource/fluent/spark_datasource.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_to_exist.py
  great_expectations/expectations/core/expect_column_values_to_be_unique.py
  great_expectations/expectations/core/expect_column_values_to_not_be_null.py
  great_expectations/expectations/core/expect_table_column_count_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_distinct_values.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_values_length_max.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_values_length_min.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_between.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_z_score.py
  great_expectations/expectations/metrics/metric_provider.py
  great_expectations/render/renderer/renderer.py
  great_expectations/self_check/util.py
  great_expectations/validator/validator.py
  tasks.py
  tests/datasource/fluent/integration/test_integration_datasource.py
Labels: core

#8747 [MAINTENANCE] Remove `ge_cloud_mode` from `Store`
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  great_expectations/data_context/store/store.py
  tests/data_context/store/test_expectations_store.py
Labels: core

#8805 [RELEASE] 0.17.21
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8798 [CONTRIB] Updates to MulticolumnValuesSumValuesEqualToSingleColumn
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_sum_values_to_be_equal_to_single_column.py
Labels: community

#8806 [DOCS] Minor Syntax Update
  docs/docusaurus/docs/cloud/quickstarts/snowflake_quickstart.md
Labels: devrel

#8717 [DOCS] Update docs to reference new `gx/` dir instead of `great_expectations/`
  docs/docusaurus/docs/contributing/style_guides/code_style.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/database/connect_sql_source_data.md
  docs/docusaurus/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/instantiate_data_context.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/configure_expectation_stores.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/configure_result_stores.md
  docs/docusaurus/docs/guides/validation/advanced/how_to_deploy_a_scheduled_checkpoint_with_cron.md
Labels: core

#8807 [MAINTENANCE] Delete legacy `JsonSchemaProfiler`
  great_expectations/profile/json_schema_profiler.py
  great_expectations/profile/multi_batch_validation_meta_analysis.py
  tests/profile/test_jsonschema_profiler.py
Labels: core

#8810 [MAINTENANCE] Column Descriptive Metrics: Default to UNKNOWN if type is not found
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever.py
Labels: dx, core

#8815 [BUGFIX] Column Descriptive Metrics: Skip finding semantic type info for UNKNOWN columns
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
Labels: dx, core

#8817 [BUGFIX] Column Descriptive Metrics: Convert table name to lowercase for snowflake
  great_expectations/expectations/metrics/util.py
Labels: dx, core

#8819 [MAINTENANCE] Column Descriptive Metrics: Empty string instead of UNKNOWN if table column type introspection fails
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever.py
Labels: dx, core

#8773 [BUGFIX] Improve datasource crud
  great_expectations/core/datasource_dict.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context/serializable_data_context.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/sources.py
  great_expectations/datasource/fluent/sql_datasource.py
  tests/conftest.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_include_rendered_content.py
  tests/data_context/test_data_context_datasources.py
  tests/data_context/test_data_context_state_management.py
  tests/datasource/fluent/_fake_cloud_api.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_contexts.py
  tests/datasource/fluent/test_metadatasource.py
  tests/experimental/metric_repository/test_cloud_data_store.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever_integration.py
Labels: core

#8816 [BUGFIX] Fix Snowflake `'connection_string'` `TestConnectionError`
  great_expectations/datasource/fluent/snowflake_datasource.py
  tests/datasource/fluent/test_snowflake_datasource.py
Labels: core

#8822 [BUGFIX] Fix missing `config_provider`
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/datasource/fluent/fluent_base_model.py
  great_expectations/datasource/fluent/snowflake_datasource.py
  great_expectations/datasource/fluent/sources.py
  great_expectations/datasource/fluent/sql_datasource.py
  tests/datasource/fluent/test_sql_datasources.py
Labels: core

#8827 [MAINTENANCE] Fix `docs-snippets` CI step
  .github/workflows/ci.yml
  tasks.py
Labels: core

#8751 [DOCS] Updated language & code refs for Databricks Getting Started
  docs/docusaurus/docs/tutorials/getting_started/how_to_use_great_expectations_in_databricks.md
Labels: devrel

#8828 [RELEASE] 0.17.22
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8785 [FEATURE] Unexpected index list with/without values - New parameter in result_format
  docs/docusaurus/docs/reference/expectations/result_format.md
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/map_metric_provider/column_map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/map_metric_provider/map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/util.py
  tests/expectations/metrics/column_map_metrics/test_unexpected_indices_and_query.py
  tests/expectations/metrics/test_metrics_util.py
  tests/expectations/test_format_map_output.py
Labels: community

#8830 [MAINTENANCE] Column Descriptive Metrics: Don't add empty string for type
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever.py
Labels: dx, core

#8803 [MAINTENANCE] Add cloud api via docker compose for testing
  .github/workflows/ci.yml
  .gitignore
  assets/docker/mercury/docker-compose.yml
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/self_check/util.py
  tasks.py
  tests/conftest.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/integration/cloud/end_to_end/conftest.py
  tests/integration/cloud/end_to_end/test_snowflake_datasource.py
Labels: core

#8825 [DOCS] Remove all mentions of profilers in public docs
  docs/docusaurus/docs/conceptual_guides/gx_overview.md
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/docusaurus/docs/glossary.md
  docs/docusaurus/docs/guides/connecting_to_your_data/datasource_configuration/components/_tip_configured_data_connector_overview.mdx
  docs/docusaurus/docs/guides/expectations/advanced/how_to_create_a_new_expectation_suite_using_rule_based_profilers.md
  docs/docusaurus/docs/guides/expectations/create_expectations_overview.md
  docs/docusaurus/docs/guides/expectations/data_assistants_lp.md
  docs/docusaurus/docs/guides/expectations/expectations_lp.md
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/configure_expectation_stores.md
  docs/docusaurus/docs/intro.md
  docs/docusaurus/docs/terms/batch.md
  docs/docusaurus/docs/terms/batch_request.md
  docs/docusaurus/docs/terms/data_asset.md
  docs/docusaurus/docs/terms/data_assistant.md
  docs/docusaurus/docs/terms/data_context.md
  docs/docusaurus/docs/terms/data_docs_store.md
  docs/docusaurus/docs/terms/datasource.md
  docs/docusaurus/docs/terms/execution_engine.md
  docs/docusaurus/docs/terms/expectation.md
  docs/docusaurus/docs/terms/expectation_suite.md
  docs/docusaurus/docs/terms/metric.md
  docs/docusaurus/docs/terms/profiler.md
  docs/docusaurus/docs/terms/validator.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/_redirects
  tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py
Labels: core

#8814 [DOCS] Create New Content for Column Descriptive Metrics in GX Cloud
  docs/docusaurus/docs/cloud/data_assets/manage_data_assets.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8833 [CONTRIB] Also run CI when a PR becomes Ready for Review
  .github/workflows/ci.yml
Labels: core

#8829 [DOCS] Document GX Cloud Data Assistant Functionality
  docs/docusaurus/docs/cloud/checkpoints/manage_checkpoints.md
  docs/docusaurus/docs/cloud/data_assets/manage_data_assets.md
  docs/docusaurus/docs/cloud/expectation_suites/manage_expectation_suites.md
  docs/docusaurus/docs/cloud/expectations/manage_expectations.md
  docs/docusaurus/docs/cloud/gx_cloud_lp.md
  docs/docusaurus/docs/cloud/validations/manage_validations.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8832 [DOCS] Update set_up_gx_cloud.md
  docs/docusaurus/docs/cloud/quickstarts/snowflake_quickstart.md
  docs/docusaurus/docs/cloud/set_up_gx_cloud.md
Labels: core

#8837 [MAINTENANCE] mypy 1.6
  contrib/cli/requirements.txt
  great_expectations/data_context/data_context/abstract_data_context.py
  reqs/requirements-dev-contrib.txt
  tests/test_packaging.py
Labels: core

#8808 [MAINTENANCE] Delete legacy `BasicSuiteBuilderProfiler`
  great_expectations/profile/__init__.py
  great_expectations/profile/basic_suite_builder_profiler.py
  tests/profile/test_basic_suite_builder_profiler.py
Labels: core

#8842 [DOCS] Update Manage Expectation Suites in GX Cloud Docs
  docs/docusaurus/docs/cloud/expectation_suites/manage_expectation_suites.md
Labels: devrel

#8839 [MAINTENANCE] Run ci-is-on-main-repo in merge queue.
  .github/workflows/ci.yml
Labels: core

#8846 [DOCS] Remove Troubleshooting Entry from GX Cloud TOC
  docs/docusaurus/sidebars.js
Labels: devrel

#8831 [MAINTENANCE] Add pact contract testing with GX Cloud
  .github/workflows/ci.yml
  .gitignore
  great_expectations/core/usage_statistics/package_dependencies.py
  pyproject.toml
  reqs/requirements-dev-lite.txt
  tasks.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/integration/cloud/__init__.py
  tests/integration/cloud/end_to_end/conftest.py
  tests/integration/cloud/end_to_end/test_snowflake_datasource.py
  tests/integration/cloud/rest_contracts/conftest.py
  tests/integration/cloud/rest_contracts/test_data_context_configuration.py
Labels: core

#8851 [MAINTENANCE] Allow re-publishing Pact on same commit
  tests/integration/cloud/rest_contracts/conftest.py
Labels: core

#8852 [RELEASE] 0.17.23
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
  tests/integration/cloud/rest_contracts/conftest.py
Labels: core

#8855 [MAINTENANCE] Use contract test response bodies as unit test mocks
  tests/integration/cloud/__init__.py
  tests/integration/cloud/rest_contracts/conftest.py
  tests/integration/cloud/rest_contracts/test_data_context_configuration.py
  tests/integration/cloud/rest_contracts/unit_test_mocks/conftest.py
  tests/integration/cloud/rest_contracts/unit_test_mocks/test_mock_cloud_data_context.py
Labels: core

#8864 [MAINTENANCE] Increase docker compose up services timeout
  tasks.py
Labels: core

#8804 [DOCS] DSB-321: Add workflow diagram to OSS Quickstart
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
Labels: devrel

#8867 [MAINTENANCE] Remove `docs-snippets` `name`
  .github/workflows/ci.yml
Labels: core

#8865 [MAINTENANCE] Column Descriptive Metrics: Remove compute_metrics_with_aborted_metrics
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/experimental/metric_repository/column_descriptive_metrics_metric_retriever.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/validator/metrics_calculator.py
  great_expectations/validator/validator.py
  tests/experimental/metric_repository/test_column_descriptive_metrics_metric_retriever.py
  tests/validator/test_metrics_calculator.py
Labels: dx, core

#8868 [MAINTENANCE] Improve Cloud update Snowflake Data Source tests
  tests/integration/cloud/end_to_end/test_snowflake_datasource.py
Labels: core

#8859 [MAINTENANCE] Remove the deprecated save_changes parameters on ADC data source crud methods
  great_expectations/data_context/config_validator/yaml_config_validator.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  pyproject.toml
  tests/data_context/abstract_data_context/test_abstract_data_context_datasource_crud.py
  tests/data_context/abstract_data_context/test_datasource_delete.py
  tests/data_context/test_data_context_datasources.py
Labels: core

#8871 [MAINTENANCE] Cloud integration tests documentation
  assets/docker/mercury/README.md
  tasks.py
  tests/integration/cloud/end_to_end/test_snowflake_datasource.py
Labels: core

#8863 [MAINTENANCE] Remove deprecated code in advance of v18 release
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/util.py
  great_expectations/render/types/__init__.py
  pyproject.toml
  tests/data_context/abstract_data_context/test_abstract_data_context_datasource_crud.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/test_data_context_deprecation.py
  tests/data_context/test_data_context_profilers.py
  tests/data_context/test_data_context_state_management.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/integration/db/bigquery.py
  tests/integration/docusaurus/reference/glossary/checkpoints.py
  tests/integration/docusaurus/validation/checkpoints/how_to_validate_data_by_running_a_checkpoint.py
  tests/integration/profiling/rule_based_profiler/test_profiler_basic_workflows.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/render/test_render.py
  tests/test_deprecation.py
Labels: core

#8873 [MAINTENANCE] Add pre-commit autofix to PRs
  .pre-commit-config.yaml
  CONTRIBUTING_EXPECTATIONS.md
  IDE_SETUP_TIPS.md
  README.md
  assets/docker/clickhouse/docker-compose.yml
  assets/docker/clickhouse/info.csv
  assets/docker/mssql/README.md
  assets/partners/anthonydb/provision.mssql
  assets/partners/anthonydb/requirements.txt
  assets/partners/rubenshift/requirements.txt
  assets/scripts/AlgoliaScripts/README.md
  ci/azure-pipelines-sqlalchemy-compatibility.yml
  contrib/time_series_expectations/README.md
  contrib/time_series_expectations/assets/models/example_prophet_date_model.json
  contrib/time_series_expectations/time_series_expectations/expectations/example_prophet_date_model.json
  docs_rtd/Makefile
  docs_rtd/community.rst
  docs_rtd/contributing.rst
  docs_rtd/contributing/contrib_pull_request_acceptance_checklist.rst
  docs_rtd/contributing/contribution_checklist.rst
  docs_rtd/contributing/levels_of_maturity.rst
  docs_rtd/contributing/make_changes_through_github.rst
  docs_rtd/contributing/setting_up_your_dev_environment.rst
  docs_rtd/guides.rst
  docs_rtd/guides/how_to_guides/configuring_data_contexts/how_to_create_a_new_data_context_with_the_cli.rst
  docs_rtd/guides/how_to_guides/configuring_generated_notebooks/how_to_configure_suite_edit_generated_notebooks.rst
  docs_rtd/guides/how_to_guides/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_azure_blob_storage.rst
  docs_rtd/guides/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_in_amazon_s3.rst
  docs_rtd/guides/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_in_azure_blob_storage.rst
  docs_rtd/guides/how_to_guides/creating_and_editing_expectations/how_to_edit_an_expectation_suite_using_a_disposable_notebook.rst
  docs_rtd/guides/how_to_guides/miscellaneous/how_to_add_comments_to_a_page_in_documentation.rst
  docs_rtd/guides/how_to_guides/validation.rst
  docs_rtd/guides/how_to_guides/validation/how_to_create_a_new_checkpoint.rst
  docs_rtd/guides/how_to_guides/validation/how_to_trigger_email_as_a_validation_action.rst
  docs_rtd/guides/how_to_guides/validation/how_to_trigger_slack_notifications_as_a_validation_action.rst
  docs_rtd/guides/tutorials/getting_started/connect_to_data.rst
  docs_rtd/guides/tutorials/getting_started/customize_your_deployment.rst
  docs_rtd/guides/tutorials/getting_started/set_up_data_docs.rst
  docs_rtd/guides/tutorials/getting_started_v3_api/connect_to_data.rst
  docs_rtd/guides/tutorials/getting_started_v3_api/customize_your_deployment.rst
  docs_rtd/guides/tutorials/getting_started_v3_api/set_up_data_docs.rst
  docs_rtd/guides/workflows_patterns/deployment_google_cloud_composer.rst
  docs_rtd/reference.rst
  docs_rtd/reference/core_concepts/data_discovery.rst
  docs_rtd/reference/core_concepts/expectation_suite_operations.rst
  docs_rtd/reference/core_concepts/expectations/implemented_expectations.rst
  docs_rtd/reference/core_concepts/expectations/result_format.rst
  docs_rtd/reference/core_concepts/metrics.rst
  docs_rtd/releasing.rst
  great_expectations/datasource/fluent/serializable_types/README.md
  great_expectations/render/v3/notebook_assets/suite_edit/HEADER.md
  great_expectations/render/view/static/styles/data_docs_default_styles.css
  reqs/requirements-dev-clickhouse.txt
  tasks.py
  tests/profile/fixtures/expected_evrs_BasicSuiteBuilderProfiler_on_titanic_demo_mode.json
  tests/profile/fixtures/expected_evrs_SuiteBuilderProfiler_on_titanic_with_configurations.json
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
Labels: core

#8880 [MAINTENANCE] Only run `docs-snippets` on doc changes
  .github/workflows/ci.yml
Labels: core

#8834 [DOCS] Create About GX Cloud Content
  docs/docusaurus/docs/cloud/about_gx.md
  docs/docusaurus/docs/cloud/data_assets/manage_data_assets.md
  docs/docusaurus/docs/cloud/gx_cloud_lp.md
  docs/docusaurus/docs/cloud/set_up_gx_cloud.md
  docs/docusaurus/sidebars.js
Labels: devrel

#8892 [MAINTENANCE] Quieter logging
  great_expectations/core/http.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/datasource/fluent/fluent_base_model.py
Labels: core

#8887 [MAINTENANCE] E2E Test - Pandas In Memory with Cloud
  tests/integration/cloud/end_to_end/test_pandas_in_memory_datasource.py
Labels: dx, core

#8879 [MAINTENANCE] Add `SparkDatasource` End-to-End test
  .github/workflows/ci.yml
  tasks.py
  tests/integration/cloud/end_to_end/conftest.py
  tests/integration/cloud/end_to_end/test_spark_datasource.py
Labels: core

#8894 [BUGFIX] Only update self.assets if cloud deletion successful
  great_expectations/datasource/fluent/interfaces.py
Labels: core

#8895 [RELEASE] 0.18.0
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8893 [DOCS] Update Cloud Quickstart save expectation suite example
  docs/docusaurus/docs/gx_cloud/tutorials/getting_started/getting_started_with_gx_cloud.md
Labels: core

#8881 [MAINTENANCE] Get checkpoint endpoint contract test
  tests/integration/cloud/rest_contracts/test_checkpoints.py
Labels: dx, core

#8885 [MAINTENANCE] Add Expectation Suite Pact tests
  tests/integration/cloud/rest_contracts/conftest.py
  tests/integration/cloud/rest_contracts/test_expectation_suites.py
  tests/integration/cloud/rest_contracts/unit_test_mocks/conftest.py
Labels: core

#8901 [MAINTENANCE] Do not skip spark tests in cloud stage
  tests/integration/cloud/end_to_end/conftest.py
  tests/integration/cloud/end_to_end/test_spark_datasource.py
Labels: core

#8886 [MAINTENANCE] List checkpoints endpoint contract test
  tests/integration/cloud/rest_contracts/test_checkpoints.py
Labels: dx, core
