Repository great-expectations/great_expectations, pull requests merged in 2023-01, with the labels that each got.

#6679 [MAINTENANCE] begin flake8 linting on tests
  setup.cfg
  tests/actions/test_validation_operators_in_data_context.py
  tests/conftest.py
  tests/core/test_batch_related_objects.py
  tests/core/test_expectation_suite.py
  tests/core/test_serialization.py
  tests/core/usage_statistics/test_usage_statistics.py
  tests/experimental/datasources/test_integration_sql_datasource.py
  tests/experimental/datasources/test_type_lookup.py
  tests/experimental/datasources/test_viral_snippets.py
  tests/jupyter_ux/test_jupyter_ux.py
  tests/profile/test_basic_suite_builder_profiler.py
  tests/profile/test_profile.py
  tests/profile/test_user_configurable_profiler_v2_batch_kwargs.py
  tests/profile/test_user_configurable_profiler_v3_batch_request.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
  tests/render/test_renderer.py
  tests/test_definitions/test_expectations_v2_api.py
  tests/test_definitions/test_expectations_v3_api.py
  tests/test_great_expectations.py
  tests/test_utils.py
  tests/validator/test_validator.py
Labels: core-team, platform

#6687 [MAINTENANCE] Clean up packaging & installation pipeline
  azure-pipelines-packaging.yml
Labels: core-team, platform

#6640 [MAINTENANCE] fix remaining core/utils.py typing issues
  great_expectations/core/util.py
Labels: core-team, platform

#6617 [MAINTENANCE] `mypy` typing for `core/util.py`
  great_expectations/core/util.py
  pyproject.toml
Labels: core-team, dx

#6684 [MAINTENANCE] Update `get_context` return type
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/data_context/ephemeral_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/data_context/serializable_data_context.py
  great_expectations/util.py
  tests/data_context/abstract_data_context/test_abstract_data_context_datasource_crud.py
Labels: core-team, platform

#6671 [MAINTENANCE] Get datetime tests working for trino/snowflake/spark in values_to_be_in_set
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_in_set.json
Labels: core-team, dx

#6676 [FEATURE] Support to include ID/PK in validation result for each row - Spark
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/map_metric_provider.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/conftest.py
  tests/expectations/metrics/test_map_metric.py
Labels: core-team, dx

#6691 [MAINTENANCE] Cleanup typing errors.
  great_expectations/alias_types.py
  great_expectations/core/util.py
  great_expectations/expectations/validation_handlers.py
  great_expectations/render/renderer/column_section_renderer.py
  great_expectations/render/renderer/content_block/content_block.py
  pyproject.toml
Labels: core-team, platform

#6693 [MAINTENANCE] Remove unused Metric and BatchMetric classes and consolidate ValidationMetricIdentifier with other identifiers
  great_expectations/core/metric.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/store/metric_store.py
  great_expectations/data_context/types/resource_identifiers.py
  great_expectations/expectations/registry.py
  tests/actions/test_store_metric_action.py
  tests/data_context/store/test_evaluation_parameter_store.py
  tests/data_context/store/test_evaluation_parameter_store_pre_v013.py
Labels: core-team, platform

#6689 [MAINTENANCE] Refactor `BaseDataContext` to leverage `get_context`
  great_expectations/data_context/data_context/base_data_context.py
Labels: core-team, platform

#6692 [FEATURE] ID/PK Pandas query returned as all unexpected indices
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/map_metric_provider.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/expectations/metrics/test_map_metric.py
  tests/render/test_render_ValidationResultsTableContentBlockRenderer.py
Labels: core-team, dx

#6680 [MAINTENANCE] expect day count to be close to equivalent week day mean
  contrib/experimental/great_expectations_experimental/expectations/expect_day_count_to_be_close_to_equivalent_week_day_mean.py
Labels: community

#6681 [MAINTENANCE] initial type checking for `rules_based_profiler`
  great_expectations/data_context/types/base.py
  great_expectations/rule_based_profiler/builder.py
  great_expectations/rule_based_profiler/config/base.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_dispatcher.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/data_assistant_result/onboarding_data_assistant_result.py
  great_expectations/rule_based_profiler/data_assistant_result/volume_data_assistant_result.py
  great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/column_pair_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/multi_column_domain_builder.py
  great_expectations/rule_based_profiler/estimators/exact_numeric_range_estimator.py
  great_expectations/rule_based_profiler/estimators/numeric_range_estimator.py
  great_expectations/rule_based_profiler/estimators/quantiles_numeric_range_estimator.py
  great_expectations/rule_based_profiler/helpers/simple_semantic_type_filter.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/mean_table_columns_set_match_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/metric_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_counts_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/value_set_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_container.py
  great_expectations/types/__init__.py
  pyproject.toml
Labels: core-team, platform, dx

#6704 [BUGFIX] Increase minimum `numpy` versions for Python 3.8 and 3.9 due to support in latest release of `scipy`
  azure-pipelines.yml
  requirements.txt
Labels: core-team, platform

#6708 [MAINTENANCE] Add deprecated Cloud variables to `_CloudConfigurationProvider.get_values()` output
  great_expectations/core/config_provider.py
  tests/core/test_config_provider.py
Labels: core-team, platform

#6700 [MAINTENANCE] Autobuild markdown stubs
  docs/sphinx_api_docs_source/README.md
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
  docs/sphinx_api_docs_source/data_context.md
  scripts/check_public_api_docstrings.py
  scripts/public_api_report.py
Labels: core-team, dx

#6712 [MAINTENANCE] API docs styling
  src/css/api_docs/api_docs.scss
  src/css/api_docs/pydata-sphinx-theme-modified.scss
Labels: core-team, dx

#6711 [BUGFIX] Format current branch name properly for tag branches in docker tests
  azure-pipelines.yml
Labels: core-team, platform

#6715 [RELEASE] 0.15.42
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#6703 [MAINTENANCE] update `cli` `DataContext` types
  great_expectations/cli/cli.py
  great_expectations/cli/datasource.py
  great_expectations/cli/toolkit.py
  great_expectations/data_context/data_context/data_context.py
  pyproject.toml
Labels: core-team, platform, dx

#6721 [MAINTENANCE] Fix missing exclamation marks in API docs admonitions
  src/css/api_docs/pydata-sphinx-theme-modified.scss
Labels: core-team, dx

#6720 [MAINTENANCE] Refactor tests to leverage `get_context` instead of `BaseDataContext`
  tests/actions/conftest.py
  tests/actions/test_validation_operators.py
  tests/actions/test_validation_operators_in_data_context.py
  tests/cli/test_docs.py
  tests/core/usage_statistics/test_usage_statistics.py
  tests/core/usage_statistics/test_usage_statistics_handler_methods.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/cloud_data_context/test_profiler_crud.py
  tests/data_context/store/test_store_backends.py
  tests/data_context/test_concurrency_config.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_config_ui.py
  tests/data_context/test_data_context_data_docs_api.py
  tests/data_context/test_data_context_datasources.py
  tests/data_context/test_data_context_in_code_config.py
  tests/data_context/test_data_context_v013.py
  tests/integration/common_workflows/simple_build_data_docs.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/spark/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/spark/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/s3/spark/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/spark_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/spark_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/in_memory/spark_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/in_memory/spark_yaml_example.py
  tests/integration/docusaurus/deployment_patterns/aws_emr_serverless_deployment_patterns.py
  tests/integration/docusaurus/deployment_patterns/aws_glue_deployment_patterns.py
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_dataframe_python_configs.py
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_dataframe_yaml_configs.py
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_file_python_configs.py
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_file_yaml_configs.py
  tests/integration/usage_statistics/instantiate_context_with_usage_statistics.py
  tests/integration/usage_statistics/test_usage_stats_common_messages_are_sent_v3api.py
  tests/performance/taxi_benchmark_util.py
  tests/render/renderer/test_checkpoint_new_notebook_renderer.py
Labels: core-team, platform

#6682 [BUGFIX] - Implementing deep copy of runtime_configuration variable
  great_expectations/validator/validator.py
  tests/validator/test_validator.py
Labels: community

#6718 [DOCS] DOC-414: Remove guide for use of outdated docker images
  docs/guides/miscellaneous/how_to_use_the_great_expectation_docker_images.md
  docs/guides/setup/components_index/_miscellaneous.mdx
  docs/guides/setup/index.md
  sidebars.js
  static/_redirects
Labels: devrel

#6735 [DOCS] Convert docs snippets to named snippets
  tests/expectations/core/test_expect_column_mean_to_be_positive.py
  tests/expectations/core/test_expect_column_values_to_be_in_set.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/azure/pandas/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/pandas/inferred_and_runtime_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/pandas/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/spark/inferred_and_runtime_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/bigquery_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/bigquery_yaml_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/postgres_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/trino_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_choose_which_dataconnector_to_use.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_create_a_batch_of_data_from_an_in_memory_pandas_dataframe.py
Labels: core-team, platform

#6696 [MAINTENANCE] Update remaining atomic prescriptive templates (1 of 2)
  great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
  great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py
  great_expectations/expectations/core/expect_column_max_to_be_between.py
  great_expectations/expectations/core/expect_column_mean_to_be_between.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_most_common_value_to_be_in_set.py
  great_expectations/expectations/core/expect_column_pair_cramers_phi_value_to_be_less_than.py
  great_expectations/expectations/core/expect_column_pair_values_a_to_be_greater_than_b.py
  great_expectations/expectations/core/expect_column_pair_values_to_be_equal.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_to_exist.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_equal.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_dateutil_parseable.py
  great_expectations/expectations/core/expect_column_values_to_be_decreasing.py
  great_expectations/expectations/core/expect_column_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/expectations/core/expect_column_values_to_be_increasing.py
  great_expectations/expectations/core/expect_column_values_to_be_null.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/core/expect_column_values_to_be_unique.py
  great_expectations/expectations/core/expect_column_values_to_match_json_schema.py
  great_expectations/expectations/core/expect_column_values_to_match_regex_list.py
  great_expectations/expectations/core/expect_column_values_to_match_strftime_format.py
  great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py
  great_expectations/expectations/core/expect_column_values_to_not_be_null.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex.py
  great_expectations/expectations/core/expect_compound_columns_to_be_unique.py
  great_expectations/expectations/core/expect_multicolumn_sum_to_equal.py
  great_expectations/expectations/core/expect_multicolumn_values_to_be_unique.py
  great_expectations/expectations/core/expect_select_column_values_to_be_unique_within_record.py
  great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py
  great_expectations/expectations/core/expect_table_columns_to_match_set.py
  great_expectations/expectations/core/expect_table_row_count_to_be_between.py
  great_expectations/expectations/core/expect_table_row_count_to_equal_other_table.py
  great_expectations/expectations/expectation.py
  great_expectations/render/renderer_configuration.py
  tests/expectations/snapshots/snap_test_expectation_atomic_renderers.py
  tests/expectations/test_expectation_atomic_renderers.py
Labels: core-team, platform

#6723 [MAINTENANCE] Refactor tests to leverage `get_context` instead of `DataContext`
  tests/checkpoint/conftest.py
  tests/cli/test_checkpoint.py
  tests/cli/test_datasource_new_pandas_paths.py
  tests/cli/test_datasource_pandas.py
  tests/cli/test_datasource_snowflake.py
  tests/cli/test_datasource_sqlite.py
  tests/cli/test_docs.py
  tests/cli/test_init.py
  tests/cli/test_init_pandas.py
  tests/cli/test_init_sqlite.py
  tests/cli/test_suite.py
  tests/cli/test_toolkit.py
  tests/conftest.py
  tests/core/usage_statistics/test_usage_statistics.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/test_base_data_context.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_config_errors.py
  tests/data_context/test_data_context_config_variables.py
  tests/data_context/test_data_context_data_docs_api.py
  tests/data_context/test_data_context_ge_cloud_mode.py
  tests/data_context/test_data_context_on_teams.py
  tests/data_context/test_data_context_variables.py
  tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/render/renderer/test_suite_scaffold_notebook_renderer.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
  tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
  tests/render/test_data_documentation_site_builder.py
  tests/validator/test_validator.py
Labels: core-team, platform

#6702 [CONTRIB] added condition to ExpectQueriedColumnListToBeUnique
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_list_to_be_unique.py
Labels: community

#6724 [MAINTENANCE] Update remaining atomic prescriptive templates (2 of 2)
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_values_to_be_json_parseable.py
  great_expectations/expectations/core/expect_column_values_to_match_regex.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex_list.py
  great_expectations/expectations/core/expect_table_column_count_to_be_between.py
  great_expectations/expectations/core/expect_table_column_count_to_equal.py
  great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_values_length_max.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_values_length_min.py
  great_expectations/expectations/regex_based_column_map_expectation.py
  great_expectations/expectations/set_based_column_map_expectation.py
  great_expectations/expectations/util.py
  pyproject.toml
  tests/expectations/snapshots/snap_test_expectation_atomic_renderers.py
Labels: core-team, platform

#6722 [BUGFIX} Re-enable unit tests in `dev` pipeline
  azure-pipelines-dev.yml
Labels: core-team, platform

#6730 [MAINTENANCE] `execution_engine` typing
  great_expectations/execution_engine/split_and_sample/data_sampler.py
  great_expectations/execution_engine/split_and_sample/data_splitter.py
  great_expectations/execution_engine/split_and_sample/sparkdf_data_splitter.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_sampler.py
  great_expectations/execution_engine/split_and_sample/sqlalchemy_data_splitter.py
  pyproject.toml
Labels: core-team, platform, dx

#6741 [BUGFIX] Patch broken `test_data_context_ge_cloud_mode_with_incomplete_cloud_config_should_throw_error`
  tests/data_context/test_data_context_ge_cloud_mode.py
Labels: core-team, platform

#6738 [DOCS] Update documentation to reference `get_context`
  docs/deployment_patterns/how_to_use_great_expectations_in_deepnote.md
  docs/deployment_patterns/how_to_use_great_expectations_with_prefect.md
  docs/guides/expectations/advanced/how_to_compare_two_tables_with_the_user_configurable_profiler.md
  docs/guides/expectations/advanced/how_to_create_a_new_expectation_suite_by_profiling_from_a_jsonschema_file.md
  docs/guides/expectations/advanced/how_to_create_expectations_that_span_multiple_batches_using_evaluation_parameters.md
  docs/guides/expectations/advanced/how_to_dynamically_load_evaluation_parameters_from_a_database.md
  docs/guides/expectations/creating_custom_expectations/how_to_use_custom_expectations.md
  docs/guides/expectations/how_to_create_and_edit_expectations_with_a_profiler.md
  docs/guides/setup/configuring_data_contexts/how_to_instantiate_a_data_context_without_a_yml_file.md
  docs/guides/validation/how_to_validate_data_by_running_a_checkpoint.md
  docs_rtd/reference/spare_parts/data_docs_reference.rst
  docs_rtd/reference/spare_parts/profiling_reference.rst
  great_expectations/cli/checkpoint_script_template.py
  great_expectations/cli/datasource.py
  great_expectations/cli/project.py
  great_expectations/cli/toolkit.py
  great_expectations/render/notebook_assets/suite_edit/header.py.j2
  great_expectations/render/renderer/suite_scaffold_notebook_renderer.py
  great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
  great_expectations/render/v3/notebook_assets/suite_edit/header.py.j2
  great_expectations/util.py
  tests/cli/test_project.py
  tests/data_asset/test_data_asset.py
  tests/data_context/conftest.py
  tests/data_context/test_configuration_storage.py
  tests/data_context/test_configuration_storage_pre_v013.py
  tests/data_context/test_data_context_config_variables_pre_v013.py
  tests/data_context/test_data_context_store_configs.py
  tests/integration/db/awsathena.py
  tests/profile/conftest.py
  tests/render/renderer/test_checkpoint_new_notebook_renderer.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project/notebooks/pandas/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project/notebooks/spark/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project/notebooks/sql/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project_with_v30_configuration_and_no_checkpoints/notebooks/pandas/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project_with_v30_configuration_and_no_checkpoints/notebooks/spark/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project_with_v30_configuration_and_no_checkpoints/notebooks/sql/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project_with_v30_configuration_and_v20_checkpoints/notebooks/pandas/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project_with_v30_configuration_and_v20_checkpoints/notebooks/spark/validation_playground.ipynb
  tests/test_fixtures/upgrade_helper/great_expectations_v20_project_with_v30_configuration_and_v20_checkpoints/notebooks/sql/validation_playground.ipynb
  tests/test_fixtures/v3/notebook_assets/suite_edit/header.py.j2
Labels: core-team, platform

#6731 [MAINTENANCE] `core/expectation_` type checking
  great_expectations/core/expectation_configuration.py
  great_expectations/core/expectation_diagnostics/expectation_diagnostics.py
  great_expectations/core/expectation_diagnostics/supporting_types.py
  great_expectations/core/expectation_validation_result.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/registry.py
  pyproject.toml
Labels: core-team, platform, dx

#6736 [DOCS] Convert remaining snippets to named snippets
  tests/integration/docusaurus/connecting_to_your_data/how_to_create_a_batch_of_data_from_an_in_memory_spark_dataframe.py
  tests/integration/docusaurus/connecting_to_your_data/how_to_introspect_and_partition_your_data/sql_database/yaml_example_gradual.py
  tests/integration/docusaurus/deployment_patterns/gcp_deployment_patterns_file_bigquery_yaml_configs.py
  tests/integration/docusaurus/deployment_patterns/gcp_deployment_patterns_file_gcs_yaml_configs.py
  tests/integration/docusaurus/expectations/advanced/user_configurable_profiler_cross_table_comparison.py
  tests/integration/docusaurus/expectations/advanced/user_configurable_profiler_cross_table_comparison_from_query.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_pair_values_to_have_a_difference_of_three.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_be_in_solfege_scale_set.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_only_contain_vowels.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_multicolumn_values_to_be_multiples_of_three.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_queried_column_value_frequency_to_meet_threshold.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_queried_table_row_count_to_be.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_table_columns_to_be_unique.py
  tests/integration/docusaurus/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.py
  tests/integration/docusaurus/expectations/examples/query_expectation_template.py
  tests/integration/docusaurus/reference/core_concepts/checkpoints_and_actions.py
  tests/integration/docusaurus/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.py
  tests/integration/docusaurus/tutorials/getting-started/getting_started.py
  tests/integration/docusaurus/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.py
  tests/integration/docusaurus/validation/checkpoints/how_to_validate_data_with_a_python_configured_in_memory_checkpoint.py
  tests/integration/docusaurus/validation/checkpoints/how_to_validate_data_with_a_yaml_configured_in_memory_checkpoint.py
Labels: core-team, platform

#6748 [DOCS] Convert line number references to named references in docs
  docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  docs/guides/connecting_to_your_data/cloud/azure/pandas.md
  docs/guides/connecting_to_your_data/cloud/gcs/pandas.md
  docs/guides/connecting_to_your_data/cloud/gcs/spark.md
  docs/guides/connecting_to_your_data/database/bigquery.md
  docs/guides/connecting_to_your_data/database/postgres.md
  docs/guides/connecting_to_your_data/database/trino.md
  docs/guides/connecting_to_your_data/how_to_choose_which_dataconnector_to_use.md
  docs/guides/connecting_to_your_data/how_to_configure_a_dataconnector_to_introspect_and_partition_tables_in_sql.md
  docs/guides/expectations/advanced/how_to_compare_two_tables_with_the_user_configurable_profiler.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_pair_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_multicolumn_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_parameterized_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_query_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
  docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant.md
  docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.md
  docs/guides/validation/advanced/how_to_validate_data_with_an_in_memory_checkpoint.md
  docs/guides/validation/checkpoints/how_to_pass_an_in_memory_dataframe_to_a_checkpoint.md
  docs/terms/checkpoint.md
  docs/tutorials/getting_started/tutorial_connect_to_data.md
  docs/tutorials/getting_started/tutorial_validate_data.md
Labels: core-team, platform

#6749 [MAINTENANCE] Remove printing of entire snippet map in `remark-named-snippet` hook
  docs/scripts/remark-named-snippets/index.js
Labels: core-team, platform

#6618 [DOCS] Doc-280 AWS golden path with S3 cloud storage and Pandas
  docs/components/cli/_store_list_info_active_stores.md
  docs/components/cli/_store_list_verify_active_configs.md
  docs/components/stores/_stores_overwrite_at_runtime.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_aws_cli_verify_installation.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_create_and_run.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_create_tab_python.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_create_tab_yaml.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_create_tabs.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_run.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_save.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_save_tab_python.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_save_tab_yaml.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_test_tab_python.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_checkpoint_test_tab_yaml.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_congratulations_aws_s3_pandas.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_data_docs_build_and_view.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_datasource_code_environment.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_expectation_suite_add_expectations_with_validator.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_expectation_suite_batch_request_validator_prepare_or_reuse.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_expectation_suite_save.md
  docs/deployment_patterns/how_to_use_gx_with_aws/components/_python_where_to_get.md
  docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_cloud_storage_and_pandas.md
  docs/guides/connecting_to_your_data/cloud/s3/components_pandas/_test_your_new_datasource.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_a_validation_result_store_in_amazon_s3/_confirm_that_the_new_validation_results_store_has_been_added_by_running_great_expectations_store_list.mdx
  docs/guides/setup/configuring_metadata_stores/components_how_to_configure_an_expectation_store_in_amazon_s3/_confirm_that_the_new_expectations_store_has_been_added_by_running_great_expectations_store_list.mdx
  sidebars.js
Labels: devrel

#6750 [MAINTENANCE] Remove `base_data_context` mark in tests
  pyproject.toml
  tests/core/usage_statistics/test_usage_statistics.py
Labels: core-team, platform

#6746 [MAINTENANCE] Consolidate different Metric Types definition Enums
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_column_profiler_report.py
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/metrics/data_profiler_metrics/data_profiler_profile_diff.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_discrete_entropy_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_distribution_to_match_benfords_law.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_kurtosis_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_skew_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_to_have_no_days_missing.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_alphabetical.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_in_set_spark_optimized.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_normally_distributed.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_string_integers_increasing.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_wasserstein_distance_to_be_less_than.py
  contrib/experimental/great_expectations_experimental/expectations/expect_day_count_to_be_close_to_equivalent_week_day_mean.py
  contrib/experimental/great_expectations_experimental/expectations/expect_table_checksum_to_equal_other_table.py
  contrib/experimental/great_expectations_experimental/expectations/expect_yesterday_count_compared_to_avg_equivalent_days_of_week.py
  contrib/great_expectations_ethical_ai_expectations/great_expectations_ethical_ai_expectations/expectations/expect_table_binary_label_model_bias.py
  contrib/great_expectations_ethical_ai_expectations/great_expectations_ethical_ai_expectations/expectations/expect_table_linear_feature_importances_to_be.py
  great_expectations/core/metric_function_types.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/column_aggregate_metric_provider.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_distinct_values.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_decreasing.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_increasing.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/metric_provider.py
  great_expectations/expectations/metrics/query_metrics/query_column.py
  great_expectations/expectations/metrics/query_metrics/query_column_pair.py
  great_expectations/expectations/metrics/query_metrics/query_multiple_columns.py
  great_expectations/expectations/metrics/query_metrics/query_table.py
  great_expectations/expectations/metrics/query_metrics/query_template_values.py
  great_expectations/expectations/metrics/table_metrics/table_row_count.py
  great_expectations/expectations/registry.py
  great_expectations/rule_based_profiler/expectation_configuration_builder/default_expectation_configuration_builder.py
  great_expectations/rule_based_profiler/expectation_configuration_builder/expectation_configuration_builder.py
  great_expectations/rule_based_profiler/parameter_builder/histogram_single_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/mean_unexpected_map_metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
  great_expectations/self_check/util.py
  pyproject.toml
  tests/conftest.py
  tests/execution_engine/test_pandas_execution_engine.py
  tests/execution_engine/test_sparkdf_execution_engine.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/expectations/metrics/test_core.py
  tests/expectations/metrics/test_map_metric.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_max_to_be_between_custom.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_equal_three.py
Labels: core-team, platform

#6737 [DOCS] Preparation for building api docs
  docs/build_docs
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
  docusaurus.config.js
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/util.py
  src/css/api_docs/basic-modified.scss
Labels: core-team, dx

#6744 [MAINTENANCE] exclude scripts directory from package
  setup.py
Labels: community

#6751 [DOCS] Change prefix reference for tutorial folder/directory
  docs/tutorials/getting_started/tutorial_connect_to_data.md
  docs/tutorials/getting_started/tutorial_create_expectations.md
Labels: community

#6752 [DOCS] Fix line-links in 4th step's 5th and 6th block
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
Labels: community

#6756 [BUGFIX] reformatting `setup.py`
  setup.py
Labels: core-team, dx

#6755 [MAINTENANCE] Force cryptography version installed where snowflake runs to be v38.0.4
  azure-pipelines-docs-integration.yml
  azure-pipelines-expectation-gallery.yml
Labels: core-team, dx

#6743 [MAINTENANCE] ID/PK - Adding semi-colon to SQL Query output
  great_expectations/expectations/metrics/util.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/expectations/metrics/column_map_metrics/test_unexpected_indices_and_query.py
  tests/expectations/metrics/test_map_metric.py
  tests/expectations/metrics/test_metrics_util.py
Labels: core-team, dx

#6716 [MAINTENANCE] ID/PK result_format documentation update
  docs/reference/expectations/result_format.md
  great_expectations/expectations/expectation.py
  tests/integration/docusaurus/reference/core_concepts/result_format.py
  tests/integration/test_script_runner.py
Labels: core-team, dx

#6757 [MAINTENANCE] Consistent use of Metric Name Enum values
  contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/profile_numeric_columns_diff_expectation.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_string_integers_increasing.py
  great_expectations/core/metric_function_types.py
  great_expectations/execution_engine/execution_engine.py
  great_expectations/expectations/metrics/column_map_metrics/column_value_lengths.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_z_score.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/compound_columns_unique.py
  tests/conftest.py
  tests/execution_engine/test_execution_engine.py
  tests/execution_engine/test_sparkdf_execution_engine.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/expectations/metrics/column_map_metrics/test_unexpected_indices_and_query.py
  tests/expectations/metrics/test_core.py
  tests/expectations/metrics/test_map_metric.py
Labels: core-team, platform

#6753 [MAINTENANCE] Fix min version test requirements install on azure async pipeline.
  azure-pipelines.yml
  constraints-test/py37-min-install.txt
  constraints-test/py38-min-install.txt
  constraints-test/py39-min-install.txt
  docker/Dockerfile.tests
Labels: core-team, platform

#6760 [MAINTENANCE] Add Python 3.10 to async Azure pipeline
  azure-pipelines.yml
  tests/core/test_yaml_handler.py
  tests/test_ge_utils.py
Labels: core-team, platform

#6747 [MAINTENANCE] Unset cloud vars when running pytest from a mac
  tests/__init__.py
Labels: core-team, dx

#6732 [DOCS] - fixed code reference in documentation
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
Labels: community

#6733 [CONTRIB] Improve Spark backend support for contrib query based expectations
  contrib/experimental/great_expectations_experimental/expectations/expect_day_sum_to_be_close_to_equivalent_week_day_mean.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_value_frequency_to_meet_threshold.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_slowly_changing_table_to_have_no_gaps.py
  contrib/experimental/great_expectations_experimental/expectations/expect_query_count_with_filter_to_meet_threshold.py
Labels: community

#6734 [CONTRIB] Refactor ExpectColumnValuesToBeHexadecimal expectation to be RegexBased
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_hexadecimal.py
Labels: community

#6725 [CONTRIB] Fix regex based expectations for spark
  assets/scripts/build_gallery.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_arn.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_scientific_notation.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_have_valid_icd10_code_format.py
Labels: community

#6763 [FEATURE] Official Python 3.10 support
  azure-pipelines.yml
  azure/dev-install-matrix.yml
  constraints-test/py310-min-install.txt
  docker/Dockerfile.tests
  docker/README.md
  docs/contributing/contributing_setup.md
  docs/guides/setup/installation/components_local/_check_python_version.mdx
  docs/guides/setup/installation/components_local/_preface.mdx
  setup.py
Labels: core-team, platform

#6768 [MAINTENANCE] Update CheckChanges for dev pipeline
  azure-pipelines-dev.yml
  azure-pipelines-docs-integration.yml
  scripts/check_for_docs_deps_changes.sh
Labels: core-team, dx

#6770 [MAINTENANCE] Update contrib pipeline to track package changes
  azure-pipelines-contrib.yml
Labels: core-team, dx

#6745 [FEATURE] F/great 1313/zep pandas poc
  great_expectations/experimental/datasources/__init__.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/postgres_datasource.py
  great_expectations/experimental/datasources/sources.py
  great_expectations/experimental/datasources/sql_datasource.py
  great_expectations/experimental/datasources/sqlite_datasource.py
  tests/experimental/datasources/test_pandas_datasource.py
  tests/experimental/datasources/test_postgres_datasource.py
Labels: core-team, platform

#6772 [MAINTENANCE] Remove chunk of code in build_gallery.py to skip processing some Expectations
  assets/scripts/build_gallery.py
Labels: core-team, dx

#6740 [FEATURE] Add GX Cloud hyperlink to slack notification
  great_expectations/checkpoint/actions.py
  great_expectations/data_context/cloud_constants.py
  great_expectations/render/renderer/slack_renderer.py
  tests/render/test_SlackRenderer.py
Labels: core-team

#6774 [FEATURE] Get ExpectationSuite, Checkpoint by name
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/configuration_store.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/gx_cloud_store_backend.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
  tests/data_context/store/test_configuration_store.py
Labels: cloud

#6764 [MAINTENANCE] Move `constraints-test` dir within `azure` dir to clean up project root
  azure-pipelines-dev.yml
  azure-pipelines.yml
  azure/constraints-test/py310-min-install.txt
  azure/constraints-test/py37-min-install.txt
  azure/constraints-test/py38-min-install.txt
  azure/constraints-test/py39-min-install.txt
Labels: core-team, platform

#6766 [FEATURE] API docs
  docs/api_docs/classes/great_expectations-data_context-data_context-data_context-DataContext.md
  docs/api_docs/methods/great_expectations-data_context-data_context-data_context-DataContext-create.md
  docs/api_docs/methods/great_expectations-data_context-data_context-data_context-DataContext-test_yaml_config.md
  docs/guides/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config.md
  docs/guides/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config__api_links.mdx
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
  docs/terms/data_context.md
  docs/terms/data_context__api_links.mdx
  great_expectations/core/_docs_decorators.py
  sidebars.js
  static/_redirects
  tests/core/test__docs_decorators.py
Labels: core-team, dx

#6777 [MAINTENANCE] Misc cleanup of `SerializableDataContext`
  great_expectations/data_context/data_context/serializable_data_context.py
  tests/data_context/test_data_context.py
Labels: core-team, platform

#6771 [MAINTENANCE] Removed some 30 type hint violations
  great_expectations/expectations/metrics/metric_provider.py
  great_expectations/expectations/registry.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  pyproject.toml
Labels: core-team, platform

#6781 [MAINTENANCE] Adjust gallery schedule and timeout
  azure-pipelines-expectation-gallery.yml
Labels: core-team, dx

#6754 [MAINTENANCE] type-checking - `metrics/util.py`
  great_expectations/expectations/metrics/util.py
  pyproject.toml
  scripts/check_docstring_coverage.py
Labels: core-team, dx

#6783 [BUGFIX] fix comment stripping when saving a zep configuration
  great_expectations/data_context/data_context/serializable_data_context.py
  tests/experimental/datasources/test_viral_snippets.py
Labels: core-team, platform

#6786 [MAINTENANCE] Update `requirements.txt` to reflect 3.10 support
  requirements.txt
Labels: core-team, platform

#6775 [MAINTENANCE] Enable more backends for some contrib expectations
  contrib/experimental/great_expectations_experimental/expectations/expect_column_skew_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_sum_to_be.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_to_have_no_days_missing.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_hexadecimal.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_arn.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_github_username.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_iata_code.py
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_be_valid_scientific_notation.py
  contrib/experimental/great_expectations_experimental/expectations/expect_day_count_to_be_close_to_equivalent_week_day_mean.py
  contrib/experimental/great_expectations_experimental/expectations/expect_day_sum_to_be_close_to_equivalent_week_day_mean.py
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_sum_values_to_be_equal_to_single_column.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_pair_values_to_have_diff.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_value_frequency_to_meet_threshold.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_values_to_exist_in_second_table_column.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_slowly_changing_table_to_have_no_gaps.py
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_table_row_count_to_be.py
  contrib/experimental/great_expectations_experimental/expectations/expect_query_count_with_filter_to_meet_threshold.py
  contrib/experimental/great_expectations_experimental/expectations/expect_table_checksum_to_equal_other_table.py
  contrib/experimental/great_expectations_experimental/expectations/expect_yesterday_count_compared_to_avg_equivalent_days_of_week.py
  contrib/great_expectations_geospatial_expectations/great_expectations_geospatial_expectations/expectations/expect_column_values_to_be_lat_lon_coordinates_in_range_of_given_point.py
  contrib/great_expectations_geospatial_expectations/great_expectations_geospatial_expectations/expectations/expect_column_values_to_be_valid_geohash.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_be_valid_http_methods.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_be_valid_iana_timezone.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_have_valid_icd10_code_format.py
Labels: core-team, dx

#6788 [MAINTENANCE] Change execution_engine_type from method to property.
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/sql_datasource.py
  tests/experimental/datasources/test_metadatasource.py
Labels: core-team, platform

#6789 [RELEASE] 0.15.43
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#6790 [MAINTENANCE] More backends for expect_yesterday_count_compared_to_avg_equivalent_days_of_week
  contrib/experimental/great_expectations_experimental/expectations/expect_yesterday_count_compared_to_avg_equivalent_days_of_week.py
Labels: core-team, dx

#6791 [MAINTENANCE] Update gallery pipeline to only have one scheduled run per day (early AM)
  azure-pipelines-expectation-gallery.yml
Labels: core-team, dx

#6787 [FEATURE] Add pandas datasource sorter by refactoring into DataAsset
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/sql_datasource.py
  tests/experimental/datasources/great_expectations.yml
  tests/experimental/datasources/test_config.py
  tests/experimental/datasources/test_pandas_datasource.py
  tests/experimental/datasources/test_postgres_datasource.py
  tests/experimental/datasources/test_viral_snippets.py
Labels: core-team, platform

#6776 Convert the validation results to JSON serializable
  great_expectations/data_context/store/validations_store.py
Labels: community

#6797 [MAINTENANCE] Only include relevant diagnostics info in gallery JSON
  assets/scripts/build_gallery.py
  great_expectations/expectations/expectation.py
Labels: core-team, dx

#6784 [MAINTENANCE] Clean up public api report part 1
  scripts/public_api_report.py
Labels: core-team, dx

#6792 [MAINTENANCE] Clean up public api report part 2
  scripts/public_api_report.py
Labels: core-team, dx

#6802 [MAINTENANCE] Shift daily gallery run by 6 hours
  azure-pipelines-expectation-gallery.yml
Labels: core-team, dx

#6801 [MAINTENANCE] Misc docstrings in `AbstractDataContext`
  great_expectations/data_context/data_context/abstract_data_context.py
Labels: core-team, platform

#6799 [DOCS] Link to gh issue #4152 for ruamel.yaml
  requirements.txt
Labels: community

#6793 [MAINTENANCE] Add checkpoint and datadoc integration test for zep pandas datasource.
  tests/experimental/datasources/test_integration_datasource.py
Labels: core-team, platform

#6805 [MAINTENANCE] Use environment variables for expectation gallery data paths
  assets/scripts/AlgoliaScripts/upload_s3_expectation_to_algolia.js
  assets/scripts/AlgoliaScripts/upload_s3_packages_to_algolia.js
  assets/scripts/copy_s3_old_prod_to_prod.sh
  assets/scripts/copy_s3_staging_to_prod.sh
  azure-pipelines-expectation-gallery.yml
  azure-pipelines-manual-staging-json-to-prod.yml
Labels: core-team, dx

#6807 Suppress 2 kl_divergence datasets for bigquery that took 90 minutes to insert
  tests/test_definitions/column_distributional_expectations/expect_column_kl_divergence_to_be_less_than.json
Labels: core-team, dx

#6808 [BUGFIX] Fix missing not operator ~
  great_expectations/expectations/metrics/column_map_metrics/column_values_not_match_regex_list.py
Labels: core-team, dx

#6804 [MAINTENANCE] Improve type hints in ExecutionEngine.resolve_metrics() flow and delete unnecessary checks
  assets/docker/postgresql/docker-compose.yml
  great_expectations/execution_engine/execution_engine.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/metric_provider.py
Labels: core-team, platform

#6809 [MAINTENANCE] Fixes for column_values_to_be_between tests
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between.json
Labels: core-team, dx

#6803 [MAINTENANCE] Clean up public api report part 3
  scripts/public_api_report.py
Labels: core-team, dx

#6785 [DOCS] ExpectationSuite and remove_expectation api docs
  great_expectations/core/expectation_suite.py
Labels: core-team, dx

#6810 [BUGFIX] Implemented lowercase function to check what type of file endswith
  great_expectations/datasource/pandas_datasource.py
  great_expectations/datasource/sparkdf_datasource.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  tests/conftest.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_pandas_execution_engine.py
  tests/datasource/test_new_datasource_with_runtime_data_connector_sparkdf_execution_engine.py
  tests/test_sets/taxi_yellow_tripdata_samples_upcase/yellow_tripdata_sample_2019-01.CSV
Labels: community

#6812 [CONTRIB] Improve contrib schwifty expectations
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_bic_belong_to_country.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_be_valid_bic.py
  contrib/great_expectations_semantic_types_expectations/great_expectations_semantic_types_expectations/expectations/expect_column_values_to_be_valid_iban.py
Labels: community

#6811 [BUGFIX]: expect_day_count_to_be_close_to_equivalent_week_day_mean
  contrib/experimental/great_expectations_experimental/expectations/expect_day_count_to_be_close_to_equivalent_week_day_mean.py
Labels: community

#6819 [MAINTENANCE] Use Enum classes for all metric name suffixes
  great_expectations/core/metric_function_types.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/expectations/core/expect_column_values_to_be_null.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/core/expect_column_values_to_not_be_null.py
  great_expectations/expectations/expectation.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_proportion_of_unique_values.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_standard_deviation.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_non_null.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_null.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/metric_provider.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/domain_builder/map_metric_column_domain_builder.py
  great_expectations/rule_based_profiler/parameter_builder/mean_unexpected_map_metric_multi_batch_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_builder/simple_date_format_string_parameter_builder.py
  tests/actions/test_store_metric_action.py
  tests/execution_engine/test_execution_engine.py
  tests/execution_engine/test_sqlalchemy_execution_engine.py
  tests/expectations/metrics/column_map_metrics/test_unexpected_indices_and_query.py
  tests/expectations/metrics/test_core.py
  tests/expectations/metrics/test_map_metric.py
  tests/expectations/test_run_diagnostics.py
  tests/rule_based_profiler/parameter_builder/test_mean_unexpected_map_metric_multi_batch_parameter_builder.py
Labels: core-team, platform

#6820 [MAINTENANCE] Use shortened_dotted_paths in API docs
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
Labels: core-team, dx

#6821 Update batch request option validation error message
  great_expectations/experimental/datasources/interfaces.py
Labels: core-team, platform

#6822 Add docstring to DataAsset.add_sorters
  great_expectations/experimental/datasources/interfaces.py
Labels: core-team, platform

#6818 [DOCS] Add GitHub PR links to changelogs
  docs/changelog.md
  docs_rtd/changelog.rst
Labels: core-team, platform

#6817 [MAINTENANCE] Misc type cleanup within`checkpoint/` and `validator/`
  great_expectations/checkpoint/configurator.py
  great_expectations/validator/exception_info.py
  pyproject.toml
Labels: core-team, platform

#6825 [DOCS] Update `yarn-snippet-check` to only target specific source code dirs
  docs/scripts/remark-named-snippets/index.js
  docs/scripts/remark-named-snippets/snippet.js
Labels: core-team, platform

#6827 [MAINTENANCE] Update algolia indexing
  .github/workflows/algoliaIndexer.yml
  docusaurus.config.js
Labels: core-team, dx

#6823 [MAINTENANCE] When running our test suite, suppress warnings `result_format` configuration in Expectations and Validators
  pyproject.toml
Labels: core-team, dx

#6830 [MAINTENANCE] ZEP - lower logging levels from `INFO` -> `DEBUG`
  great_expectations/experimental/datasources/metadatasource.py
  great_expectations/experimental/datasources/sources.py
  great_expectations/experimental/datasources/type_lookup.py
Labels: core-team, platform

#6829 [DOCS] Adding docstring for ExpectationSuite.add_expectation
  great_expectations/core/expectation_suite.py
Labels: core-team

#6832 [BUGFIX] Pandas ID/PK query was causing DataDocs error
  great_expectations/expectations/expectation.py
  tests/render/test_render_ValidationResultsTableContentBlockRenderer.py
Labels: core-team, dx

#6831 [MAINTENANCE] Use shortened dotted paths in api docs
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
  scripts/public_api_report.py
  tests/scripts/test_public_api_report.py
Labels: core-team, dx

#6835 [DOCS] DOC-394: Fix broken redirect links
  static/_redirects
Labels: devrel

#6816 [MAINTENANCE] Remove outdated refs to Superconductive
  great_expectations/data_context/store/gx_cloud_store_backend.py
Labels: core-team, platform

#6839 [MAINTENANCE] Update `teams.yml`
  .github/teams.yml
Labels: core-team, platform

#6836 [MAINTENANCE] invoke 2.0 and `schema` task (for zep types)
  great_expectations/experimental/datasources/type_lookup.py
  reqs/requirements-dev-contrib.txt
  tasks.py
Labels: core-team, platform

#6838 [RELEASE] 0.15.44
  docs/changelog.md
  docs/tutorials/getting_started/tutorial_version_snippet.mdx
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core-team, platform

#6842 [MAINTENANCE] Build hierarchy in sidebars for API docs
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
  docs/sphinx_api_docs_source/conf.py
Labels: core-team, dx

#6843 [MAINTENANCE] Change public_api task name to avoid confusion
  docs/sphinx_api_docs_source/tasks.py
Labels: core-team, dx

#6845 [MAINTENANCE] Add the fragment back to internal references
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
Labels: core-team, dx

#6846 [MAINTENANCE] Clean up public_api excludes
  scripts/public_api_report.py
Labels: core-team, dx

#6848 [MAINTENANCE] Fix the error message for invalid batch request options
  great_expectations/experimental/datasources/interfaces.py
Labels: core-team, platform

#6765 [FEATURE] Experimental datasources `batch.head()`
  great_expectations/core/batch_manager.py
  great_expectations/expectations/metrics/table_metrics/table_head.py
  great_expectations/experimental/datasources/interfaces.py
  great_expectations/experimental/datasources/pandas_datasource.py
  great_expectations/experimental/datasources/sql_datasource.py
  great_expectations/render/renderer/inline_renderer.py
  great_expectations/validator/validator.py
  tests/experimental/datasources/test_integration_datasource.py
Labels: core-team, platform

#6841 [DOCS] Adding docstring for `Checkpoint.self_check()`
  great_expectations/checkpoint/checkpoint.py
Labels: core-team, dx

#6826 [MAINTENANCE] Standardize Store CRUD
  great_expectations/data_context/config_validator/yaml_config_validator.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/file_data_context.py
  great_expectations/data_context/store/store.py
  great_expectations/data_context/types/base.py
  great_expectations/data_context/util.py
  tests/data_context/migrator/conftest.py
  tests/data_context/store/test_store.py
  tests/data_context/test_data_context_state_management.py
  tests/data_context/test_data_context_utils.py
  tests/test_utils.py
Labels: core-team, platform

#6851 [DOCS] `AbstractDataContext.add_store` docstring
  great_expectations/data_context/data_context/abstract_data_context.py
Labels: core-team, platform

#6856 [DOCS] Doc Strings for ExpectationSuite Display Methods
  great_expectations/core/expectation_suite.py
Labels: core-team, platform

#6862 [DOCS] `DataAssistantResult.get_expectation_suite()` docstring
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
Labels: core-team, dx

#6867 [MAINTENANCE] Fix scripts not found error in invoke
  docs/sphinx_api_docs_source/tasks.py
  tasks.py
Labels: core-team, dx

#6850 Fix argument name typo
  great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py
Labels: community

#6866 [DOCS] Misc docstrings around `DataAssistant`
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
Labels: core-team, platform

#6868 [DOCS] enable running `invoke docstrings` on select modules
  scripts/check_public_api_docstrings.py
  tasks.py
Labels: core-team, platform

#6870 more clearly specifies range of supported python versions
  docs/guides/setup/installation/components_local/_preface.mdx
  docs/tutorials/getting_started/tutorial_setup.md
Labels: cloud

#6857 add validate_configuration docstring
  great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py
Labels: cloud

#6855 [DOCS] Adds docstring for expect_column_distinct_values_to_contain_set
  great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py
  great_expectations/expectations/core/expect_column_median_to_be_between.py
  great_expectations/expectations/core/expect_column_min_to_be_between.py
  great_expectations/expectations/core/expect_column_most_common_value_to_be_in_set.py
  great_expectations/expectations/core/expect_column_pair_values_a_to_be_greater_than_b.py
  great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py
  great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py
  great_expectations/expectations/core/expect_column_values_to_match_regex.py
  great_expectations/expectations/core/expect_column_values_to_match_strftime_format.py
  great_expectations/expectations/core/expect_column_values_to_not_match_regex_list.py
Labels: devrel

#6859 docstring for expect_column_values_to_not_be_null#validate_configuration
  great_expectations/expectations/core/expect_column_values_to_not_be_null.py
Labels: cloud

#6872 [DOCS] Documentation Strings for Metric Domain Types and Metric Function Types
  great_expectations/core/metric_domain_types.py
  great_expectations/core/metric_function_types.py
Labels: core-team, platform

#6837 [MAINTENANCE] Standardize project config CRUD
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/types/base.py
  tests/data_context/test_data_context_state_management.py
Labels: core-team, platform

#6871 updated docstring on validate configuration
  great_expectations/expectations/core/expect_column_values_to_not_match_regex.py
Labels: cloud

#6903 [MAINTENANCE] Exclude unit tests from `comprehensive` stage of `dev` CI
  azure-pipelines-dev.yml
Labels: core-team, platform

#6778 [MAINTENANCE] Refactor `file_relative_path` util
  great_expectations/data_context/util.py
  tests/render/test_column_section_renderer.py
  tests/render/test_data_documentation_site_builder.py
  tests/render/test_default_jinja_view.py
  tests/render/test_render.py
  tests/render/test_render_BulletListContentBlock.py
Labels: core-team, platform

#6888 [MAINTENANCE] switch to `ruff` linter
  .pre-commit-config.yaml
  README.md
  azure-pipelines-contrib.yml
  azure-pipelines-dev.yml
  azure-pipelines.yml
  contrib/cli/requirements.txt
  docs/contributing/style_guides/code_style.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_pair_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_multicolumn_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_query_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_regex_based_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_set_based_column_map_expectations.md
  docs/guides/expectations/creating_custom_expectations/how_to_create_custom_table_expectations.md
  docs_rtd/contributing/style_guide.rst
  great_expectations/cli/python_subprocess.py
  great_expectations/cli/v012/python_subprocess.py
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/data_asset/data_asset.py
  great_expectations/data_context/types/base.py
  great_expectations/render/renderer_configuration.py
  great_expectations/rule_based_profiler/parameter_container.py
  pyproject.toml
  reqs/requirements-dev-contrib.txt
  setup.cfg
  tasks.py
Labels: docs, core-team, platform

#6906 [MAINTENANCE] Use docusaurus style code block in api docs
  docs/sphinx_api_docs_source/README.md
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
  docs/sphinx_api_docs_source/conf.py
  src/css/api_docs/api_docs.scss
Labels: core-team, dx

#6889 [MAINTENANCE] metrics linting
  great_expectations/expectations/metrics/column_aggregate_metric.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_value_counts.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_between.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_json_parseable.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_non_null.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_null.py
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_equal.py
  great_expectations/expectations/metrics/column_pair_map_metrics/column_pair_values_greater.py
  great_expectations/expectations/metrics/map_metric.py
  great_expectations/expectations/metrics/map_metric_provider.py
  great_expectations/expectations/metrics/multicolumn_map_metrics/select_column_values_unique_within_record.py
  great_expectations/expectations/metrics/table_metric.py
  great_expectations/expectations/metrics/table_metrics/table_head.py
  great_expectations/expectations/metrics/util.py
  pyproject.toml
Labels: core-team, platform

#6795 [MAINTENANCE] Add exception message to `RenderedAtomicContent` failure renderer
  great_expectations/expectations/expectation.py
  great_expectations/render/components.py
  great_expectations/render/renderer/inline_renderer.py
  tests/data_context/test_data_context.py
  tests/render/test_inline_renderer.py
Labels: core-team, platform

#6881 [MAINTENANCE] Remove CloudNotificationAction
  great_expectations/checkpoint/__init__.py
  great_expectations/checkpoint/actions.py
  great_expectations/checkpoint/util.py
  great_expectations/validation_operators/__init__.py
  tests/actions/test_core_actions.py
Labels: core-team, dx

#6884 [DOCS] added docstrings for the public API
  great_expectations/expectations/core/expect_column_pair_values_to_be_equal.py
  great_expectations/expectations/core/expect_column_pair_values_to_be_in_set.py
  great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
  great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py
  great_expectations/expectations/core/expect_column_stdev_to_be_between.py
  great_expectations/expectations/core/expect_column_sum_to_be_between.py
  great_expectations/expectations/core/expect_column_to_exist.py
  great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py
  great_expectations/expectations/core/expect_column_value_lengths_to_equal.py
Labels: community

#6913 [MAINTENANCE] Use ruff linter for docstring linting
  great_expectations/core/usage_statistics/package_dependencies.py
  pyproject.toml
  reqs/requirements-dev-lite.txt
  scripts/check_public_api_docstrings.py
Labels: core-team, dx

#6897 [DOCS] Add public API docstring for `expect_column_values_to_be_unique` `validate_configuration`
  great_expectations/expectations/core/expect_column_values_to_be_unique.py
Labels: core-team, platform

#6852 [DOCS] Miscellaneous docstrings for `DataContext` and utils
  great_expectations/cli/toolkit.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/base_data_context.py
  great_expectations/data_context/migrator/configuration_bundle.py
  great_expectations/render/util.py
Labels: core-team, platform

#6896 [DOCS] Add public API docstring for `expect_column_values_to_be_of_type` `validate_configuration`
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
Labels: core-team, platform

#6917 [BUGFIX] Fix issues rendering code blocks in API docs
  docs/sphinx_api_docs_source/README.md
  docs/sphinx_api_docs_source/build_sphinx_api_docs.py
Labels: core-team, dx

#6919 [DOCS] Exclude DataAssistantRunner.run()
  scripts/public_api_report.py
Labels: core-team, dx

#6879 [DOCS] StoreValidationResultAction, StoreEvaluationParametersAction and StoreMetricsAction api docs
  great_expectations/checkpoint/actions.py
Labels: core-team
