Repository great-expectations/great_expectations, pull requests merged in 2023-06, with the labels that each got.

#8040 [BUGFIX] Remove perpetually failing test -- in preparation for release.
  tests/data_context/cloud_data_context/test_datasource_crud.py
Labels: dx, core

#8044 [BUGFIX] meta_notes rendered inline can fail schema validation for a valid string-only configuration
  great_expectations/render/components.py
  great_expectations/render/renderer_configuration.py
  tests/render/test_inline_renderer.py
Labels: core

#8032 [BUGFIX] Ensure That DataFrame for Fluent Datasource Pandas/Spark DataFrame Data Assets is specified only in one API method
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/pandas_datasource.pyi
  great_expectations/datasource/fluent/spark_datasource.py
  tests/checkpoint/conftest.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/conftest.py
  tests/data_context/test_data_context_datasources.py
  tests/datasource/fluent/integration/test_integration_datasource.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/datasource/fluent/test_spark_datasource.py
Labels: dx, core

#8035 [DOCS] Cloud - Getting started uses Fluent Datasources
  docs/docusaurus/docs/gx_cloud/tutorials/getting_started/getting_started_with_gx_cloud.md
Labels: core

#8046 [FEATURE] Update mySQL docker compose to specify platform
  CONTRIBUTING_CODE.md
  assets/docker/mysql/docker-compose.yml
Labels: core

#8049 [RELEASE] 0.16.15
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: dx, core

#8054 [DOCS] Update Links in How to use auto-initializing Expectations
  docs/docusaurus/docs/guides/expectations/how_to_use_auto_initializing_expectations.md
Labels: devrel

#8052 [DOCS] Update How to create Expectations Interactively in Python
  docs/docusaurus/docs/guides/expectations/how_to_create_and_edit_expectations_with_instant_feedback_from_a_sample_batch_of_data.md
  tests/integration/docusaurus/validation/validator/how_to_create_and_edit_expectations_with_instant_feedback_fluent.py
Labels: devrel

#8059 [MAINTENANCE] Minor stylistic clean up of "DataAssistant.build_metric_multi_batch_parameter_builder()" method usage
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
Labels: dx, core

#8024 [MAINTENANCE] type-checking `core/batch.py`
  great_expectations/checkpoint/util.py
  great_expectations/core/batch.py
  great_expectations/core/batch_manager.py
  great_expectations/datasource/data_connector/data_connector.py
  great_expectations/datasource/data_connector/runtime_data_connector.py
  great_expectations/execution_engine/sparkdf_execution_engine.py
  great_expectations/profile/user_configurable_profiler.py
  great_expectations/self_check/util.py
  pyproject.toml
Labels: dx, core

#8061 [MAINTENANCE] Improve code elegance and fix informational string
  great_expectations/rule_based_profiler/helpers/simple_semantic_type_filter.py
Labels: dx, core

#8047 [FEATURE] Update GX Cloud on job status
  great_expectations/agent/actions/agent_action.py
  great_expectations/agent/actions/run_onboarding_data_assistant.py
  great_expectations/agent/agent.py
  great_expectations/agent/models.py
  tests/agent/actions/test_run_onboarding_assistant_action.py
  tests/agent/test_agent.py
Labels: core

#8064 [MAINTENANCE] Misc refactor of `Store` CRUD
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  great_expectations/data_context/store/_store_backend.py
  great_expectations/data_context/store/expectations_store.py
  great_expectations/data_context/store/gx_cloud_store_backend.py
  great_expectations/data_context/store/profiler_store.py
  great_expectations/data_context/store/store.py
Labels: core

#7931 [BUGFIX] Set SQLALCHEMY_WARN_20 in Dockerfile
  ci/azure-pipelines.yml
  docker/Dockerfile.tests
Labels: dx, core

#8057 [FEATURE] DX-441 put how_to_connect_to_in_memory_data_using_pandas un…
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/in_memory/how_to_connect_to_in_memory_data_using_pandas.md
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_in_memory_data_using_pandas.py
  tests/integration/test_script_runner.py
Labels: core

#8065 [MAINTENANCE] Fix pandas model schema differences across python versions
  great_expectations/datasource/fluent/dynamic_pandas.py
  great_expectations/datasource/fluent/schemas/PandasAzureBlobStorageDatasource/CSVAsset.json
  great_expectations/datasource/fluent/schemas/PandasAzureBlobStorageDatasource/HTMLAsset.json
  great_expectations/datasource/fluent/schemas/PandasAzureBlobStorageDatasource/JSONAsset.json
  great_expectations/datasource/fluent/schemas/PandasDBFSDatasource/CSVAsset.json
  great_expectations/datasource/fluent/schemas/PandasDBFSDatasource/HTMLAsset.json
  great_expectations/datasource/fluent/schemas/PandasDBFSDatasource/JSONAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/CSVAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/HTMLAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/JSONAsset.json
  great_expectations/datasource/fluent/schemas/PandasFilesystemDatasource/CSVAsset.json
  great_expectations/datasource/fluent/schemas/PandasFilesystemDatasource/HTMLAsset.json
  great_expectations/datasource/fluent/schemas/PandasFilesystemDatasource/JSONAsset.json
  great_expectations/datasource/fluent/schemas/PandasGoogleCloudStorageDatasource/CSVAsset.json
  great_expectations/datasource/fluent/schemas/PandasGoogleCloudStorageDatasource/HTMLAsset.json
  great_expectations/datasource/fluent/schemas/PandasGoogleCloudStorageDatasource/JSONAsset.json
  great_expectations/datasource/fluent/schemas/PandasS3Datasource/CSVAsset.json
  great_expectations/datasource/fluent/schemas/PandasS3Datasource/HTMLAsset.json
  great_expectations/datasource/fluent/schemas/PandasS3Datasource/JSONAsset.json
Labels: core

#8062 [BUGFIX] Ensure CloudDataContext Add Checkpoint flow returns Checkpoint with cloud-updated values
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/checkpoint_store.py
  pyproject.toml
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
Labels: bug, core

#8066 [BUGFIX] Erroneous Code Duplication and Lack of Type Hints in Expectation Parent Class
  great_expectations/expectations/expectation.py
Labels: dx, core

#8069 [DOCS] Add guidance for "DataFrameAsset.build_batch_request()" in "https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/in_memory/how_to_connect_to_in_memory_data_using_pandas".
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/batch_requests/how_to_request_data_from_a_data_asset.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/in_memory/how_to_connect_to_in_memory_data_using_pandas.md
  docs/docusaurus/docs/terms/evaluation_parameter.md
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/get_existing_data_asset_from_existing_datasource_pandas_filesystem_example.py
  tests/integration/docusaurus/connecting_to_your_data/fluent_datasources/how_to_connect_to_in_memory_data_using_pandas.py
Labels: dx, core

#8068 [DOCS] Update set_based_column_map_expectation_template.py
  examples/expectations/set_based_column_map_expectation_template.py
Labels: devrel

#8072 [MAINTENANCE] Updating CLI messages to point to new docs
  great_expectations/cli/cli_messages.py
Labels: core

#8073 [MAINTENANCE] Update GitHub templates for issues/PRs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: core

#8075 [DOCS] Remove mention of CLI in evaluation_parameters terminology page.
  docs/docusaurus/docs/terms/evaluation_parameter.md
Labels: dx, core

#8074 [MAINTENANCE] Update default action list in `Checkpoint` based on user environment
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/types/base.py
  tests/checkpoint/test_checkpoint.py
  tests/checkpoint/test_checkpoint_with_fluent_datasources.py
  tests/cli/test_checkpoint.py
  tests/core/test_serialization.py
  tests/data_context/migrator/conftest.py
  tests/data_context/store/test_gx_cloud_store_backend.py
  tests/data_context/test_data_context.py
  tests/data_context/test_data_context_state_management.py
Labels: core

#8077 [MAINTENANCE] Ruff `0.0.271` update
  .pre-commit-config.yaml
  contrib/cli/requirements.txt
  great_expectations/cli/datasource.py
  great_expectations/cli/upgrade_helpers/upgrade_helper_v13.py
  great_expectations/core/batch.py
  great_expectations/core/expectation_configuration.py
  great_expectations/core/util.py
  great_expectations/data_context/config_validator/yaml_config_validator.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/store/configuration_store.py
  great_expectations/datasource/data_connector/batch_filter.py
  great_expectations/datasource/data_connector/data_connector.py
  great_expectations/datasource/fluent/batch_request.py
  great_expectations/datasource/fluent/dynamic_pandas.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/sources.py
  great_expectations/datasource/fluent/spark_datasource.py
  great_expectations/datasource/fluent/type_lookup.py
  great_expectations/execution_engine/pandas_execution_engine.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_histogram.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py
  great_expectations/expectations/metrics/map_metric_provider/map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/meta_metric_provider.py
  great_expectations/expectations/metrics/util.py
  great_expectations/rule_based_profiler/config/base.py
  great_expectations/rule_based_profiler/estimators/quantiles_numeric_range_estimator.py
  great_expectations/rule_based_profiler/helpers/simple_semantic_type_filter.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/util.py
  great_expectations/validator/metrics_calculator.py
  pyproject.toml
  reqs/requirements-dev-contrib.txt
  tests/checkpoint/test_checkpoint_result_format.py
  tests/conftest.py
  tests/core/test_serialization.py
  tests/data_context/datasource/test_data_context_datasource_runtime_data_connector_pandas_execution_engine.py
  tests/datasource/fluent/integration/test_integration_datasource.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/datasource/fluent/test_postgres_datasource.py
  tests/datasource/fluent/test_spark_datasource.py
  tests/datasource/test_datasource_anonymizer.py
  tests/render/renderer/test_checkpoint_new_notebook_renderer.py
  tests/render/renderer/test_datasource_new_notebook_renderer.py
  tests/render/renderer/v3/test_suite_edit_notebook_renderer.py
  tests/test_ge_utils.py
  tests/test_packaging.py
  tests/validator/test_metrics_calculator.py
Labels: core

#8079 [MAINTENANCE] Update PR template to reference `invoke` for linting
  .github/pull_request_template.md
Labels: core

#8083 [BUGFIX] Fix broken Cloud tests around `Checkpoint`
  tests/data_context/conftest.py
Labels: core

#8082 [MAINTENANCE] Delete `LegacyCheckpoint`
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  great_expectations/checkpoint/__init__.py
  great_expectations/checkpoint/checkpoint.py
  great_expectations/cli/checkpoint.py
  great_expectations/cli/toolkit.py
  great_expectations/cli/upgrade_helpers/upgrade_helper_v13.py
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/types/base.py
  great_expectations/render/renderer/suite_scaffold_notebook_renderer.py
  great_expectations/validation_operators/validation_operators.py
  tests/checkpoint/test_checkpoint.py
  tests/checkpoint/test_simple_checkpoint.py
  tests/checkpoint/test_simple_checkpoint_with_fluent_datasources.py
  tests/cli/upgrade_helpers/test_upgrade_helper.py
  tests/data_context/fixtures/contexts/my_checkpoint.yml
  tests/data_context/store/test_checkpoint_store.py
  tests/data_context/test_data_context.py
  tests/integration/test_definitions/spark/integration_tests.py
  tests/integration/test_script_runner.py
  tests/render/renderer/test_suite_scaffold_notebook_renderer.py
Labels: core

#7963 [BUGFIX] fix issue-7954
  great_expectations/render/renderer/site_builder.py
Labels: community

#8060 [MAINTENANCE] Add public_api to read_parquet
  docs/sphinx_api_docs_source/public_api_missing_threshold.py
  great_expectations/datasource/fluent/pandas_datasource.py
Labels: core

#8031 [MAINTENANCE] Postgres starter reference environment
  examples/reference_environments/README.md
  examples/reference_environments/__init__.py
  examples/reference_environments/postgres/README.md
  examples/reference_environments/postgres/compose.yaml
  examples/reference_environments/postgres/db_dump.sql
  examples/reference_environments/postgres/jupyter.Dockerfile
  examples/reference_environments/postgres/postgres.Dockerfile
  examples/reference_environments/postgres/postgres_example.ipynb
  great_expectations/cli/example.py
Labels: dx, core

#8084 [BUGFIX] Fix Update Checkpoint for Cloud
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  great_expectations/data_context/store/checkpoint_store.py
  great_expectations/data_context/store/gx_cloud_store_backend.py
  tests/data_context/cloud_data_context/test_checkpoint_crud.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
Labels: bug, core

#8087 [BUGFIX] Mock correct method in test
  tests/data_context/cloud_data_context/test_include_rendered_content.py
Labels: bug, core

#8037 [MAINTENANCE] Add tests for file and Cloud-backed quickstart workflows
  great_expectations/data_context/store/gx_cloud_store_backend.py
  tests/datasource/fluent/_fake_cloud_api.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_contexts.py
  tests/datasource/fluent/test_viral_snippets.py
Labels: core

#8036 [DOCS] Update Quickstart guide to be Cloud-compatible
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
  tests/integration/docusaurus/tutorials/quickstart/quickstart.py
Labels: core

#8090 [MAINTENANCE] Check if PR is a fork in some docs_integration stages
  ci/azure-pipelines-docs-integration.yml
Labels: dx, core

#8092 [FEATURE] Agent prints stack trace on error
  great_expectations/agent/agent.py
Labels: core

#8067 [MAINTENANCE] Update how_to_host_and_share_data_docs_on_gcs
  tests/integration/docusaurus/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.py
Labels: core

#8091 [DOCS] Temporarily hardcode quickstart snippet due to substitution error
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
Labels: core

#8089 [MAINTENANCE] Add persistent OSS user identifier to anonymized usage statistics payloads
  great_expectations/core/usage_statistics/payload_builder.py
  great_expectations/core/usage_statistics/schemas.py
  great_expectations/core/usage_statistics/usage_statistics.py
  great_expectations/core/usage_statistics/usage_statistics_record_schema.json
  great_expectations/data_context/data_context/abstract_data_context.py
  tests/conftest.py
  tests/core/usage_statistics/test_payload_builder.py
  tests/core/usage_statistics/test_schema_validation.py
  tests/core/usage_statistics/test_usage_statistics_handler_methods.py
  tests/expectations/test_expectation_arguments.py
  tests/integration/usage_statistics/example_events/cloud_migrate_example_events.py
  tests/integration/usage_statistics/example_events/data_context_run_validation_operator.py
  tests/integration/usage_statistics/test_usage_statistics_messages.py
  tests/integration/usage_statistics/usage_stats_event_examples.py
Labels: core

#8009 [DOCS] Update prefect gx tutorial
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_prefect.md
  docs/docusaurus/docs/images/artifact.png
  docs/docusaurus/docs/images/flow_run.png
Labels: community

#7719 [FEATURE] Clickhouse Integration
  assets/docker/clickhouse/docker-compose.yml
  assets/docker/clickhouse/info.csv
  great_expectations/cli/datasource.py
  great_expectations/core/profiler_types_mapping.py
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/execution_engine/sqlalchemy_dialect.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  great_expectations/expectations/metrics/util.py
  great_expectations/self_check/util.py
  great_expectations/util.py
  pyproject.toml
  reqs/requirements-dev-clickhouse.txt
  reqs/requirements-dev-sqlalchemy.txt
  setup.py
  tests/cli/test_datasource_sqlite.py
  tests/conftest.py
  tests/expectations/test_util.py
  tests/profile/test_jsonschema_profiler.py
  tests/test_packaging.py
  tests/test_the_utils_in_test_utils.py
Labels: community

#8093 [MAINTENANCE] Update MSSQL docker container and instructions for Apple Silicon Macs
  .gitignore
  CONTRIBUTING_CODE.md
  assets/docker/mssql/README.md
  assets/docker/mssql/docker-compose.yml
Labels: core

#7633 [FEATURE] Pandas 2.0.0 and Sqlalchemy 2.0.0 compatibility
  assets/docker/mysql-mac-m1/docker-compose.yml
  ci/azure-pipelines-sqlalchemy-compatibility.yml
  great_expectations/compatibility/sqlalchemy_and_pandas.py
  great_expectations/compatibility/sqlalchemy_compatibility_wrappers.py
  great_expectations/core/usage_statistics/package_dependencies.py
  great_expectations/datasource/fluent/interfaces.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/metrics/map_metric_provider/map_condition_auxilliary_methods.py
  great_expectations/expectations/metrics/table_metrics/table_head.py
  great_expectations/expectations/metrics/util.py
  pyproject.toml
  reqs/requirements-dev-lite.txt
  reqs/requirements-dev-teradata.txt
  requirements.txt
  tests/datasource/test_new_datasource_with_runtime_data_connector_sql_execution_engine.py
  tests/datasource/test_simple_sqlalchemy_datasource.py
  tests/execution_engine/split_and_sample/test_sqlalchemy_execution_engine_splitting.py
  tests/profile/test_user_configurable_profiler_v3_batch_request.py
  tests/test_packaging.py
Labels: dx, core

#8105 [MAINTENANCE] Type hint cleanup in usage statistics
  great_expectations/core/usage_statistics/usage_statistics.py
  pyproject.toml
Labels: core

#8101 [FEATURE] Better pandas query
  great_expectations/expectations/metrics/map_metric_provider/map_condition_auxilliary_methods.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/expectations/metrics/column_map_metrics/test_unexpected_indices_and_query.py
  tests/expectations/metrics/test_map_metric.py
Labels: core

#8104 [MAINTENANCE] Remove the mysql-mac-m1 and starburst directories from assets/docker
  assets/docker/mysql-mac-m1/conf.d/docker.cnf
  assets/docker/mysql-mac-m1/conf.d/mysql.cnf
  assets/docker/mysql-mac-m1/docker-compose.yml
  assets/docker/starburst/docker-compose.yml
Labels: dx, core

#8110 [MAINTENANCE] Typing Data Assistant Result
  great_expectations/rule_based_profiler/data_assistant_result/data_assistant_result.py
  great_expectations/rule_based_profiler/data_assistant_result/plot_components.py
  pyproject.toml
Labels: core

#8109 [MAINTENANCE] Ensure that new usage statistics schema changes are backwards compatible
  great_expectations/core/usage_statistics/schemas.py
  great_expectations/core/usage_statistics/usage_statistics_record_schema.json
  tests/integration/usage_statistics/test_usage_statistics_messages.py
Labels: core

#8019 [MAINTENANCE] Cleanup generate_expectation_tests
  great_expectations/self_check/util.py
  tests/expectations/test_util.py
Labels: dx, core

#8108 [BUGFIX] Fix conditional for pyspark compatibility
  great_expectations/core/batch.py
Labels: dx, core

#8017 [MAINTENANCE] Update build_in_memory_runtime_context to accept which datasources to include
  great_expectations/self_check/util.py
  great_expectations/util.py
  tests/expectations/core/test_expect_column_value_z_scores_to_be_less_than.py
  tests/expectations/core/test_expect_column_values_to_be_in_type_list.py
  tests/expectations/core/test_expect_queried_column_value_frequency_to_meet_threshold.py
  tests/expectations/core/test_expect_queried_table_row_count_to_be.py
Labels: dx, core

#8111 [BUGFIX] respect result format bool only for validators and checkpoints
  great_expectations/expectations/expectation.py
  tests/checkpoint/test_checkpoint_result_format.py
  tests/validator/test_validator.py
Labels: bug, core

#8115 [BUGFIX] Robust Handling Of Column Types And Empty DataFrames For DataBricks/Spark Environment
  great_expectations/expectations/metrics/table_metrics/table_column_types.py
  great_expectations/expectations/metrics/table_metrics/table_columns.py
  great_expectations/expectations/metrics/table_metrics/table_head.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
  great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
  great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py
  great_expectations/rule_based_profiler/domain_builder/map_metric_column_domain_builder.py
  great_expectations/rule_based_profiler/helpers/util.py
  great_expectations/rule_based_profiler/parameter_builder/regex_pattern_string_parameter_builder.py
  great_expectations/rule_based_profiler/parameter_container.py
Labels: dx, core

#8119 [FEATURE] Add Pandas FWFAsset - fixed width file
  great_expectations/datasource/fluent/dynamic_pandas.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.pyi
  great_expectations/datasource/fluent/pandas_datasource.py
  great_expectations/datasource/fluent/pandas_datasource.pyi
  great_expectations/datasource/fluent/pandas_file_path_datasource.py
  great_expectations/datasource/fluent/pandas_file_path_datasource.pyi
  great_expectations/datasource/fluent/pandas_filesystem_datasource.pyi
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.pyi
  great_expectations/datasource/fluent/pandas_s3_datasource.pyi
  great_expectations/datasource/fluent/schemas/PandasAzureBlobStorageDatasource/FWFAsset.json
  great_expectations/datasource/fluent/schemas/PandasDBFSDatasource/FWFAsset.json
  great_expectations/datasource/fluent/schemas/PandasDatasource/FWFAsset.json
  great_expectations/datasource/fluent/schemas/PandasFilesystemDatasource/FWFAsset.json
  great_expectations/datasource/fluent/schemas/PandasGoogleCloudStorageDatasource/FWFAsset.json
  great_expectations/datasource/fluent/schemas/PandasS3Datasource/FWFAsset.json
  tasks.py
  tests/datasource/fluent/test_pandas_datasource.py
  tests/datasource/fluent/test_pandas_filesystem_datasource.py
Labels: core

#8076 [MAINTENANCE] Misc/docs integration uncommented
  ci/azure-pipelines-docs-integration.yml
  great_expectations/compatibility/sqlalchemy.py
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_gcs_data_connector.py
  pyproject.toml
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/pandas/configured_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/cloud/gcs/pandas/configured_yaml_example.py
  tests/integration/docusaurus/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_gcs.py
  tests/integration/docusaurus/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_gcs.py
  tests/integration/docusaurus/validation/validator/how_to_create_and_edit_expectations_with_instant_feedback_block_config.py
  tests/integration/docusaurus/validation/validator/how_to_create_and_edit_expectations_with_instant_feedback_fluent.py
  tests/integration/test_definitions/abs/integration_tests.py
  tests/integration/test_definitions/bigquery/integration_tests.py
  tests/integration/test_definitions/gcs/integration_tests.py
  tests/integration/test_definitions/multiple_backend/integration_tests.py
  tests/integration/test_definitions/spark/integration_tests.py
  tests/integration/test_script_runner.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/MultiBatchExample_InferredAssetSQLExample.ipynb
  tests/test_utils.py
Labels: dx, core

#7816 [DOCS] Remove examples of specifying a test_backends list of dicts
  contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_thai.py
  contrib/experimental/great_expectations_experimental/expectations/expect_day_count_to_be_close_to_equivalent_week_day_mean.py
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_sum_values_to_be_between.py
  contrib/experimental/great_expectations_experimental/expectations/expect_multicolumn_values_not_to_be_all_null.py
  contrib/time_series_expectations/time_series_expectations/expectations/expect_batch_row_count_to_match_prophet_date_model.py
  contrib/time_series_expectations/time_series_expectations/expectations/expect_column_max_to_match_prophet_date_model.py
  contrib/time_series_expectations/time_series_expectations/expectations/expect_column_pair_values_to_match_prophet_date_model.py
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_batch_expectations.md
  docs/docusaurus/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_example_cases_for_an_expectation.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_spark_support_for_an_expectation.md
  docs/docusaurus/docs/guides/expectations/features_custom_expectations/how_to_add_sqlalchemy_support_for_an_expectation.md
  great_expectations/self_check/util.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_max_to_be_between_custom.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_be_in_solfege_scale_set.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_values_to_only_contain_vowels.py
  tests/integration/docusaurus/expectations/creating_custom_expectations/expect_multicolumn_values_to_be_multiples_of_three.py
Labels: dx, core

#8122 [MAINTENANCE] Fixes for test_dependency_versions pipeline
  ci/constraints-test/py310-min-install.txt
  ci/constraints-test/py38-min-install.txt
  ci/constraints-test/py39-min-install.txt
  great_expectations/compatibility/sqlalchemy_compatibility_wrappers.py
Labels: dx, core

#8128 [BUGFIX] Patch bad mock in GCS test
  tests/data_context/store/test_store_backends.py
Labels: core

#8129 [RELEASE] 0.17.0
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8130 [MAINTENANCE] update location of link in data docs footer
  great_expectations/render/view/templates/cloud-footer.j2
Labels: devrel

#8127 [MAINTENANCE] invoke show-automerges
  tasks.py
Labels: core

#8123 [MAINTENANCE] Lint `assets` dir
  .pre-commit-config.yaml
  assets/benchmark/benchmark.py
  assets/partners/anthonydb/just_connect.py
  assets/partners/anthonydb/run.py
  assets/partners/rubenshift/run.py
  assets/scripts/build_gallery.py
  assets/scripts/build_package_gallery.py
  assets/scripts/gx_cloud/experimental/onboarding_script.py
  great_expectations/datasource/fluent/sql_datasource.py
  great_expectations/datasource/fluent/sqlite_datasource.py
  pyproject.toml
  tasks.py
  tests/test_deprecation.py
Labels: core

#8125 [DOCS] Enable docs versioning for 0.16.16
  ci/azure-pipelines-docs.yml
  docs/docusaurus/README.md
  docs/docusaurus/docusaurus.config.js
  docs/prepare_prior_versions.py
  docs/prepare_to_build_docs.sh
  tests/docs/test_prepare_prior_versions.py
Labels: dx, core

#8132 [MAINTENANCE] test/integration linting
  .pre-commit-config.yaml
  pyproject.toml
  tests/conftest.py
  tests/integration/db/bigquery.py
  tests/integration/db/taxi_data_utils.py
  tests/integration/db/test_sql_data_sampling.py
  tests/integration/fixtures/split_and_sample_data/splitter_test_cases_and_fixtures.py
  tests/integration/profiling/rule_based_profiler/test_profiler_user_workflows.py
  tests/integration/profiling/rule_based_profiler/test_rule_based_profiler.py
  tests/integration/spark/test_spark_config.py
  tests/integration/test_script_runner.py
  tests/integration/usage_statistics/test_usage_statistics_messages.py
Labels: core

#8106 [MAINTENANCE] minimal Anonymizer type-checking
  great_expectations/core/usage_statistics/anonymizers/action_anonymizer.py
  great_expectations/core/usage_statistics/anonymizers/anonymizer.py
  great_expectations/core/usage_statistics/anonymizers/base.py
  great_expectations/core/usage_statistics/anonymizers/data_connector_anonymizer.py
  great_expectations/core/usage_statistics/anonymizers/profiler_anonymizer.py
  great_expectations/core/usage_statistics/anonymizers/store_anonymizer.py
  great_expectations/core/usage_statistics/anonymizers/store_backend_anonymizer.py
  great_expectations/util.py
  pyproject.toml
Labels: core

#8137 [MAINTENANCE] Use Available Enums Instead of Strings for Metric Name Extensions
  great_expectations/rule_based_profiler/data_assistant/data_assistant.py
Labels: dx, core

#8142 [DOCS] Update set_based_column_map_expectation.py
  great_expectations/expectations/set_based_column_map_expectation.py
Labels: core

#8144 [MAINTENANCE] Add env var to avoid out of memory error when building docs
  ci/azure-pipelines.yml
Labels: dx, core

#8114 [MAINTENANCE] Update single cloud onboarding script to use fluent datasources
  assets/scripts/gx_cloud/experimental/onboarding_script.py
Labels: maintenance, cloud, core

#7949 [CONTRIB] expect_queried_column_pair_values_to_be_both_filled_or_null
  contrib/experimental/great_expectations_experimental/expectations/expect_queried_column_pair_values_to_be_both_filled_or_null.py
Labels: community

#8146 [DOCS] Fix broken links and reenable link checking
  docs/docusaurus/README.md
  docs/docusaurus/docusaurus.config.js
  docs/prepare_prior_versions.py
  tests/docs/test_prepare_prior_versions.py
Labels: dx, core

#8155 [DOCS] Add version info to markdown links for earlier versions
  docs/prepare_prior_versions.py
  tests/docs/test_prepare_prior_versions.py
Labels: dx, core

#8152 [MAINTENANCE] Add default `table_name` to `TableAsset` if omitted
  great_expectations/datasource/fluent/schemas/PostgresDatasource.json
  great_expectations/datasource/fluent/schemas/PostgresDatasource/TableAsset.json
  great_expectations/datasource/fluent/schemas/SQLDatasource.json
  great_expectations/datasource/fluent/schemas/SQLDatasource/TableAsset.json
  great_expectations/datasource/fluent/schemas/SqliteDatasource.json
  great_expectations/datasource/fluent/schemas/SqliteDatasource/SqliteTableAsset.json
  great_expectations/datasource/fluent/sql_datasource.py
  tests/datasource/fluent/test_config.py
Labels: core

#8148 [FEATURE] Reference Environment - Snowflake
  examples/reference_environments/README.md
  examples/reference_environments/snowflake/README.md
  examples/reference_environments/snowflake/compose.yaml
  examples/reference_environments/snowflake/jupyter.Dockerfile
  examples/reference_environments/snowflake/snowflake_example.ipynb
  great_expectations/cli/example.py
  reqs/requirements-dev-sqlalchemy-less-than-2.txt
  setup.py
  tests/test_packaging.py
Labels: dx, core

#8118 [FEATURE] Fluent Datasource ABS, GCS, and S3 recursive file discovery
  docs/docusaurus/docs/components/connect_to_data/cloud/_abs_batching_regex_explaination.md
  docs/docusaurus/docs/components/connect_to_data/cloud/_abs_fluent_data_asset_config_keys.mdx
  docs/docusaurus/docs/components/connect_to_data/cloud/_gcs_fluent_data_asset_config_keys.mdx
  docs/docusaurus/docs/components/connect_to_data/cloud/_s3_fluent_data_asset_config_keys.mdx
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_azure_blob_storage_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_azure_blob_storage_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_gcs_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_gcs_using_spark.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_s3_using_pandas.md
  docs/docusaurus/docs/guides/connecting_to_your_data/fluent/cloud/how_to_connect_to_data_on_s3_using_spark.md
  great_expectations/datasource/data_connector/util.py
  great_expectations/datasource/fluent/data_asset/data_connector/azure_blob_storage_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/google_cloud_storage_data_connector.py
  great_expectations/datasource/fluent/data_asset/data_connector/s3_data_connector.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.pyi
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.pyi
  great_expectations/datasource/fluent/pandas_s3_datasource.py
  great_expectations/datasource/fluent/pandas_s3_datasource.pyi
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.pyi
  great_expectations/datasource/fluent/spark_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/spark_google_cloud_storage_datasource.pyi
  great_expectations/datasource/fluent/spark_s3_datasource.py
  great_expectations/datasource/fluent/spark_s3_datasource.pyi
  tests/datasource/fluent/test_pandas_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_pandas_google_cloud_storage_datasource.py
  tests/datasource/fluent/test_pandas_s3_datasource.py
  tests/datasource/fluent/test_spark_azure_blob_storage_datasource.py
  tests/datasource/fluent/test_spark_google_cloud_storage_datasource.py
  tests/datasource/fluent/test_spark_s3_datasource.py
Labels: community

#8164 [BUGFIX] Persist SQLDatasource splitters on creation
  great_expectations/datasource/fluent/sql_datasource.py
  great_expectations/datasource/fluent/sqlite_datasource.py
  tests/datasource/fluent/conftest.py
  tests/datasource/fluent/test_contexts.py
  tests/datasource/fluent/test_postgres_datasource.py
Labels: core

#8168 [RELEASE] 0.17.1
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8166 [FEATURE] AWS S3 reference environment
  examples/reference_environments/postgres/jupyter.Dockerfile
  examples/reference_environments/s3/README.md
  examples/reference_environments/s3/compose.yaml
  examples/reference_environments/s3/jupyter.Dockerfile
  examples/reference_environments/s3/s3_public_nyc_tlc_bucket_example.ipynb
  examples/reference_environments/snowflake/jupyter.Dockerfile
  great_expectations/cli/example.py
Labels: dx, core

#8158 [MAINTENANCE] Raise error on unsupported versions of python.
  great_expectations/__init__.py
Labels: core

#8167 [MAINTENANCE] Reference Environment - Update Snowflake Notebook to Specify Python 3.10
  examples/reference_environments/snowflake/compose.yaml
  examples/reference_environments/snowflake/jupyter.Dockerfile
  examples/reference_environments/snowflake/snowflake_example.ipynb
Labels: dx, core

#8169 [MAINTENANCE] Refactor reference environment CLI for consistency
  great_expectations/cli/example.py
Labels: dx, core

#8124 [DOCS] Add table listing supported evaluation parameter expressions to the docs
  docs/docusaurus/docs/terms/evaluation_parameter.md
Labels: devrel

#8025 [MAINTENANCE] DX-565 remove allow_cross_type_comparison from column_pair_values.a_greater_than_b
  great_expectations/core/expectation_configuration.py
  great_expectations/expectations/core/expect_column_pair_values_a_to_be_greater_than_b.py
  great_expectations/expectations/core/expect_column_values_to_be_between.py
  great_expectations/expectations/metrics/column_map_metrics/column_values_between.py
  great_expectations/jupyter_ux/expectation_explorer.py
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between.json
  tests/test_definitions/column_map_expectations/expect_column_values_to_be_between_tz_naive.json
Labels: core

#8157 [FEATURE] Snowflake FDS
  great_expectations/datasource/fluent/__init__.py
  great_expectations/datasource/fluent/schemas/SnowflakeDatasource.json
  great_expectations/datasource/fluent/schemas/SnowflakeDatasource/QueryAsset.json
  great_expectations/datasource/fluent/schemas/SnowflakeDatasource/TableAsset.json
  great_expectations/datasource/fluent/snowflake_datasource.py
  great_expectations/datasource/fluent/sources.pyi
  tests/datasource/fluent/great_expectations.yml
Labels: core

#8149 [FEATURE] Fix Bigquery/GCS integration tests
  great_expectations/data_context/types/base.py
  tests/integration/test_definitions/bigquery/integration_tests.py
  tests/integration/test_definitions/gcs/integration_tests.py
  tests/test_utils.py
Labels: core

#8174 [FEATURE] Python 3.11 support
  ci/azure-pipelines.yml
  great_expectations/__init__.py
  great_expectations/datasource/fluent/pandas_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/pandas_google_cloud_storage_datasource.py
  great_expectations/datasource/fluent/spark_azure_blob_storage_datasource.py
  great_expectations/datasource/fluent/spark_google_cloud_storage_datasource.py
Labels: core

#8160 [BUGFIX] Allow for `create_temp_table` to be `False` when creating a `SqlAlchemyBatchData` object
  great_expectations/compatibility/sqlalchemy.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  tests/execution_engine/test_sqlalchemy_batch_data.py
  tests/validator/test_validator.py
Labels: dx, core

#8180 [MAINTENANCE] Python 3.11 SQLAlchemy import time fix
  great_expectations/datasource/data_connector/data_connector.py
  great_expectations/datasource/data_connector/runtime_data_connector.py
  great_expectations/execution_engine/sqlalchemy_batch_data.py
  great_expectations/validator/validation_graph.py
Labels: core

#8185 [MAINTENANCE] Rich comments and docstrings for DataAssistant related modules.
  great_expectations/rule_based_profiler/data_assistant/data_assistant_dispatcher.py
  great_expectations/rule_based_profiler/data_assistant/data_assistant_runner.py
  great_expectations/rule_based_profiler/helpers/runtime_environment.py
  great_expectations/rule_based_profiler/rule_based_profiler.py
Labels: dx, core

#8135 [MAINTENANCE] Start cleaning up outdated deprecation warnings
  great_expectations/data_asset/data_asset.py
  great_expectations/expectations/metrics/map_metric.py
  great_expectations/expectations/registry.py
  tests/test_deprecation.py
Labels: core

#8191 [MAINTENANCE] Replace Non-Existent Expectation Name With Correct Existing Expectation Name
  docs/docusaurus/docs/terms/evaluation_parameter.md
  tests/integration/profiling/rule_based_profiler/test_profiler_basic_workflows.py
  tests/test_fixtures/rule_based_profiler/example_notebooks/BasicExample_RBP_Instantiation_and_running.ipynb
Labels: dx, core

#8143 [DOCS] Getting Started with GX
  docs/docusaurus/docs/components/setup/link_lists/_setup_and_install_for_hosted_data.md
  docs/docusaurus/docs/deployment_patterns/how_to_instantiate_a_data_context_hosted_environments.md
  docs/docusaurus/docs/deployment_patterns/index.md
  docs/docusaurus/docs/guides/connecting_to_your_data/components/spark_data_context_note.md
  docs/docusaurus/docs/reference/customize_your_deployment.md
  docs/docusaurus/docs/team_templates/conceptual_template.md
  docs/docusaurus/docs/team_templates/how_to_template.md
  docs/docusaurus/docs/team_templates/reference_template.md
  docs/docusaurus/docs/team_templates/tutorial_template.md
  docs/docusaurus/docs/tutorials/getting_started/how_to_use_great_expectations_in_databricks.md
  docs/docusaurus/docs/tutorials/getting_started/how_to_use_great_expectations_with_sql.md
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
  docs/docusaurus/sidebars.js
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_dataframe_python_configs.py
  tests/integration/docusaurus/deployment_patterns/databricks_deployment_patterns_file_python_configs.py
  tests/integration/docusaurus/deployment_patterns/postgres_deployment_patterns.py
  tests/integration/test_definitions/postgresql/integration_tests.py
Labels: devrel

#8171 [FEATURE] Fix azure docs tests
  tests/integration/test_definitions/abs/integration_tests.py
Labels: core

#8176 [FEATURE] Reference Environment - BigQuery
  examples/reference_environments/bigquery/README.md
  examples/reference_environments/bigquery/bigquery_example.ipynb
  examples/reference_environments/bigquery/compose.yaml
  examples/reference_environments/bigquery/jupyter.Dockerfile
  great_expectations/cli/example.py
Labels: dx, core

#8170 [BUGFIX] Raise more informative error on failure of getting an expectation suite by name
  great_expectations/data_context/data_context/cloud_data_context.py
  tests/data_context/cloud_data_context/test_expectation_suite_crud.py
Labels: core

#8192 [MAINTENANCE] Deal with Python 3.11 deprecations
  great_expectations/compatibility/google.py
  great_expectations/compatibility/pyspark.py
  pyproject.toml
  setup.py
  tests/test_deprecation.py
Labels: core

#8195 [BUGFIX] Enable Pandas Column Aggregate Metrics To Support Decimal Numeric Types
  great_expectations/expectations/metrics/column_aggregate_metrics/column_mean.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_standard_deviation.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_sum.py
  great_expectations/util.py
  tests/expectations/metrics/test_core.py
Labels: dx, core

#8198 [MAINTENANCE] Placing S3, Trino Imports Under Compatibility Pattern
  great_expectations/checkpoint/util.py
  great_expectations/cli/upgrade_helpers/upgrade_helper_v11.py
  great_expectations/compatibility/aws.py
  great_expectations/compatibility/sqlalchemy.py
  great_expectations/compatibility/trino.py
  great_expectations/core/config_substitutor.py
  great_expectations/data_context/store/tuple_store_backend.py
  great_expectations/datasource/batch_kwargs_generator/s3_batch_kwargs_generator.py
  great_expectations/datasource/data_connector/configured_asset_aws_glue_data_catalog_data_connector.py
  great_expectations/datasource/data_connector/configured_asset_s3_data_connector.py
  great_expectations/datasource/data_connector/inferred_asset_s3_data_connector.py
  great_expectations/datasource/fluent/pandas_s3_datasource.py
  great_expectations/datasource/fluent/pandas_s3_datasource.pyi
  great_expectations/datasource/fluent/spark_s3_datasource.py
  great_expectations/datasource/pandas_datasource.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py
  great_expectations/expectations/metrics/util.py
  great_expectations/self_check/util.py
  pyproject.toml
  tests/core/test_config_substitutor.py
  tests/profile/test_basic_suite_builder_profiler.py
  tests/test_definitions/test_expectations_v3_api.py
Labels: dx, core

#8190 [MAINTENANCE] Deprecate adding legacy datasources in Cloud-backed environments
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/data_context/cloud_data_context.py
  tests/data_context/abstract_data_context/test_datasource_delete.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
  tests/data_context/conftest.py
  tests/data_context/test_data_context_datasources.py
Labels: core

#8199 [BUGFIX] Relax numpy version requirements for python 3.10
  ci/constraints-test/py310-min-install.txt
  requirements.txt
Labels: core

#8202 [DOCS] Get Started Section Revisions
  docs/docusaurus/docs/guides/setup/get_started_lp.md
  docs/docusaurus/docs/guides/setup/installation/install_gx.md
  docs/docusaurus/docs/guides/setup/setup_overview.md
  docs/docusaurus/docs/guides/setup/setup_overview_lp.md
  docs/docusaurus/docs/tutorials/getting_started/how_to_use_great_expectations_in_databricks.md
  docs/docusaurus/docs/tutorials/getting_started/how_to_use_great_expectations_with_sql.md
  docs/docusaurus/docs/tutorials/quickstart/quickstart.md
  docs/docusaurus/sidebars.js
  docs/docusaurus/static/img/databricks_icon.svg
  docs/docusaurus/static/img/sql_icon.svg
  docs/docusaurus/static/img/test_icon.svg
Labels: devrel

#8197 [FEATURE] Reference Environment - Google Cloud Storage
  examples/reference_environments/gcs/README.md
  examples/reference_environments/gcs/compose.yaml
  examples/reference_environments/gcs/gcs_public_nyc_tlc_bucket_example.ipynb
  examples/reference_environments/gcs/jupyter.Dockerfile
  great_expectations/cli/example.py
  great_expectations/expectations/expectation.py
Labels: dx, core

#8194 [FEATURE] Enable updating active stores and CRUD for data docs sites
  great_expectations/data_context/data_context/abstract_data_context.py
  great_expectations/data_context/store/store.py
  tests/data_context/abstract_data_context/test_data_docs_config_crud.py
  tests/data_context/abstract_data_context/test_store_config_crud.py
Labels: dx, core

#8207 [MAINTENANCE] Add `pytest.deprecated_call` to misc usages of `add_datasource` in tests
  tests/conftest.py
  tests/data_context/cloud_data_context/test_datasource_crud.py
Labels: core

#8205 [MAINTENANCE] Placing AWS RedShift Imports Under Compatibility Pattern
  great_expectations/compatibility/aws.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/metrics/util.py
  great_expectations/self_check/util.py
Labels: dx, core

#8210 [MAINTENANCE] Placing Snowflake Imports Under Compatibility Pattern
  great_expectations/compatibility/snowflake.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/self_check/util.py
  tests/test_definitions/test_expectations_v3_api.py
Labels: dx, core

#8208 [FEATURE] Use PythonScript task type for custom docs ci checks
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs.yml
Labels: core

#8213 [MAINTENANCE] Placing AWS Athena Imports Under Compatibility Pattern
  great_expectations/compatibility/aws.py
  great_expectations/compatibility/sqlalchemy_bigquery.py
  great_expectations/self_check/util.py
  tests/expectations/core/test_expect_column_values_to_be_in_type_list.py
  tests/expectations/core/test_expect_column_values_to_be_of_type.py
Labels: dx, core

#8215 [MAINTENANCE] Update notebook link to non-legacy docs
  great_expectations/render/notebook_assets/suite_edit/FOOTER.md
Labels: core

#8214 [MAINTENANCE] Placing BigQuery Imports Under Compatibility Pattern
  great_expectations/cli/batch_request.py
  great_expectations/compatibility/bigquery.py
  great_expectations/execution_engine/sqlalchemy_execution_engine.py
  great_expectations/expectations/core/expect_column_values_to_be_of_type.py
  great_expectations/expectations/metrics/util.py
  great_expectations/self_check/util.py
  tests/datasource/test_new_datasource_with_sql_data_connector.py
  tests/render/renderer/test_suite_edit_notebook_renderer.py
  tests/test_definitions/test_expectations_v3_api.py
Labels: dx, core

#8203 [MAINTENANCE] Fix Python 3.11 async expectations tests
  tests/expectations/test_generate_diagnostic_checklist.py
Labels: core

#8139 [FEATURE] ExpectDaySumToBeCloseToEquivalentWeekDayMean: User can give `weeks_back` as argument
  contrib/experimental/great_expectations_experimental/expectations/expect_day_sum_to_be_close_to_equivalent_week_day_mean.py
Labels: community

#8220 [RELEASE] 0.17.2
  docs/docusaurus/docs/changelog.md
  docs/docusaurus/docs/components/_data.jsx
  docs/docusaurus/docusaurus.config.js
  docs_rtd/changelog.rst
  great_expectations/deployment_version
Labels: core

#8211 [FEATURE] Examples of using different store backends in reference environments
  docs/docusaurus/docs/guides/setup/configuring_metadata_stores/configure_expectation_stores.md
  examples/reference_environments/abs/README.md
  examples/reference_environments/abs/abs_example_abs_stores.ipynb
  examples/reference_environments/abs/compose.yaml
  examples/reference_environments/abs/jupyter.Dockerfile
  examples/reference_environments/gcs/README.md
  examples/reference_environments/gcs/compose.yaml
  examples/reference_environments/gcs/gcs_public_nyc_tlc_bucket_gcs_stores_example.ipynb
  examples/reference_environments/gcs/jupyter.Dockerfile
  examples/reference_environments/postgres/README.md
  examples/reference_environments/postgres/jupyter.Dockerfile
  examples/reference_environments/postgres/postgres_example_postgres_stores.ipynb
  examples/reference_environments/s3/README.md
  examples/reference_environments/s3/compose.yaml
  examples/reference_environments/s3/jupyter.Dockerfile
  examples/reference_environments/s3/s3_public_nyc_tlc_bucket_s3_stores_example.ipynb
  great_expectations/cli/example.py
Labels: dx, core

#8178 [FEATURE] Add checker to ensure snippets are being used
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs.yml
  ci/checks/check_name_tag_snippets_referenced.py
  ci/checks/check_only_name_tag_snippets.py
  docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
  tests/integration/db/awsathena.py
  tests/integration/docusaurus/connecting_to_your_data/database/athena_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/database/postgres_python_example.py
  tests/integration/docusaurus/connecting_to_your_data/datasource_configuration/how_to_configure_a_pandas_datasource.py
  tests/integration/docusaurus/connecting_to_your_data/filesystem/spark_yaml_example.py
  tests/integration/docusaurus/setup/configuring_metadata_stores/how_to_configure_an_expectation_store_in_gcs.py
  tests/integration/docusaurus/tutorials/quickstart/quickstart.py
  tests/integration/docusaurus/validation/checkpoints/how_to_create_a_new_checkpoint.py
Labels: core

#8206 [DOCS] Update Install GX
  docs/docusaurus/docs/guides/setup/get_started_lp.md
  docs/docusaurus/docs/guides/setup/installation/install_gx.md
  docs/docusaurus/docs/guides/setup/setup_overview_lp.md
  docs/docusaurus/docs/tutorials/getting_started/how_to_use_great_expectations_in_databricks.md
  docs/docusaurus/docs/tutorials/getting_started/how_to_use_great_expectations_with_sql.md
Labels: devrel

#8224 [MAINTENANCE] Arranging call arguments to `build_batch_request()` utility method to be in consistent order
  great_expectations/rule_based_profiler/helpers/util.py
Labels: dx, core

#8221 [FEATURE] Host data docs for the postgres reference environment
  examples/reference_environments/postgres/README.md
  examples/reference_environments/postgres/compose.yaml
  examples/reference_environments/postgres/data_docs.Dockerfile
  examples/reference_environments/postgres/jupyter.Dockerfile
  examples/reference_environments/postgres/postgres_example.ipynb
Labels: dx, core

#8186 [FEATURE] Add checker to ensure test files have fixture definition
  ci/azure-pipelines-dev.yml
  ci/azure-pipelines-docs.yml
  ci/checks/check_integration_test_gets_run.py
Labels: core

#8216 [FEATURE] make backend_dependencies required and not optional for doc integration tests
  tests/integration/integration_test_fixture.py
  tests/integration/test_script_runner.py
Labels: core

#8229 [MAINTENANCE] Use python static file server
  examples/reference_environments/postgres/data_docs.Dockerfile
Labels: dx, core

#8223 [MAINTENANCE] Fix race condition in integration tests using context manager
  tests/integration/db/taxi_data_utils.py
  tests/integration/db/test_sql_data_sampling.py
  tests/integration/db/test_sql_data_split_on_column_value.py
  tests/integration/db/test_sql_data_split_on_datetime_and_day_part.py
  tests/integration/db/test_sql_data_split_on_divided_integer.py
  tests/integration/db/test_sql_data_split_on_hashed_column.py
  tests/integration/db/test_sql_data_split_on_mod_integer.py
  tests/integration/db/test_sql_data_split_on_multi_column_values.py
  tests/integration/db/test_sql_data_split_on_whole_table.py
Labels: core

#8231 [FEATURE] View data docs inside snowflake and bigquery reference environments
  examples/reference_environments/README.md
  examples/reference_environments/bigquery/README.md
  examples/reference_environments/bigquery/bigquery_example.ipynb
  examples/reference_environments/bigquery/compose.yaml
  examples/reference_environments/bigquery/data_docs.Dockerfile
  examples/reference_environments/bigquery/jupyter.Dockerfile
  examples/reference_environments/postgres/README.md
  examples/reference_environments/postgres/compose.yaml
  examples/reference_environments/postgres/postgres_example_postgres_stores.ipynb
  examples/reference_environments/snowflake/README.md
  examples/reference_environments/snowflake/compose.yaml
  examples/reference_environments/snowflake/data_docs.Dockerfile
  examples/reference_environments/snowflake/jupyter.Dockerfile
  examples/reference_environments/snowflake/snowflake_example.ipynb
  great_expectations/cli/example.py
Labels: dx, core
